# First print your name in the cell below then save this file. (or something nice about your instructor)

In [1]:
# In this cell print your name 
print("Faith")

Faith

In [1]:
!pip3 install pandas numpy

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.0.5)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/faithlin/Library/Python/3.13/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/faithlin/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip

# Data wrangling with Pandas exercise
* For this exercise we will be using the `listings.csv` data file.

In [2]:
import pandas as pd
import numpy as np

# Load in the data file using `pd.read_csv()`

In [3]:
# Load data here
df = pd.read_csv('../data/listings.csv') #need to go one folder up because current hw file is in exercises folder

df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340

## Exercise 2 - Filtering

Return the following subsets of the dataframe.

1. How many listings are there with a price less than 100? 


2. Find how many listings there are in just Brooklyn.


3. Find how many listings there are in Brooklyn with a price less than 100.


4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.


5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  The prices for all other listings should be the same as the were before. 


6. What % of the rooms are private, and what % of the rooms are shared.  
    * Hint, use `.value_counts()`

In [ ]:
# 1. How many listings are there with a price less than 100? 
c1 = df['price'] < 100 #create condition
c1

df_less_than_100 = df[c1].copy() #create copy of df with condition
df_less_than_100 #display listings with price < 100

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340
5,5203,Cozy Clean Guest Room - Family Apt,7490,MaryEllen,Manhattan,Upper West Side,40.80178,-73.96723,Private room,75,2,118,2017-07-21,0.89,1,0
8,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,88,4,180,2020-03-18,1.31,3,344
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46520,44804690,"Cozy place, peaceful, friendly and affordable.",362419479,Elia,Queens,St. Albans,40.69980,-73.77104,Private room,44,1,0,NaN,NaN,1,161
46523,44807786,Cozy & comfy apt in the heart of Inwood Manhattan,284790520,Salar,Manhattan,Washington Heights,40.85820,-73.92733,Entire home/apt,87,6,0,NaN,NaN,2,85
46524,44811717,Comfortable safe environment 24hr security camera,362453686,Nicole,Brooklyn,East Flatbush,40.65399,-73.93287,Private room,59,3,0,NaN,NaN,1,90
46525,44814944,Upper West Side studio 86th Street,4039777,Fernando,Manhattan,Upper West Side,40.78731,-73.97029,Entire home/apt,80,30,0,NaN,NaN,1,113
46526,44818009,"5MIN D/N trains, NEAR THE BEACH, 50’ TO MANHATTAN",48098268,Marina,Brooklyn,Gravesend,40.59945,-73.98209,Private room,66,1,0,NaN,NaN,1,38

In [ ]:
#num of listings with a price less than $100
(c1).sum() #print the sum of the condition (the actual count/num)

np.int64(22778)

In [ ]:
# 2. Make a new DataFrame of listings in Brooklyn named `df_bk` 
# and find how many listings in just Brooklyn.

c2 = df['neighbourhood_group'] == 'Brooklyn' #create condition

df_bk = df[c2].copy() #create copy of df with condition
df_bk #display the df

#df_bk.neighbourhood_group.value_counts() #can use value_counts() to double check since using a df col

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295
8,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,88,4,180,2020-03-18,1.31,3,344
11,6848,Only 2 stops to Manhattan studio,15991,Allen & Irina,Brooklyn,Williamsburg,40.70837,-73.95352,Entire home/apt,109,2,181,2020-03-16,1.32,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46517,44802032,A very large room in Williamsburg,213793805,Omer,Brooklyn,Williamsburg,40.71970,-73.95632,Private room,55,14,0,NaN,NaN,1,45
46518,44802224,Unique & beautiful design! Skylights-Washer/dryer,143513836,Elisabeth,Brooklyn,Crown Heights,40.67302,-73.91695,Private room,61,30,0,NaN,NaN,5,363
46519,44803201,1200 SF Duplex apt in an old shoe factory/ mon...,921746,Michael + Josué,Brooklyn,Clinton Hill,40.69034,-73.96179,Entire home/apt,253,30,0,NaN,NaN,1,74
46524,44811717,Comfortable safe environment 24hr security camera,362453686,Nicole,Brooklyn,East Flatbush,40.65399,-73.93287,Private room,59,3,0,NaN,NaN,1,90
46526,44818009,"5MIN D/N trains, NEAR THE BEACH, 50’ TO MANHATTAN",48098268,Marina,Brooklyn,Gravesend,40.59945,-73.98209,Private room,66,1,0,NaN,NaN,1,38

In [ ]:
#num of listings in Brooklyn
(c2).sum() #print the sum of the condition (the actual count/num)

np.int64(18632)

In [ ]:
# 3. Find how many listings there are in Brooklyn with a price less than 100.

bk_low = df[c1 & c2] #combine the two conditions
bk_low #display the df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
8,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,88,4,180,2020-03-18,1.31,3,344
21,10452,Large B&B Style rooms,35935,Angela,Brooklyn,Bedford-Stuyvesant,40.68310,-73.95473,Private room,70,3,75,2019-10-12,0.60,2,365
22,10962,"Lovely Room 2; Garden; Best area, Legal",9744,Laurie,Brooklyn,South Slope,40.66869,-73.98780,Private room,88,4,180,2020-08-03,1.36,3,365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46510,44798876,Unique & beautiful design! Skylights-Washer/dryer,143513836,Elisabeth,Brooklyn,Crown Heights,40.67156,-73.91651,Private room,61,30,0,NaN,NaN,5,329
46517,44802032,A very large room in Williamsburg,213793805,Omer,Brooklyn,Williamsburg,40.71970,-73.95632,Private room,55,14,0,NaN,NaN,1,45
46518,44802224,Unique & beautiful design! Skylights-Washer/dryer,143513836,Elisabeth,Brooklyn,Crown Heights,40.67302,-73.91695,Private room,61,30,0,NaN,NaN,5,363
46524,44811717,Comfortable safe environment 24hr security camera,362453686,Nicole,Brooklyn,East Flatbush,40.65399,-73.93287,Private room,59,3,0,NaN,NaN,1,90
46526,44818009,"5MIN D/N trains, NEAR THE BEACH, 50’ TO MANHATTAN",48098268,Marina,Brooklyn,Gravesend,40.59945,-73.98209,Private room,66,1,0,NaN,NaN,1,38

In [11]:
#num of listings in Brooklyn and with a price < $100
#print the sum of the condition (the actual count/num)
(c1 & c2).sum() #this works, but (bk_low).sum() does not

np.int64(10473)

In [12]:
# 4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.
# How many total are there that have those names

names = ['Michael', 'David', 'John', 'Daniel'] #put the names we are searching for in a list

c3 = df.host_name.isin(names) #select the names in the list
df[c3]['host_name'].value_counts() #count the num for each name

host_name
Michael    387
David      348
John       270
Daniel     253
Name: count, dtype: int64

In [ ]:
# 5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  
# The prices for all other listings should be the same as the were before. 

#use np.where()
c4 = df['neighbourhood'] == 'Williamsburg' 
df['adjusted_price'] = np.where(c4, 100, df['price']) #use c4 as condition, 100 if True, org price if False

# Sanity check to view if our assignment worked correctly. To check the Williamsburg listings, if only did df, can't see the Williamsburg listings
select_statement = df['adjusted_price'] == 100

new_df = df[ select_statement ]

new_df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,adjusted_price
11,6848,Only 2 stops to Manhattan studio,15991,Allen & Irina,Brooklyn,Williamsburg,40.70837,-73.95352,Entire home/apt,109,2,181,2020-03-16,1.32,1,0,100
15,7801,Sweet and Spacious Brooklyn Loft,21207,Chaya,Brooklyn,Williamsburg,40.71842,-73.95718,Entire home/apt,299,3,9,2011-12-28,0.07,1,337,100
29,12940,Charming Brownstone 3 - Near PRATT,50148,Adreinne,Brooklyn,Bedford-Stuyvesant,40.68111,-73.95591,Entire home/apt,100,5,66,2020-03-02,0.51,1,19,100
35,14290,* ORIGINAL BROOKLYN LOFT *,56104,James,Brooklyn,Williamsburg,40.70420,-73.93560,Entire home/apt,131,3,95,2020-05-28,0.73,1,164,100
38,14377,Williamsburg 1 bedroom Apartment,56512,Joanna,Brooklyn,Williamsburg,40.70881,-73.95930,Entire home/apt,175,10,113,2020-01-24,0.87,1,165,100

In [18]:
# 6. What % of the rooms are private, and what % of the rooms are shared.  

#Of all rooms?
#private = private room
#shared = entire/home apt? 

#df.room_type.value_counts() #without percentage
df.room_type.value_counts(normalize=True)

room_type
Entire home/apt    0.515787
Private room       0.454446
Shared room        0.021213
Hotel room         0.008554
Name: proportion, dtype: float64

# Exercise 3 - Grouping

1. Using `groupby`, count how many listings are in each neighbourhood_group.


2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 


3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


4. Using `groupby`, find the median price for each room type in each neighbourhood_group.


5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices for each room type in each neighbourhood_group.

In [ ]:
# 1. Using `groupby`, count how many listings are in each neighbourhood_group.

#Use count
gb = df.groupby('neighbourhood_group')
#gb['neighbourhood_group'].count().sum() #finds the total num of listings
gb['neighbourhood_group'].count() #counts num of listings in each borough, use neighbourhood_group col

neighbourhood_group
Bronx             1183
Brooklyn         18632
Manhattan        20580
Queens            5791
Staten Island      341
Name: neighbourhood_group, dtype: int64

In [20]:
# 2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 

#Use the prev cell gb for neighbourhood_group
gb['price'].mean()  #use the PRICE col

neighbourhood_group
Bronx             92.751479
Brooklyn         120.225258
Manhattan        191.880466
Queens            99.754965
Staten Island    110.947214
Name: price, dtype: float64

In [21]:
# 2.5. Using `groupby`, find the mean price for each room_type. 

#create a new groupby, group by room_type
gb2 = df.groupby('room_type') 
gb2['price'].mean() #use the PRICE col

room_type
Entire home/apt    199.395950
Hotel room         275.015075
Private room        91.453084
Shared room         87.063830
Name: price, dtype: float64

In [ ]:
# 3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 

gb['price'].agg(['min', 'max']) #agg() takes a list of functions

                     min    max
neighbourhood_group
Bronx                 16   1404
Brooklyn               0  10000
Manhattan              0  10000
Queens                 0  10000
Staten Island         19   1200

In [23]:
# 4. Using `groupby`, find the mean price for each room_type in each neighbourhood_group.

group_by_list = ['neighbourhood_group', 'room_type'] #put relevant col in list
gb3 = df.groupby(group_by_list) #group by those col (in the list)

gb3['price'].mean() #use the PRICE col

neighbourhood_group  room_type
Bronx                Entire home/apt    138.004819
                     Private room        68.419668
                     Shared room         66.391304
Brooklyn             Entire home/apt    171.587687
                     Hotel room         147.300000
                     Private room        71.291189
                     Shared room         57.870091
Manhattan            Entire home/apt    231.335572
                     Hotel room         292.515670
                     Private room       128.277069
                     Shared room        111.735084
Queens               Entire home/apt    150.168900
                     Hotel room         139.058824
                     Private room        69.972564
                     Shared room         89.891892
Staten Island        Entire home/apt    151.720930
                     Private room        70.312883
                     Shared room         46.000000
Name: price, dtype: float64

In [ ]:
# 5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices 
# for each room type in each neighbourhood_group.


gb3['price'].agg(['count', 'min', 'max', 'mean', 'median', 'std']) #put the func in a list

                                     count  min    max        mean  median  \
neighbourhood_group room_type
Bronx               Entire home/apt    415   25   1404  138.004819   103.0
                    Private room       722   16    700   68.419668    55.0
                    Shared room         46   20    800   66.391304    44.0
Brooklyn            Entire home/apt   9112   20  10000  171.587687   135.0
                    Hotel room          30    0    399  147.300000   129.0
                    Private room      9159   10   2500   71.291189    60.0
                    Shared room        331   15   1500   57.870091    36.0
Manhattan           Entire home/apt  12209    0  10000  231.335572   165.0
                    Hotel room         351    0   2211  292.515670   210.0
                    Private room      7601   10  10000  128.277069    80.0
                    Shared room        419   10  10000  111.735084    60.0
Queens              Entire home/apt   2090   10  10000  150.168900   115.0
                    Hotel room          17    0    249  139.058824   149.0
                    Private room      3499   18   9000   69.972564    55.0
                    Shared room        185   14   3000   89.891892    40.0
Staten Island       Entire home/apt    172   39   1200  151.720930   111.0
                    Private room       163   20    800   70.312883    55.0
                    Shared room          6   19     82   46.000000    38.0

                                            std
neighbourhood_group room_type
Bronx               Entire home/apt  126.032106
                    Private room      57.337866
                    Shared room      114.442703
Brooklyn            Entire home/apt  236.732843
                    Hotel room        91.153206
                    Private room      69.023165
                    Shared room       92.217618
Manhattan           Entire home/apt  410.306439
                    Hotel room       315.924085
                    Private room     448.677306
                    Shared room      502.728868
Queens              Entire home/apt  252.606739
                    Hotel room        50.743806
                    Private room     163.814468
                    Shared room      275.675158
Staten Island       Entire home/apt  147.518392
                    Private room      70.759593
                    Shared room       28.446441

# Load, Merge, and Export files.
1. Load the `prices.csv` and the `n_listings.csv`
    * Having an error..? Inspect the actual csv file if you're having trouble

2. Do join that keeps all the records for each table.
    * Neighbourhood groups should include ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island',
       'LongIsland']

       
3. Save your joined csv as `joined.csv` into the data folder. 


4. Load your saved table and see if it looks the same or different that the DataFrame you used to create it.

In [30]:
# 1. Load the `prices.csv` and the `n_listings.csv`

#need to go one folder up
df2 = pd.read_csv('../data/prices.csv') #load the prices.csv, store in df2 variable

df2

  neighbourhood_group   mean_price
0               Bronx    92.751479
1            Brooklyn   120.225258
2           Manhattan   191.880466
3              Queens    99.754965
4       Staten Island   110.947214

In [31]:
#need to go one folder up
df3 = pd.read_csv('../data/n_listings.csv', sep = ';') #load the n_listings.csv, store in df3 variable

df3

  neighbourhood_group  n_listings
0               Bronx        1183
1            Brooklyn       18632
2           Manhattan       20580
3          LongIsland        4121

In [ ]:
# 2. Do join that keeps all the records for each table.

#Outer Join to keep all records from both tables, use df2 and df3 from prev cells
all_records = pd.merge(df2,                      # Outer join
                      df3,
                      on = "neighbourhood_group",
                      how = "outer")
all_records

  neighbourhood_group   mean_price  n_listings
0               Bronx    92.751479      1183.0
1            Brooklyn   120.225258     18632.0
2          LongIsland          NaN      4121.0
3           Manhattan   191.880466     20580.0
4              Queens    99.754965         NaN
5       Staten Island   110.947214         NaN

In [33]:
# 3. Save your joined csv as `joined.csv` into the data folder. 

#need to go one folder up
new_file = '../data/joined.csv' #want to save in data folder
all_records.to_csv(new_file) #use name_of_df.to_csv(folder_name), used all_records bc that is the name of the dataframe

In [34]:
# 4. Load your newly saved file, see if it looks the same.  If not, try saving with argument `index=False`

#use new_file --> name of the df file var
with open(new_file, 'rt') as text_file:
    for line in text_file.readlines():
        print(line)

,neighbourhood_group, mean_price,n_listings

0,Bronx,92.75147928994085,1183.0

1,Brooklyn,120.22525762129668,18632.0

2,LongIsland,,4121.0

3,Manhattan,191.8804664723032,20580.0

4,Queens,99.75496460024176,

5,Staten Island,110.94721407624634,

# Extra Credit
Every question below this cell is extra credit and optional.

### 2. (Very Easy) Find other cool Panda packages / add ons and show us what they can do well. And how you installed them.

### 3. (Medium) Use the grammys.csv data for the next section of questions.

1. Who was won Album of the Year in 2016?


2. Who won Best Rap Album in 2009?


3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

In [ ]:
grammy_df = pd.read_csv('../data/grammys.csv') #reading the csv into a df variable
grammy_df

,year,category,nominee,workers,winner
0,1959,Album of the Year,The Music from Peter Gunn.,Henry Mancini,True
1,1959,Best Album Cover,Only the Lonely,Frank Sinatra (art director),True
2,1959,Best Arrangement,The Music From Peter Gunn,Henry Mancini (artist/arranger),True
3,1959,Best Classical Performance - Chamber Music (in...,Beethoven: Quartet 130,"The Hollywood String Quartet, Paul Shure (arti...",True
4,1959,Best Classical Performance - Instrumentalist (...,Segovia Golden Jubilee,Andrés Segovia,True
...,...,...,...,...,...
6318,2019,Record of the Year,Rockstar,"Post Malone (artist), 21 Savage (artist), Loui...",False
6319,2019,Song of the Year,This is America (Childish Gambino),"Ludwig Göransson (songwriter), Young Thug (son...",True
6320,2019,Song of the Year,The Joke (Brandi Carlile),"Brandi Carlile (songwriter), Dave Cobb (songwr...",False
6321,2019,Song of the Year,Boo'd Up (Ella Mai),"Ella Mai (songwriter), Larrance Dopson (songwr...",False
6322,2019,Song of the Year,In My Blood (Shawn Mendes),"Shawn Mendes (songwriter), Teddy Geiger (songw...",False

In [ ]:
grammy_df.info() #display the col datatypes

<class 'pandas.DataFrame'>
RangeIndex: 6323 entries, 0 to 6322
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   year      6323 non-null   int64
 1   category  6323 non-null   str
 2   nominee   6320 non-null   str
 3   workers   5983 non-null   str
 4   winner    6323 non-null   bool
dtypes: bool(1), int64(1), str(3)
memory usage: 203.9 KB

In [ ]:
#Q1: Who won Album of the Year in 2016?

#create conditions for the category, year, and the winner
g_c1 = grammy_df['category'] == "Album of the Year"
g_c2 = grammy_df['year'] == 2016
g_c3 = grammy_df['winner'] == True #boolean

winner = grammy_df[g_c1 & g_c2 & g_c3] #use AND
winner #displays the entire row

,year,category,nominee,workers,winner
5505,2016,Album of the Year,1989.,"Taylor Swift (artist/producer), Jack Antonoff ...",True

In [ ]:
winner = grammy_df["workers"][g_c1 & g_c2 & g_c3] #only displays the winner names (workers column)
winner

5505    Taylor Swift (artist/producer), Jack Antonoff ...
Name: workers, dtype: str

In [ ]:
#Q2: Who won Best Rap Album in 2009?

#create conditions for the category and year, reuse boolean condition (for winner)
g_c4 = grammy_df['category'] == "Best Rap Album"
g_c5 = grammy_df['year'] == 2009

winner2 = grammy_df[g_c4 & g_c5 & g_c3] #use AND
winner2 #displays the entire row

      year        category         nominee     workers  winner
4396  2009  Best Rap Album  Tha Carter III  Lil' Wayne    True

In [ ]:
winner2 = grammy_df["workers"][g_c4 & g_c5 & g_c3] #only displays the winner names (workers column)
winner2

4396    Lil' Wayne
Name: workers, dtype: str

In [ ]:
#Q3: How many awards was Kendrick Lamar nominated for and how many did he win?

artist = ['Kendrick Lamar'] #put the artist name we are searching for in a list
g_c6 = grammy_df.workers.isin(artist) #select the name(s) in the list, use .isin()
grammy_df[g_c6 & g_c3]['workers'].value_counts() #count the num for each name AND if he won - BOTH conditions

#g_c3 is the boolean winner condition

workers
Kendrick Lamar    4
Name: count, dtype: int64

In [ ]:
winner3 = grammy_df[g_c6 & g_c3] #use AND, want to find both Kendrick Lamar and if winner == True
winner3

      year              category               nominee         workers  winner
5448  2015  Best Rap Performance                    i.  Kendrick Lamar    True
5596  2016        Best Rap Album  To Pimp a Butterfly.  Kendrick Lamar    True
5599  2016  Best Rap Performance              Alright.  Kendrick Lamar    True
6003  2018  Best Rap Performance               HUMBLE.  Kendrick Lamar    True

In [ ]:
#displays ALL of Lamar's nominations (including those he won and lost)
winner4 = grammy_df[g_c6]
winner4

,year,category,nominee,workers,winner
5269,2014,Best Rap Album,"Good Kid, M.A.A.D City.",Kendrick Lamar,False
5272,2014,Best Rap Performance,Swimming Pools (Drank).,Kendrick Lamar,False
5448,2015,Best Rap Performance,i.,Kendrick Lamar,True
5596,2016,Best Rap Album,To Pimp a Butterfly.,Kendrick Lamar,True
5599,2016,Best Rap Performance,Alright.,Kendrick Lamar,True
6003,2018,Best Rap Performance,HUMBLE.,Kendrick Lamar,True

In [ ]:
#another way to display ALL of Lamar's nominations - creating a condition instead of .isin()
artist2 = grammy_df["workers"] == "Kendrick Lamar"

grammy_df[artist2]

,year,category,nominee,workers,winner
5269,2014,Best Rap Album,"Good Kid, M.A.A.D City.",Kendrick Lamar,False
5272,2014,Best Rap Performance,Swimming Pools (Drank).,Kendrick Lamar,False
5448,2015,Best Rap Performance,i.,Kendrick Lamar,True
5596,2016,Best Rap Album,To Pimp a Butterfly.,Kendrick Lamar,True
5599,2016,Best Rap Performance,Alright.,Kendrick Lamar,True
6003,2018,Best Rap Performance,HUMBLE.,Kendrick Lamar,True

### (Hard) Load the Game Logs for 2022 and add the column names using a dictionary.  
* [Link to the data page](https://www.retrosheet.org/gamelogs/)
* [Link to the column names](https://procatinator.com/)
* haha, gotta find them yourself!

### (Extra Hard) Download the files for the past 5 years into a new folder and add them all into one data frame using pandas, then save that new file.
* Try to not hard code in the file names. We want to do this programmatically because what if we want to add new/more file names in the future.