# First print your name in the cell below then save this file. (or something nice about your instructor)

In [1]:
# In this cell print your name 

print("My name is Kevin Munoz, and both my professor and TA seem like cool and interesting people")

My name is Kevin Munoz, and both my professor and TA seem like cool and interesting people

# Data wrangling with Pandas exercise
* For this exercise we will be using the `listings.csv` data file.

In [2]:
import pandas as pd
import numpy as np

# Load in the data file using `pd.read_csv()`

In [3]:
# Load data here
df = pd.read_csv('/workspaces/ds-fall-2026/Week-01-Pandas/data/listings.csv')

## Exercise 2 - Filtering

Return the following subsets of the dataframe.

1. How many listings are there with a price less than 100? 


2. Find how many listings there are in just Brooklyn.


3. Find how many listings there are in Brooklyn with a price less than 100.


4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.


5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  The prices for all other listings should be the same as the were before. 


6. What % of the rooms are private, and what % of the rooms are shared.  
    * Hint, use `.value_counts()`

In [4]:
# 1. How many listings are there with a price less than 100? 
under_100 = df[df['price'] < 100]
len(under_100)

22778

In [5]:
# 2. Make a new DataFrame of listings in Brooklyn named `df_bk` 
# and find how many listings in just Brooklyn.
df_bk = df[df['neighbourhood_group'] == 'Brooklyn']
len(df_bk)

18632

In [7]:
# 3. Find how many listings there are in Brooklyn with a price less than 100.
bk_100 = df[(df['neighbourhood_group'] == 'Brooklyn') & (df['price'] < 100)]
len(bk_100)

10473

In [9]:
# 4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.
# How many total are there that have those names
hosts = ['Michael', 'David', 'John', 'Daniel']
names = df[df['host_name'].isin(hosts)]
len(names)

1258

In [11]:
# 5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  
# The prices for all other listings should be the same as the were before. 
df['adjusted_price'] = np.where(
    df['neighbourhood'] == 'Williamsburg',
    df['price'] + 100,
    df['price']
)
df[df['neighbourhood'] == 'Williamsburg'][['neighbourhood', 'price', 'adjusted_price']]

      neighbourhood  price  adjusted_price
11     Williamsburg    109             209
15     Williamsburg    299             399
35     Williamsburg    131             231
38     Williamsburg    175             275
42     Williamsburg     80             180
...             ...    ...             ...
46484  Williamsburg    250             350
46489  Williamsburg    464             564
46493  Williamsburg    100             200
46513  Williamsburg    180             280
46517  Williamsburg     55             155

[3486 rows x 3 columns]

In [ ]:
# 6. What % of the rooms are private, and what % of the rooms are shared.  
room_percents = df['room_type'].value_counts(normalize=True) * 100
print(room_percents)

room_type
Entire home/apt    51.578653
Private room       45.444581
Shared room         2.121349
Hotel room          0.855417
Name: proportion, dtype: float64

# Exercise 3 - Grouping

1. Using `groupby`, count how many listings are in each neighbourhood_group.


2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 


3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


4. Using `groupby`, find the median price for each room type in each neighbourhood_group.


5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices for each room type in each neighbourhood_group.

In [13]:
# 1. Using `groupby`, count how many listings are in each neighbourhood_group.
df.groupby('neighbourhood_group')['price'].count()

neighbourhood_group
Bronx             1183
Brooklyn         18632
Manhattan        20580
Queens            5791
Staten Island      341
Name: price, dtype: int64

In [14]:
# 2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 
df.groupby('neighbourhood_group')['price'].mean()

neighbourhood_group
Bronx             92.751479
Brooklyn         120.225258
Manhattan        191.880466
Queens            99.754965
Staten Island    110.947214
Name: price, dtype: float64

In [15]:
# 2.5. Using `groupby`, find the mean price for each room_type. 
df.groupby('room_type')['price'].mean()

room_type
Entire home/apt    199.395950
Hotel room         275.015075
Private room        91.453084
Shared room         87.063830
Name: price, dtype: float64

In [16]:
# 3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 
df.groupby('neighbourhood_group')['price'].agg(['min', 'max'])

                     min    max
neighbourhood_group
Bronx                 16   1404
Brooklyn               0  10000
Manhattan              0  10000
Queens                 0  10000
Staten Island         19   1200

In [17]:
# 4. Using `groupby`, find the mean price for each room_type in each neighbourhood_group.
df.groupby(['neighbourhood_group', 'room_type'])['price'].median()

neighbourhood_group  room_type
Bronx                Entire home/apt    103.0
                     Private room        55.0
                     Shared room         44.0
Brooklyn             Entire home/apt    135.0
                     Hotel room         129.0
                     Private room        60.0
                     Shared room         36.0
Manhattan            Entire home/apt    165.0
                     Hotel room         210.0
                     Private room        80.0
                     Shared room         60.0
Queens               Entire home/apt    115.0
                     Hotel room         149.0
                     Private room        55.0
                     Shared room         40.0
Staten Island        Entire home/apt    111.0
                     Private room        55.0
                     Shared room         38.0
Name: price, dtype: float64

In [ ]:
# 5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices 
# for each room type in each neighbourhood_group.

df.groupby(['neighbourhood_group', 'room_type'])['price'].agg(['count', 'min', 'max', 'mean', 'median', 'std'])

# Load, Merge, and Export files.
1. Load the `prices.csv` and the `n_listings.csv`
    * Having an error..? Inspect the actual csv file if you're having trouble

2. Do join that keeps all the records for each table.
    * Neighbourhood groups should include ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island',
       'LongIsland']

       
3. Save your joined csv as `joined.csv` into the data folder. 


4. Load your saved table and see if it looks the same or different that the DataFrame you used to create it.

In [18]:
# 1. Load the `prices.csv` and the `n_listings.csv`
prices = pd.read_csv('/workspaces/ds-fall-2026/Week-01-Pandas/data/prices.csv')
n_listings = pd.read_csv('/workspaces/ds-fall-2026/Week-01-Pandas/data/new_listings.csv')

In [20]:
# 2. Do join that keeps all the records for each table.
joined = prices.merge(n_listings, on='neighbourhood_group', how='outer')
joined

,neighbourhood_group,mean_price,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,new_price
0,Bronx,92.751479,44096,Room with a View,190409,Waundell,Highbridge,40.83232,-73.93184,Private room,50,1,277,2020-02-25,2.29,3,364,5000
1,Bronx,92.751479,45935,Room in Beautiful Townhouse.,204586,L,Port Morris,40.80640,-73.92395,Private room,60,3,0,NaN,NaN,1,83,6000
2,Bronx,92.751479,54626,Cozy bedroom by Yankee Stadium,190409,Waundell,Highbridge,40.83075,-73.93058,Private room,55,1,181,2020-03-06,1.66,3,364,5500
3,Bronx,92.751479,63588,LL3,295128,Carol Gloria,Clason Point,40.81309,-73.85514,Private room,89,2,0,NaN,NaN,7,270,8900
4,Bronx,92.751479,63610,DOMINIQUE'S NY mini efficiency pad* SANITIZED*...,310670,Vie,Eastchester,40.88100,-73.83511,Entire home/apt,102,2,44,2020-06-28,0.49,9,363,10200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46522,Staten Island,110.947214,44288244,Huge Private Room/Suite @ Ferry.,117492425,Dine,St. George,40.64602,-74.07896,Private room,49,4,0,NaN,NaN,8,365,4900
46523,Staten Island,110.947214,44322571,Rosebank Townhome,299411542,Karen,Clifton,40.61847,-74.06974,Private room,300,1,0,NaN,NaN,2,179,30000
46524,Staten Island,110.947214,44322911,Oakwood Room,299411542,Karen,Oakwood,40.56436,-74.13019,Private room,150,1,0,NaN,NaN,2,179,15000
46525,Staten Island,110.947214,44415969,Style Home away from home,121399223,Weifeng(Daniel),Tompkinsville,40.63380,-74.08298,Entire home/apt,160,1,1,2020-08-02,1.00,3,365,16000
46526,Staten Island,110.947214,44574046,Home away from home,356621108,Andrew,Howland Hook,40.63348,-74.16950,Entire home/apt,250,1,0,NaN,NaN,1,14,25000

In [24]:
# 3. Save your joined csv as `joined.csv` into the data folder. 
joined.to_csv('/workspaces/ds-fall-2026/Week-01-Pandas/data/joined.csv', index=False)

In [25]:
# 4. Load your newly saved file, see if it looks the same.  If not, try saving with argument `index=False`
joined_loaded = pd.read_csv('/workspaces/ds-fall-2026/Week-01-Pandas/data/joined.csv')
joined_loaded

,neighbourhood_group,mean_price,id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,new_price
0,Bronx,92.751479,44096,Room with a View,190409,Waundell,Highbridge,40.83232,-73.93184,Private room,50,1,277,2020-02-25,2.29,3,364,5000
1,Bronx,92.751479,45935,Room in Beautiful Townhouse.,204586,L,Port Morris,40.80640,-73.92395,Private room,60,3,0,NaN,NaN,1,83,6000
2,Bronx,92.751479,54626,Cozy bedroom by Yankee Stadium,190409,Waundell,Highbridge,40.83075,-73.93058,Private room,55,1,181,2020-03-06,1.66,3,364,5500
3,Bronx,92.751479,63588,LL3,295128,Carol Gloria,Clason Point,40.81309,-73.85514,Private room,89,2,0,NaN,NaN,7,270,8900
4,Bronx,92.751479,63610,DOMINIQUE'S NY mini efficiency pad* SANITIZED*...,310670,Vie,Eastchester,40.88100,-73.83511,Entire home/apt,102,2,44,2020-06-28,0.49,9,363,10200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46522,Staten Island,110.947214,44288244,Huge Private Room/Suite @ Ferry.,117492425,Dine,St. George,40.64602,-74.07896,Private room,49,4,0,NaN,NaN,8,365,4900
46523,Staten Island,110.947214,44322571,Rosebank Townhome,299411542,Karen,Clifton,40.61847,-74.06974,Private room,300,1,0,NaN,NaN,2,179,30000
46524,Staten Island,110.947214,44322911,Oakwood Room,299411542,Karen,Oakwood,40.56436,-74.13019,Private room,150,1,0,NaN,NaN,2,179,15000
46525,Staten Island,110.947214,44415969,Style Home away from home,121399223,Weifeng(Daniel),Tompkinsville,40.63380,-74.08298,Entire home/apt,160,1,1,2020-08-02,1.00,3,365,16000
46526,Staten Island,110.947214,44574046,Home away from home,356621108,Andrew,Howland Hook,40.63348,-74.16950,Entire home/apt,250,1,0,NaN,NaN,1,14,25000

# Extra Credit
Every question below this cell is extra credit and optional.

### 2. (Very Easy) Find other cool Panda packages / add ons and show us what they can do well. And how you installed them.

### 3. (Medium) Use the grammys.csv data for the next section of questions.

1. Who was won Album of the Year in 2016?


2. Who won Best Rap Album in 2009?


3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

### (Hard) Load the Game Logs for 2022 and add the column names using a dictionary.  
* [Link to the data page](https://www.retrosheet.org/gamelogs/)
* [Link to the column names](https://procatinator.com/)
* haha, gotta find them yourself!

### (Extra Hard) Download the files for the past 5 years into a new folder and add them all into one data frame using pandas, then save that new file.
* Try to not hard code in the file names. We want to do this programmatically because what if we want to add new/more file names in the future.