# First print your name in the cell below then save this file. (or something nice about your instructor)

In [44]:
# In this cell print your name 

print("Ishmum Ibrahim")

Ishmum Ibrahim

# Data wrangling with Pandas exercise
* For this exercise we will be using the `listings.csv` data file.

In [45]:
import pandas as pd
import numpy as np

# Load in the data file using `pd.read_csv()`

In [46]:
# Load data here
df = pd.read_csv("./data/listings.csv")
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46522,44807522,Designer Gramercy Studio Townhouse by UNSQ,12941925,Brian,Manhattan,Gramercy,40.73433,-73.98383,Entire home/apt,145,7,0,NaN,NaN,1,164
46523,44807786,Cozy & comfy apt in the heart of Inwood Manhattan,284790520,Salar,Manhattan,Washington Heights,40.85820,-73.92733,Entire home/apt,87,6,0,NaN,NaN,2,85
46524,44811717,Comfortable safe environment 24hr security camera,362453686,Nicole,Brooklyn,East Flatbush,40.65399,-73.93287,Private room,59,3,0,NaN,NaN,1,90
46525,44814944,Upper West Side studio 86th Street,4039777,Fernando,Manhattan,Upper West Side,40.78731,-73.97029,Entire home/apt,80,30,0,NaN,NaN,1,113
46526,44818009,"5MIN D/N trains, NEAR THE BEACH, 50’ TO MANHATTAN",48098268,Marina,Brooklyn,Gravesend,40.59945,-73.98209,Private room,66,1,0,NaN,NaN,1,38

## Exercise 2 - Filtering

Return the following subsets of the dataframe.

1. How many listings are there with a price less than 100? 


2. Find how many listings there are in just Brooklyn.


3. Find how many listings there are in Brooklyn with a price less than 100.


4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.


5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  The prices for all other listings should be the same as the were before. 


6. What % of the rooms are private, and what % of the rooms are shared.  
    * Hint, use `.value_counts()`

In [47]:
# 1. How many listings are there with a price less than 100? 
count = 0
for cost in df["price"]:
    if cost < 100:
        count+=1
        
print(count)

22778

In [48]:
# 2. Make a new DataFrame of listings in Brooklyn named `df_bk` 
# and find how many listings in just Brooklyn.

df_bk = df[df["neighbourhood_group"] == "Brooklyn"]
df_bk

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295
8,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,88,4,180,2020-03-18,1.31,3,344
11,6848,Only 2 stops to Manhattan studio,15991,Allen & Irina,Brooklyn,Williamsburg,40.70837,-73.95352,Entire home/apt,109,2,181,2020-03-16,1.32,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46517,44802032,A very large room in Williamsburg,213793805,Omer,Brooklyn,Williamsburg,40.71970,-73.95632,Private room,55,14,0,NaN,NaN,1,45
46518,44802224,Unique & beautiful design! Skylights-Washer/dryer,143513836,Elisabeth,Brooklyn,Crown Heights,40.67302,-73.91695,Private room,61,30,0,NaN,NaN,5,363
46519,44803201,1200 SF Duplex apt in an old shoe factory/ mon...,921746,Michael + Josué,Brooklyn,Clinton Hill,40.69034,-73.96179,Entire home/apt,253,30,0,NaN,NaN,1,74
46524,44811717,Comfortable safe environment 24hr security camera,362453686,Nicole,Brooklyn,East Flatbush,40.65399,-73.93287,Private room,59,3,0,NaN,NaN,1,90
46526,44818009,"5MIN D/N trains, NEAR THE BEACH, 50’ TO MANHATTAN",48098268,Marina,Brooklyn,Gravesend,40.59945,-73.98209,Private room,66,1,0,NaN,NaN,1,38

In [49]:
# 3. Find how many listings there are in Brooklyn with a price less than 100.

print(len(df_bk[df_bk["price"] < 100]))

10473

In [50]:
# 4. Using `.isin()` select anyone that has the host name of Michael, David, John, and Daniel.
# How many total are there that have those names
print(len(df["host_name"].isin(["Michael", "David", "John", "Daniel"])))

46527

In [51]:
# 5. Create a new column called `adjusted_price` that has $100 added to every listing in Williamsburg.  
# The prices for all other listings should be the same as the were before. 

df["adjusted_price"] = 100

df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,adjusted_price
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365,100
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265,100
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365,100
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295,100
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46522,44807522,Designer Gramercy Studio Townhouse by UNSQ,12941925,Brian,Manhattan,Gramercy,40.73433,-73.98383,Entire home/apt,145,7,0,NaN,NaN,1,164,100
46523,44807786,Cozy & comfy apt in the heart of Inwood Manhattan,284790520,Salar,Manhattan,Washington Heights,40.85820,-73.92733,Entire home/apt,87,6,0,NaN,NaN,2,85,100
46524,44811717,Comfortable safe environment 24hr security camera,362453686,Nicole,Brooklyn,East Flatbush,40.65399,-73.93287,Private room,59,3,0,NaN,NaN,1,90,100
46525,44814944,Upper West Side studio 86th Street,4039777,Fernando,Manhattan,Upper West Side,40.78731,-73.97029,Entire home/apt,80,30,0,NaN,NaN,1,113,100
46526,44818009,"5MIN D/N trains, NEAR THE BEACH, 50’ TO MANHATTAN",48098268,Marina,Brooklyn,Gravesend,40.59945,-73.98209,Private room,66,1,0,NaN,NaN,1,38,100

In [52]:
# 6. What % of the rooms are private, and what % of the rooms are shared.  


private = (len(df[df["room_type"] == "Private room"])/len(df))*100
shared = (len(df[df["room_type"] == "Entire home/apt" ])/len(df))*100

print(private,shared)

45.444580566122895 51.57865325509919

# Exercise 3 - Grouping

1. Using `groupby`, count how many listings are in each neighbourhood_group.


2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 


3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 


4. Using `groupby`, find the median price for each room type in each neighbourhood_group.


5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices for each room type in each neighbourhood_group.

In [53]:
# 1. Using `groupby`, count how many listings are in each neighbourhood_group.

df_neighbourhood_group = df.groupby(["neighbourhood_group"]).size()
df_neighbourhood_group

neighbourhood_group
Bronx             1183
Brooklyn         18632
Manhattan        20580
Queens            5791
Staten Island      341
dtype: int64

In [54]:
# 2. Using `groupby`, find the mean price for each of the neighbourhood_groups. 

df_mean_price = df.groupby(["neighbourhood_group"])["price"].mean()
df_mean_price

neighbourhood_group
Bronx             92.751479
Brooklyn         120.225258
Manhattan        191.880466
Queens            99.754965
Staten Island    110.947214
Name: price, dtype: float64

In [55]:
# 2.5. Using `groupby`, find the mean price for each room_type. 
df_mean_price_room = df.groupby("room_type")["price"].mean()
df_mean_price_room

room_type
Entire home/apt    199.395950
Hotel room         275.015075
Private room        91.453084
Shared room         87.063830
Name: price, dtype: float64

In [56]:
# 3. Using `groupby` and `.agg()`, find the min and max price for each of the neighbourhood_groups. 

df_min_max = df.groupby("neighbourhood_group")["price"].agg(["min","max"])
df_min_max

                     min    max
neighbourhood_group
Bronx                 16   1404
Brooklyn               0  10000
Manhattan              0  10000
Queens                 0  10000
Staten Island         19   1200

In [57]:
# 4. Using `groupby`, find the mean price for each room_type in each neighbourhood_group.
df_neighbourhood_mean = df.groupby("neighbourhood_group")["price"].mean()
df_neighbourhood_mean

neighbourhood_group
Bronx             92.751479
Brooklyn         120.225258
Manhattan        191.880466
Queens            99.754965
Staten Island    110.947214
Name: price, dtype: float64

In [58]:
# 5. Using `groupby` and `.agg()`, find the count, min, max, mean, median, and std of the prices 
# for each room type in each neighbourhood_group.

df_neighbourhood_data = df.groupby("neighbourhood_group")["price"].agg(["count", "min", "max", "mean", "median", "std"])

df_neighbourhood_data

                     count  min    max        mean  median         std
neighbourhood_group
Bronx                 1183   16   1404   92.751479    69.0   95.787081
Brooklyn             18632    0  10000  120.225258    90.0  180.136376
Manhattan            20580    0  10000  191.880466   129.0  428.682578
Queens                5791    0  10000   99.754965    70.0  207.648739
Staten Island          341   19   1200  110.947214    79.0  122.676152

# Load, Merge, and Export files.
1. Load the `prices.csv` and the `n_listings.csv`
    * Having an error..? Inspect the actual csv file if you're having trouble

2. Do join that keeps all the records for each table.
    * Neighbourhood groups should include ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island',
       'LongIsland']

       
3. Save your joined csv as `joined.csv` into the data folder. 


4. Load your saved table and see if it looks the same or different that the DataFrame you used to create it.

In [59]:
# 1. Load the `prices.csv` and the `n_listings.csv`
df_prices = pd.read_csv("./data/prices.csv")
df_listings = pd.read_csv("./data/n_listings.csv")

df_prices
df_listings

  neighbourhood_group;n_listings
0                     Bronx;1183
1                 Brooklyn;18632
2                Manhattan;20580
3                LongIsland;4121

In [68]:
# 2. Do join that keeps all the records for each table.
df_prices_listings = df_prices.join(df_listings)

df_prices_listings

  neighbourhood_group   mean_price neighbourhood_group;n_listings
0               Bronx    92.751479                     Bronx;1183
1            Brooklyn   120.225258                 Brooklyn;18632
2           Manhattan   191.880466                Manhattan;20580
3              Queens    99.754965                LongIsland;4121
4       Staten Island   110.947214                            NaN

In [64]:
# 3. Save your joined csv as `joined.csv` into the data folder. 
df_prices_listings.to_csv("data/joined.csv", index=False)

In [66]:
# 4. Load your newly saved file, see if it looks the same.  If not, try saving with argument `index=False`

new_df =  pd.read_csv("data/joined.csv")
new_df

  neighbourhood_group   mean_price neighbourhood_group;n_listings
0               Bronx    92.751479                     Bronx;1183
1            Brooklyn   120.225258                 Brooklyn;18632
2           Manhattan   191.880466                Manhattan;20580
3              Queens    99.754965                LongIsland;4121
4       Staten Island   110.947214                            NaN

# Extra Credit
Every question below this cell is extra credit and optional.

### 2. (Very Easy) Find other cool Panda packages / add ons and show us what they can do well. And how you installed them.

### 3. (Medium) Use the grammys.csv data for the next section of questions.

1. Who was won Album of the Year in 2016?


2. Who won Best Rap Album in 2009?


3. How many awards was Kendrick Lamar nomiated for, and how many did he win...?

### (Hard) Load the Game Logs for 2022 and add the column names using a dictionary.  
* [Link to the data page](https://www.retrosheet.org/gamelogs/)
* [Link to the column names](https://procatinator.com/)
* haha, gotta find them yourself!

### (Extra Hard) Download the files for the past 5 years into a new folder and add them all into one data frame using pandas, then save that new file.
* Try to not hard code in the file names. We want to do this programmatically because what if we want to add new/more file names in the future.