# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1]:
# Import here.
import numpy as np
import pandas as pd

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

In [2]:
# Load the Food choices data set into a variable (e.g., df_food).

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [3]:
# Count by hand. (lol kidding)
len(df_food)

125

What are the columns and their types in this data set?

In [4]:
# Show the column names and their types.
df_food.dtypes

GPA                     str
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports             str
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight                  str
Length: 61, dtype: object

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns?

In [5]:
# Remove ‘em.
df_food = df_food[['calories_day', 'weight', 'Gender']]
df_food

     calories_day                    weight  Gender
0             NaN                       187       2
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
..            ...                       ...     ...
120           4.0                       156       1
121           2.0                       180       1
122           NaN                       120       1
123           4.0                       135       2
124           NaN                       135       1

[125 rows x 3 columns]

What about `NaN`s? How many are there?

In [6]:
# Count ‘em.
df_food.isna().sum()

calories_day    19
weight           2
Gender           0
dtype: int64

We gotta remove those `NaN`s―the entire row.

In [7]:
# Drop ‘em.

df_food = df_food.dropna()
df_food

     calories_day                    weight  Gender
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
5             3.0                       190       1
..            ...                       ...     ...
118           3.0                       140       1
119           3.0                       185       2
120           4.0                       156       1
121           2.0                       180       1
123           4.0                       135       2

[104 rows x 3 columns]

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [9]:
# Fix that.
df_food['weight'] = pd.to_numeric(df_food['weight'], errors='coerce')
df_food = df_food.dropna()
df_food

     calories_day  weight  Gender
1             3.0   155.0       1
4             2.0   190.0       1
5             3.0   190.0       1
6             3.0   180.0       2
7             3.0   137.0       1
..            ...     ...     ...
118           3.0   140.0       1
119           3.0   185.0       2
120           4.0   156.0       1
121           2.0   180.0       1
123           4.0   135.0       2

[101 rows x 3 columns]

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [10]:
# Savey save!
df_food.to_csv('cleaned_food_data.csv', index=False)

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

In [15]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set into a variable (e.g., df_salary).
df_salary = pd.read_csv('../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv', sep='\t')
df_salary

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28057,7/12/2024 22:52:01,35-44,Health care,Veterinarian,NaN,135000,NaN,USD,NaN,NaN,United States,Missouri,Wentzville,11 - 20 years,11 - 20 years,"Professional degree (MD, JD, etc.)",Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28059,7/24/2024 12:22:58,18-24,"Accounting, Banking & Finance",Risk Management Associate,NaN,1200,0.0,USD,NaN,NaN,Myanmar,Colorado,Yangon,2 - 4 years,2 - 4 years,Some college,Man,Asian or Asian American
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American
28061,8/20/2024 1:06:13,25-34,Health care,Clinical physiologist,NaN,1200000,NaN,Other,NGN,NaN,Nigeria,NaN,Lagos,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American

Was that hard? 🙃

#### rename the file to something that is better for all systems.  
* No spaces in filename (can use '_')
* all lower case

### Explore

You know the drill.

How much data did you just load?

In [16]:
# Count by hand. I’m dead serious.
len(df_salary)

28062

What are the columns and their types?

In [17]:
# Show the column names and their types.
df_salary.dtypes

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [19]:
# Rename ‘em.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race
df_salary.columns = [
    'timestamp',
    'age',
    'industry',
    'title',
    'title_context',
    'salary',
    'additional_compensation',
    'currency',
    'other_currency',
    'salary_context',
    'country',
    'state',
    'city',
    'total_yoe',
    'field_yoe',
    'highest_education_completed',
    'gender',
    'race'
]
df_salary.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [20]:
# List the unique industries and a count of their instances.
df_salary["industry"].value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new dataframe.

In [30]:
# Filtery filter. (Save it to a new variable, df_salary_tech.)
df_salary_tech = df_salary[df_salary['industry'] == 'Computing or Tech']

Do a sanity check to make sure that the only values you kept are the one you are filtered for.

In [31]:
# Sanity Check 
df_salary_tech["industry"].value_counts()

industry
Computing or Tech    4699
Name: count, dtype: int64

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [32]:
# Filtery filter for just the jobs that pay in USD!
df_salary_usd = df_salary_tech[df_salary_tech['currency'] == "USD"]
df_salary_usd.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,USA,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White

What we really want know is how each U.S. city pays in tech. What value in `country` represents the United States of America?

In [33]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary_usd['country'].value_counts()

country
United States               1576
USA                         1222
US                           412
U.S.                         108
United States of America      90
                            ...
Ghana                          1
Nigeria                        1
ss                             1
Nigeria                        1
Burma                          1
Name: count, Length: 76, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [35]:
# Replace them all with 'US'.
df_salary_usd['country'] = df_salary_usd['country'].replace(["United States of America", "USA", "US", "U.S.", "United States"], "US")
df_salary_usd

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,US,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",US,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,US,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,US,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28044,6/3/2024 16:15:43,18-24,Computing or Tech,Research Data Analyst Associate,NaN,60000,0.0,USD,NaN,NaN,US,Illinois,Evanston,2 - 4 years,1 year or less,College degree,Woman,White
28051,7/1/2024 20:05:58,25-34,Computing or Tech,Junior data analyst,NaN,35000,15000.0,USD,NaN,NaN,Usa,Alabama,Alabama,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American
28052,7/3/2024 14:02:01,25-34,Computing or Tech,Senior Global Public Relations Manager,NaN,144000,15000.0,USD,NaN,NaN,Usa,Massachusetts,Boise-but remote. Company located in Boston,8 - 10 years,8 - 10 years,Master's degree,Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,US,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American

Have a look at the count of each unique country again now.

In [37]:
# Count again.
df_salary_usd["country"].value_counts()

country
US                3408
United States       68
Usa                 59
USA                 56
usa                 28
                  ...
Ghana                1
Nigeria              1
ss                   1
Nigeria              1
Burma                1
Name: count, Length: 72, dtype: int64

Did you notice anything interesting?

In [40]:
# BONUS CREDIT: resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.
df_salary_usd['country'] = df_salary_usd['country'].str.strip().str.lower()
df_salary_usd['country'] = df_salary_usd['country'].replace(['us', 'usa', 'united states', 'united states of america', 'u.s.a.', 'u.s.'], 'US')

In [41]:

# BONUS CREDIT: if you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.
df_salary_usd['country'].value_counts()

country
US                         3705
canada                        5
israel                        5
u.s.a                         3
united state of america       2
unite states                  2
australia                     2
unitedstates                  2
india                         2
u.s                           2
singapore                     2
spain                         2
brazil                        2
united kingdom                2
new zealand                   2
poland                        2
france                        2
denmark                       2
nigeria                       2
uniyed states                 1
america                       1
puerto rico                   1
united state                  1
cuba                          1
danmark                       1
italy                         1
international                 1
united stated                 1
remote (philippines)          1
uruguay                       1
mexico                        1
united stateds                1
isa                           1
pakistan                      1
netherlands                   1
china                         1
san francisco                 1
romania                       1
japan                         1
united stares                 1
australian                    1
jamaica                       1
unites states                 1
thailand                      1
colombia                      1
ghana                         1
ss                            1
burma                         1
Name: count, dtype: int64

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [42]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
df_salary_usd.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

TypeError: dtype 'str' does not support operation 'mean'

Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed.

In [43]:
# Fix it.
df_salary_usd['salary'] = df_salary_usd['salary'].str.replace(',', '')
df_salary_usd['salary'] = pd.to_numeric(df_salary_usd['salary'])

Let’s try that again.

In [44]:
# Try it again. Yeah!
df_salary_usd.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

                                min           mean      max
state
Michigan, Texas, Washington  340000  340000.000000   340000
California, Oregon           200000  200000.000000   200000
California, Colorado         176000  176000.000000   176000
Georgia, Massachusetts       175000  175000.000000   175000
Florida                       28800  157457.232143  2600000
...                             ...            ...      ...
Louisiana                     35360   83269.090909   150000
Massachusetts, Pennsylvania   83000   83000.000000    83000
California, Maryland          81500   81500.000000    81500
Arkansas                          4   74257.000000   144000
Alabama, Montana              72000   72000.000000    72000

[66 rows x 3 columns]

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [45]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_salary_usd['timestamp'] = pd.to_datetime(df_salary_usd['timestamp'])

df_salary_recent = df_salary_usd[df_salary_usd['timestamp'].dt.year.isin([2021, 2022, 2023])]

df_salary_recent.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

                                  min           mean     max
state
Michigan, Texas, Washington    340000  340000.000000  340000
California, Oregon             200000  200000.000000  200000
California, Colorado           176000  176000.000000  176000
Georgia, Massachusetts         175000  175000.000000  175000
Alabama, District of Columbia  156000  156000.000000  156000
...                               ...            ...     ...
Louisiana                       35360   83269.090909  150000
Massachusetts, Pennsylvania     83000   83000.000000   83000
Arkansas                        55000   81682.300000  144000
California, Maryland            81500   81500.000000   81500
Alabama, Montana                72000   72000.000000   72000

[66 rows x 3 columns]

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

In [47]:
df_salary_bonus = df_salary.copy()

# Keep only USD salaries
df_salary_bonus = df_salary_bonus[
    df_salary_bonus['currency'] == 'USD'
]

# Normalize country text
df_salary_bonus['country'] = (
    df_salary_bonus['country']
    .str.strip()
    .str.lower()
)

# Convert U.S. variations to one value
df_salary_bonus['country'] = df_salary_bonus['country'].replace(
    ['us', 'usa', 'united states', 'united states of america'],
    'US'
)

# Keep only U.S.
df_salary_bonus = df_salary_bonus[
    df_salary_bonus['country'] == 'US'
]

# Clean salary and convert it to numeric
df_salary_bonus['salary'] = (
    df_salary_bonus['salary']
    .str.replace(',', '', regex=False)
)

df_salary_bonus['salary'] = pd.to_numeric(
    df_salary_bonus['salary'],
    errors='coerce'
)

# Drop rows where salary could not be converted
df_salary_bonus = df_salary_bonus.dropna(subset=['salary'])

# Minimum, mean, and maximum salary by state
df_salary_bonus.groupby('state')['salary'].agg(
    ['min', 'mean', 'max']
).sort_values('mean', ascending=False)

,min,mean,max
state,,,
"Michigan, Texas, Washington",340000,340000.000000,340000
"Indiana, Ohio",245000,245000.000000,245000
Alaska,27040,238025.887097,10000000
"Colorado, Nevada",190000,190000.000000,190000
"California, Montana",185000,185000.000000,185000
...,...,...,...
"District of Columbia, Washington",35000,35000.000000,35000
"Delaware, Pennsylvania",35000,35000.000000,35000
"Alabama, California",29120,29120.000000,29120
"District of Columbia, Maryland, Pennsylvania, Virginia",27040,27040.000000,27040
"Maryland, New York",14000,14000.000000,14000

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

In [48]:
salary_by_state = df_salary_bonus.groupby('state')['salary'].agg(
    ['min', 'mean', 'max']
).sort_values('mean', ascending=False)

salary_by_state.style.format({
    'min': '${:,.2f}',
    'mean': '${:,.2f}',
    'max': '${:,.2f}'
})

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

In [50]:
valid_states = [
    'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
    'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia',
    'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa',
    'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
    'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri',
    'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey',
    'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio',
    'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina',
    'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
    'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'
]

df_salary_bonus = df_salary_bonus[
    df_salary_bonus['state'].isin(valid_states)
]

df_salary_bonus.groupby('state')['salary'].agg(
    ['min', 'mean', 'max']
).sort_values('mean', ascending=False)

                  min           mean       max
state
Alaska          27040  238025.887097  10000000
California          0  114590.160400    875000
Washington         72  107230.274390   1260000
New York           80  105158.257252   3000000
New Jersey      14850  101466.065104   5000044
Massachusetts     155   98737.949759   1650000
Virginia           57   94971.660526   1300000
Connecticut         0   94039.280172   1900000
Illinois            0   90543.708298   1100000
Colorado           65   90184.292763    630000
Maryland            0   89885.892393    353200
Oregon              0   89657.068220    320000
Texas               0   88747.016543   1200000
Delaware        35000   88359.833333    220000
Utah            18720   87525.297436    576000
Georgia             0   86585.849421    860000
Florida           150   83844.512770   2600000
Pennsylvania       55   83307.380849   1100000
Minnesota          40   81920.407246    321250
New Mexico         78   81606.489583    300000
North Carolina  13600   81477.362847    560000
Arizona         12000   80364.693878    380000
Nevada             55   79637.741573    425000
Rhode Island    18000   77610.213333    200000
Hawaii          12000   76930.482759    500000
Michigan           55   76730.402299    500000
Wisconsin           1   76390.401345    920000
Tennessee       20800   76062.423358    657900
Ohio               36   75938.313505    954000
Missouri           70   75116.396923    335000
Arkansas        26000   74712.405797    488000
Indiana           105   73051.071875    925000
New Hampshire      55   73033.655172    208000
Nebraska        18000   72473.805825    224000
Louisiana       17000   71901.233871    253300
Vermont         24960   71169.375000    200000
Alabama            54   71100.654867    350000
Idaho              38   70652.718750    312000
Iowa            13000   68140.637427    200000
Kansas             52   67951.033784    167000
South Carolina      0   66379.121429    250000
Kentucky            0   65639.105820    208000
Oklahoma        18000   65308.458716    180000
Maine           22000   65193.581967    173000
South Dakota    29000   64806.625000    150000
North Dakota        0   62174.342857    150000
Montana         19200   62076.616667    172000
Mississippi     25000   61865.833333    130000
West Virginia       0   58903.575000    125000
Wyoming         29000   58896.652174    140000

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)

In [51]:
salary_stats = (
    df_salary_bonus
    .groupby('state')['salary']
    .describe(percentiles=[0.05, 0.25, 0.50, 0.75, 0.95])
)

salary_stats = salary_stats[
    ['count', 'min', '5%', '25%', '50%', '75%', '95%', 'max']
]

# Sort by median (50th percentile)
salary_stats = salary_stats.sort_values(
    '50%',
    ascending=False
)

salary_stats

,count,min,5%,25%,50%,75%,95%,max
state,,,,,,,,
California,2500.0,0.0,42000.00,71712.50,100330.0,148000.00,220050.00,875000.0
Washington,1148.0,72.0,40000.00,65000.00,90325.5,135000.00,200825.00,1260000.0
New York,2103.0,80.0,41000.00,64000.00,89470.0,128000.00,210000.00,3000000.0
Massachusetts,1453.0,155.0,42000.00,64000.00,86000.0,120000.00,180000.00,1650000.0
Delaware,42.0,35000.0,41620.80,57073.25,84750.0,108750.00,168049.50,220000.0
Maryland,539.0,0.0,39900.00,60000.00,83000.0,110301.50,165000.00,353200.0
Connecticut,232.0,0.0,33617.50,61750.00,82000.0,100000.00,164500.00,1900000.0
Virginia,760.0,57.0,36955.00,58412.50,81000.0,115000.00,180000.00,1300000.0
Oregon,601.0,0.0,36400.00,60000.00,79000.0,110000.00,185000.00,320000.0
Colorado,608.0,65.0,38837.00,58209.00,76998.5,111250.00,165825.00,630000.0
Illinois,1169.0,0.0,37500.00,56000.00,76000.0,110000.00,171200.00,1100000.0
Texas,1209.0,0.0,35360.00,55000.00,76000.0,110000.00,175000.00,1200000.0
Minnesota,690.0,40.0,39520.00,55838.75,75000.0,100300.00,150000.00,321250.0
Georgia,518.0,0.0,32000.00,53000.00,75000.0,105000.00,175000.00,860000.0
New Jersey,384.0,14850.0,36150.00,58000.00,75000.0,103250.00,175850.00,5000044.0
North Carolina,576.0,13600.0,34769.25,51000.00,74250.0,98237.50,150000.00,560000.0
Utah,195.0,18720.0,33196.00,54175.00,73000.0,105000.00,176600.00,576000.0
Alaska,62.0,27040.0,40000.00,58250.00,72900.0,91500.00,144850.00,10000000.0
Rhode Island,75.0,18000.0,35820.00,50500.00,72000.0,94750.00,135300.00,200000.0
Pennsylvania,919.0,55.0,33748.00,52000.00,70700.0,100000.00,165200.00,1100000.0
Nevada,89.0,55.0,33056.80,52000.00,70000.0,95000.00,155800.00,425000.0
New Mexico,96.0,78.0,33820.00,51950.00,68000.0,109375.00,168000.00,300000.0
Michigan,522.0,55.0,31715.00,52230.00,68000.0,91525.00,147909.60,500000.0
Florida,509.0,150.0,31200.00,47840.00,67000.0,98000.00,162600.00,2600000.0
Arizona,294.0,12000.0,34234.65,50000.00,67000.0,100000.00,155700.00,380000.0
Wisconsin,446.0,1.0,34125.00,50000.00,66000.0,89000.00,145000.00,920000.0
Ohio,622.0,36.0,33000.00,50000.00,66000.0,88761.25,150000.00,954000.0
Indiana,320.0,105.0,34850.00,48825.00,65000.0,84752.50,135010.00,925000.0
Nebraska,103.0,18000.0,32620.10,47180.00,65000.0,88500.00,139500.00,224000.0
New Hampshire,116.0,55.0,30972.00,46600.00,65000.0,88625.00,143001.25,208000.0
Missouri,325.0,70.0,30560.00,47500.00,65000.0,94000.00,145000.00,335000.0
Tennessee,274.0,20800.0,32879.60,47262.50,63250.0,86500.00,160346.00,657900.0
Hawaii,29.0,12000.0,30984.00,53000.00,62700.0,75000.00,120000.00,500000.0
Iowa,171.0,13000.0,30000.00,47840.00,62500.0,82500.00,121375.00,200000.0
Vermont,64.0,24960.0,33354.00,50000.00,62000.0,84750.00,124700.00,200000.0
Louisiana,124.0,17000.0,29552.00,45503.25,61900.0,85000.00,149550.00,253300.0
Kansas,148.0,52.0,33350.00,45375.00,61250.0,81000.00,123250.00,167000.0
Idaho,96.0,38.0,30900.00,45940.00,60500.0,78500.00,130000.00,312000.0
South Dakota,24.0,29000.0,31470.00,44937.50,60175.0,69728.75,127850.00,150000.0
Alabama,113.0,54.0,27200.00,45000.00,60000.0,85000.00,147400.00,350000.0
Arkansas,69.0,26000.0,30680.00,46000.00,60000.0,85000.00,144600.00,488000.0
North Dakota,35.0,0.0,27584.00,45000.00,59000.0,75000.00,110500.00,150000.0
Kentucky,189.0,0.0,29000.00,43500.00,58635.0,78000.00,130000.00,208000.0
Maine,122.0,22000.0,34352.05,43625.00,58500.0,83750.00,114950.00,173000.0
South Carolina,140.0,0.0,29120.00,43420.00,56750.0,80375.00,130450.00,250000.0
Oklahoma,109.0,18000.0,27014.40,42000.00,54000.0,80000.00,134200.00,180000.0
Mississippi,48.0,25000.0,31070.00,37215.75,53500.0,82250.00,114400.00,130000.0
Wyoming,23.0,29000.0,31803.20,43250.00,50004.0,71500.00,97200.00,140000.0
Montana,60.0,19200.0,33975.40,37375.00,49700.0,85000.00,128100.00,172000.0
West Virginia,40.0,0.0,25651.75,40750.00,49544.0,72300.00,117640.20,125000.0