# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [2]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

In [ ]:
# Load the Food choices data set into a variable (e.g., df_food).

food_data_set_path = 'data/food_coded.csv'

df_food = pd.read_csv('data/food_coded.csv')

### Explore the Data

How much data did you just load?

In [ ]:
# Count by hand. (lol kidding)
df_food.size

What are the columns and their types in this data set?

In [ ]:
# Show the column names and their types.
df_food.dtypes

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns?

In [ ]:
# Remove ‘em.
df_clean = df_food[['calories_day', 'weight', 'Gender']]
print(df_clean)

What about `NaN`s? How many are there?

In [ ]:
# Count ‘em.
df_clean.isna()

We gotta remove those `NaN`s―the entire row.

In [ ]:
# Drop ‘em.
df_clean = df_clean.dropna()

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [ ]:
# Fix that.
columns = ['weight', 'calories_day', 'Gender']
df_clean[columns] = df_clean[columns].apply(pd.to_numeric, errors='coerce')
df_num = df_clean.dropna()

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [ ]:
# Savey save!
to_csv_path = 'data/food_cleaned.csv'
df_clean.to_csv(to_csv_path, index=False)

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

In [3]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set into a variable (e.g., df_salary).
df_salary = pd.read_csv("./data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv", sep='\t')

Was that hard? 🙃

#### rename the file to something that is better for all systems.  
* No spaces in filename (can use '_')
* all lower case

### Explore

You know the drill.

How much data did you just load?

In [4]:
# Count by hand. I’m dead serious.
df_salary.size

505116

What are the columns and their types?

In [5]:
# Show the column names and their types.
df_salary.dtypes

Timestamp                                                                                                                                                                                                                                object
How old are you?                                                                                                                                                                                                                         object
What industry do you work in?                                                                                                                                                                                                            object
Job title                                                                                                                                                                                                                                object
If your job title needs additional context, please clarify here:                                                                                                                                                                         object
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)     object
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                             object
If "Other," please indicate the currency here:                                                                                                                                                                                           object
If your income needs additional context, please provide it here:                                                                                                                                                                         object
What country do you work in?                                                                                                                                                                                                             object
If you're in the U.S., what state do you work in?                                                                                                                                                                                        object
What city do you work in?                                                                                                                                                                                                                object
How many years of professional work experience do you have overall?                                                                                                                                                                      object
How many years of professional work experience do you have in your field?                                                                                                                                                                object
What is your highest level of education completed?                                                                                                                                                                                       object
What is your gender?                                                                                                                                                                                                                     object
What is your race? (Choose all that apply.)                                                                                                                                                                                              object
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [6]:
# Rename ‘em.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race
df_salary = df_salary.rename(columns={'Timestamp': 'timestamp', 
                                      'How old are you?': 'age', 
                                      'What industry do you work in?': 'industry', 
                                      'Job title': 'title', 
                                      'If your job title needs additional context, please clarify here:': 'title_context', 
                                      "What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)": 'salary', 
                                      'How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.': 'additional_compensation', 
                                      'Please indicate the currency': 'currency', 
                                      'If "Other," please indicate the currency here: ': 'other_currency', 
                                      'If your income needs additional context, please provide it here:': 'salary_context', 
                                      'What country do you work in?': 'country', 
                                      "If you're in the U.S., what state do you work in?": 'state', 
                                      'What city do you work in?': 'city', 
                                      'How many years of professional work experience do you have overall?': 'total_yoe', 
                                      'How many years of professional work experience do you have in your field?': 'field_yoe', 
                                      'What is your highest level of education completed?': 'highest_education',
                                      'What is your gender?': 'gender',
                                      'What is your race? (Choose all that apply.)': 'race'})
print(df_salary.dtypes)

timestamp                   object
age                         object
industry                    object
title                       object
title_context               object
salary                      object
additional_compensation    float64
currency                    object
other_currency              object
salary_context              object
country                     object
state                       object
city                        object
total_yoe                   object
field_yoe                   object
highest_education           object
gender                      object
race                        object
dtype: object

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [7]:
# List the unique industries and a count of their instances.
df_industry = df_salary['industry'].value_counts()
print(df_industry)

industry
Computing or Tech                        4699
Education (Higher Education)             2464
Nonprofits                               2419
Health care                              1896
Government and Public Administration     1889
                                         ...
Warehousing                                 1
Education (Early Childhood Education)       1
SAAS                                        1
Health and Safety                           1
Aerospace Manufacturing                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new dataframe.

In [8]:
# Filtery filter. (Save it to a new variable, df_salary_tech.)
df_salary_tech = df_salary[df_salary['industry'] == 'Computing or Tech']
print(df_salary_tech)

                timestamp    age           industry  \
1      4/27/2021 11:02:22  25-34  Computing or Tech
8      4/27/2021 11:03:01  45-54  Computing or Tech
43     4/27/2021 11:04:04  25-34  Computing or Tech
44     4/27/2021 11:04:04  25-34  Computing or Tech
46     4/27/2021 11:04:07  35-44  Computing or Tech
...                   ...    ...                ...
28050   7/1/2024 13:38:46  25-34  Computing or Tech
28051   7/1/2024 20:05:58  25-34  Computing or Tech
28052   7/3/2024 14:02:01  25-34  Computing or Tech
28058  7/23/2024 17:51:03  25-34  Computing or Tech
28060  7/26/2024 11:20:45  18-24  Computing or Tech

                                              title  \
1          Change & Internal Communications Manager
8                                   Systems Analyst
43                      Principal Software Engineer
44                             Intelligence Analyst
46                                 Mobile developer
...                                             ...
28050  Research & Systems Technician Data Analytics
28051                          Junior data analyst
28052        Senior Global Public Relations Manager
28058                             Systems Architect
28060                                            IT

                      title_context   salary  additional_compensation  \
1                               NaN   54,600                   4000.0
8      Data developer/ETL Developer  112,000                  10000.0
43                              NaN  187,500                   5000.0
44                              NaN  110,000                  20000.0
46                              NaN  144,600                   2500.0
...                             ...      ...                      ...
28050                           NaN    22000                      NaN
28051                           NaN    35000                  15000.0
28052                           NaN   144000                  15000.0
28058                           NaN   109000                      NaN
28060                           NaN     1700                     10.0

      currency other_currency                 salary_context         country  \
1          GBP            NaN                            NaN  United Kingdom
8          USD            NaN                            NaN              US
43         USD            NaN                            NaN   United States
44         USD            NaN  Around 20,000 a year in stock             USA
46         USD            NaN                            NaN             USA
...        ...            ...                            ...             ...
28050      EUR            NaN                            NaN           Spain
28051      USD            NaN                            NaN             Usa
28052      USD            NaN                            NaN             Usa
28058      USD            NaN                            NaN             USA
28060      USD            NaN                            NaN           Burma

               state                                          city  \
1                NaN                                     Cambridge
8           Missouri                                     St. Louis
43      Pennsylvania                                    Pittsburgh
44          Virginia                                 Arlington, VA
46     Massachusetts                                        Boston
...              ...                                           ...
28050            NaN                                     Barcelona
28051        Alabama                                      Alabama
28052  Massachusetts  Boise-but remote. Company located in Boston
28058        Georgia                                       Atlanta
28060            NaN                                        Yangon

           total_yoe       field_yoe highest_education      gender  \
1       8 - 10 years       5-7 years    College degree  Non-binary
8      21 - 30 years   21 - 30 years    College degree       Woman
43      8 - 10 years       5-7 years    College degree       Woman
44      8 - 10 years    8 - 10 years   Master's degree         Man
46         5-7 years       5-7 years               PhD       Woman
...              ...             ...               ...         ...
28050    2 - 4 years     2 - 4 years    College degree         Man
28051    2 - 4 years     2 - 4 years    College degree       Woman
28052   8 - 10 years    8 - 10 years   Master's degree       Woman
28058      5-7 years       5-7 years    College degree         Man
28060    2 - 4 years  1 year or less      Some college         Man

                                      race
1                                    White
8                                    White
43                                   White
44                                   White
46                                   White
...                                    ...
28050  Hispanic, Latino, or Spanish origin
28051            Black or African American
28052                                White
28058                                White
28060              Asian or Asian American

[4699 rows x 18 columns]

Do a sanity check to make sure that the only values you kept are the one you are filtered for.

In [9]:
# Sanity Check 
print(df_salary_tech.count())
# print(df_salary_tech.shape)
# print(df_salary_tech.head())
# print(df_salary_tech.tail())

timestamp                  4699
age                        4699
industry                   4699
title                      4699
title_context               882
salary                     4699
additional_compensation    3584
currency                   4699
other_currency               54
salary_context              642
country                    4699
state                      3705
city                       4686
total_yoe                  4699
field_yoe                  4699
highest_education          4654
gender                     4674
race                       4667
dtype: int64

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [10]:
# Filtery filter for just the jobs that pay in USD!
df_salary_usd = df_salary_tech[df_salary_tech['currency'] == 'USD']
print(df_salary_usd.head(10))

             timestamp    age           industry  \
8   4/27/2021 11:03:01  45-54  Computing or Tech
43  4/27/2021 11:04:04  25-34  Computing or Tech
44  4/27/2021 11:04:04  25-34  Computing or Tech
46  4/27/2021 11:04:07  35-44  Computing or Tech
47  4/27/2021 11:04:09  35-44  Computing or Tech
53  4/27/2021 11:04:19  35-44  Computing or Tech
68  4/27/2021 11:04:36  25-34  Computing or Tech
74  4/27/2021 11:04:41  35-44  Computing or Tech
79  4/27/2021 11:04:49  35-44  Computing or Tech
95  4/27/2021 11:05:08  45-54  Computing or Tech

                                 title                 title_context   salary  \
8                      Systems Analyst  Data developer/ETL Developer  112,000
43         Principal Software Engineer                           NaN  187,500
44                Intelligence Analyst                           NaN  110,000
46                    Mobile developer                           NaN  144,600
47             Product Design Director                           NaN  200,850
53  Managed Services Sales Coordinator    Primarily proposal writing   72,000
68                Technical specialist                           NaN   34,000
74                         Tech Writer                           NaN   88,000
79             Senior Business Analyst                           NaN  125,000
95    senior web application developer                           NaN   98,166

    additional_compensation currency other_currency  \
8                   10000.0      USD            NaN
43                   5000.0      USD            NaN
44                  20000.0      USD            NaN
46                   2500.0      USD            NaN
47                  40000.0      USD            NaN
53                   3000.0      USD            NaN
68                   2000.0      USD            NaN
74                      NaN      USD            NaN
79                      NaN      USD            NaN
95                      0.0      USD            NaN

                   salary_context        country           state  \
8                             NaN             US        Missouri
43                            NaN  United States    Pennsylvania
44  Around 20,000 a year in stock            USA        Virginia
46                            NaN            USA   Massachusetts
47                            NaN            USA  North Carolina
53                            NaN  United States        Michigan
68                            NaN  United States       Minnesota
74                            NaN            USA        Maryland
79                            NaN             US        New York
95                            NaN  United States         Indiana

                    city      total_yoe      field_yoe highest_education  \
8              St. Louis  21 - 30 years  21 - 30 years    College degree
43            Pittsburgh   8 - 10 years      5-7 years    College degree
44         Arlington, VA   8 - 10 years   8 - 10 years   Master's degree
46                Boston      5-7 years      5-7 years               PhD
47           Chapel Hill  11 - 20 years  11 - 20 years    College degree
53                  Troy  11 - 20 years      5-7 years   Master's degree
68           Minneapolis      5-7 years      5-7 years    College degree
74  prefer not to answer  11 - 20 years   8 - 10 years    College degree
79              New York  11 - 20 years   8 - 10 years   Master's degree
95          Indianapolis  21 - 30 years  21 - 30 years    College degree

   gender                                               race
8   Woman                                              White
43  Woman                                              White
44    Man                                              White
46  Woman                                              White
47  Woman                                              White
53  Woman                                              White
68  Woman                                              White
74  Woman  Another option not listed here or prefer not t...
79  Woman                                              White
95    Man                                              White

What we really want know is how each U.S. city pays in tech. What value in `country` represents the United States of America?

In [11]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary_usd.value_counts('country', ascending=False)

country
United States               1576
USA                         1222
US                           412
U.S.                         108
United States of America      90
                            ...
Uruguay                        1
Uniyed states                  1
ss                             1
denmark                        1
singapore                      1
Name: count, Length: 76, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [12]:
# Replace them all with 'US'.
df_US = df_salary_usd['country'].head(5).replace(['US', 'United States', 'USA', 'U.S.', 'U.S.A.', 'United States of America'], 'US')
print(df_US.value_counts())

country
US    5
Name: count, dtype: int64

Have a look at the count of each unique country again now.

In [13]:
# Count again.
print(df_salary['country'].value_counts())

country
United States                                8992
USA                                          7934
US                                           2610
Canada                                       1570
United States                                 667
                                             ...
Aotearoa New Zealand                            1
croatia                                         1
Company in Germany. I work from Pakistan.       1
Liechtenstein                                   1
United States is America                        1
Name: count, Length: 379, dtype: int64

Did you notice anything interesting?

In [20]:
# BONUS CREDIT: resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

df_US_clean = df_salary_usd['country']

us_values = {
    'us',
    'usa',
    'united states',
    'u.s.',
    'u.s.a.',
    'united states of america'
}

mask = df_US_clean.str.strip().str.casefold().isin(us_values)
df_US_clean.loc[mask] = 'US'

print(df_US_clean.value_counts())
# can't account for misspellings

country
US                         3705
Israel                        5
Canada                        4
United State of America       2
Australia                     2
U.S                           2
India                         2
UnitedStates                  2
Unite States                  2
Spain                         2
Poland                        2
United Kingdom                2
Brazil                        2
New Zealand                   2
France                        2
U.S.A                         2
Italy                         1
International                 1
Puerto Rico                   1
Uniyed states                 1
America                       1
Singapore                     1
Remote (philippines)          1
United Stated                 1
United State                  1
Cuba                          1
Danmark                       1
Uruguay                       1
Canada                        1
singapore                     1
ISA                           1
United Stateds                1
Pakistan                      1
Netherlands                   1
China                         1
San Francisco                 1
Mexico                        1
Romania                       1
Japan                         1
United Stares                 1
Australian                    1
Denmark                       1
Jamaica                       1
Unites States                 1
Thailand                      1
U.S.A                         1
Colombia                      1
denmark                       1
Ghana                         1
Nigeria                       1
ss                            1
Nigeria                       1
Burma                         1
Name: count, dtype: int64

C:\Users\holdi\AppData\Local\Temp\ipykernel_12304\763637129.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_US_clean.loc[mask] = 'US'

In [21]:

## BONUS CREDIT: if you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.
print(df_US_clean.value_counts())

country
US                         3705
Israel                        5
Canada                        4
United State of America       2
Australia                     2
U.S                           2
India                         2
UnitedStates                  2
Unite States                  2
Spain                         2
Poland                        2
United Kingdom                2
Brazil                        2
New Zealand                   2
France                        2
U.S.A                         2
Italy                         1
International                 1
Puerto Rico                   1
Uniyed states                 1
America                       1
Singapore                     1
Remote (philippines)          1
United Stated                 1
United State                  1
Cuba                          1
Danmark                       1
Uruguay                       1
Canada                        1
singapore                     1
ISA                           1
United Stateds                1
Pakistan                      1
Netherlands                   1
China                         1
San Francisco                 1
Mexico                        1
Romania                       1
Japan                         1
United Stares                 1
Australian                    1
Denmark                       1
Jamaica                       1
Unites States                 1
Thailand                      1
U.S.A                         1
Colombia                      1
denmark                       1
Ghana                         1
Nigeria                       1
ss                            1
Nigeria                       1
Burma                         1
Name: count, dtype: int64

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [39]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
df_salary.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values(by='mean', ascending=False)

KeyError: 'state'

Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed.

In [40]:
# Fix it.
df_salary['salary'].dtype # check the data type of the salary column
df_salary['salary'] = pd.to_numeric(df_salary['salary'], errors='coerce')
df_salary['salary'].dtype

dtype('float64')

Let’s try that again.

In [41]:
# Try it again. Yeah!
df_salary.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values(by='mean', ascending=False)

                                   min        mean         max
state
Alabama, South Carolina      5000000.0  5000000.00   5000000.0
Alaska                         47840.0   702486.75  10000000.0
Michigan, Texas, Washington   340000.0   340000.00    340000.0
California, Oregon            200000.0   200000.00    200000.0
California, Colorado          176000.0   176000.00    176000.0
...                                ...         ...         ...
North Carolina, Utah               NaN         NaN         NaN
Ohio, Washington                   NaN         NaN         NaN
Ohio, Wyoming                      NaN         NaN         NaN
Texas, Virginia                    NaN         NaN         NaN
Utah, Vermont                      NaN         NaN         NaN

[134 rows x 3 columns]

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [34]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_salary['timestamp'] = pd.to_datetime(df_salary['timestamp'], errors='coerce')

df_filtered = df_salary[
    df_salary['timestamp'].dt.year.isin([2021, 2022, 2023])
]

print(
    df_filtered.groupby('state')['salary']
    .agg(['min', 'mean', 'max'])
    .sort_values(by='mean', ascending=False)
)
print(df_filtered.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values(by='mean', ascending=False))

                                  min           mean       max
state
Michigan, Texas, Washington  340000.0  340000.000000  340000.0
California, Oregon           200000.0  200000.000000  200000.0
California, Colorado         176000.0  176000.000000  176000.0
New Jersey, New York         135000.0  138666.666667  141000.0
Indiana, Massachusetts       132000.0  132000.000000  132000.0
...                               ...            ...       ...
North Carolina, Utah              NaN            NaN       NaN
Ohio, Washington                  NaN            NaN       NaN
Ohio, Wyoming                     NaN            NaN       NaN
Texas, Virginia                   NaN            NaN       NaN
Utah, Vermont                     NaN            NaN       NaN

[131 rows x 3 columns]
                                  min           mean       max
state
Michigan, Texas, Washington  340000.0  340000.000000  340000.0
California, Oregon           200000.0  200000.000000  200000.0
California, Colorado         176000.0  176000.000000  176000.0
New Jersey, New York         135000.0  138666.666667  141000.0
Indiana, Massachusetts       132000.0  132000.000000  132000.0
...                               ...            ...       ...
North Carolina, Utah              NaN            NaN       NaN
Ohio, Washington                  NaN            NaN       NaN
Ohio, Wyoming                     NaN            NaN       NaN
Texas, Virginia                   NaN            NaN       NaN
Utah, Vermont                     NaN            NaN       NaN

[131 rows x 3 columns]

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

In [44]:
df_salary.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values(by='mean', ascending=False)

                                   min        mean         max
state
Alabama, South Carolina      5000000.0  5000000.00   5000000.0
Alaska                         47840.0   702486.75  10000000.0
Michigan, Texas, Washington   340000.0   340000.00    340000.0
California, Oregon            200000.0   200000.00    200000.0
California, Colorado          176000.0   176000.00    176000.0
...                                ...         ...         ...
North Carolina, Utah               NaN         NaN         NaN
Ohio, Washington                   NaN         NaN         NaN
Ohio, Wyoming                      NaN         NaN         NaN
Texas, Virginia                    NaN         NaN         NaN
Utah, Vermont                      NaN         NaN         NaN

[134 rows x 3 columns]

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

In [ ]:
#find a way to account for all currencies and format respectively
formatted_salary = df_salary.style.format("${:,.2f}")
currency_symbols = {
    "USD": "$",
    "GBP": "£",
    "EUR": "€",
    "CAD": "C$",
    "AUD": "A$",
    "NZD": "NZ$",
    "JPY": "¥",
    "CHF": "CHF ",
    "INR": "₹",
    "SEK": "kr ",
    "NOK": "kr ",
    "DKK": "kr ",
    "BRL": "R$",
    "ZAR": "R ",
    "PLN": "zł ",
}

salary_display = df_salary[["salary", "currency"]].copy()

def format_salary(row):
    if pd.isna(row["salary"]):
        return ""
    symbol = currency_symbols.get(row["currency"], f'{row["currency"]} ')
    return f"{symbol}{row['salary']:,.2f}"

salary_display["salary"] = salary_display.apply(format_salary, axis=1)

salary_display.style.hide(axis="index")

TypeError: 'Styler' object is not subscriptable

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)