# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1596]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in c:\Users\axylo\.pyenv\pyenv-win\versions\3.12.10\Lib\site-packages (2.2.2)
Requirement already satisfied: numpy in c:\Users\axylo\.pyenv\pyenv-win\versions\3.12.10\Lib\site-packages (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\axylo\AppData\Roaming\Python\Python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\axylo\AppData\Roaming\Python\Python312\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\axylo\AppData\Roaming\Python\Python312\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\axylo\AppData\Roaming\Python\Python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: c:\Users\axylo\.pyenv\pyenv-win\versions\3.12.10\python.exe -m pip install --upgrade pip

In [1597]:
# Import here.

import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [1598]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [1599]:
# Count by hand. (lol kidding)

df_food # there's 125 rows, 61 columns

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,...,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,...,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,...,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,...,1.0,2.0,2,725.0,345,NaN,4,2,575,135

In [1600]:
# Try to print or display it nicely.

df_food_shape = df_food.shape # this is a tuple 

rows, cols = df_food_shape

print("Rows: ", rows)
print("Columns: ", cols)

Rows:  125
Columns:  61

What are the columns and their types in this data set?

In [1601]:
# Show the column names and their types.

df_food.columns

Index(['GPA', 'Gender', 'breakfast', 'calories_chicken', 'calories_day',
       'calories_scone', 'coffee', 'comfort_food', 'comfort_food_reasons',
       'comfort_food_reasons_coded', 'cook', 'comfort_food_reasons_coded.1',
       'cuisine', 'diet_current', 'diet_current_coded', 'drink',
       'eating_changes', 'eating_changes_coded', 'eating_changes_coded1',
       'eating_out', 'employment', 'ethnic_food', 'exercise',
       'father_education', 'father_profession', 'fav_cuisine',
       'fav_cuisine_coded', 'fav_food', 'food_childhood', 'fries', 'fruit_day',
       'grade_level', 'greek_food', 'healthy_feeling', 'healthy_meal',
       'ideal_diet', 'ideal_diet_coded', 'income', 'indian_food',
       'italian_food', 'life_rewarding', 'marital_status',
       'meals_dinner_friend', 'mother_education', 'mother_profession',
       'nutritional_check', 'on_off_campus', 'parents_cook', 'pay_meal_out',
       'persian_food', 'self_perception_weight', 'soup', 'sports', 'thai_food',
       'tortilla_calories', 'turkey_calories', 'type_sports', 'veggies_day',
       'vitamins', 'waffle_calories', 'weight'],
      dtype='object')

In [1602]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.

df_food.iloc[0:100]

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
5,2.25,1,1,610,3.0,980.0,2,"Candy, brownies and soda.","None, i don't eat comfort food. I just eat whe...",4.0,...,1.0,2.0,4,940.0,345,None.,1,2,1315,190
6,3.8,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.0,1.0,5,940.0,690,soccer,4,1,1315,180
7,3.3,1,1,720,3.0,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,...,1.0,2.0,1,725.0,500,none,4,2,1315,137
8,3.3,1,1,430,NaN,420.0,1,"Donuts, ice cream, chips",Boredom,2.0,...,2.0,2.0,5,725.0,345,none,3,2,760,180
9,3.3,1,1,430,3.0,315.0,2,"Mac and cheese, chocolate, and pasta","Stress, anger and sadness",1.0,...,1.0,1.0,4,580.0,345,field hockey,5,1,900,125
10,3.5,1,1,610,3.0,980.0,2,"Pasta, grandma homemade chocolate cake anythin...",Boredom,2.0,...,1.0,1.0,2,940.0,345,soccer,5,2,900,116
11,3.904,1,1,720,4.0,420.0,2,"chocolate, pasta, soup, chips, popcorn","sadness, stress, cold weather",3.0,...,1.0,1.0,5,940.0,500,Running,5,1,900,110
12,3.4,2,1,430,3.0,420.0,2,"Cookies, popcorn, and chips","Sadness, boredom, late night snack",3.0,...,2.0,1.0,3,940.0,500,Soccer and basketball,3,2,575,264
13,3.6,1,1,610,3.0,420.0,2,"ice cream, cake, chocolate","stress, boredom, special occasions",1.0,...,1.0,1.0,5,1165.0,850,intramural volleyball,5,2,1315,123
14,3.1,2,1,610,3.0,420.0,2,"Pizza, fruit, spaghetti, chicken and Potatoes","Friends, environment and boredom",2.0,...,1.0,1.0,4,940.0,500,Hockey,5,1,900,185
15,NaN,2,2,430,NaN,980.0,2,"cookies, donuts, candy bars",boredom,2.0,...,2.0,1.0,1,940.0,345,Hockey,1,2,1315,180
16,4,1,1,265,3.0,420.0,1,"Saltfish, Candy and Kit Kat",Stress,1.0,...,1.0,2.0,1,580.0,345,NaN,5,1,760,145
17,3.6,2,1,430,3.0,980.0,2,"chips, cookies, ice cream",I usually only eat comfort food when I'm bored...,2.0,...,1.0,1.0,3,940.0,500,hockey,4,2,900,170
18,3.4,1,1,720,3.0,980.0,1,"Chocolate, ice crea","Sadness, stress",3.0,...,2.0,2.0,1,1165.0,690,dancing,5,1,1315,135
19,2.2,2,1,430,2.0,420.0,2,"pizza, wings, Chinese","boredom, sadness, hungry",2.0,...,1.0,NaN,3,940.0,345,basketball,2,2,900,165
20,3.3,2,1,610,3.0,980.0,2,"Fast food, pizza, subs","happiness, satisfaction",7.0,...,1.0,1.0,1,1165.0,850,Soccer,3,2,1315,175
21,3.87,2,1,610,3.0,315.0,1,"chocolate, sweets, ice cream",Mostly boredom,2.0,...,2.0,1.0,5,725.0,500,Tennis,2,2,900,195
22,3.7,2,1,610,3.0,420.0,1,"burgers, chips, cookies","sadness, depression",3.0,...,1.0,1.0,4,940.0,850,tennis soccer gym,3,1,1315,185
23,3.7,2,2,610,3.0,420.0,2,"Chilli, soup, pot pie",Stress and boredom,1.0,...,1.0,1.0,4,940.0,690,Gaelic Football,4,1,1315,185
24,3.9,1,1,720,2.0,420.0,2,"Soup, pasta, brownies, cake","A long day, not feeling well, winter",6.0,...,2.0,2.0,4,940.0,500,none,4,2,1315,105
25,2.8,1,2,720,3.0,420.0,2,"chocolate, ice cream/milkshake, cookies",boredom,2.0,...,1.0,1.0,3,1165.0,690,Ice hockey,3,2,760,125
26,3.7,2,1,610,2.0,420.0,1,"Chips, ice cream, microwaveable foods","Boredom, lazyniss",2.0,...,2.0,1.0,2,1165.0,850,Hockey,3,2,1315,160
27,3,2,1,610,4.0,980.0,2,"Chicken fingers, pizza",Boredom,2.0,...,1.0,1.0,3,1165.0,500,Lacrosse,5,1,1315,175
28,3.2,2,1,610,2.0,420.0,2,"cookies, hot chocolate, beef jerky","survival, bored",2.0,...,1.0,2.0,1,940.0,500,NaN,2,1,1315,180
29,3.5,2,1,265,2.0,420.0,2,"Tomato soup, pizza, Fritos, Meatball sub, Dr. ...","Boredom, anger, drunkeness",2.0,...,1.0,2.0,5,580.0,500,NaN,4,1,760,167
30,4,1,1,720,3.0,420.0,2,"cookies, mac-n-cheese, brownies, french fries,","stress, boredom, cold weather",1.0,...,2.0,1.0,3,940.0,500,snowboarding,5,1,1315,115
31,4,2,1,610,3.0,420.0,2,"chips and dip, pepsi,","stres, boredom, and nighttime",1.0,...,2.0,2.0,4,940.0,690,none organized,5,1,1315,205
32,3.4,2,1,610,3.0,315.0,2,"Grandma's Chinese, Peruvian food from back hom...",Hunger and Boredom,4.0,...,1.0,1.0,5,580.0,345,Soccer,5,1,760,NaN
33,2.8,1,1,720,3.0,420.0,1,"Ice cream, cookies, Chinese food, and chicken...","boredom, sadness, and if it has a good taste.",2.0,...,1.0,2.0,1,1165.0,500,NaN,3,1,900,128
34,3.65,1,1,610,3.0,420.0,2,"french fries, chips, ice cream","boredom, stressed, sad",2.0,...,1.0,1.0,3,940.0,345,softball,4,1,1315,150
35,3,1,1,610,2.0,420.0,2,"mac n cheese, peanut butter and banana sandwic...",Boredom usually,2.0,...,1.0,1.0,2,940.0,690,Lacrosse,5,2,760,150
36,3.7,1,1,610,3.0,420.0,2,"pizza, doughnuts, mcdonalds",boredom,2.0,...,2.0,1.0,2,1165.0,500,Softball,5,2,900,150
37,3.4,1,1,720,4.0,420.0,2,"chocolate, chips, candy",Stress,1.0,...,1.0,1.0,5,940.0,500,Dancing,4,2,1315,170
38,3.89,1,1,610,3.0,980.0,2,"chocolate, popcorn, ice cream","boredom, stress",2.0,...,1.0,1.0,2,1165.0,690,Lacrosse,3,2,1315,150
39,3,2,1,720,NaN,980.0,2,Candy\rPop\rChocolate \rChipotle \rMoe's,No reasons,9.0,...,1.0,1.0,3,1165.0,690,Hockey,3,2,1315,175
40,3.4,2,1,430,3.0,315.0,1,"Pizza, Ice cream, fries, cereal, cookies",Usually if I'm sad or depressed.,3.0,...,1.0,1.0,3,940.0,500,wrestling,4,2,760,140
41,2.9,1,1,720,4.0,980.0,2,"Ice cream, chocolate, twizzlers",Tired,5.0,...,1.0,2.0,4,940.0,690,NaN,5,1,1315,120
42,3.6,1,1,610,3.0,420.0,2,"ice cream, cookie dough, cookies, cheese","Boredom!, sadness",2.0,...,1.0,2.0,4,940.0,500,NaN,4,2,900,135
43,3.5,1,1,430,2.0,980.0,1,"ice cream, cereal, and salt and vinegar chips","All of the above; sadness, boredom and confusion",3.0,...,2.0,2.0,5,940.0,345,no particular engagement,4,1,900,100
44,3.2,1,1,610,4.0,420.0,2,"Potato chips, ice cream, chocolate, cookies","Stress, boredom, craving",1.0,...,1.0,1.0,5,725.0,500,Volleyball,5,1,760,170
45,3.605,1,1,610,3.0,315.0,2,"Mac and cheese, fried chicken, cornbread","Hunger, boredom",4.0,...,1.0,2.0,5,940.0,500,none,5,2,900,113
46,3.8,2,1,430,2.0,420.0,1,"popcorn, chips, candy, & fries","sadness, boredom, & anger",3.0,...,1.0,1.0,3,725.0,345,soccer,4,2,900,168
47,2.8,2,1,430,NaN,980.0,2,"Chex-mix, Wegmans cookies, Cheez-Its","Boredom, happiness, distraught",2.0,...,1.0,1.0,1,940.0,345,wrestling & rowing,5,2,900,145
48,3.5,2,2,430,NaN,315.0,1,"pizza, ice cream, chips","stressed, upset, or just craving a cheat meal",1.0,...,2.0,1.0,4,940.0,345,Wrestling,5,1,760,155
49,3.83,2,1,430,3.0,315.0,2,"fried chicken. mashed potatoes, mac and cheese",They taste better than other food. They are a ...,5.0,...,2.0,2.0,4,1165.0,690,none,3,2,900,150
50,3.6,2,1,720,3.0,420.0,2,"Popcorn, Chex Mix, Pizza","Stress, boredom",1.0,...,1.0,2.0,1,1165.0,500,NaN,5,2,760,169
51,3.3,2,1,610,4.0,980.0,1,Burger,Lazy,5.0,...,1.0,1.0,5,1165.0,500,Hockey,4,1,1315,185
52,3.3,2,1,610,4.0,420.0,2,"Pizza, chocolate, and ice cream","Boredom, sadness and anger",2.0,...,2.0,1.0,3,1165.0,500,Lacrosse,5,2,900,200
53,3.292,2,1,610,NaN,980.0,2,"fries, chips, fried chicken, pizza, grapes","Boredom, sadness",2.0,...,1.0,2.0,1,940.0,500,NaN,4,1,1315,265
54,3.5,2,1,610,3.0,420.0,2,"peanut butter sandwich, pretzals, garlic bread","stress, anger and boredom",1.0,...,1.0,1.0,4,940.0,690,hockey,5,1,900,165
55,3.35,1,2,610,2.0,315.0,2,"chips, dip, fries, pizza","bored, stress",2.0,...,1.0,1.0,3,940.0,500,softball,4,2,900,192
56,3.8,2,1,720,4.0,315.0,2,"Pizza, Ice Cream, Chicken Wings",I usually only eat comfort foods when I am bor...,2.0,...,1.0,1.0,5,1165.0,500,Hockey,5,1,1315,175
57,2.8,1,1,610,4.0,980.0,2,Pizza chocolate chips bagels ice Capps,Just cause,9.0,...,2.0,1.0,2,725.0,345,softball,4,1,1315,140
58,3.5,1,1,610,3.0,420.0,2,"Chocolate, ice cream, pasta","Stress, boredom, sadness",1.0,...,1.0,1.0,5,1165.0,690,Skiing,5,1,1315,155
59,3.7,1,1,610,NaN,420.0,2,Mac n Cheese. Chips and salsa. Ice cream.,Boredom. Celebration.,2.0,...,2.0,1.0,5,1165.0,500,skiing,4,2,1315,155
60,3.6,1,1,610,4.0,420.0,2,"peanut butter, dessets, pretzels.","Sadness, boredom, lonely.",3.0,...,1.0,1.0,1,1165.0,690,Water polo and running,5,1,1315,135
61,Personal,1,1,610,2.0,980.0,2,"Macaroons, truffles, peanut butter n chocolate...","I do not really eat ""comfort food"" but I guess...",3.0,...,2.0,2.0,2,725.0,500,NaN,3,1,1315,118
62,3.9,2,1,610,4.0,980.0,2,"ice cream, cookies, ice cream","boredom, sadness",2.0,...,1.0,1.0,2,1165.0,850,Ice Hockey,4,1,1315,210
63,2.6,1,1,610,4.0,980.0,2,"carrots and ranch, pretzels, dark chocolate",sadness,3.0,...,NaN,1.0,4,1165.0,690,rowing,5,2,1315,180
64,3.5,1,1,610,3.0,420.0,1,"cookies, nutella, ice cream, coffee, fruit","Bordem, happiness, sadness",2.0,...,2.0,1.0,3,940.0,500,Volleyball,5,1,760,140
65,3.2,1,1,610,NaN,315.0,2,mac and cheese,boredom,2.0,...,1.0,2.0,4,725.0,500,NaN,3,2,900,112
66,3,1,1,720,3.0,420.0,1,"Chocolate, Popcorn, Icecream",sadness,3.0,...,1.0,1.0,3,940.0,500,tennis,5,1,900,125
67,3.6,1,1,610,2.0,420.0,1,"Ice cream, cake, mozzarella sticks, pierogies",Boredom,2.0,...,1.0,1.0,2,940.0,690,"Recreational Basketball, Equestrian Team",5,2,1315,144 lbs
68,3.2,1,1,430,3.0,315.0,1,"Chips, Mac and cheese, pizza, French fries","Stress, sadness, bored",1.0,...,1.0,1.0,4,725.0,500,soccer,5,2,760,145
69,3.67,1,2,720,4.0,420.0,2,"Pizza, burritos, slim jims","Boredom, stress, and it tastes good",2.0,...,2.0,2.0,5,1165.0,690,NaN,5,1,1315,130
70,3.73,1,1,610,3.0,980.0,2,"Broccoli, spaghetti squash, quinoa, and grille...","Bad day, bored, sadness",2.0,...,1.0,1.0,5,1165.0,500,Rec Volleyball,5,1,1315,140
71,4,1,1,720,NaN,420.0,2,"Chocolate, ice cream, cookie dough","Boredom, being in your period, and long bus ri...",2.0,...,1.0,1.0,4,1165.0,690,Softball,5,1,1315,140
72,3.1,2,2,610,3.0,980.0,2,"pizza, pretzels, fruit snacks, deli sandwhich","boredom, anger, happy",2.0,...,1.0,2.0,3,1165.0,345,NaN,5,1,1315,140
73,3.79 bitch,2,1,720,4.0,420.0,2,"Chips, ice cream","Boredom, stress",2.0,...,1.0,1.0,2,1165.0,850,baseball,4,1,1315,200
74,2.71,2,2,265,2.0,420.0,1,NaN,NaN,9.0,...,1.0,2.0,3,580.0,345,NaN,4,2,760,NaN
75,3,1,1,610,3.0,420.0,2,"mac and cheese, potato soup, ice cream, chips ...","sadness, stressed, boredom",3.0,...,1.0,2.0,4,940.0,500,I danced in high school,4,1,900,120
76,3.7,1,2,610,3.0,420.0,1,"chocolate, pizza, and mashed potatoes",boredom and stress,2.0,...,2.0,1.0,1,1165.0,690,horse back riding,2,2,1315,150
77,3.1,2,2,265,2.0,420.0,1,Pizza cookies steak,Boredom comfort hunger,2.0,...,2.0,1.0,2,725.0,345,Basketball,2,2,900,200
78,3,1,1,720,3.0,420.0,2,"chocolate, fruit, and ice cream","stress, boredom",1.0,...,1.0,1.0,3,580.0,345,competitive skiing,4,1,1315,135
79,3.9,2,1,720,3.0,420.0,2,Chips sweets popcorn,Boredom,2.0,...,1.0,1.0,5,1165.0,850,"Rowing, Running, and Cycling",4,2,1315,145
80,3.4,1,1,430,2.0,420.0,2,"Cookies, burgers, chicken noodle soup, ice cream","happiness, hunger, sadness",7.0,...,1.0,2.0,4,1165.0,500,NaN,2,1,900,130
81,3.5,1,2,610,3.0,420.0,1,"cake, French fries, chicken nuggets","boredom, sadness",2.0,...,2.0,1.0,4,725.0,500,softball and basketball,2,2,900,190
82,3.7,1,1,265,NaN,315.0,2,"pizza, ice cream, cookies",boredom,2.0,...,1.0,1.0,3,580.0,345,wrestling,3,2,575,170
83,3.7,1,1,430,3.0,420.0,2,"Mashed potatoes, pasta","Boredom, sadness, or with friends",2.0,...,1.0,1.0,5,940.0,690,Marching Band,4,2,1315,127
84,3.83,1,1,720,3.0,420.0,2,"Pasta dishes, Cheesecake, Pancakes","Sadness, Loneliness, Boredom",3.0,...,1.0,1.0,5,725.0,690,Collegiate Water Polo,5,1,760,167
85,2.6,1,1,265,3.0,315.0,2,"Ice cream, pizza, cookies",Mostly Stress,1.0,...,1.0,2.0,3,580.0,500,None right now,4,1,760,140
86,3,1,1,610,3.0,420.0,2,"Chinese food, moes, sponge candy, homemade las...","boredom, sadness",2.0,...,1.0,1.0,4,580.0,500,"volleyball, lacrosse",4,1,900,190
87,3.2,2,1,720,3.0,420.0,1,"pizza, pasta, mac and cheese",when i am sad or craving,3.0,...,1.0,1.0,1,1165.0,690,field hockey,4,1,1315,155
88,3.5,2,2,720,4.0,980.0,2,"Little Debbie snacks, donuts, pizza",NaN,9.0,...,1.0,2.0,5,1165.0,850,NaN,4,1,1315,175
89,3.2,1,1,610,3.0,420.0,2,"carrots, plantain chips, almonds, popcorn","stress, boredom, college as whole",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,129
90,3.68,2,1,720,4.0,420.0,2,"chips, ice cream, fruit snacks",boredom,2.0,...,2.0,1.0,3,1165.0,850,Fotball,4,1,1315,260
91,3.8,1,2,610,2.0,420.0,2,"Macaroni and cheese, chicken noodle soup, pizza",Boredom and stress,2.0,...,1.0,2.0,1,725.0,500,crew,1,2,900,135
92,3.3,2,2,720,NaN,420.0,2,"Chocolate, Chips, Ice cream, French Fires, Pizza","Stress, sadness, boredom",1.0,...,1.0,1.0,1,1165.0,690,"Football, Basketball, Volleyball, Golf",4,2,900,190
93,3.2,2,1,720,NaN,420.0,2,"Mac and cheese, lasagna, Chinese food","Boredom, sadness",2.0,...,1.0,2.0,5,1165.0,690,NaN,5,2,1315,165
94,3.75,2,1,610,3.0,420.0,2,"candy, Chinese, mcdonalds",laziness and hungover,5.0,...,1.0,1.0,5,940.0,690,"hockey, soccer, golf",5,1,1315,175
95,3.5,2,1,265,NaN,420.0,2,"Doritos, mac and cheese, ice cream","Boredom, hunger, snacking.",2.0,...,2.0,1.0,4,1165.0,690,Wrestling,4,2,1315,184
96,3.92,2,1,430,3.0,420.0,2,"Ice cream, cake, pop, pizza, and milkshakes.","Happiness, sadness, celebration.",7.0,...,1.0,2.0,3,725.0,500,Soccer,2,1,900,210
97,3.9,1,1,720,3.0,420.0,2,"Mac and Cheese, Pizza, Ice Cream and French Fr...","Boredom, anger and just being hungry in general.",2.0,...,1.0,1.0,3,1165.0,500,Running,5,2,760,155
98,3.9,2,1,720,3.0,315.0,1,"Soup, pasta, cake","Depression, comfort, accessibility",3.0,...,1.0,1.0,5,1165.0,690,Tennis,4,1,1315,185
99,3.2,1,1,430,4.0,420.0,1,"mac & cheese, frosted brownies, chicken nuggs","they are yummy, my boyfriend sometimes makes m...",3.0,...,1.0,1.0,1,1165.0,690,softball,5,1,900,165

In [1603]:
df_food.iloc[100:rows]

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
100,3.5,1,1,610,3.0,NaN,2,"watermelon, grapes, ice cream","Sad, bored, excited",3.0,...,1.0,1.0,5,NaN,500,"Volleyball, Track",5,2,900,125
101,3.4,1,1,610,NaN,420.0,2,"macaroni and cheese, stuffed peppers, hamburge...","boredom, stress, mood swings",2.0,...,1.0,2.0,3,1165.0,500,NaN,5,2,1315,160
102,NaN,1,1,610,4.0,420.0,2,"Pizza, mashed potatoes, spaghetti","Anger, sadness",3.0,...,1.0,2.0,2,940.0,500,NaN,5,1,900,135
103,3.7,1,1,610,3.0,420.0,2,"dark chocolate, terra chips, reese's cups(dark...","Anxiousness, watching TV I desire ""comfort food""",8.0,...,1.0,2.0,3,725.0,345,"When I can, rarely though play pool, darts, an...",5,1,760,130
104,Unknown,1,1,720,3.0,420.0,2,"Chips, chocolate, ,mozzarella sticks","Boredom, sadness, anxiety",2.0,...,2.0,2.0,5,940.0,690,None at the moment,5,1,1315,230
105,3,1,1,720,3.0,420.0,2,"ice cream, chips, candy","Boredom, laziness, anger",2.0,...,2.0,1.0,3,1165.0,690,volleyball,2,2,1315,125
106,3,1,1,430,3.0,315.0,2,"Pizza, soda, chocolate brownie, chicken tikka ...",Stress and sadness,NaN,...,1.0,2.0,4,580.0,500,NaN,5,2,760,130
107,3.8,1,1,430,3.0,420.0,1,"Chocolate, Pasta, Cookies","I am always stressed out, and bored when I am ...",NaN,...,1.0,2.0,5,1165.0,690,I used to play softball,4,2,900,165
108,3.8,1,1,430,2.0,420.0,2,"Candy, salty snacks, toast","Stress, sadness, boredom",NaN,...,1.0,1.0,2,580.0,345,Ice hockey,5,2,760,128
109,3.4,1,1,610,3.0,420.0,2,"Mac in cheese, pizza, mozzarella sticks","Stress, frustration, self-consciousness",NaN,...,1.0,2.0,2,940.0,690,None,3,1,1315,200
110,3.7,1,1,610,3.0,315.0,1,"Ice-cream, pizza, chocolate",Sadness and cravings,NaN,...,1.0,1.0,3,580.0,690,Volleyball,3,2,900,160
111,2.9,2,1,265,2.0,980.0,2,"snacks, chips,",boredom,NaN,...,1.0,2.0,1,725.0,345,NaN,3,2,1315,170
112,3.9,1,1,610,4.0,315.0,2,"Chocolate, Ice cream, pizza","Sadness, happiness and boredom",NaN,...,1.0,2.0,5,725.0,500,NaN,3,2,900,129
113,3.6,1,1,430,2.0,420.0,1,"ice cream, pizza, Chinese food",Boredom and sadness,NaN,...,1.0,2.0,2,1165.0,690,NaN,2,2,900,170
114,2.8,2,1,610,3.0,315.0,2,"Burgers, indian and korean food\r","sadness, happiness and hunger",NaN,...,1.0,1.0,5,940.0,850,"Tennis, Basketball",3,2,760,138
115,3.3,2,1,610,4.0,980.0,2,"chocolate bar, ice cream, pretzels, potato chi...","Stress, boredom and physical activity",NaN,...,1.0,1.0,1,1165.0,690,Hockey,2,2,1315,150
116,3.4,1,1,610,NaN,420.0,2,"Ice cream, chocolate, pizza, cucumber","loneliness, homework, boredom",NaN,...,1.0,2.0,5,725.0,345,none,5,1,1315,170
117,3.77,1,1,610,NaN,315.0,2,"Noodle ( any kinds of noodle), Tuna sandwich, ...",When i'm eating with my close friends/ Food s...,NaN,...,1.0,2.0,5,725.0,690,"No, I don't play sport.",3,1,760,113
118,3.63,1,1,430,3.0,420.0,1,"Chinese, chips, cake",Stress and boredom,NaN,...,1.0,2.0,4,940.0,345,NaN,5,2,1315,140
119,3.2,2,1,610,3.0,420.0,2,"chips, rice, chicken curry,","Happiness, boredom, social event",NaN,...,1.0,1.0,5,1165.0,690,Soccer,5,2,1315,185
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,...,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,...,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,...,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,...,1.0,2.0,2,725.0,345,NaN,4,2,575,135

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [1604]:
# Remove ‘em.

df_food_col_subset = df_food[["calories_day", "weight", "Gender"]]

df_food_col_subset

     calories_day                    weight  Gender
0             NaN                       187       2
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
..            ...                       ...     ...
120           4.0                       156       1
121           2.0                       180       1
122           NaN                       120       1
123           4.0                       135       2
124           NaN                       135       1

[125 rows x 3 columns]

In [1605]:
# Is there a second way to remove columns?

# idea from: https://stackoverflow.com/questions/11285613/selecting-multiple-columns-in-a-pandas-dataframe

df_food_col_subset = df_food.loc[:, ["calories_day", "weight", "Gender"]]

df_food_col_subset

     calories_day                    weight  Gender
0             NaN                       187       2
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
..            ...                       ...     ...
120           4.0                       156       1
121           2.0                       180       1
122           NaN                       120       1
123           4.0                       135       2
124           NaN                       135       1

[125 rows x 3 columns]

In [1606]:
# 🚀 Extra credit: What about a third way to remove columns?
df_food_col_subset = df_food.loc[:, df_food.columns.isin(["calories_day", "weight", "Gender"])]

df_food_col_subset

     Gender  calories_day                    weight
0         2           NaN                       187
1         1           3.0                       155
2         1           4.0  I'm not answering this.
3         1           3.0             Not sure, 240
4         1           2.0                       190
..      ...           ...                       ...
120       1           4.0                       156
121       1           2.0                       180
122       1           NaN                       120
123       2           4.0                       135
124       1           NaN                       135

[125 rows x 3 columns]

What about `NaN`s? How many are there?

In [1607]:
# Count ‘em.

print(df_food.isna().sum())

GPA                              2
Gender                           0
breakfast                        0
calories_chicken                 0
calories_day                    19
calories_scone                   1
coffee                           0
comfort_food                     1
comfort_food_reasons             2
comfort_food_reasons_coded      19
cook                             3
comfort_food_reasons_coded.1     0
cuisine                         17
diet_current                     1
diet_current_coded               0
drink                            2
eating_changes                   3
eating_changes_coded             0
eating_changes_coded1            0
eating_out                       0
employment                       9
ethnic_food                      0
exercise                        13
father_education                 1
father_profession                3
fav_cuisine                      2
fav_cuisine_coded                0
fav_food                         2
food_childhood                   1
fries                            0
fruit_day                        0
grade_level                      0
greek_food                       0
healthy_feeling                  0
healthy_meal                     1
ideal_diet                       1
ideal_diet_coded                 0
income                           1
indian_food                      0
italian_food                     0
life_rewarding                   1
marital_status                   1
meals_dinner_friend              3
mother_education                 3
mother_profession                2
nutritional_check                0
on_off_campus                    1
parents_cook                     0
pay_meal_out                     0
persian_food                     1
self_perception_weight           1
soup                             1
sports                           2
thai_food                        0
tortilla_calories                1
turkey_calories                  0
type_sports                     26
veggies_day                      0
vitamins                         0
waffle_calories                  0
weight                           2
dtype: int64

In [1608]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.

df_food_na_counts = pd.DataFrame(df_food.isna().sum(), columns=["NaN Count"])
print(df_food_na_counts)

                              NaN Count
GPA                                   2
Gender                                0
breakfast                             0
calories_chicken                      0
calories_day                         19
calories_scone                        1
coffee                                0
comfort_food                          1
comfort_food_reasons                  2
comfort_food_reasons_coded           19
cook                                  3
comfort_food_reasons_coded.1          0
cuisine                              17
diet_current                          1
diet_current_coded                    0
drink                                 2
eating_changes                        3
eating_changes_coded                  0
eating_changes_coded1                 0
eating_out                            0
employment                            9
ethnic_food                           0
exercise                             13
father_education                      1
father_profession                     3
fav_cuisine                           2
fav_cuisine_coded                     0
fav_food                              2
food_childhood                        1
fries                                 0
fruit_day                             0
grade_level                           0
greek_food                            0
healthy_feeling                       0
healthy_meal                          1
ideal_diet                            1
ideal_diet_coded                      0
income                                1
indian_food                           0
italian_food                          0
life_rewarding                        1
marital_status                        1
meals_dinner_friend                   3
mother_education                      3
mother_profession                     2
nutritional_check                     0
on_off_campus                         1
parents_cook                          0
pay_meal_out                          0
persian_food                          1
self_perception_weight                1
soup                                  1
sports                                2
thai_food                             0
tortilla_calories                     1
turkey_calories                       0
type_sports                          26
veggies_day                           0
vitamins                              0
waffle_calories                       0
weight                                2

In [1609]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

df_food_na_counts = \
    pd.DataFrame(df_food.isna().sum(), 
                 columns=["NaN Count"])
print(df_food_na_counts)

                              NaN Count
GPA                                   2
Gender                                0
breakfast                             0
calories_chicken                      0
calories_day                         19
calories_scone                        1
coffee                                0
comfort_food                          1
comfort_food_reasons                  2
comfort_food_reasons_coded           19
cook                                  3
comfort_food_reasons_coded.1          0
cuisine                              17
diet_current                          1
diet_current_coded                    0
drink                                 2
eating_changes                        3
eating_changes_coded                  0
eating_changes_coded1                 0
eating_out                            0
employment                            9
ethnic_food                           0
exercise                             13
father_education                      1
father_profession                     3
fav_cuisine                           2
fav_cuisine_coded                     0
fav_food                              2
food_childhood                        1
fries                                 0
fruit_day                             0
grade_level                           0
greek_food                            0
healthy_feeling                       0
healthy_meal                          1
ideal_diet                            1
ideal_diet_coded                      0
income                                1
indian_food                           0
italian_food                          0
life_rewarding                        1
marital_status                        1
meals_dinner_friend                   3
mother_education                      3
mother_profession                     2
nutritional_check                     0
on_off_campus                         1
parents_cook                          0
pay_meal_out                          0
persian_food                          1
self_perception_weight                1
soup                                  1
sports                                2
thai_food                             0
tortilla_calories                     1
turkey_calories                       0
type_sports                          26
veggies_day                           0
vitamins                              0
waffle_calories                       0
weight                                2

We gotta remove those `NaN`s―the entire row.

In [1610]:
# Drop ‘em in-place.

df_food.dropna(inplace=True)
print(df_food)

            GPA  Gender  breakfast  calories_chicken  calories_day  \
1         3.654       1          1               610           3.0
2           3.3       1          1               720           4.0
4           3.5       1          1               720           2.0
6           3.8       2          1               610           3.0
7           3.3       1          1               720           3.0
9           3.3       1          1               430           3.0
10          3.5       1          1               610           3.0
11        3.904       1          1               720           4.0
12          3.4       2          1               430           3.0
13          3.6       1          1               610           3.0
14          3.1       2          1               610           3.0
17          3.6       2          1               430           3.0
18          3.4       1          1               720           3.0
20          3.3       2          1               610           3.0
22          3.7       2          1               610           3.0
23          3.7       2          2               610           3.0
25          2.8       1          2               720           3.0
26          3.7       2          1               610           2.0
27            3       2          1               610           4.0
31            4       2          1               610           3.0
34         3.65       1          1               610           3.0
35            3       1          1               610           2.0
37          3.4       1          1               720           4.0
38         3.89       1          1               610           3.0
40          3.4       2          1               430           3.0
44          3.2       1          1               610           4.0
46          3.8       2          1               430           2.0
51          3.3       2          1               610           4.0
54          3.5       2          1               610           3.0
56          3.8       2          1               720           4.0
57          2.8       1          1               610           4.0
58          3.5       1          1               610           3.0
60          3.6       1          1               610           4.0
62          3.9       2          1               610           4.0
64          3.5       1          1               610           3.0
67          3.6       1          1               610           2.0
68          3.2       1          1               430           3.0
70         3.73       1          1               610           3.0
73   3.79 bitch       2          1               720           4.0
75            3       1          1               610           3.0
76          3.7       1          2               610           3.0
77          3.1       2          2               265           2.0
78            3       1          1               720           3.0
79          3.9       2          1               720           3.0
81          3.5       1          2               610           3.0
84         3.83       1          1               720           3.0
85          2.6       1          1               265           3.0
86            3       1          1               610           3.0
87          3.2       2          1               720           3.0
91          3.8       1          2               610           2.0
96         3.92       2          1               430           3.0
103         3.7       1          1               610           3.0

     calories_scone  coffee  \
1             420.0       2
2             420.0       2
4             420.0       2
6             420.0       2
7             420.0       1
9             315.0       2
10            980.0       2
11            420.0       2
12            420.0       2
13            420.0       2
14            420.0       2
17            980.0       2
18            980.0       1
20            980.0       2
22            420.0       1
23            420.0       2
25            420.0       2
26            420.0       1
27            980.0       2
31            420.0       2
34            420.0       2
35            420.0       2
37            420.0       2
38            980.0       2
40            315.0       1
44            420.0       2
46            420.0       1
51            980.0       1
54            420.0       2
56            315.0       2
57            980.0       2
58            420.0       2
60            420.0       2
62            980.0       2
64            420.0       1
67            420.0       1
68            315.0       1
70            980.0       2
73            420.0       2
75            420.0       2
76            420.0       1
77            420.0       1
78            420.0       2
79            420.0       2
81            420.0       1
84            420.0       2
85            315.0       2
86            420.0       2
87            420.0       1
91            420.0       2
96            420.0       2
103           420.0       2

                                          comfort_food  \
1                          chocolate, chips, ice cream
2                      frozen yogurt, pizza, fast food
4                         Ice cream, chocolate, chips
6         Chocolate, ice cream, french fries, pretzels
7                     Ice cream, cheeseburgers, chips.
9                Mac and cheese, chocolate, and pasta
10   Pasta, grandma homemade chocolate cake anythin...
11              chocolate, pasta, soup, chips, popcorn
12                         Cookies, popcorn, and chips
13                          ice cream, cake, chocolate
14     Pizza, fruit, spaghetti, chicken and Potatoes
17                           chips, cookies, ice cream
18                                Chocolate, ice crea
20                              Fast food, pizza, subs
22                             burgers, chips, cookies
23                               Chilli, soup, pot pie
25             chocolate, ice cream/milkshake, cookies
26              Chips, ice cream, microwaveable foods
27                             Chicken fingers, pizza
31                              chips and dip, pepsi,
34                      french fries, chips, ice cream
35   mac n cheese, peanut butter and banana sandwic...
37                             chocolate, chips, candy
38                       chocolate, popcorn, ice cream
40          Pizza, Ice cream, fries, cereal, cookies
44         Potato chips, ice cream, chocolate, cookies
46                     popcorn, chips, candy, & fries
51                                              Burger
54      peanut butter sandwich, pretzals, garlic bread
56                     Pizza, Ice Cream, Chicken Wings
57             Pizza chocolate chips bagels ice Capps
58                         Chocolate, ice cream, pasta
60                  peanut butter, dessets, pretzels.
62                       ice cream, cookies, ice cream
64         cookies, nutella, ice cream, coffee, fruit
67      Ice cream, cake, mozzarella sticks, pierogies
68         Chips, Mac and cheese, pizza, French fries
70   Broccoli, spaghetti squash, quinoa, and grille...
73                                    Chips, ice cream
75   mac and cheese, potato soup, ice cream, chips ...
76               chocolate, pizza, and mashed potatoes
77                                Pizza cookies steak
78                     chocolate, fruit, and ice cream
79                                Chips sweets popcorn
81                 cake, French fries, chicken nuggets
84                  Pasta dishes, Cheesecake, Pancakes
85                           Ice cream, pizza, cookies
86   Chinese food, moes, sponge candy, homemade las...
87                        pizza, pasta, mac and cheese
91     Macaroni and cheese, chicken noodle soup, pizza
96        Ice cream, cake, pop, pizza, and milkshakes.
103  dark chocolate, terra chips, reese's cups(dark...

                                  comfort_food_reasons  \
1                                 Stress, bored, anger
2                                      stress, sadness
4                           Stress, boredom, cravings
6                                      stress, boredom
7    I eat comfort food when im stressed out from s...
9                           Stress, anger and sadness
10                                            Boredom
11                       sadness, stress, cold weather
12                 Sadness, boredom, late night snack
13                 stress,  boredom, special occasions
14                    Friends, environment and boredom
17   I usually only eat comfort food when I'm bored...
18                                     Sadness, stress
20                             happiness, satisfaction
22                                sadness, depression
23                                 Stress and boredom
25                                             boredom
26                                  Boredom, lazyniss
27                                            Boredom
31                       stres, boredom, and nighttime
34                              boredom, stressed, sad
35                                     Boredom usually
37                                              Stress
38                                     boredom, stress
40                   Usually if I'm sad or depressed.
44                            Stress, boredom, craving
46                          sadness, boredom, & anger
51                                                Lazy
54                           stress, anger and boredom
56   I usually only eat comfort foods when I am bor...
57                                         Just cause
58                            Stress, boredom, sadness
60                           Sadness, boredom, lonely.
62                                    boredom, sadness
64                          Bordem, happiness, sadness
67                                             Boredom
68                             Stress, sadness, bored
70                             Bad day, bored, sadness
73                                     Boredom, stress
75                          sadness, stressed, boredom
76                                  boredom and stress
77                             Boredom comfort hunger
78                                     stress, boredom
79                                             Boredom
81                                    boredom, sadness
84                        Sadness, Loneliness, Boredom
85                                       Mostly Stress
86                                   boredom, sadness
87                            when i am sad or craving
91                                  Boredom and stress
96                    Happiness, sadness, celebration.
103  Anxiousness, watching TV I desire "comfort food"

     comfort_food_reasons_coded  ...  soup  sports  thai_food  \
1                           1.0  ...   1.0     1.0          2
2                           1.0  ...   1.0     2.0          5
4                           1.0  ...   1.0     1.0          4
6                           1.0  ...   1.0     1.0          5
7                           1.0  ...   1.0     2.0          1
9                           1.0  ...   1.0     1.0          4
10                          2.0  ...   1.0     1.0          2
11                          3.0  ...   1.0     1.0          5
12                          3.0  ...   2.0     1.0          3
13                          1.0  ...   1.0     1.0          5
14                          2.0  ...   1.0     1.0          4
17                          2.0  ...   1.0     1.0          3
18                          3.0  ...   2.0     2.0          1
20                          7.0  ...   1.0     1.0          1
22                          3.0  ...   1.0     1.0          4
23                          1.0  ...   1.0     1.0          4
25                          2.0  ...   1.0     1.0          3
26                          2.0  ...   2.0     1.0          2
27                          2.0  ...   1.0     1.0          3
31                          1.0  ...   2.0     2.0          4
34                          2.0  ...   1.0     1.0          3
35                          2.0  ...   1.0     1.0          2
37                          1.0  ...   1.0     1.0          5
38                          2.0  ...   1.0     1.0          2
40                          3.0  ...   1.0     1.0          3
44                          1.0  ...   1.0     1.0          5
46                          3.0  ...   1.0     1.0          3
51                          5.0  ...   1.0     1.0          5
54                          1.0  ...   1.0     1.0          4
56                          2.0  ...   1.0     1.0          5
57                          9.0  ...   2.0     1.0          2
58                          1.0  ...   1.0     1.0          5
60                          3.0  ...   1.0     1.0          1
62                          2.0  ...   1.0     1.0          2
64                          2.0  ...   2.0     1.0          3
67                          2.0  ...   1.0     1.0          2
68                          1.0  ...   1.0     1.0          4
70                          2.0  ...   1.0     1.0          5
73                          2.0  ...   1.0     1.0          2
75                          3.0  ...   1.0     2.0          4
76                          2.0  ...   2.0     1.0          1
77                          2.0  ...   2.0     1.0          2
78                          1.0  ...   1.0     1.0          3
79                          2.0  ...   1.0     1.0          5
81                          2.0  ...   2.0     1.0          4
84                          3.0  ...   1.0     1.0          5
85                          1.0  ...   1.0     2.0          3
86                          2.0  ...   1.0     1.0          4
87                          3.0  ...   1.0     1.0          1
91                          2.0  ...   1.0     2.0          1
96                          7.0  ...   1.0     2.0          3
103                         8.0  ...   1.0     2.0          3

    tortilla_calories  turkey_calories  \
1               725.0              690
2              1165.0              500
4               940.0              500
6               940.0              690
7               725.0              500
9               580.0              345
10              940.0              345
11              940.0              500
12              940.0              500
13             1165.0              850
14              940.0              500
17              940.0              500
18             1165.0              690
20             1165.0              850
22              940.0              850
23              940.0              690
25             1165.0              690
26             1165.0              850
27             1165.0              500
31              940.0              690
34              940.0              345
35              940.0              690
37              940.0              500
38             1165.0              690
40              940.0              500
44              725.0              500
46              725.0              345
51             1165.0              500
54              940.0              690
56             1165.0              500
57              725.0              345
58             1165.0              690
60             1165.0              690
62             1165.0              850
64              940.0              500
67              940.0              690
68              725.0              500
70             1165.0              500
73             1165.0              850
75              940.0              500
76             1165.0              690
77              725.0              345
78              580.0              345
79             1165.0              850
81              725.0              500
84              725.0              690
85              580.0              500
86              580.0              500
87             1165.0              690
91              725.0              500
96              725.0              500
103             725.0              345

                                           type_sports veggies_day  vitamins  \
1                                          Basketball            4         2
2                                                 none           5         1
4                                             Softball           4         2
6                                               soccer           4         1
7                                                 none           4         2
9                                         field hockey           5         1
10                                              soccer           5         2
11                                             Running           5         1
12                              Soccer and basketball            3         2
13                               intramural volleyball           5         2
14                                              Hockey           5         1
17                                              hockey           4         2
18                                            dancing            5         1
20                                              Soccer           3         2
22                                   tennis soccer gym           3         1
23                                     Gaelic Football           4         1
25                                          Ice hockey           3         2
26                                              Hockey           3         2
27                                           Lacrosse            5         1
31                                      none organized           5         1
34                                            softball           4         1
35                                            Lacrosse           5         2
37                                             Dancing           4         2
38                                            Lacrosse           3         2
40                                          wrestling            4         2
44                                          Volleyball           5         1
46                                             soccer            4         2
51                                              Hockey           4         1
54                                              hockey           5         1
56                                              Hockey           5         1
57                                            softball           4         1
58                                              Skiing           5         1
60                             Water polo and running            5         1
62                                          Ice Hockey           4         1
64                                          Volleyball           5         1
67            Recreational Basketball, Equestrian Team           5         2
68                                              soccer           5         2
70                                      Rec Volleyball           5         1
73                                            baseball           4         1
75                             I danced in high school           4         1
76                                   horse back riding           2         2
77                                         Basketball            2         2
78                                  competitive skiing           4         1
79                        Rowing, Running, and Cycling           4         2
81                             softball and basketball           2         2
84                               Collegiate Water Polo           5         1
85                                      None right now           4         1
86                                volleyball, lacrosse           4         1

In [1611]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂

df_food # it affected the original

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
6,3.8,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.0,1.0,5,940.0,690,soccer,4,1,1315,180
7,3.3,1,1,720,3.0,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,...,1.0,2.0,1,725.0,500,none,4,2,1315,137
9,3.3,1,1,430,3.0,315.0,2,"Mac and cheese, chocolate, and pasta","Stress, anger and sadness",1.0,...,1.0,1.0,4,580.0,345,field hockey,5,1,900,125
10,3.5,1,1,610,3.0,980.0,2,"Pasta, grandma homemade chocolate cake anythin...",Boredom,2.0,...,1.0,1.0,2,940.0,345,soccer,5,2,900,116
11,3.904,1,1,720,4.0,420.0,2,"chocolate, pasta, soup, chips, popcorn","sadness, stress, cold weather",3.0,...,1.0,1.0,5,940.0,500,Running,5,1,900,110
12,3.4,2,1,430,3.0,420.0,2,"Cookies, popcorn, and chips","Sadness, boredom, late night snack",3.0,...,2.0,1.0,3,940.0,500,Soccer and basketball,3,2,575,264
13,3.6,1,1,610,3.0,420.0,2,"ice cream, cake, chocolate","stress, boredom, special occasions",1.0,...,1.0,1.0,5,1165.0,850,intramural volleyball,5,2,1315,123
14,3.1,2,1,610,3.0,420.0,2,"Pizza, fruit, spaghetti, chicken and Potatoes","Friends, environment and boredom",2.0,...,1.0,1.0,4,940.0,500,Hockey,5,1,900,185
17,3.6,2,1,430,3.0,980.0,2,"chips, cookies, ice cream",I usually only eat comfort food when I'm bored...,2.0,...,1.0,1.0,3,940.0,500,hockey,4,2,900,170
18,3.4,1,1,720,3.0,980.0,1,"Chocolate, ice crea","Sadness, stress",3.0,...,2.0,2.0,1,1165.0,690,dancing,5,1,1315,135
20,3.3,2,1,610,3.0,980.0,2,"Fast food, pizza, subs","happiness, satisfaction",7.0,...,1.0,1.0,1,1165.0,850,Soccer,3,2,1315,175
22,3.7,2,1,610,3.0,420.0,1,"burgers, chips, cookies","sadness, depression",3.0,...,1.0,1.0,4,940.0,850,tennis soccer gym,3,1,1315,185
23,3.7,2,2,610,3.0,420.0,2,"Chilli, soup, pot pie",Stress and boredom,1.0,...,1.0,1.0,4,940.0,690,Gaelic Football,4,1,1315,185
25,2.8,1,2,720,3.0,420.0,2,"chocolate, ice cream/milkshake, cookies",boredom,2.0,...,1.0,1.0,3,1165.0,690,Ice hockey,3,2,760,125
26,3.7,2,1,610,2.0,420.0,1,"Chips, ice cream, microwaveable foods","Boredom, lazyniss",2.0,...,2.0,1.0,2,1165.0,850,Hockey,3,2,1315,160
27,3,2,1,610,4.0,980.0,2,"Chicken fingers, pizza",Boredom,2.0,...,1.0,1.0,3,1165.0,500,Lacrosse,5,1,1315,175
31,4,2,1,610,3.0,420.0,2,"chips and dip, pepsi,","stres, boredom, and nighttime",1.0,...,2.0,2.0,4,940.0,690,none organized,5,1,1315,205
34,3.65,1,1,610,3.0,420.0,2,"french fries, chips, ice cream","boredom, stressed, sad",2.0,...,1.0,1.0,3,940.0,345,softball,4,1,1315,150
35,3,1,1,610,2.0,420.0,2,"mac n cheese, peanut butter and banana sandwic...",Boredom usually,2.0,...,1.0,1.0,2,940.0,690,Lacrosse,5,2,760,150
37,3.4,1,1,720,4.0,420.0,2,"chocolate, chips, candy",Stress,1.0,...,1.0,1.0,5,940.0,500,Dancing,4,2,1315,170
38,3.89,1,1,610,3.0,980.0,2,"chocolate, popcorn, ice cream","boredom, stress",2.0,...,1.0,1.0,2,1165.0,690,Lacrosse,3,2,1315,150
40,3.4,2,1,430,3.0,315.0,1,"Pizza, Ice cream, fries, cereal, cookies",Usually if I'm sad or depressed.,3.0,...,1.0,1.0,3,940.0,500,wrestling,4,2,760,140
44,3.2,1,1,610,4.0,420.0,2,"Potato chips, ice cream, chocolate, cookies","Stress, boredom, craving",1.0,...,1.0,1.0,5,725.0,500,Volleyball,5,1,760,170
46,3.8,2,1,430,2.0,420.0,1,"popcorn, chips, candy, & fries","sadness, boredom, & anger",3.0,...,1.0,1.0,3,725.0,345,soccer,4,2,900,168
51,3.3,2,1,610,4.0,980.0,1,Burger,Lazy,5.0,...,1.0,1.0,5,1165.0,500,Hockey,4,1,1315,185
54,3.5,2,1,610,3.0,420.0,2,"peanut butter sandwich, pretzals, garlic bread","stress, anger and boredom",1.0,...,1.0,1.0,4,940.0,690,hockey,5,1,900,165
56,3.8,2,1,720,4.0,315.0,2,"Pizza, Ice Cream, Chicken Wings",I usually only eat comfort foods when I am bor...,2.0,...,1.0,1.0,5,1165.0,500,Hockey,5,1,1315,175
57,2.8,1,1,610,4.0,980.0,2,Pizza chocolate chips bagels ice Capps,Just cause,9.0,...,2.0,1.0,2,725.0,345,softball,4,1,1315,140
58,3.5,1,1,610,3.0,420.0,2,"Chocolate, ice cream, pasta","Stress, boredom, sadness",1.0,...,1.0,1.0,5,1165.0,690,Skiing,5,1,1315,155
60,3.6,1,1,610,4.0,420.0,2,"peanut butter, dessets, pretzels.","Sadness, boredom, lonely.",3.0,...,1.0,1.0,1,1165.0,690,Water polo and running,5,1,1315,135
62,3.9,2,1,610,4.0,980.0,2,"ice cream, cookies, ice cream","boredom, sadness",2.0,...,1.0,1.0,2,1165.0,850,Ice Hockey,4,1,1315,210
64,3.5,1,1,610,3.0,420.0,1,"cookies, nutella, ice cream, coffee, fruit","Bordem, happiness, sadness",2.0,...,2.0,1.0,3,940.0,500,Volleyball,5,1,760,140
67,3.6,1,1,610,2.0,420.0,1,"Ice cream, cake, mozzarella sticks, pierogies",Boredom,2.0,...,1.0,1.0,2,940.0,690,"Recreational Basketball, Equestrian Team",5,2,1315,144 lbs
68,3.2,1,1,430,3.0,315.0,1,"Chips, Mac and cheese, pizza, French fries","Stress, sadness, bored",1.0,...,1.0,1.0,4,725.0,500,soccer,5,2,760,145
70,3.73,1,1,610,3.0,980.0,2,"Broccoli, spaghetti squash, quinoa, and grille...","Bad day, bored, sadness",2.0,...,1.0,1.0,5,1165.0,500,Rec Volleyball,5,1,1315,140
73,3.79 bitch,2,1,720,4.0,420.0,2,"Chips, ice cream","Boredom, stress",2.0,...,1.0,1.0,2,1165.0,850,baseball,4,1,1315,200
75,3,1,1,610,3.0,420.0,2,"mac and cheese, potato soup, ice cream, chips ...","sadness, stressed, boredom",3.0,...,1.0,2.0,4,940.0,500,I danced in high school,4,1,900,120
76,3.7,1,2,610,3.0,420.0,1,"chocolate, pizza, and mashed potatoes",boredom and stress,2.0,...,2.0,1.0,1,1165.0,690,horse back riding,2,2,1315,150
77,3.1,2,2,265,2.0,420.0,1,Pizza cookies steak,Boredom comfort hunger,2.0,...,2.0,1.0,2,725.0,345,Basketball,2,2,900,200
78,3,1,1,720,3.0,420.0,2,"chocolate, fruit, and ice cream","stress, boredom",1.0,...,1.0,1.0,3,580.0,345,competitive skiing,4,1,1315,135
79,3.9,2,1,720,3.0,420.0,2,Chips sweets popcorn,Boredom,2.0,...,1.0,1.0,5,1165.0,850,"Rowing, Running, and Cycling",4,2,1315,145
81,3.5,1,2,610,3.0,420.0,1,"cake, French fries, chicken nuggets","boredom, sadness",2.0,...,2.0,1.0,4,725.0,500,softball and basketball,2,2,900,190
84,3.83,1,1,720,3.0,420.0,2,"Pasta dishes, Cheesecake, Pancakes","Sadness, Loneliness, Boredom",3.0,...,1.0,1.0,5,725.0,690,Collegiate Water Polo,5,1,760,167
85,2.6,1,1,265,3.0,315.0,2,"Ice cream, pizza, cookies",Mostly Stress,1.0,...,1.0,2.0,3,580.0,500,None right now,4,1,760,140
86,3,1,1,610,3.0,420.0,2,"Chinese food, moes, sponge candy, homemade las...","boredom, sadness",2.0,...,1.0,1.0,4,580.0,500,"volleyball, lacrosse",4,1,900,190
87,3.2,2,1,720,3.0,420.0,1,"pizza, pasta, mac and cheese",when i am sad or craving,3.0,...,1.0,1.0,1,1165.0,690,field hockey,4,1,1315,155
91,3.8,1,2,610,2.0,420.0,2,"Macaroni and cheese, chicken noodle soup, pizza",Boredom and stress,2.0,...,1.0,2.0,1,725.0,500,crew,1,2,900,135
96,3.92,2,1,430,3.0,420.0,2,"Ice cream, cake, pop, pizza, and milkshakes.","Happiness, sadness, celebration.",7.0,...,1.0,2.0,3,725.0,500,Soccer,2,1,900,210
103,3.7,1,1,610,3.0,420.0,2,"dark chocolate, terra chips, reese's cups(dark...","Anxiousness, watching TV I desire ""comfort food""",8.0,...,1.0,2.0,3,725.0,345,"When I can, rarely though play pool, darts, an...",5,1,760,130

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [1612]:
# Fix that in-place.

for x in df_food.index:
  gpa_value = df_food.loc[x, "GPA"]
  try:
      val = float(gpa_value)
  except ValueError:
      df_food.drop(x, inplace=True)
      print(x, "Invalid float")

df_food # it affected the original

73 Invalid float

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
6,3.8,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.0,1.0,5,940.0,690,soccer,4,1,1315,180
7,3.3,1,1,720,3.0,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,...,1.0,2.0,1,725.0,500,none,4,2,1315,137
9,3.3,1,1,430,3.0,315.0,2,"Mac and cheese, chocolate, and pasta","Stress, anger and sadness",1.0,...,1.0,1.0,4,580.0,345,field hockey,5,1,900,125
10,3.5,1,1,610,3.0,980.0,2,"Pasta, grandma homemade chocolate cake anythin...",Boredom,2.0,...,1.0,1.0,2,940.0,345,soccer,5,2,900,116
11,3.904,1,1,720,4.0,420.0,2,"chocolate, pasta, soup, chips, popcorn","sadness, stress, cold weather",3.0,...,1.0,1.0,5,940.0,500,Running,5,1,900,110
12,3.4,2,1,430,3.0,420.0,2,"Cookies, popcorn, and chips","Sadness, boredom, late night snack",3.0,...,2.0,1.0,3,940.0,500,Soccer and basketball,3,2,575,264
13,3.6,1,1,610,3.0,420.0,2,"ice cream, cake, chocolate","stress, boredom, special occasions",1.0,...,1.0,1.0,5,1165.0,850,intramural volleyball,5,2,1315,123
14,3.1,2,1,610,3.0,420.0,2,"Pizza, fruit, spaghetti, chicken and Potatoes","Friends, environment and boredom",2.0,...,1.0,1.0,4,940.0,500,Hockey,5,1,900,185
17,3.6,2,1,430,3.0,980.0,2,"chips, cookies, ice cream",I usually only eat comfort food when I'm bored...,2.0,...,1.0,1.0,3,940.0,500,hockey,4,2,900,170
18,3.4,1,1,720,3.0,980.0,1,"Chocolate, ice crea","Sadness, stress",3.0,...,2.0,2.0,1,1165.0,690,dancing,5,1,1315,135
20,3.3,2,1,610,3.0,980.0,2,"Fast food, pizza, subs","happiness, satisfaction",7.0,...,1.0,1.0,1,1165.0,850,Soccer,3,2,1315,175
22,3.7,2,1,610,3.0,420.0,1,"burgers, chips, cookies","sadness, depression",3.0,...,1.0,1.0,4,940.0,850,tennis soccer gym,3,1,1315,185
23,3.7,2,2,610,3.0,420.0,2,"Chilli, soup, pot pie",Stress and boredom,1.0,...,1.0,1.0,4,940.0,690,Gaelic Football,4,1,1315,185
25,2.8,1,2,720,3.0,420.0,2,"chocolate, ice cream/milkshake, cookies",boredom,2.0,...,1.0,1.0,3,1165.0,690,Ice hockey,3,2,760,125
26,3.7,2,1,610,2.0,420.0,1,"Chips, ice cream, microwaveable foods","Boredom, lazyniss",2.0,...,2.0,1.0,2,1165.0,850,Hockey,3,2,1315,160
27,3,2,1,610,4.0,980.0,2,"Chicken fingers, pizza",Boredom,2.0,...,1.0,1.0,3,1165.0,500,Lacrosse,5,1,1315,175
31,4,2,1,610,3.0,420.0,2,"chips and dip, pepsi,","stres, boredom, and nighttime",1.0,...,2.0,2.0,4,940.0,690,none organized,5,1,1315,205
34,3.65,1,1,610,3.0,420.0,2,"french fries, chips, ice cream","boredom, stressed, sad",2.0,...,1.0,1.0,3,940.0,345,softball,4,1,1315,150
35,3,1,1,610,2.0,420.0,2,"mac n cheese, peanut butter and banana sandwic...",Boredom usually,2.0,...,1.0,1.0,2,940.0,690,Lacrosse,5,2,760,150
37,3.4,1,1,720,4.0,420.0,2,"chocolate, chips, candy",Stress,1.0,...,1.0,1.0,5,940.0,500,Dancing,4,2,1315,170
38,3.89,1,1,610,3.0,980.0,2,"chocolate, popcorn, ice cream","boredom, stress",2.0,...,1.0,1.0,2,1165.0,690,Lacrosse,3,2,1315,150
40,3.4,2,1,430,3.0,315.0,1,"Pizza, Ice cream, fries, cereal, cookies",Usually if I'm sad or depressed.,3.0,...,1.0,1.0,3,940.0,500,wrestling,4,2,760,140
44,3.2,1,1,610,4.0,420.0,2,"Potato chips, ice cream, chocolate, cookies","Stress, boredom, craving",1.0,...,1.0,1.0,5,725.0,500,Volleyball,5,1,760,170
46,3.8,2,1,430,2.0,420.0,1,"popcorn, chips, candy, & fries","sadness, boredom, & anger",3.0,...,1.0,1.0,3,725.0,345,soccer,4,2,900,168
51,3.3,2,1,610,4.0,980.0,1,Burger,Lazy,5.0,...,1.0,1.0,5,1165.0,500,Hockey,4,1,1315,185
54,3.5,2,1,610,3.0,420.0,2,"peanut butter sandwich, pretzals, garlic bread","stress, anger and boredom",1.0,...,1.0,1.0,4,940.0,690,hockey,5,1,900,165
56,3.8,2,1,720,4.0,315.0,2,"Pizza, Ice Cream, Chicken Wings",I usually only eat comfort foods when I am bor...,2.0,...,1.0,1.0,5,1165.0,500,Hockey,5,1,1315,175
57,2.8,1,1,610,4.0,980.0,2,Pizza chocolate chips bagels ice Capps,Just cause,9.0,...,2.0,1.0,2,725.0,345,softball,4,1,1315,140
58,3.5,1,1,610,3.0,420.0,2,"Chocolate, ice cream, pasta","Stress, boredom, sadness",1.0,...,1.0,1.0,5,1165.0,690,Skiing,5,1,1315,155
60,3.6,1,1,610,4.0,420.0,2,"peanut butter, dessets, pretzels.","Sadness, boredom, lonely.",3.0,...,1.0,1.0,1,1165.0,690,Water polo and running,5,1,1315,135
62,3.9,2,1,610,4.0,980.0,2,"ice cream, cookies, ice cream","boredom, sadness",2.0,...,1.0,1.0,2,1165.0,850,Ice Hockey,4,1,1315,210
64,3.5,1,1,610,3.0,420.0,1,"cookies, nutella, ice cream, coffee, fruit","Bordem, happiness, sadness",2.0,...,2.0,1.0,3,940.0,500,Volleyball,5,1,760,140
67,3.6,1,1,610,2.0,420.0,1,"Ice cream, cake, mozzarella sticks, pierogies",Boredom,2.0,...,1.0,1.0,2,940.0,690,"Recreational Basketball, Equestrian Team",5,2,1315,144 lbs
68,3.2,1,1,430,3.0,315.0,1,"Chips, Mac and cheese, pizza, French fries","Stress, sadness, bored",1.0,...,1.0,1.0,4,725.0,500,soccer,5,2,760,145
70,3.73,1,1,610,3.0,980.0,2,"Broccoli, spaghetti squash, quinoa, and grille...","Bad day, bored, sadness",2.0,...,1.0,1.0,5,1165.0,500,Rec Volleyball,5,1,1315,140
75,3,1,1,610,3.0,420.0,2,"mac and cheese, potato soup, ice cream, chips ...","sadness, stressed, boredom",3.0,...,1.0,2.0,4,940.0,500,I danced in high school,4,1,900,120
76,3.7,1,2,610,3.0,420.0,1,"chocolate, pizza, and mashed potatoes",boredom and stress,2.0,...,2.0,1.0,1,1165.0,690,horse back riding,2,2,1315,150
77,3.1,2,2,265,2.0,420.0,1,Pizza cookies steak,Boredom comfort hunger,2.0,...,2.0,1.0,2,725.0,345,Basketball,2,2,900,200
78,3,1,1,720,3.0,420.0,2,"chocolate, fruit, and ice cream","stress, boredom",1.0,...,1.0,1.0,3,580.0,345,competitive skiing,4,1,1315,135
79,3.9,2,1,720,3.0,420.0,2,Chips sweets popcorn,Boredom,2.0,...,1.0,1.0,5,1165.0,850,"Rowing, Running, and Cycling",4,2,1315,145
81,3.5,1,2,610,3.0,420.0,1,"cake, French fries, chicken nuggets","boredom, sadness",2.0,...,2.0,1.0,4,725.0,500,softball and basketball,2,2,900,190
84,3.83,1,1,720,3.0,420.0,2,"Pasta dishes, Cheesecake, Pancakes","Sadness, Loneliness, Boredom",3.0,...,1.0,1.0,5,725.0,690,Collegiate Water Polo,5,1,760,167
85,2.6,1,1,265,3.0,315.0,2,"Ice cream, pizza, cookies",Mostly Stress,1.0,...,1.0,2.0,3,580.0,500,None right now,4,1,760,140
86,3,1,1,610,3.0,420.0,2,"Chinese food, moes, sponge candy, homemade las...","boredom, sadness",2.0,...,1.0,1.0,4,580.0,500,"volleyball, lacrosse",4,1,900,190
87,3.2,2,1,720,3.0,420.0,1,"pizza, pasta, mac and cheese",when i am sad or craving,3.0,...,1.0,1.0,1,1165.0,690,field hockey,4,1,1315,155
91,3.8,1,2,610,2.0,420.0,2,"Macaroni and cheese, chicken noodle soup, pizza",Boredom and stress,2.0,...,1.0,2.0,1,725.0,500,crew,1,2,900,135
96,3.92,2,1,430,3.0,420.0,2,"Ice cream, cake, pop, pizza, and milkshakes.","Happiness, sadness, celebration.",7.0,...,1.0,2.0,3,725.0,500,Soccer,2,1,900,210
103,3.7,1,1,610,3.0,420.0,2,"dark chocolate, terra chips, reese's cups(dark...","Anxiousness, watching TV I desire ""comfort food""",8.0,...,1.0,2.0,3,725.0,345,"When I can, rarely though play pool, darts, an...",5,1,760,130

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [1613]:
# Savey save!

df_food.to_csv('../data/food_coded_cleaned.csv', index=False)

In [1614]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.

plain_text_lines = open('../data/food_coded_cleaned.csv').readlines()
for i in range(5):
    print(plain_text_lines[i])

GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,cook,comfort_food_reasons_coded.1,cuisine,diet_current,diet_current_coded,drink,eating_changes,eating_changes_coded,eating_changes_coded1,eating_out,employment,ethnic_food,exercise,father_education,father_profession,fav_cuisine,fav_cuisine_coded,fav_food,food_childhood,fries,fruit_day,grade_level,greek_food,healthy_feeling,healthy_meal,ideal_diet,ideal_diet_coded,income,indian_food,italian_food,life_rewarding,marital_status,meals_dinner_friend,mother_education,mother_profession,nutritional_check,on_off_campus,parents_cook,pay_meal_out,persian_food,self_perception_weight,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight

3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,3.0,1,1.0,I eat about three times a day with some snacks. I try to eat healthy but it doesn't always work out that- sometimes eat fast food and mainly eat at Laker/ Egan ,2,2.0,I eat out more than usual. ,1,2,2,2.0,4,1.0,2.0,Self employed ,Italian,1,1.0,"chicken and biscuits, beef soup, baked beans",1,4,4,4,5,"Grains, Veggies, (more of grains and veggies), small protein and fruit with dairy ","Try to eat 5-6 small meals a day. While trying to properly distribute carbs, protein, fruits, veggies, and dairy.  ",3,4.0,4,4,1.0,2.0,"Pasta, steak, chicken ",4.0,Nurse RN ,4,1.0,1,4,4.0,3.0,1.0,1.0,2,725.0,690,Basketball ,4,2,900,155

3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,1.0,1,3.0,"toast and fruit for breakfast, salad for lunch, usually grilled chicken and veggies (or some variation) for dinner",3,1.0,sometimes choosing to eat fast food instead of cooking simply for convenience,1,3,2,3.0,5,2.0,2.0,owns business,italian,1,3.0,"mac and cheese, pizza, tacos",1,5,3,5,6,usually includes natural ingredients; nonprocessed food,i would say my ideal diet is my current diet,6,6.0,5,5,7.0,2.0,"chicken and rice with veggies, pasta, some kind of healthy recipe",2.0,owns business,4,2.0,1,3,5.0,6.0,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.

3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips ","Stress, boredom, cravings ",1.0,1.0,1,2.0,I try to eat healthy but often struggle because of living on campus. I still try to keep the choices I do make balanced with fruits and vegetables and limit the sweats. ,2,2.0,I have eaten generally the same foods but I do find myself eating the same food frequently due to what I have found I like from egan and the laker. ,3,4,2,2.0,4,1.0,4.0,IT,Italian ,1,3.0,"Pasta, chicken tender, pizza ",1,4,4,4,6,"A lean protein such as grilled chicken, green vegetables and  brown rice or other whole grain ",Ideally I would like to be able to eat healthier foods in order to loose weight. ,2,6.0,2,5,1.0,1.0,"Chicken Parmesan, Pulled Pork, Spaghetti and meatballs ",5.0,Substance Abuse Conselor,3,1.0,1,4,2.0,4.0,1.0,1.0,4,940.0,500,Softball,4,2,760,190

3.8,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,2.0,1,1.0,"I eat a lot of chicken and broccoli for dinner, and usually tuna sandwiches for lunch.",3,1.0,I started eating a lot less and healthier because I wasn't playing sports year round anymore.,2,5,2,3.0,5,1.0,4.0,Assembler ,Thai,4,1.0,"grilled chicken, hamburgers",1,4,4,5,4,"Protein, vegetables, fruit, and some carbs","I would ideally like to eat more fresh fruits and vegetables. However, its difficult to get to the store all the time to buy fresh.",2,4.0,5,5,8.0,1.0,"Grilled chicken, steak, pizza",4.0,Journalist,4,2.0,2,2,5.0,4.0,1.0,1.0,5,940.0,690,soccer,4,1,1315,180

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [ ]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.

df_salary = pd.read_csv('../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv', sep='\t')

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [ ]:
# Count by hand. I’m dead serious.

df_salary.shape

(28062, 18)

What are the columns and their types?

In [ ]:
# Show the column names and their types.

df_salary_col = df_salary.columns
for col in df_salary_col:
    print(col, "|", type(col))

Timestamp | <class 'str'>
How old are you? | <class 'str'>
What industry do you work in? | <class 'str'>
Job title | <class 'str'>
If your job title needs additional context, please clarify here: | <class 'str'>
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.) | <class 'str'>
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits. | <class 'str'>
Please indicate the currency | <class 'str'>
If "Other," please indicate the currency here:  | <class 'str'>
If your income needs additional context, please provide it here: | <class 'str'>
What country do you work in? | <class 'str'>
If you're in the U.S., what state do you work in? | <class 'str'>
What city do you work in? | <class 'str'>
How many years of professional work experience do you have overall? | <class 'str'>
How many years of professional work experience do you have in your field? | <class 'str'>
What is your highest level of education completed? | <class 'str'>
What is your gender? | <class 'str'>
What is your race? (Choose all that apply.) | <class 'str'>

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [ ]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race

df_salary.rename(columns={
    "Timestamp":"timestamp",
    "How old are you?":"age",
    "What industry do you work in?":"industry",
    "Job title":"title",
    "If your job title needs additional context, please clarify here:":"title_context",
    "What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)":"salary",
    "How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.":"additional_compensation",
    "Please indicate the currency":"currency",
    "If \"Other,\" please indicate the currency here: ":"other_currency",
    "If your income needs additional context, please provide it here:":"salary_context",
    "What country do you work in?":"country",
    "If you're in the U.S., what state do you work in?":"state",
    "What city do you work in?":"city",
    "How many years of professional work experience do you have overall?":"total_yoe",
    "How many years of professional work experience do you have in your field?":"field_yoe",
    "What is your highest level of education completed?":"highest_education_completed",
    "What is your gender?":"gender",
    "What is your race? (Choose all that apply.)":"race"
}, inplace=True)

df_salary.columns

Index(['timestamp', 'age', 'industry', 'title', 'title_context', 'salary',
       'additional_compensation', 'currency', 'other_currency',
       'salary_context', 'country', 'state', 'city', 'total_yoe', 'field_yoe',
       'highest_education_completed', 'gender', 'race'],
      dtype='object')

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [ ]:
# List the unique industries and a count of their instances.

df_salary["industry"].value_counts()
# 4699 corresponds

industry
Computing or Tech                        4699
Education (Higher Education)             2464
Nonprofits                               2419
Health care                              1896
Government and Public Administration     1889
                                         ...
Warehousing                                 1
Education (Early Childhood Education)       1
SAAS                                        1
Health and Safety                           1
Aerospace Manufacturing                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [ ]:
# Filtery filter.

df_salary_filtered = df_salary[df_salary["industry"] == "Computing or Tech"]
print(df_salary_filtered)

                timestamp    age           industry  \
1      4/27/2021 11:02:22  25-34  Computing or Tech
8      4/27/2021 11:03:01  45-54  Computing or Tech
43     4/27/2021 11:04:04  25-34  Computing or Tech
44     4/27/2021 11:04:04  25-34  Computing or Tech
46     4/27/2021 11:04:07  35-44  Computing or Tech
...                   ...    ...                ...
28050   7/1/2024 13:38:46  25-34  Computing or Tech
28051   7/1/2024 20:05:58  25-34  Computing or Tech
28052   7/3/2024 14:02:01  25-34  Computing or Tech
28058  7/23/2024 17:51:03  25-34  Computing or Tech
28060  7/26/2024 11:20:45  18-24  Computing or Tech

                                              title  \
1          Change & Internal Communications Manager
8                                   Systems Analyst
43                      Principal Software Engineer
44                             Intelligence Analyst
46                                 Mobile developer
...                                             ...
28050  Research & Systems Technician Data Analytics
28051                          Junior data analyst
28052        Senior Global Public Relations Manager
28058                             Systems Architect
28060                                            IT

                      title_context   salary  additional_compensation  \
1                               NaN   54,600                   4000.0
8      Data developer/ETL Developer  112,000                  10000.0
43                              NaN  187,500                   5000.0
44                              NaN  110,000                  20000.0
46                              NaN  144,600                   2500.0
...                             ...      ...                      ...
28050                           NaN    22000                      NaN
28051                           NaN    35000                  15000.0
28052                           NaN   144000                  15000.0
28058                           NaN   109000                      NaN
28060                           NaN     1700                     10.0

      currency other_currency                 salary_context         country  \
1          GBP            NaN                            NaN  United Kingdom
8          USD            NaN                            NaN              US
43         USD            NaN                            NaN   United States
44         USD            NaN  Around 20,000 a year in stock             USA
46         USD            NaN                            NaN             USA
...        ...            ...                            ...             ...
28050      EUR            NaN                            NaN           Spain
28051      USD            NaN                            NaN             Usa
28052      USD            NaN                            NaN             Usa
28058      USD            NaN                            NaN             USA
28060      USD            NaN                            NaN           Burma

               state                                          city  \
1                NaN                                     Cambridge
8           Missouri                                     St. Louis
43      Pennsylvania                                    Pittsburgh
44          Virginia                                 Arlington, VA
46     Massachusetts                                        Boston
...              ...                                           ...
28050            NaN                                     Barcelona
28051        Alabama                                      Alabama
28052  Massachusetts  Boise-but remote. Company located in Boston
28058        Georgia                                       Atlanta
28060            NaN                                        Yangon

           total_yoe       field_yoe highest_education_completed      gender  \
1       8 - 10 years       5-7 years              College degree  Non-binary
8      21 - 30 years   21 - 30 years              College degree       Woman
43      8 - 10 years       5-7 years              College degree       Woman
44      8 - 10 years    8 - 10 years             Master's degree         Man
46         5-7 years       5-7 years                         PhD       Woman
...              ...             ...                         ...         ...
28050    2 - 4 years     2 - 4 years              College degree         Man
28051    2 - 4 years     2 - 4 years              College degree       Woman
28052   8 - 10 years    8 - 10 years             Master's degree       Woman
28058      5-7 years       5-7 years              College degree         Man
28060    2 - 4 years  1 year or less                Some college         Man

                                      race
1                                    White
8                                    White
43                                   White
44                                   White
46                                   White
...                                    ...
28050  Hispanic, Latino, or Spanish origin
28051            Black or African American
28052                                White
28058                                White
28060              Asian or Asian American

[4699 rows x 18 columns]

Do a sanity check by counting.

In [ ]:
# Sanity check count.

df_salary_filtered.shape

(4699, 18)

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [ ]:
# Filtery filter (in place) for just the jobs that pay in USD!

df_salary_filtered = df_salary[df_salary["industry"] == "Computing or Tech"]
print(df_salary_filtered)

                timestamp    age           industry  \
1      4/27/2021 11:02:22  25-34  Computing or Tech
8      4/27/2021 11:03:01  45-54  Computing or Tech
43     4/27/2021 11:04:04  25-34  Computing or Tech
44     4/27/2021 11:04:04  25-34  Computing or Tech
46     4/27/2021 11:04:07  35-44  Computing or Tech
...                   ...    ...                ...
28050   7/1/2024 13:38:46  25-34  Computing or Tech
28051   7/1/2024 20:05:58  25-34  Computing or Tech
28052   7/3/2024 14:02:01  25-34  Computing or Tech
28058  7/23/2024 17:51:03  25-34  Computing or Tech
28060  7/26/2024 11:20:45  18-24  Computing or Tech

                                              title  \
1          Change & Internal Communications Manager
8                                   Systems Analyst
43                      Principal Software Engineer
44                             Intelligence Analyst
46                                 Mobile developer
...                                             ...
28050  Research & Systems Technician Data Analytics
28051                          Junior data analyst
28052        Senior Global Public Relations Manager
28058                             Systems Architect
28060                                            IT

                      title_context   salary  additional_compensation  \
1                               NaN   54,600                   4000.0
8      Data developer/ETL Developer  112,000                  10000.0
43                              NaN  187,500                   5000.0
44                              NaN  110,000                  20000.0
46                              NaN  144,600                   2500.0
...                             ...      ...                      ...
28050                           NaN    22000                      NaN
28051                           NaN    35000                  15000.0
28052                           NaN   144000                  15000.0
28058                           NaN   109000                      NaN
28060                           NaN     1700                     10.0

      currency other_currency                 salary_context         country  \
1          GBP            NaN                            NaN  United Kingdom
8          USD            NaN                            NaN              US
43         USD            NaN                            NaN   United States
44         USD            NaN  Around 20,000 a year in stock             USA
46         USD            NaN                            NaN             USA
...        ...            ...                            ...             ...
28050      EUR            NaN                            NaN           Spain
28051      USD            NaN                            NaN             Usa
28052      USD            NaN                            NaN             Usa
28058      USD            NaN                            NaN             USA
28060      USD            NaN                            NaN           Burma

               state                                          city  \
1                NaN                                     Cambridge
8           Missouri                                     St. Louis
43      Pennsylvania                                    Pittsburgh
44          Virginia                                 Arlington, VA
46     Massachusetts                                        Boston
...              ...                                           ...
28050            NaN                                     Barcelona
28051        Alabama                                      Alabama
28052  Massachusetts  Boise-but remote. Company located in Boston
28058        Georgia                                       Atlanta
28060            NaN                                        Yangon

           total_yoe       field_yoe highest_education_completed      gender  \
1       8 - 10 years       5-7 years              College degree  Non-binary
8      21 - 30 years   21 - 30 years              College degree       Woman
43      8 - 10 years       5-7 years              College degree       Woman
44      8 - 10 years    8 - 10 years             Master's degree         Man
46         5-7 years       5-7 years                         PhD       Woman
...              ...             ...                         ...         ...
28050    2 - 4 years     2 - 4 years              College degree         Man
28051    2 - 4 years     2 - 4 years              College degree       Woman
28052   8 - 10 years    8 - 10 years             Master's degree       Woman
28058      5-7 years       5-7 years              College degree         Man
28060    2 - 4 years  1 year or less                Some college         Man

                                      race
1                                    White
8                                    White
43                                   White
44                                   White
46                                   White
...                                    ...
28050  Hispanic, Latino, or Spanish origin
28051            Black or African American
28052                                White
28058                                White
28060              Asian or Asian American

[4699 rows x 18 columns]

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [ ]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.

df_salary_filtered["country"].value_counts()

country
United States     1576
USA               1222
US                 413
Canada             227
United Kingdom     145
                  ...
Nigeria              1
ss                   1
ibdia                1
Nigeria              1
Burma                1
Name: count, Length: 145, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [ ]:
# Replace them all in-place with 'US'.

first_5_values = df_salary["country"].value_counts().index[:6].tolist()

df_salary["country"] = df_salary["country"].replace(first_5_values, "US")

Have a look at the count of each unique country again now.

In [ ]:
# Count again.

df_salary["country"].value_counts()

country
US                           22353
UK                             574
United Kingdom                 547
USA                            468
Usa                            448
                             ...
Aotearoa New Zealand             1
U.S.A                            1
United States of American        1
ENGLAND                          1
Canadá                           1
Name: count, Length: 374, dtype: int64

Did you notice anything interesting?

In [ ]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [ ]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [ ]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.

salary_stats_by_state = df_salary.groupby("state")["salary"].agg(['min', 'mean', 'max'])
print(salary_stats_by_state)

TypeError: agg function failed [how->mean,dtype->object]

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [ ]:
# Fix it in-place.
df_salary["salary"] = pd.to_numeric(
    df_salary["salary"]
    .astype(str)
    .str.replace(r'[,]', '', regex=True)  # no more ,
    .str.strip(),                         
    errors='coerce'
)

salary_stats_by_state = df_salary.groupby("state")["salary"].agg(['min', 'mean', 'max'])
print(salary_stats_by_state)

                                  min           mean      max
state
Alabama                             0   98178.475410  3600000
Alabama, Alaska, Arizona           15      15.000000       15
Alabama, California             29120   29120.000000    29120
Alabama, District of Columbia  156000  156000.000000   156000
Alabama, Kansas                 64197   64197.000000    64197
...                               ...            ...      ...
Virginia                           57   94679.388041  1300000
Washington                         72  107803.852196  1260000
West Virginia                       0   59162.928571   125000
Wisconsin                           1   76351.454158   920000
Wyoming                         29000   58089.291667   140000

[134 rows x 3 columns]

Let’s try that again.

In [ ]:
# Try it again. Yeah!

df_salary["salary"] = pd.to_numeric(
    df_salary["salary"]
    .astype(str)
    .str.replace(r'[,]', '', regex=True)  # no more ,
    .str.strip(),                         
    errors='coerce'
)

salary_stats_by_state = df_salary.groupby("state")["salary"].agg(['min', 'mean', 'max'])
print(salary_stats_by_state)

                                  min           mean      max
state
Alabama                             0   98178.475410  3600000
Alabama, Alaska, Arizona           15      15.000000       15
Alabama, California             29120   29120.000000    29120
Alabama, District of Columbia  156000  156000.000000   156000
Alabama, Kansas                 64197   64197.000000    64197
...                               ...            ...      ...
Virginia                           57   94679.388041  1300000
Washington                         72  107803.852196  1260000
West Virginia                       0   59162.928571   125000
Wisconsin                           1   76351.454158   920000
Wyoming                         29000   58089.291667   140000

[134 rows x 3 columns]

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [ ]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.

df_salary_years_filtered = df_salary[df_salary["timestamp"].str.contains("2021|2022|2023", na=False)]

salary_stats_by_state_filtered = df_salary_years_filtered.groupby("state")["salary"].agg(['min', 'mean', 'max'])
print(salary_stats_by_state_filtered)

                                  min           mean      max
state
Alabama                             0  100565.153846  3600000
Alabama, California             29120   29120.000000    29120
Alabama, District of Columbia  156000  156000.000000   156000
Alabama, Kansas                 64197   64197.000000    64197
Alabama, Minnesota, Nevada     130000  130000.000000   130000
...                               ...            ...      ...
Virginia                           57   94679.388041  1300000
Washington                         72  107809.476754  1260000
West Virginia                       0   59162.928571   125000
Wisconsin                           1   76351.454158   920000
Wyoming                         29000   58089.291667   140000

[131 rows x 3 columns]

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)