# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [2]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy in /usr/local/python/3.14.2/lib/python3.14/site-packages (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
# Import here.
import pandas as pd 
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [4]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [5]:
df_food.value_counts()

GPA         Gender  breakfast  calories_chicken  calories_day  calories_scone  coffee  comfort_food                                                                                       comfort_food_reasons                                                                                                                       comfort_food_reasons_coded  cook  comfort_food_reasons_coded.1  cuisine  diet_current                                                                                                                                                                                                                                                            diet_current_coded  drink  eating_changes                                                                                                                                                                                                                                                                                                                  eating_changes_coded  eating_changes_coded1  eating_out  employment  ethnic_food  exercise  father_education  father_profession                  fav_cuisine                            fav_cuisine_coded  fav_food  food_childhood                                                                               fries  fruit_day  grade_level  greek_food  healthy_feeling  healthy_meal                                                                                                        ideal_diet                                                                                                                                                                                                     ideal_diet_coded  income  indian_food  italian_food  life_rewarding  marital_status  meals_dinner_friend                                                                                                       mother_education  mother_profession                nutritional_check  on_off_campus  parents_cook  pay_meal_out  persian_food  self_perception_weight  soup  sports  thai_food  tortilla_calories  turkey_calories  type_sports                                                  veggies_day  vitamins  waffle_calories  weight
3.654       1       1          610               3.0           420.0           2       chocolate, chips, ice cream                                                                        Stress, bored, anger                                                                                                                       1.0                         3.0   1                             1.0      I eat about three times a day with some snacks. I try to eat healthy but it doesn't always work out that- sometimes eat fast food and mainly eat at Laker/ Egan                                                                                                         2                   2.0    I eat out more than usual.                                                                                                                                                                                                                                                                                                      1                     2                      2           2.0         4            1.0       2.0               Self employed                      Italian                                1                  1.0       chicken and biscuits, beef soup, baked beans                                                 1      4          4            4           5                Grains, Veggies, (more of grains and veggies), small protein and fruit with dairy                                   Try to eat 5-6 small meals a day. While trying to properly distribute carbs, protein, fruits, veggies, and dairy.                                                                                              3                 4.0     4            4             1.0             2.0             Pasta, steak, chicken                                                                                                     4.0               Nurse RN                         4                  1.0            1             4             4.0           3.0                     1.0   1.0     2          725.0              690              Basketball                                                   4            2         900              155                         1
3.3         1       1          720               4.0           420.0           2       frozen yogurt, pizza, fast food                                                                    stress, sadness                                                                                                                            1.0                         1.0   1                             3.0      toast and fruit for breakfast, salad for lunch, usually grilled chicken and veggies (or some variation) for dinner                                                                                                                                                      3                   1.0    sometimes choosing to eat fast food instead of cooking simply for convenience                                                                                                                                                                                                                                                   1                     3                      2           3.0         5            2.0       2.0               owns business                      italian                                1                  3.0       mac and cheese, pizza, tacos                                                                 1      5          3            5           6                usually includes natural ingredients; nonprocessed food                                                             i would say my ideal diet is my current diet                                                                                                                                                                   6                 6.0     5            5             7.0             2.0             chicken and rice with veggies, pasta, some kind of healthy recipe                                                         2.0               owns business                    4                  2.0            1             3             5.0           6.0                     1.0   2.0     5          1165.0             500              none                                                         5            1         900              I'm not answering this.     1
3.5         1       1          720               2.0           420.0           2       Ice cream, chocolate, chips                                                                        Stress, boredom, cravings                                                                                                                  1.0                         1.0   1                             2.0      I try to eat healthy but often struggle because of living on campus. I still try to keep the choices I do make balanced with fruits and vegetables and limit the sweats.                                                                                                2                   2.0    I have eaten generally the same foods but I do find myself eating the same food frequently due to what I have found I like from egan and the laker.                                                                                                                                                                             3                     4                      2           2.0         4            1.0       4.0               IT                                 Italian                                1                  3.0       Pasta, chicken tender, pizza                                                                 1      4          4            4           6                A lean protein such as grilled chicken, green vegetables and  brown rice or other whole grain                       Ideally I would like to be able to eat healthier foods in order to loose weight.                                                                                                                               2                 6.0     2            5             1.0             1.0             Chicken Parmesan, Pulled Pork, Spaghetti and meatballs                                                                    5.0               Substance Abuse Conselor         3                  1.0            1             4             2.0           4.0                     1.0   1.0     4          940.0              500              Softball                                                     4            2         760              190                         1
3.8         2       1          610               3.0           420.0           2       Chocolate, ice cream, french fries, pretzels                                                       stress, boredom                                                                                                                            1.0                         2.0   1                             1.0      I eat a lot of chicken and broccoli for dinner, and usually tuna sandwiches for lunch.                                                                                                                                                                                  3                   1.0    I started eating a lot less and healthier because I wasn't playing sports year round anymore.                                                                                                                                                                                                                                   2                     5                      2           3.0         5            1.0       4.0               Assembler                          Thai                                   4                  1.0       grilled chicken, hamburgers                                                                  1      4          4            5           4                Protein, vegetables, fruit, and some carbs                                                                          I would ideally like to eat more fresh fruits and vegetables. However, its difficult to get to the store all the time to buy fresh.                                                                            2                 4.0     5            5             8.0             1.0             Grilled chicken, steak, pizza                                                                                             4.0               Journalist                       4                  2.0            2             2             5.0           4.0                     1.0   1.0     5          940.0              690              soccer                                                       4            1         1315             180                         1
3.3         1       1          720               3.0           420.0           1       Ice cream, cheeseburgers, chips.                                                                   I eat comfort food when im stressed out from school(finals week), when I`m sad, or when i am dealing with personal family issues.          1.0                         3.0   1                             1.0      I eat a very healthy diet. Ocassionally, i will eat out and get unhealthy food.                                                                                                                                                                                         1                   2.0    Freshmen year i ate very unhealthy, but now it is much healthier because of self control.                                                                                                                                                                                                                                       2                     5                      2           2.0         2            2.0       3.0               Business guy                       Anything american style.               5                  1.0       chicken, cheesey potatoes, and hot dogs                                                      1      5          2            3           3                A healthy meal has a piece of meat followed by a lot of fruit and veggies                                           My ideal diet is filled with a lot of fruit and chicken. I also really enjoy eggs any type of way with toast.                                                                                                  2                 5.0     1            3             3.0             1.0             chicken, steak, pasta                                                                                                     2.0               cook                             4                  1.0            1             5             1.0           3.0                     1.0   2.0     1          725.0              500              none                                                         4            2         1315             137                         1
                               430               3.0           315.0           2       Mac and cheese, chocolate, and pasta                                                               Stress, anger and sadness                                                                                                                  1.0                         3.0   1                             1.0      I eat healthy all the time when possible. I treat myself occasionally. I don't really like the greasy meals, if anything I would eat sweets over the greasy meals.                                                                                                      1                   1.0    I cook a lot of my own foods back at home so not being able to cook my own healthy choices. I eat more carbs than normal when I'm at college due to the choices given in the cafe.                                                                                                                                              1                     3                      3           3.0         5            1.0       5.0               commissioner of erie county        Italian                                1                  1.0       Pasta, Eggs, Pancakes                                                                        1      5          1            5           3                Chicken and rice with a side of veggies.                                                                            Lots of protein, carbs, and fruits and veggies.                                                                                                                                                                2                 4.0     4            5             3.0             2.0             pasta salad and bread                                                                                                     5.0               Pharmaceutical rep               5                  1.0            3             3             4.0           3.0                     1.0   1.0     4          580.0              345              field hockey                                                 5            1         900              125                         1
3.5         1       1          610               3.0           980.0           2       Pasta, grandma homemade chocolate cake anything homemade                                           Boredom                                                                                                                                    2.0                         1.0   2                             1.0      i eat very healthy. Maybe eat out 1-2 times a week.                                                                                                                                                                                                                     1                   2.0    Nun                                                                                                                                                                                                                                                                                                                             3                     4                      2           1.0         5            1.0       2.0               Idk                                Orange chicken and chow mani noodles   4                  1.0       Chicken                                                                                      1      5          3            1           9                Chicken, and veggies                                                                                                Chicken, fish                                                                                                                                                                                                  7                 3.0     1            5             8.0             1.0             chicken al king, spaghetti, fish                                                                                          4.0               Chidos Cleaners                  2                  3.0            1             2             2.0           1.0                     1.0   1.0     2          940.0              345              soccer                                                       5            2         900              116                         1

In [6]:
# Try to print or display it nicely.
df_food.head(10)

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
5,2.25,1,1,610,3.0,980.0,2,"Candy, brownies and soda.","None, i don't eat comfort food. I just eat whe...",4.0,...,1.0,2.0,4,940.0,345,None.,1,2,1315,190
6,3.8,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.0,1.0,5,940.0,690,soccer,4,1,1315,180
7,3.3,1,1,720,3.0,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,...,1.0,2.0,1,725.0,500,none,4,2,1315,137
8,3.3,1,1,430,NaN,420.0,1,"Donuts, ice cream, chips",Boredom,2.0,...,2.0,2.0,5,725.0,345,none,3,2,760,180
9,3.3,1,1,430,3.0,315.0,2,"Mac and cheese, chocolate, and pasta","Stress, anger and sadness",1.0,...,1.0,1.0,4,580.0,345,field hockey,5,1,900,125

What are the columns and their types in this data set?

In [7]:
# Show the column names and their types.

df_food.info()
#print(df_food.dtypes)

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    str
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    str
 8   comfort_food_reasons          123 non-null    str
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    str
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    str
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    str
 25  fav_cuisine                   123 non-null    str
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    str
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    str
 35  ideal_diet                    124 non-null    str
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    str
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    str
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     str
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    str
dtypes: float64(20), int64(27), str(14)
memory usage: 59.7 KB

In [8]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
pd.DataFrame({'Column': df_food.columns, 'Type': df_food.dtypes.values})

                          Column     Type
0                            GPA      str
1                         Gender    int64
2                      breakfast    int64
3               calories_chicken    int64
4                   calories_day  float64
5                 calories_scone  float64
6                         coffee    int64
7                   comfort_food      str
8           comfort_food_reasons      str
9     comfort_food_reasons_coded  float64
10                          cook  float64
11  comfort_food_reasons_coded.1    int64
12                       cuisine  float64
13                  diet_current      str
14            diet_current_coded    int64
15                         drink  float64
16                eating_changes      str
17          eating_changes_coded    int64
18         eating_changes_coded1    int64
19                    eating_out    int64
20                    employment  float64
21                   ethnic_food    int64
22                      exercise  float64
23              father_education  float64
24             father_profession      str
25                   fav_cuisine      str
26             fav_cuisine_coded    int64
27                      fav_food  float64
28                food_childhood      str
29                         fries    int64
30                     fruit_day    int64
31                   grade_level    int64
32                    greek_food    int64
33               healthy_feeling    int64
34                  healthy_meal      str
35                    ideal_diet      str
36              ideal_diet_coded    int64
37                        income  float64
38                   indian_food    int64
39                  italian_food    int64
40                life_rewarding  float64
41                marital_status  float64
42           meals_dinner_friend      str
43              mother_education  float64
44             mother_profession      str
45             nutritional_check    int64
46                 on_off_campus  float64
47                  parents_cook    int64
48                  pay_meal_out    int64
49                  persian_food  float64
50        self_perception_weight  float64
51                          soup  float64
52                        sports  float64
53                     thai_food    int64
54             tortilla_calories  float64
55               turkey_calories    int64
56                   type_sports      str
57                   veggies_day    int64
58                      vitamins    int64
59               waffle_calories    int64
60                        weight      str

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [9]:
# Remove 'em.
df_food_col_subset = df_food[['calories_day', 'weight', 'Gender']]

In [10]:
# Is there a second way to remove columns?

df_food_col_subset = df_food.filter(['calories_day', 'weight', 'Gender'])

In [11]:
# 🚀 Extra credit: What about a third way to remove columns?

What about `NaN`s? How many are there?

In [12]:
# Count ‘em.
df_food.isnull().sum()

GPA                              2
Gender                           0
breakfast                        0
calories_chicken                 0
calories_day                    19
calories_scone                   1
coffee                           0
comfort_food                     1
comfort_food_reasons             2
comfort_food_reasons_coded      19
cook                             3
comfort_food_reasons_coded.1     0
cuisine                         17
diet_current                     1
diet_current_coded               0
drink                            2
eating_changes                   3
eating_changes_coded             0
eating_changes_coded1            0
eating_out                       0
employment                       9
ethnic_food                      0
exercise                        13
father_education                 1
father_profession                3
fav_cuisine                      2
fav_cuisine_coded                0
fav_food                         2
food_childhood                   1
fries                            0
fruit_day                        0
grade_level                      0
greek_food                       0
healthy_feeling                  0
healthy_meal                     1
ideal_diet                       1
ideal_diet_coded                 0
income                           1
indian_food                      0
italian_food                     0
life_rewarding                   1
marital_status                   1
meals_dinner_friend              3
mother_education                 3
mother_profession                2
nutritional_check                0
on_off_campus                    1
parents_cook                     0
pay_meal_out                     0
persian_food                     1
self_perception_weight           1
soup                             1
sports                           2
thai_food                        0
tortilla_calories                1
turkey_calories                  0
type_sports                     26
veggies_day                      0
vitamins                         0
waffle_calories                  0
weight                           2
dtype: int64

In [ ]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.

In [ ]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

We gotta remove those `NaN`s―the entire row.

In [13]:
# Drop ‘em in-place.  

df_food_col_subset.dropna(inplace=True)

In [ ]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [14]:
# Fix that in-place.

df_food_col_subset['calories_day'] = pd.to_numeric(df_food_col_subset['calories_day'], errors='coerce')
df_food_col_subset.dropna(inplace=True)

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [15]:
# Savey save!
df_food_col_subset.to_csv('cleaned_food_data.csv', index=False)
#I need index = False because I don't want the index to be saved in the csv file

In [ ]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [16]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.
df_salary = pd.read_csv('../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv', sep='\t')

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [17]:
# Count by hand. I'm dead serious.
print(f"Shape: {df_salary.shape}")
print(f"Rows: {df_salary.shape[0]}, Columns: {df_salary.shape[1]}")
df_salary

Shape: (28062, 18)
Rows: 28062, Columns: 18

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28057,7/12/2024 22:52:01,35-44,Health care,Veterinarian,NaN,135000,NaN,USD,NaN,NaN,United States,Missouri,Wentzville,11 - 20 years,11 - 20 years,"Professional degree (MD, JD, etc.)",Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28059,7/24/2024 12:22:58,18-24,"Accounting, Banking & Finance",Risk Management Associate,NaN,1200,0.0,USD,NaN,NaN,Myanmar,Colorado,Yangon,2 - 4 years,2 - 4 years,Some college,Man,Asian or Asian American
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American
28061,8/20/2024 1:06:13,25-34,Health care,Clinical physiologist,NaN,1200000,NaN,Other,NGN,NaN,Nigeria,NaN,Lagos,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American

What are the columns and their types?

In [18]:
# Show the column names and their types.
df_salary.info()

<class 'pandas.DataFrame'>
RangeIndex: 28062 entries, 0 to 28061
Data columns (total 18 columns):
 #   Column                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                --------------  -----
 0   Timestamp                                                                                                                                                                                                                             28062 non-null  str
 1   How old are you?                                                                                                                                                                                                                      28062 non-null  str
 2   What industry do you work in?                                                                                                                                                                                                         27988 non-null  str
 3   Job title                                                                                                                                                                                                                             28061 non-null  str
 4   If your job title needs additional context, please clarify here:                                                                                                                                                                      7262 non-null   str
 5   What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)  28062 non-null  str
 6   How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                        20766 non-null  float64
 7   Please indicate the currency                                                                                                                                                                                                          28062 non-null  str
 8   If "Other," please indicate the currency here:                                                                                                                                                                                        206 non-null    str
 9   If your income needs additional context, please provide it here:                                                                                                                                                                      3042 non-null   str
 10  What country do you work in?                                                                                                                                                                                                          28062 non-null  str
 11  If you're in the U.S., what state do you work in?                                                                                                                                                                                     23039 non-null  str
 12  What city do you work in?                                                                                                                                                                                                             27980 non-null  str
 13  How many years of professional work experience do you have overall?                                                                                                                                                                   28062 non-null  str
 14  How many years of professional work experience do you have in your field?                                                                                                                                                             28062 non-null  str
 15  What is your highest level of education completed?                                                                                                                                                                                    27840 non-null  str
 16  What is your gender?                                                                                                                                                                                                                  27891 non-null  str
 17  What is your race? (Choose all that apply.)                                                                                                                                                                                           27885 non-null  str
dtypes: float64(1), str(17)
memory usage: 3.9 MB

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [19]:
# Rename 'em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed, gender, race
df_salary.columns = ['timestamp', 'age', 'industry', 'title', 'title_context', 'salary', 'additional_compensation', 'currency', 'other_currency', 'salary_context', 'country', 'state', 'city', 'total_yoe', 'field_yoe', 'highest_education_completed', 'gender', 'race']

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [20]:
# List the unique industries and a count of their instances.
df_salary['industry'].value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [21]:
# Filtery filter.
#df_salary['industry'].value_counts().head(5)
df_salary_tech = df_salary[df_salary['industry'] == 'Tech']

Do a sanity check by counting.

In [22]:
# Sanity check count.
df_salary_tech.shape[0]

3

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [23]:
# Filtery filter (in place) for just the jobs that pay in USD!
df_salary_usd = df_salary[df_salary['currency'].str.upper() == 'USD']

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [24]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.

df_salary['country'].unique()

df_salary_us = df_salary[df_salary['country'] == 'US']
df_salary_us['country'].value_counts()

df_salary_us_tech = df_salary_us[df_salary_us['industry'] == 'Tech']

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [25]:
# Replace them all in-place with 'US'.

df_salary['country'] = df_salary['country'].replace({
    'USA': 'US',
    'United States': 'US',
    'U.S.': 'US',
    'America': 'US',
    'US': 'US'
})

Have a look at the count of each unique country again now.

In [26]:
# Count again.
df_salary['country'].value_counts()

country
US                20137
Canada             1570
United States       667
UK                  574
United Kingdom      547
                  ...
LOUTRELAND            1
philippines           1
ff                    1
Myanmar               1
Burma                 1
Name: count, Length: 375, dtype: int64

Did you notice anything interesting?

In [ ]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [ ]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [ ]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
#df_salary_us['salary'].dtype
df_salary_us.groupby('state')['salary'].agg(['min', 'mean', 'max'])

dtype('float64')

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [47]:
# Fix it in-place.
df_salary_us['salary'] = pd.to_numeric(df_salary_us['salary'], errors='coerce')

Let’s try that again.

In [48]:
# Try it again. Yeah!
df_salary_us.groupby('state')['salary'].agg(['min', 'mean', 'max'])

                                     min           mean       max
state
Alabama                          87000.0   87000.000000   87000.0
Alabama, Montana                     NaN            NaN       NaN
Alabama, Oregon                  50000.0   50000.000000   50000.0
Alaska                           47840.0   60920.000000   74000.0
Arizona                          53000.0   94400.000000  121000.0
Arizona, Utah                        NaN            NaN       NaN
Arkansas                         60000.0   77333.333333   95000.0
California                         105.0  117533.715909  358000.0
California, Oklahoma                 NaN            NaN       NaN
California, Oregon                   NaN            NaN       NaN
Colorado                            65.0   75071.562500  155000.0
Connecticut                      43000.0   82500.000000  132900.0
Delaware                             NaN            NaN       NaN
District of Columbia             48000.0  109084.210526  254000.0
District of Columbia, Maryland       NaN            NaN       NaN
Florida                          30000.0   71603.571429  120500.0
Georgia                          45000.0   86500.000000  200000.0
Hawaii                           53000.0   53000.000000   53000.0
Idaho                            34000.0   40000.000000   46000.0
Illinois                             0.0   88636.621622  195000.0
Illinois, North Carolina         52000.0   52000.000000   52000.0
Indiana                          40000.0   79050.000000  133000.0
Iowa                             38000.0   66833.333333  115000.0
Kansas                           62000.0   93500.000000  125000.0
Kentucky                             0.0   59416.666667  130000.0
Kentucky, Ohio                       NaN            NaN       NaN
Louisiana                        26325.0   75831.250000  107000.0
Maine                            38000.0   76250.000000  114000.0
Maryland                         12000.0  101728.761905  323000.0
Massachusetts                    27000.0   96812.195122  260000.0
Michigan                            55.0   83261.923077  240000.0
Minnesota                        43000.0   87354.062500  150000.0
Mississippi                      31200.0   42600.000000   54000.0
Missouri                            80.0   63433.625000  105000.0
Montana                          19200.0   68066.666667  100000.0
Nebraska                         49955.0  136977.500000  224000.0
Nevada                          165000.0  165000.000000  165000.0
Nevada, Oregon                       NaN            NaN       NaN
New Hampshire                    45760.0   71921.000000  115000.0
New Jersey                       44720.0  106055.384615  170000.0
New Jersey, Pennsylvania             NaN            NaN       NaN
New Mexico                      127000.0  152000.000000  177000.0
New York                         33000.0  119157.397260  305000.0
North Carolina                   31000.0   72095.625000  150000.0
North Dakota                     70000.0   70000.000000   70000.0
Ohio                             18000.0   67907.000000  109000.0
Ohio, Wyoming                        NaN            NaN       NaN
Oklahoma                         35360.0   57680.000000   80000.0
Oregon                               0.0   78007.437500  135200.0
Pennsylvania                     22880.0   85813.393939  252000.0
Rhode Island                     27040.0   48520.000000   70000.0
South Carolina                   40050.0   64210.000000   86228.0
South Dakota                         NaN            NaN       NaN
Tennessee                        41600.0  106068.750000  275000.0
Texas                            45000.0   99918.114286  170000.0
Utah                             65000.0  112600.000000  140000.0
Vermont                          41600.0   55800.000000   70000.0
Virginia                         47000.0  126779.076923  378000.0
Washington                       16000.0  106517.074074  300000.0
West Virginia                       35.0   58133.750000  120000.0
Wisconsin                        28080.0   80159.533333  120000.0
Wyoming                              NaN            NaN       NaN

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [51]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.

df_salary_us['timestamp'] = pd.to_datetime(df_salary_us['timestamp'], errors='coerce')

df_salary_recent = df_salary_us[
    df_salary_us['timestamp'].dt.year.isin([2021, 2022, 2023])
]

df_salary_recent['salary'] = pd.to_numeric(df_salary_recent['salary'], errors='coerce')

df_salary_recent.groupby('state')['salary'].agg(['min', 'mean', 'max'])

                                     min           mean       max
state
Alabama                          87000.0   87000.000000   87000.0
Alabama, Montana                     NaN            NaN       NaN
Alabama, Oregon                  50000.0   50000.000000   50000.0
Alaska                           47840.0   60920.000000   74000.0
Arizona                          53000.0   94400.000000  121000.0
Arizona, Utah                        NaN            NaN       NaN
Arkansas                         60000.0   77333.333333   95000.0
California                         105.0  118080.080460  358000.0
California, Oklahoma                 NaN            NaN       NaN
California, Oregon                   NaN            NaN       NaN
Colorado                            65.0   75071.562500  155000.0
Connecticut                      43000.0   82500.000000  132900.0
Delaware                             NaN            NaN       NaN
District of Columbia             48000.0  109084.210526  254000.0
District of Columbia, Maryland       NaN            NaN       NaN
Florida                          30000.0   71603.571429  120500.0
Georgia                          45000.0   86500.000000  200000.0
Hawaii                           53000.0   53000.000000   53000.0
Idaho                            34000.0   40000.000000   46000.0
Illinois                           110.0   91098.750000  195000.0
Illinois, North Carolina         52000.0   52000.000000   52000.0
Indiana                          40000.0   79050.000000  133000.0
Iowa                             38000.0   66833.333333  115000.0
Kansas                           62000.0   93500.000000  125000.0
Kentucky                             0.0   59416.666667  130000.0
Kentucky, Ohio                       NaN            NaN       NaN
Louisiana                        26325.0   75831.250000  107000.0
Maine                            38000.0   76250.000000  114000.0
Maryland                         12000.0  101728.761905  323000.0
Massachusetts                    27000.0   96812.195122  260000.0
Michigan                            55.0   83261.923077  240000.0
Minnesota                        43000.0   87354.062500  150000.0
Mississippi                      31200.0   42600.000000   54000.0
Missouri                            80.0   63433.625000  105000.0
Montana                          19200.0   68066.666667  100000.0
Nebraska                         49955.0  136977.500000  224000.0
Nevada                          165000.0  165000.000000  165000.0
Nevada, Oregon                       NaN            NaN       NaN
New Hampshire                    45760.0   71921.000000  115000.0
New Jersey                       44720.0  106055.384615  170000.0
New Jersey, Pennsylvania             NaN            NaN       NaN
New Mexico                      127000.0  152000.000000  177000.0
New York                         33000.0  119242.916667  305000.0
North Carolina                   31000.0   72095.625000  150000.0
North Dakota                     70000.0   70000.000000   70000.0
Ohio                             18000.0   67907.000000  109000.0
Ohio, Wyoming                        NaN            NaN       NaN
Oklahoma                         35360.0   57680.000000   80000.0
Oregon                               0.0   78007.437500  135200.0
Pennsylvania                     22880.0   85813.393939  252000.0
Rhode Island                     27040.0   48520.000000   70000.0
South Carolina                   40050.0   64210.000000   86228.0
South Dakota                         NaN            NaN       NaN
Tennessee                        41600.0  106068.750000  275000.0
Texas                            45000.0   99918.114286  170000.0
Utah                             65000.0  112600.000000  140000.0
Vermont                          41600.0   55800.000000   70000.0
Virginia                         47000.0  126779.076923  378000.0
Washington                       16000.0  106517.074074  300000.0
West Virginia                       35.0   58133.750000  120000.0
Wisconsin                        28080.0   80159.533333  120000.0
Wyoming                              NaN            NaN       NaN

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)