# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [6]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.3.3)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/bryanmogrovejo/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /Users/bryanmogrovejo/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [7]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [8]:
# Load the Food choices data set.

Food_Data_Set_Path = '/users/bryanmogrovejo/ds-fall-2026/week-02-pandas-and-how-to-make-a-sick-project/data/food_coded.csv'

df_Food = pd.read_csv(Food_Data_Set_Path)

### Explore the Data

How much data did you just load?

In [9]:
# Count by hand. (lol kidding)

df_Food.shape

(125, 61)

In [10]:
# Try to print or display it nicely.

df_Food.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190

What are the columns and their types in this data set?

In [11]:
# Show the column names and their types.

df_Food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    object
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    object
 8   comfort_food_reasons          123 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    object
 25  fav_cuisine                   123 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    object
 35  ideal_diet                    124 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    object
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     object
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    object
dtypes: float64(20), int64(27), object(14)
memory usage: 59.7+ KB

In [12]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
df_Columns = pd.DataFrame({
  "Column": df_Food.columns,
  "Non-Null Values": df_Food.notna().sum().values,
  "DType": df_Food.dtypes.values
})

df_Columns

                          Column  Non-Null Values    DType
0                            GPA              123   object
1                         Gender              125    int64
2                      breakfast              125    int64
3               calories_chicken              125    int64
4                   calories_day              106  float64
5                 calories_scone              124  float64
6                         coffee              125    int64
7                   comfort_food              124   object
8           comfort_food_reasons              123   object
9     comfort_food_reasons_coded              106  float64
10                          cook              122  float64
11  comfort_food_reasons_coded.1              125    int64
12                       cuisine              108  float64
13                  diet_current              124   object
14            diet_current_coded              125    int64
15                         drink              123  float64
16                eating_changes              122   object
17          eating_changes_coded              125    int64
18         eating_changes_coded1              125    int64
19                    eating_out              125    int64
20                    employment              116  float64
21                   ethnic_food              125    int64
22                      exercise              112  float64
23              father_education              124  float64
24             father_profession              122   object
25                   fav_cuisine              123   object
26             fav_cuisine_coded              125    int64
27                      fav_food              123  float64
28                food_childhood              124   object
29                         fries              125    int64
30                     fruit_day              125    int64
31                   grade_level              125    int64
32                    greek_food              125    int64
33               healthy_feeling              125    int64
34                  healthy_meal              124   object
35                    ideal_diet              124   object
36              ideal_diet_coded              125    int64
37                        income              124  float64
38                   indian_food              125    int64
39                  italian_food              125    int64
40                life_rewarding              124  float64
41                marital_status              124  float64
42           meals_dinner_friend              122   object
43              mother_education              122  float64
44             mother_profession              123   object
45             nutritional_check              125    int64
46                 on_off_campus              124  float64
47                  parents_cook              125    int64
48                  pay_meal_out              125    int64
49                  persian_food              124  float64
50        self_perception_weight              124  float64
51                          soup              124  float64
52                        sports              123  float64
53                     thai_food              125    int64
54             tortilla_calories              124  float64
55               turkey_calories              125    int64
56                   type_sports               99   object
57                   veggies_day              125    int64
58                      vitamins              125    int64
59               waffle_calories              125    int64
60                        weight              123   object

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [13]:
# Remove ‘em.
selected_Cols = ['calories_day', 'weight', 'Gender']
df_Food_Col_Subset = df_Food[selected_Cols]
df_Food_Col_Subset.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

In [14]:
# Is there a second way to remove columns?
df_Food_Col_Subset2 = df_Food.loc[:, selected_Cols]
df_Food_Col_Subset2.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

In [15]:
# 🚀 Extra credit: What about a third way to remove columns?
df_Food_Col_Subset3 = df_Food.drop(columns= df_Food.columns.difference(selected_Cols))
df_Food_Col_Subset3.head()

   Gender  calories_day                    weight
0       2           NaN                       187
1       1           3.0                       155
2       1           4.0  I'm not answering this.
3       1           3.0             Not sure, 240
4       1           2.0                       190

What about `NaN`s? How many are there?

In [16]:
# Count ‘em.
df_Food_Col_Subset.isnull().sum()

calories_day    19
weight           2
Gender           0
dtype: int64

In [17]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.
df_Food_Col_Subset_NaN = pd.DataFrame({
  "Column": df_Food_Col_Subset.columns,
  "NaN": df_Food_Col_Subset.isnull().sum().values
})
df_Food_Col_Subset_NaN.head()

         Column  NaN
0  calories_day   19
1        weight    2
2        Gender    0

In [18]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

We gotta remove those `NaN`s―the entire row.

In [19]:
# Drop ‘em in-place.
df_Food_Col_Subset.dropna()

     calories_day                    weight  Gender
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
5             3.0                       190       1
..            ...                       ...     ...
118           3.0                       140       1
119           3.0                       185       2
120           4.0                       156       1
121           2.0                       180       1
123           4.0                       135       2

[104 rows x 3 columns]

In [20]:
df_Food_Col_Subset.isnull().sum()

calories_day    19
weight           2
Gender           0
dtype: int64

In [21]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂
df_Food.isnull().sum()

GPA                              2
Gender                           0
breakfast                        0
calories_chicken                 0
calories_day                    19
calories_scone                   1
coffee                           0
comfort_food                     1
comfort_food_reasons             2
comfort_food_reasons_coded      19
cook                             3
comfort_food_reasons_coded.1     0
cuisine                         17
diet_current                     1
diet_current_coded               0
drink                            2
eating_changes                   3
eating_changes_coded             0
eating_changes_coded1            0
eating_out                       0
employment                       9
ethnic_food                      0
exercise                        13
father_education                 1
father_profession                3
fav_cuisine                      2
fav_cuisine_coded                0
fav_food                         2
food_childhood                   1
fries                            0
fruit_day                        0
grade_level                      0
greek_food                       0
healthy_feeling                  0
healthy_meal                     1
ideal_diet                       1
ideal_diet_coded                 0
income                           1
indian_food                      0
italian_food                     0
life_rewarding                   1
marital_status                   1
meals_dinner_friend              3
mother_education                 3
mother_profession                2
nutritional_check                0
on_off_campus                    1
parents_cook                     0
pay_meal_out                     0
persian_food                     1
self_perception_weight           1
soup                             1
sports                           2
thai_food                        0
tortilla_calories                1
turkey_calories                  0
type_sports                     26
veggies_day                      0
vitamins                         0
waffle_calories                  0
weight                           2
dtype: int64

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [22]:
# Fix that in-place.
df_Food_Col_Subset[['calories_day', 'weight']] = df_Food_Col_Subset[['calories_day', 'weight']].apply(pd.to_numeric, errors='coerce')
df_Food_Col_Subset_Clean = df_Food_Col_Subset.dropna(subset=['calories_day', 'weight'])
df_Food_Col_Subset_Clean

/var/folders/pl/_xbqq8d11h1fjjj3y86fhvc80000gn/T/ipykernel_34885/351572593.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Food_Col_Subset[['calories_day', 'weight']] = df_Food_Col_Subset[['calories_day', 'weight']].apply(pd.to_numeric, errors='coerce')

     calories_day  weight  Gender
1             3.0   155.0       1
4             2.0   190.0       1
5             3.0   190.0       1
6             3.0   180.0       2
7             3.0   137.0       1
..            ...     ...     ...
118           3.0   140.0       1
119           3.0   185.0       2
120           4.0   156.0       1
121           2.0   180.0       1
123           4.0   135.0       2

[101 rows x 3 columns]

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [23]:
# Savey save!
df_Food_Col_Subset_Clean.to_csv('Food_Column_Subset_Cleaned.csv', index=False)

In [24]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.
with open('food_column_subset_cleaned.csv', 'r') as cleaned:
  for i in range(10):
    print(cleaned.readline())

calories_day,weight,Gender

3.0,155.0,1

2.0,190.0,1

3.0,190.0,1

3.0,180.0,2

3.0,137.0,1

3.0,125.0,1

3.0,116.0,1

4.0,110.0,1

3.0,264.0,2

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [25]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.
df_Salary = pd.read_csv('/users/bryanmogrovejo/ds-fall-2026/week-02-pandas-and-how-to-make-a-sick-project/data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv', sep='\t')
df_Salary.head()

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [26]:
# Count by hand. I’m dead serious.
df_Salary.shape

(28062, 18)

What are the columns and their types?

In [27]:
# Show the column names and their types.
df_Salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28062 entries, 0 to 28061
Data columns (total 18 columns):
 #   Column                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                --------------  -----
 0   Timestamp                                                                                                                                                                                                                             28062 non-null  object
 1   How old are you?                                                                                                                                                                                                                      28062 non-null  object
 2   What industry do you work in?                                                                                                                                                                                                         27988 non-null  object
 3   Job title                                                                                                                                                                                                                             28061 non-null  object
 4   If your job title needs additional context, please clarify here:                                                                                                                                                                      7262 non-null   object
 5   What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)  28062 non-null  object
 6   How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                        20766 non-null  float64
 7   Please indicate the currency                                                                                                                                                                                                          28062 non-null  object
 8   If "Other," please indicate the currency here:                                                                                                                                                                                        206 non-null    object
 9   If your income needs additional context, please provide it here:                                                                                                                                                                      3042 non-null   object
 10  What country do you work in?                                                                                                                                                                                                          28062 non-null  object
 11  If you're in the U.S., what state do you work in?                                                                                                                                                                                     23039 non-null  object
 12  What city do you work in?                                                                                                                                                                                                             27980 non-null  object
 13  How many years of professional work experience do you have overall?                                                                                                                                                                   28062 non-null  object
 14  How many years of professional work experience do you have in your field?                                                                                                                                                             28062 non-null  object
 15  What is your highest level of education completed?                                                                                                                                                                                    27840 non-null  object
 16  What is your gender?                                                                                                                                                                                                                  27891 non-null  object
 17  What is your race? (Choose all that apply.)                                                                                                                                                                                           27885 non-null  object
dtypes: float64(1), object(17)
memory usage: 3.9+ MB

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [28]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race

df_Salary.columns = ['timestamp', 'age', 'industry', 'title', 'title_context', 'salary', 
                     'additional_compensation','currency', 'other_currency', 'salary_context', 'country', 
                     'state', 'city', 'total_yoe', 'field_yoe', 'highest_education_completed', 'gender', 'race']

df_Salary.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [49]:
# List the unique industries and a count of their instances.
df_Salary.industry.value_counts()

industry
Computing or Tech                          4699
Education (Higher Education)               2464
Nonprofits                                 2419
Health care                                1896
Government and Public Administration       1889
                                           ...
Gaming (Gambling)                             1
Regulatory Affairs- nutraceuticals            1
Manufacturing : corporate admin support       1
Real Estate Investment Support                1
Wine & Spirits                                1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [55]:
# Filtery filter.
selected_condition = df_Salary['industry'] == 'Computing or Tech'
df_Salary_Tech = df_Salary[selected_condition].copy()
df_Salary_Tech.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White

Do a sanity check by counting.

In [59]:
# Sanity check count.
df_Salary_Tech.shape

(4699, 18)

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [65]:
# Filtery filter (in place) for just the jobs that pay in USD!
select_USD_Condition = df_Salary_Tech['currency'] == 'USD'
df_Salary_Tech_USD = df_Salary_Tech[select_USD_Condition].copy()
df_Salary_Tech_USD.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,USA,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [67]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_Salary_Tech_USD.country.value_counts()

country
United States                1576
USA                          1222
US                            412
U.S.                          108
United States of America       90
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
UnitedStates                    2
New Zealand                     2
united States                   2
United Kingdom                  2
Brazil                          2
France                          2
U.S.A                           2
Spain                           2
United States of america        2
Usa                             2
U.S                             2
India                           2
Poland                          2
United States Of America        2
United State of America         2
Australia                       2
U.S.                            2
Unite States                    2
Jamaica                         1
Romania                         1
United STates                   1
Japan                           1
US                              1
United Stares                   1
Australian                      1
Denmark                         1
Thailand                        1
Unites States                   1
China                           1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
San Francisco                   1
International                   1
Netherlands                     1
Mexico                          1
United Stated                   1
Danmark                         1
Cuba                            1
Remote (philippines)            1
Singapore                       1
United State                    1
Uruguay                         1
 US                             1
U.s.                            1
Italy                           1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Puerto Rico                     1
America                         1
Uniyed states                   1
Burma                           1
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [73]:
# Replace them all in-place with 'US'.
first_five = df_Salary_Tech_USD['country'].value_counts().head(5).index
df_Salary_Tech_USD.country = df_Salary_Tech_USD['country'].replace(first_five, 'US')

Have a look at the count of each unique country again now.

In [74]:
# Count again.
df_Salary_Tech_USD['country'].value_counts()

country
US                          3700
UnitedStates                   2
Poland                         2
New Zealand                    2
united States                  2
U.S.                           2
United Kingdom                 2
Brazil                         2
U.S.A                          2
Spain                          2
United States Of America       2
United States of america       2
Usa                            2
India                          2
U.S                            2
France                         2
United State of America        2
Australia                      2
Unite States                   2
Ghana                          1
Nigeria                        1
ss                             1
China                          1
San Francisco                  1
Romania                        1
Nigeria                        1
United STates                  1
Denmark                        1
Japan                          1
Jamaica                        1
Colombia                       1
U.S.A                          1
United Stares                  1
Thailand                       1
Netherlands                    1
Australian                     1
Unites States                  1
denmark                        1
United Stateds                 1
Pakistan                       1
Danmark                        1
US                             1
Uniyed states                  1
America                        1
Puerto Rico                    1
U.s.                           1
 US                            1
United State                   1
Cuba                           1
Italy                          1
singapore                      1
International                  1
United Stated                  1
Remote (philippines)           1
Singapore                      1
Uruguay                        1
Mexico                         1
Canada                         1
ISA                            1
Burma                          1
Name: count, dtype: int64

Did you notice anything interesting?

In [36]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [37]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [ ]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
gb_State = df_Salary_Tech_USD.groupby('state')
gb_State['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [91]:
# Fix it in-place.
df_Salary_Tech_USD['salary'] = pd.to_numeric(df_Salary_Tech_USD['salary'], errors='coerce')

Let’s try that again.

In [93]:
# Try it again. Yeah!
gb_State = df_Salary_Tech_USD.groupby('state')
gb_State['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

                                     min           mean        max
state
Michigan, Texas, Washington     340000.0  340000.000000   340000.0
Florida                          28800.0  210711.000000  2600000.0
California, Oregon              200000.0  200000.000000   200000.0
California, Colorado            176000.0  176000.000000   176000.0
Delaware                        169000.0  169000.000000   169000.0
Connecticut                      68000.0  161610.000000   270000.0
California                           0.0  153286.988827   520000.0
New York                         14000.0  146594.112150   590000.0
Wisconsin                            1.0  145806.888889   920000.0
District of Columbia             59000.0  142923.076923   200000.0
New Jersey, New York            135000.0  137500.000000   140000.0
Ohio                             42000.0  137066.666667   954000.0
Washington                          72.0  136923.916667   300000.0
Massachusetts                    41000.0  125899.155844   400000.0
Nevada                          107100.0  124550.000000   142000.0
New Jersey                       67500.0  124090.909091   192000.0
Oregon                           16200.0  122640.000000   230000.0
West Virginia                   120000.0  120000.000000   120000.0
Maryland                         62000.0  119955.461538   176000.0
Illinois                         36000.0  117555.571429   228800.0
Alabama                          35000.0  117400.000000   350000.0
Louisiana, Washington           117000.0  117000.000000   117000.0
Pennsylvania                     52000.0  116826.388889   237000.0
Georgia                          29120.0  115297.647059   242000.0
Virginia                         58750.0  115086.696970   378000.0
Montana                          65000.0  112666.666667   145000.0
Kansas                           41500.0  109666.666667   167000.0
Colorado                         49400.0  109291.891892   165000.0
District of Columbia, Virginia  109200.0  109200.000000   109200.0
Vermont                          91250.0  105625.000000   120000.0
Idaho                            74860.0  105465.000000   170000.0
Utah                             33280.0  105023.333333   176000.0
Maine                            50000.0  103833.333333   173000.0
Texas                            10700.0  103685.245902   190000.0
Kentucky                         62000.0  102500.000000   125000.0
Iowa                             63000.0  101200.000000   142000.0
Minnesota                        52124.0  101064.941176   210000.0
Rhode Island                     76000.0   99475.000000   122950.0
North Carolina                   29000.0   97841.666667   165000.0
Arizona                          35000.0   97833.333333   145000.0
Michigan                         41600.0   95758.823529   235000.0
New Mexico                       82000.0   95733.333333   115200.0
Tennessee                        61500.0   91750.000000   144000.0
New Hampshire                       55.0   87175.833333   130000.0
Oklahoma                         36958.0   84802.571429   180000.0
Indiana                          15000.0   82875.000000   140000.0
California, Maryland             81500.0   81500.000000    81500.0
Louisiana                        75000.0   80500.000000    84000.0
Missouri                            80.0   80339.923077   200000.0
Nebraska                         43000.0   76736.000000   140000.0
Arkansas                             4.0   58001.000000    95000.0
South Carolina                   40000.0   40000.000000    40000.0
Alabama, District of Columbia        NaN            NaN        NaN
Alabama, Montana                     NaN            NaN        NaN
Alaska                               NaN            NaN        NaN
Arizona, Utah                        NaN            NaN        NaN
Georgia, Massachusetts               NaN            NaN        NaN
Georgia, Washington                  NaN            NaN        NaN
Massachusetts, New Hampshire         NaN            NaN        NaN
Massachusetts, Pennsylvania          NaN            NaN        NaN
Massachusetts, Rhode Island          NaN            NaN        NaN
Mississippi                          NaN            NaN        NaN
New York, Texas                      NaN            NaN        NaN
North Dakota                         NaN            NaN        NaN
South Dakota                         NaN            NaN        NaN
Utah, Vermont                        NaN            NaN        NaN

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [97]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_Salary_Tech_USD['timestamp'] = pd.to_datetime(df_Salary_Tech_USD['timestamp'], errors='coerce')

select_Years = df_Salary_Tech_USD['timestamp'].dt.year.isin([2021, 2022, 2023])
df_Salary_Tech_USD_Years = df_Salary_Tech_USD[select_Years].copy()

gb_State_2021_to_2023 = df_Salary_Tech_USD_Years.groupby('state')
gb_State_2021_to_2023['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

                                     min           mean       max
state
Michigan, Texas, Washington     340000.0  340000.000000  340000.0
California, Oregon              200000.0  200000.000000  200000.0
California, Colorado            176000.0  176000.000000  176000.0
Delaware                        169000.0  169000.000000  169000.0
Connecticut                      68000.0  161610.000000  270000.0
California                           0.0  153754.893258  520000.0
New York                         14000.0  146594.112150  590000.0
Wisconsin                            1.0  145806.888889  920000.0
District of Columbia             59000.0  142923.076923  200000.0
Alabama                          52000.0  138000.000000  350000.0
New Jersey, New York            135000.0  137500.000000  140000.0
Washington                          72.0  137427.774648  300000.0
Ohio                             42000.0  137066.666667  954000.0
Massachusetts                    41000.0  125660.986842  400000.0
Nevada                          107100.0  124550.000000  142000.0
New Jersey                       67500.0  124090.909091  192000.0
Oregon                           16200.0  122640.000000  230000.0
West Virginia                   120000.0  120000.000000  120000.0
Maryland                         62000.0  119955.461538  176000.0
Illinois                         36000.0  119248.382353  228800.0
Louisiana, Washington           117000.0  117000.000000  117000.0
Pennsylvania                     52000.0  116826.388889  237000.0
Georgia                          29120.0  115488.484848  242000.0
Virginia                         58750.0  115086.696970  378000.0
Montana                          65000.0  112666.666667  145000.0
Kansas                           41500.0  109666.666667  167000.0
Colorado                         49400.0  109291.891892  165000.0
District of Columbia, Virginia  109200.0  109200.000000  109200.0
Vermont                          91250.0  105625.000000  120000.0
Idaho                            74860.0  105465.000000  170000.0
Utah                             33280.0  105023.333333  176000.0
Maine                            50000.0  103833.333333  173000.0
Texas                            10700.0  103685.245902  190000.0
Kentucky                         62000.0  102500.000000  125000.0
Minnesota                        52124.0  102381.500000  210000.0
Florida                          28800.0  102106.954545  170000.0
Iowa                             63000.0  101200.000000  142000.0
Rhode Island                     76000.0   99475.000000  122950.0
Arizona                          35000.0   97833.333333  145000.0
North Carolina                   29000.0   97250.000000  165000.0
Michigan                         41600.0   95758.823529  235000.0
New Mexico                       82000.0   95733.333333  115200.0
Tennessee                        61500.0   91750.000000  144000.0
New Hampshire                       55.0   87175.833333  130000.0
Oklahoma                         36958.0   84802.571429  180000.0
Indiana                          15000.0   82875.000000  140000.0
California, Maryland             81500.0   81500.000000   81500.0
Louisiana                        75000.0   80500.000000   84000.0
Missouri                            80.0   80339.923077  200000.0
Arkansas                         60000.0   77333.333333   95000.0
Nebraska                         43000.0   76736.000000  140000.0
Alabama, District of Columbia        NaN            NaN       NaN
Alabama, Montana                     NaN            NaN       NaN
Alaska                               NaN            NaN       NaN
Arizona, Utah                        NaN            NaN       NaN
Georgia, Massachusetts               NaN            NaN       NaN
Georgia, Washington                  NaN            NaN       NaN
Massachusetts, New Hampshire         NaN            NaN       NaN
Massachusetts, Pennsylvania          NaN            NaN       NaN
Massachusetts, Rhode Island          NaN            NaN       NaN
Mississippi                          NaN            NaN       NaN
New York, Texas                      NaN            NaN       NaN
North Dakota                         NaN            NaN       NaN
South Carolina                       NaN            NaN       NaN
South Dakota                         NaN            NaN       NaN
Utah, Vermont                        NaN            NaN       NaN

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)