# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [235]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in /Users/imad_lol/Desktop/ctp/.venv/lib/python3.13/site-packages (3.0.6)
Requirement already satisfied: numpy in /Users/imad_lol/Desktop/ctp/.venv/lib/python3.13/site-packages (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/imad_lol/Desktop/ctp/.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/imad_lol/Desktop/ctp/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [236]:
# Import here.
import pandas as pd 
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [237]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [238]:
# Count by hand. (lol kidding)
print(len(df_food))

125

In [239]:
# Try to print or display it nicely.
print(df_food)

       GPA  Gender  breakfast  calories_chicken  calories_day  calories_scone  \
0      2.4       2          1               430           NaN           315.0
1    3.654       1          1               610           3.0           420.0
2      3.3       1          1               720           4.0           420.0
3      3.2       1          1               430           3.0           420.0
4      3.5       1          1               720           2.0           420.0
..     ...     ...        ...               ...           ...             ...
120    3.5       1          1               610           4.0           420.0
121      3       1          1               265           2.0           315.0
122  3.882       1          1               720           NaN           420.0
123      3       2          1               720           4.0           420.0
124    3.9       1          1               430           NaN           315.0

     coffee                             comfort_food  \
0         1                                     none
1         2              chocolate, chips, ice cream
2         2          frozen yogurt, pizza, fast food
3         2         Pizza, Mac and cheese, ice cream
4         2             Ice cream, chocolate, chips
..      ...                                      ...
120       2  wine. mac and cheese, pizza, ice cream
121       2               Pizza / Wings / Cheesecake
122       1               rice, potato, seaweed soup
123       1             Mac n Cheese, Lasagna, Pizza
124       2             Chocolates, pizza, and Ritz.

                              comfort_food_reasons  \
0                            we dont have comfort
1                             Stress, bored, anger
2                                  stress, sadness
3                                          Boredom
4                       Stress, boredom, cravings
..                                             ...
120                           boredom and sadness
121                Loneliness / Homesick / Sadness
122                                        sadness
123  happiness, they are some of my favorite foods
124               hormones, Premenstrual syndrome.

     comfort_food_reasons_coded  ...  soup  sports  thai_food  \
0                           9.0  ...   1.0     1.0          1
1                           1.0  ...   1.0     1.0          2
2                           1.0  ...   1.0     2.0          5
3                           2.0  ...   1.0     2.0          5
4                           1.0  ...   1.0     1.0          4
..                          ...  ...   ...     ...        ...
120                         NaN  ...   1.0     1.0          5
121                         NaN  ...   1.0     NaN          4
122                         NaN  ...   1.0     2.0          5
123                         NaN  ...   2.0     2.0          1
124                         NaN  ...   1.0     2.0          2

    tortilla_calories  turkey_calories  type_sports veggies_day  vitamins  \
0              1165.0              345   car racing           5         1
1               725.0              690  Basketball            4         2
2              1165.0              500         none           5         1
3               725.0              690          NaN           3         1
4               940.0              500     Softball           4         2
..                ...              ...          ...         ...       ...
120             940.0              500     Softball           5         1
121             940.0              500  basketball            5         2
122             580.0              690         none           4         2
123             940.0              500          NaN           3         1
124             725.0              345          NaN           4         2

     waffle_calories                    weight
0               1315                       187
1                900                       155
2                900  I'm not answering this.
3               1315             Not sure, 240
4                760                       190
..               ...                       ...
120             1315                       156
121             1315                       180
122             1315                       120
123             1315                       135
124              575                       135

[125 rows x 61 columns]

What are the columns and their types in this data set?

In [240]:
# Show the column names and their types.
print(df_food.dtypes)

GPA                                 str
Gender                            int64
breakfast                         int64
calories_chicken                  int64
calories_day                    float64
calories_scone                  float64
coffee                            int64
comfort_food                        str
comfort_food_reasons                str
comfort_food_reasons_coded      float64
cook                            float64
comfort_food_reasons_coded.1      int64
cuisine                         float64
diet_current                        str
diet_current_coded                int64
drink                           float64
eating_changes                      str
eating_changes_coded              int64
eating_changes_coded1             int64
eating_out                        int64
employment                      float64
ethnic_food                       int64
exercise                        float64
father_education                float64
father_profession                   str
fav_cuisine                         str
fav_cuisine_coded                 int64
fav_food                        float64
food_childhood                      str
fries                             int64
fruit_day                         int64
grade_level                       int64
greek_food                        int64
healthy_feeling                   int64
healthy_meal                        str
ideal_diet                          str
ideal_diet_coded                  int64
income                          float64
indian_food                       int64
italian_food                      int64
life_rewarding                  float64
marital_status                  float64
meals_dinner_friend                 str
mother_education                float64
mother_profession                   str
nutritional_check                 int64
on_off_campus                   float64
parents_cook                      int64
pay_meal_out                      int64
persian_food                    float64
self_perception_weight          float64
soup                            float64
sports                          float64
thai_food                         int64
tortilla_calories               float64
turkey_calories                   int64
type_sports                         str
veggies_day                       int64
vitamins                          int64
waffle_calories                   int64
weight                              str
dtype: object

In [241]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.
# Try to display the column information as a nice pandas DataFrame.
df_food.dtypes.to_frame(name='Data Type')

                             Data Type
GPA                                str
Gender                           int64
breakfast                        int64
calories_chicken                 int64
calories_day                   float64
calories_scone                 float64
coffee                           int64
comfort_food                       str
comfort_food_reasons               str
comfort_food_reasons_coded     float64
cook                           float64
comfort_food_reasons_coded.1     int64
cuisine                        float64
diet_current                       str
diet_current_coded               int64
drink                          float64
eating_changes                     str
eating_changes_coded             int64
eating_changes_coded1            int64
eating_out                       int64
employment                     float64
ethnic_food                      int64
exercise                       float64
father_education               float64
father_profession                  str
fav_cuisine                        str
fav_cuisine_coded                int64
fav_food                       float64
food_childhood                     str
fries                            int64
fruit_day                        int64
grade_level                      int64
greek_food                       int64
healthy_feeling                  int64
healthy_meal                       str
ideal_diet                         str
ideal_diet_coded                 int64
income                         float64
indian_food                      int64
italian_food                     int64
life_rewarding                 float64
marital_status                 float64
meals_dinner_friend                str
mother_education               float64
mother_profession                  str
nutritional_check                int64
on_off_campus                  float64
parents_cook                     int64
pay_meal_out                     int64
persian_food                   float64
self_perception_weight         float64
soup                           float64
sports                         float64
thai_food                        int64
tortilla_calories              float64
turkey_calories                  int64
type_sports                        str
veggies_day                      int64
vitamins                         int64
waffle_calories                  int64
weight                             str

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [242]:
# Remove ‘em.
df_food_col_subset=df_food[['calories_day','weight','Gender']]
df_food_col_subset.head()
#print(df_food.head())

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

In [243]:
# Is there a second way to remove columns?

df_food_col_subset=df_food.filter(items=['calories_day','weight','Gender'])

df_food_col_subset.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

In [244]:
# 🚀 Extra credit: What about a third way to remove columns?
# The colon ':' means "keep all rows"
# The list after the comma means "keep only these columns"
df_food_col_subset = df_food_col_subset.loc[:, ['calories_day', 'weight', 'Gender']] # ':' means keep all rows and columns after, means only keep these coliums
df_food_col_subset.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

What about `NaN`s? How many are there?

In [245]:
# Count ‘em.
print(df_food.isna().sum())

GPA                              2
Gender                           0
breakfast                        0
calories_chicken                 0
calories_day                    19
calories_scone                   1
coffee                           0
comfort_food                     1
comfort_food_reasons             2
comfort_food_reasons_coded      19
cook                             3
comfort_food_reasons_coded.1     0
cuisine                         17
diet_current                     1
diet_current_coded               0
drink                            2
eating_changes                   3
eating_changes_coded             0
eating_changes_coded1            0
eating_out                       0
employment                       9
ethnic_food                      0
exercise                        13
father_education                 1
father_profession                3
fav_cuisine                      2
fav_cuisine_coded                0
fav_food                         2
food_childhood                   1
fries                            0
fruit_day                        0
grade_level                      0
greek_food                       0
healthy_feeling                  0
healthy_meal                     1
ideal_diet                       1
ideal_diet_coded                 0
income                           1
indian_food                      0
italian_food                     0
life_rewarding                   1
marital_status                   1
meals_dinner_friend              3
mother_education                 3
mother_profession                2
nutritional_check                0
on_off_campus                    1
parents_cook                     0
pay_meal_out                     0
persian_food                     1
self_perception_weight           1
soup                             1
sports                           2
thai_food                        0
tortilla_calories                1
turkey_calories                  0
type_sports                     26
veggies_day                      0
vitamins                         0
waffle_calories                  0
weight                           2
dtype: int64

In [246]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.

df_Nan = df_food.isna().sum()
df_Nan.to_frame(name='NaN')

                              NaN
GPA                             2
Gender                          0
breakfast                       0
calories_chicken                0
calories_day                   19
calories_scone                  1
coffee                          0
comfort_food                    1
comfort_food_reasons            2
comfort_food_reasons_coded     19
cook                            3
comfort_food_reasons_coded.1    0
cuisine                        17
diet_current                    1
diet_current_coded              0
drink                           2
eating_changes                  3
eating_changes_coded            0
eating_changes_coded1           0
eating_out                      0
employment                      9
ethnic_food                     0
exercise                       13
father_education                1
father_profession               3
fav_cuisine                     2
fav_cuisine_coded               0
fav_food                        2
food_childhood                  1
fries                           0
fruit_day                       0
grade_level                     0
greek_food                      0
healthy_feeling                 0
healthy_meal                    1
ideal_diet                      1
ideal_diet_coded                0
income                          1
indian_food                     0
italian_food                    0
life_rewarding                  1
marital_status                  1
meals_dinner_friend             3
mother_education                3
mother_profession               2
nutritional_check               0
on_off_campus                   1
parents_cook                    0
pay_meal_out                    0
persian_food                    1
self_perception_weight          1
soup                            1
sports                          2
thai_food                       0
tortilla_calories               1
turkey_calories                 0
type_sports                    26
veggies_day                     0
vitamins                        0
waffle_calories                 0
weight                          2

In [247]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

df_Nan = df_food.isna() \
                    .sum() \
                    .to_frame(name='NaN Count')

df_Nan

                              NaN Count
GPA                                   2
Gender                                0
breakfast                             0
calories_chicken                      0
calories_day                         19
calories_scone                        1
coffee                                0
comfort_food                          1
comfort_food_reasons                  2
comfort_food_reasons_coded           19
cook                                  3
comfort_food_reasons_coded.1          0
cuisine                              17
diet_current                          1
diet_current_coded                    0
drink                                 2
eating_changes                        3
eating_changes_coded                  0
eating_changes_coded1                 0
eating_out                            0
employment                            9
ethnic_food                           0
exercise                             13
father_education                      1
father_profession                     3
fav_cuisine                           2
fav_cuisine_coded                     0
fav_food                              2
food_childhood                        1
fries                                 0
fruit_day                             0
grade_level                           0
greek_food                            0
healthy_feeling                       0
healthy_meal                          1
ideal_diet                            1
ideal_diet_coded                      0
income                                1
indian_food                           0
italian_food                          0
life_rewarding                        1
marital_status                        1
meals_dinner_friend                   3
mother_education                      3
mother_profession                     2
nutritional_check                     0
on_off_campus                         1
parents_cook                          0
pay_meal_out                          0
persian_food                          1
self_perception_weight                1
soup                                  1
sports                                2
thai_food                             0
tortilla_calories                     1
turkey_calories                       0
type_sports                          26
veggies_day                           0
vitamins                              0
waffle_calories                       0
weight                                2

We gotta remove those `NaN`s―the entire row.

In [248]:
# Drop ‘em in-place.
df_Nan = df_food.dropna()
df_Nan.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
6,3.8,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.0,1.0,5,940.0,690,soccer,4,1,1315,180
7,3.3,1,1,720,3.0,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,...,1.0,2.0,1,725.0,500,none,4,2,1315,137

In [249]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂
print(len(df_food))

125

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [250]:
# Fix that in-place.
# print(df_food.dtypes) # check data types of all columns 
# print("BEFORE:")
# print("GPA:")
# print(df_food['GPA'].unique()) # check actually entries 
# print("WEIGHT:")
# print(df_food['weight'].unique())

# convert invalid entries to NaN
df_food['GPA']=pd.to_numeric(df_food['GPA'],errors='coerce')
df_food['weight']=pd.to_numeric(df_food['weight'],errors='coerce')

print("AFTER:")
print("GPA:")
print(df_food['GPA'].unique()) 
print("WEIGHT:")
print(df_food['weight'].unique())

# drop nan rows 
df_food=df_food.dropna(subset=['GPA','weight'])

# check if everything is numbers now 
print(df_food.dtypes)

AFTER:
GPA:
[2.4   3.654 3.3   3.2   3.5   2.25  3.8   3.904 3.4   3.6   3.1     nan
 4.    2.2   3.87  3.7   3.9   2.8   3.    3.65  3.89  2.9   3.605 3.83
 3.292 3.35  2.6   3.67  3.73  2.71  3.68  3.75  3.92  3.77  3.63  3.882]
WEIGHT:
[187. 155.  nan 190. 180. 137. 125. 116. 110. 264. 123. 185. 145. 170.
 135. 165. 175. 195. 105. 160. 167. 115. 205. 128. 150. 140. 120. 100.
 113. 168. 169. 200. 265. 192. 118. 210. 112. 130. 127. 129. 260. 184.
 230. 138. 156.]
GPA                             float64
Gender                            int64
breakfast                         int64
calories_chicken                  int64
calories_day                    float64
calories_scone                  float64
coffee                            int64
comfort_food                        str
comfort_food_reasons                str
comfort_food_reasons_coded      float64
cook                            float64
comfort_food_reasons_coded.1      int64
cuisine                         float64
diet_current                        str
diet_current_coded                int64
drink                           float64
eating_changes                      str
eating_changes_coded              int64
eating_changes_coded1             int64
eating_out                        int64
employment                      float64
ethnic_food                       int64
exercise                        float64
father_education                float64
father_profession                   str
fav_cuisine                         str
fav_cuisine_coded                 int64
fav_food                        float64
food_childhood                      str
fries                             int64
fruit_day                         int64
grade_level                       int64
greek_food                        int64
healthy_feeling                   int64
healthy_meal                        str
ideal_diet                          str
ideal_diet_coded                  int64
income                          float64
indian_food                       int64
italian_food                      int64
life_rewarding                  float64
marital_status                  float64
meals_dinner_friend                 str
mother_education                float64
mother_profession                   str
nutritional_check                 int64
on_off_campus                   float64
parents_cook                      int64
pay_meal_out                      int64
persian_food                    float64
self_perception_weight          float64
soup                            float64
sports                          float64
thai_food                         int64
tortilla_calories               float64
turkey_calories                   int64
type_sports                         str
veggies_day                       int64
vitamins                          int64
waffle_calories                   int64
weight                          float64
dtype: object

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [251]:
# Savey save!
df_food.to_csv('final_food_data.csv',index=False)

In [252]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.

data_set_path='final_food_data.csv'
new_df=pd.read_csv(data_set_path)
new_df.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.400,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187.0
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155.0
2,3.500,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190.0
3,2.250,1,1,610,3.0,980.0,2,"Candy, brownies and soda.","None, i don't eat comfort food. I just eat whe...",4.0,...,1.0,2.0,4,940.0,345,None.,1,2,1315,190.0
4,3.800,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.0,1.0,5,940.0,690,soccer,4,1,1315,180.0

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [253]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.
salary_df_path='../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv'

df_salary=pd.read_csv(salary_df_path, sep='\t') # csv are seperated by commas if spesrayed by anything else will get an error 

df_salary.head()

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [254]:
# Count by hand. I’m dead serious.
print(len(df_salary))

28062

What are the columns and their types?

In [255]:
# Show the column names and their types.
print(df_salary.dtypes)

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [256]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race

# overwrite all columns 
df_salary.columns =['timestamp','age','industry', 'title', 'title_context', 'salary', 'additional_compensation', 'currency', 'other_currency', 'salary_context', 'country', 'state', 'city', 'total_yoe', 'field_yoe', 'highest_education_completed','gender', 'race']
df_salary.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [257]:
# List the unique industries and a count of their instances.
print(df_salary['industry'].value_counts())

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [258]:
# Filtery filter.
df_salary_tech = df_salary[df_salary['industry'] == 'Computing or Tech']
df_salary_tech.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White

Do a sanity check by counting.

In [259]:
# Sanity check count.
print(len(df_salary_tech))

4699

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [260]:
# Filtery filter (in place) for just the jobs that pay in USD!
df_salary_tech=df_salary_tech[df_salary_tech['currency']=='USD']
df_salary_tech.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,USA,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [261]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
print(df_salary_tech['country'].value_counts())

country
United States                1576
USA                          1222
US                            412
U.S.                          108
United States of America       90
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [262]:
# Replace them all in-place with 'US'.

top_5 = df_salary_tech['country'].value_counts().head(5).index # get top 5 

df_salary_tech['country'] = df_salary_tech['country'].replace(top_5, 'US') # replace with 'US'

df_salary_tech.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,US,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",US,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,US,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,US,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White

Have a look at the count of each unique country again now.

In [263]:
# Count again.
print(df_salary_tech['country'].value_counts())

country
US                           3408
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

Did you notice anything interesting?

In [264]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [265]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [266]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
salary_by_state = (
    df_salary_tech[df_salary_tech['country'] == 'US']
    .groupby('state')['salary']
    .agg(['min', 'mean', 'max'])
    .reset_index()
)

print(salary_by_state)

TypeError: dtype 'str' does not support operation 'mean'

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [ ]:
# Fix it in-place.
df_salary_tech['salary']=pd.to_numeric(df_salary_tech['salary'],errors='coerce')
# drop nan rows 
df_salary_tech=df_salary_tech.dropna(subset=['salary'])

Let’s try that again.

In [ ]:
# Try it again. Yeah!
# Find the minimum, mean, and maximum salary in USD by U.S. state.
salary_by_state = (
    df_salary_tech[df_salary_tech['country'] == 'US']
    .groupby('state')['salary']
    .agg(['min', 'mean', 'max'])
    .reset_index()
)

print(salary_by_state)

                             state       min           mean        max
0                          Alabama   35000.0  117400.000000   350000.0
1                          Arizona   35000.0   97833.333333   145000.0
2                         Arkansas   60000.0   77333.333333    95000.0
3                       California       0.0  154125.843931   520000.0
4             California, Colorado  176000.0  176000.000000   176000.0
5             California, Maryland   81500.0   81500.000000    81500.0
6               California, Oregon  200000.0  200000.000000   200000.0
7                         Colorado   49400.0  109565.714286   165000.0
8                      Connecticut   68000.0  161610.000000   270000.0
9                         Delaware  169000.0  169000.000000   169000.0
10            District of Columbia   59000.0  146181.818182   200000.0
11  District of Columbia, Virginia  109200.0  109200.000000   109200.0
12                         Florida   28800.0  210711.000000  2600000.0
13                         Georgia   29120.0  114321.818182   242000.0
14                           Idaho   74860.0  105465.000000   170000.0
15                        Illinois   36000.0  117555.571429   228800.0
16                         Indiana   15000.0   82875.000000   140000.0
17                            Iowa   63000.0  101200.000000   142000.0
18                          Kansas   41500.0  109666.666667   167000.0
19                        Kentucky   62000.0  102500.000000   125000.0
20                       Louisiana   75000.0   80500.000000    84000.0
21           Louisiana, Washington  117000.0  117000.000000   117000.0
22                           Maine   50000.0  103833.333333   173000.0
23                        Maryland   62000.0  122038.272727   176000.0
24                   Massachusetts   41000.0  125759.932432   400000.0
25                        Michigan   41600.0   98618.750000   235000.0
26                       Minnesota   52124.0  101064.941176   210000.0
27                        Missouri      80.0   80339.923077   200000.0
28                         Montana   65000.0  112666.666667   145000.0
29                        Nebraska   43000.0   70920.000000   140000.0
30                          Nevada  107100.0  124550.000000   142000.0
31                   New Hampshire      55.0   78611.000000   120000.0
32                      New Jersey   90000.0  129750.000000   192000.0
33            New Jersey, New York  135000.0  137500.000000   140000.0
34                      New Mexico   82000.0   95733.333333   115200.0
35                        New York   14000.0  146995.904762   590000.0
36                  North Carolina   29000.0   97353.448276   165000.0
37                            Ohio   42000.0  137066.666667   954000.0
38                        Oklahoma   36958.0   84802.571429   180000.0
39                          Oregon   16200.0  122563.636364   230000.0
40                    Pennsylvania   52000.0  116826.388889   237000.0
41                    Rhode Island   76000.0   99475.000000   122950.0
42                  South Carolina   40000.0   40000.000000    40000.0
43                       Tennessee   61500.0   91750.000000   144000.0
44                           Texas   10700.0  104296.666667   190000.0
45                            Utah   33280.0  105023.333333   176000.0
46                         Vermont   91250.0  105625.000000   120000.0
47                        Virginia   58750.0  115382.612903   378000.0
48                      Washington      72.0  136313.060606   300000.0
49                   West Virginia  120000.0  120000.000000   120000.0
50                       Wisconsin       1.0  142069.269231   920000.0

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [ ]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.

#print(df_salary_tech.dtypes)

# need to convert timestamps str into dates 
df_salary_tech['timestamp'] = pd.to_datetime(df_salary_tech['timestamp'])

# filter by year

df_21_to_23 = df_salary_tech[
    (df_salary_tech['country'] == 'US') & 
    (df_salary_tech['timestamp'].dt.year.isin([2021, 2022, 2023]))
]


salary_by_state = (
    df_21_to_23
    .groupby(['timestamp','state'])['salary']
    .agg(['min', 'mean', 'max'])
    .reset_index()
)

print(salary_by_state)

              timestamp          state       min      mean       max
0   2021-04-27 17:02:03      Wisconsin       1.0       1.0       1.0
1   2021-04-28 06:41:31  New Hampshire      55.0      55.0      55.0
2   2021-04-28 16:45:53     California       0.0       0.0       0.0
3   2021-04-28 17:22:37     California     240.0     240.0     240.0
4   2021-04-28 22:49:19     Washington      72.0      72.0      72.0
..                  ...            ...       ...       ...       ...
968 2023-03-28 18:41:56       Maryland  116421.0  116421.0  116421.0
969 2023-04-18 09:26:31        Georgia   60000.0   60000.0   60000.0
970 2023-05-09 17:57:30       Virginia   65000.0   65000.0   65000.0
971 2023-05-28 16:10:53       New York   65000.0   65000.0   65000.0
972 2023-09-08 12:35:45          Texas   35000.0   35000.0   35000.0

[973 rows x 5 columns]

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)