# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy in /usr/local/python/3.14.2/lib/python3.14/site-packages (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Import here.
import numpy as np
import pandas as pd

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [5]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [6]:
# Count by hand. (lol kidding)

print("Number of rows:", len(df_food))
print("Number of columns:", len(df_food.columns))
print("Shape:", df_food.shape)

Number of rows: 125
Number of columns: 61
Shape: (125, 61)

In [7]:
# Try to print or display it nicely.

df_food.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190

What are the columns and their types in this data set?

In [8]:
# Show the column names and their types.

df_food.dtypes

GPA                     str
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports             str
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight                  str
Length: 61, dtype: object

In [9]:
pd.set_option("display.max_rows", 100)  # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.

column_info = pd.DataFrame({
    "column_name": df_food.columns,
    "dtype": df_food.dtypes.values
})

column_info

                     column_name    dtype
0                            GPA      str
1                         Gender    int64
2                      breakfast    int64
3               calories_chicken    int64
4                   calories_day  float64
5                 calories_scone  float64
6                         coffee    int64
7                   comfort_food      str
8           comfort_food_reasons      str
9     comfort_food_reasons_coded  float64
10                          cook  float64
11  comfort_food_reasons_coded.1    int64
12                       cuisine  float64
13                  diet_current      str
14            diet_current_coded    int64
15                         drink  float64
16                eating_changes      str
17          eating_changes_coded    int64
18         eating_changes_coded1    int64
19                    eating_out    int64
20                    employment  float64
21                   ethnic_food    int64
22                      exercise  float64
23              father_education  float64
24             father_profession      str
25                   fav_cuisine      str
26             fav_cuisine_coded    int64
27                      fav_food  float64
28                food_childhood      str
29                         fries    int64
30                     fruit_day    int64
31                   grade_level    int64
32                    greek_food    int64
33               healthy_feeling    int64
34                  healthy_meal      str
35                    ideal_diet      str
36              ideal_diet_coded    int64
37                        income  float64
38                   indian_food    int64
39                  italian_food    int64
40                life_rewarding  float64
41                marital_status  float64
42           meals_dinner_friend      str
43              mother_education  float64
44             mother_profession      str
45             nutritional_check    int64
46                 on_off_campus  float64
47                  parents_cook    int64
48                  pay_meal_out    int64
49                  persian_food  float64
50        self_perception_weight  float64
51                          soup  float64
52                        sports  float64
53                     thai_food    int64
54             tortilla_calories  float64
55               turkey_calories    int64
56                   type_sports      str
57                   veggies_day    int64
58                      vitamins    int64
59               waffle_calories    int64
60                        weight      str

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [10]:
# Remove ‘em.

columns_to_keep = ["Gender", "calories_day", "weight"]
df_food_col_subset = df_food[columns_to_keep].copy()

df_food_col_subset.head()

   Gender  calories_day                    weight
0       2           NaN                       187
1       1           3.0                       155
2       1           4.0  I'm not answering this.
3       1           3.0             Not sure, 240
4       1           2.0                       190

In [11]:
# Is there a second way to remove columns?

df_food_col_subset = df_food.loc[:, ["Gender", "calories_day", "weight"]].copy()

df_food_col_subset.head()

   Gender  calories_day                    weight
0       2           NaN                       187
1       1           3.0                       155
2       1           4.0  I'm not answering this.
3       1           3.0             Not sure, 240
4       1           2.0                       190

In [ ]:
# 🚀 Extra credit: What about a third way to remove columns?

What about `NaN`s? How many are there?

In [ ]:
# Count ‘em.

df_food_col_subset.isna().sum()

In [ ]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.

In [ ]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

We gotta remove those `NaN`s―the entire row.

In [12]:
# Drop ‘em in-place.

df_food_col_subset = df_food_col_subset.dropna().copy()

print(df_food_col_subset.shape)

(104, 3)

In [ ]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [13]:
# Fix that in-place.

df_food_col_subset["weight"] = pd.to_numeric(df_food_col_subset["weight"], errors="coerce")
df_food_col_subset = df_food_col_subset.dropna().copy()

print(df_food_col_subset.dtypes)

Gender            int64
calories_day    float64
weight          float64
dtype: object

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [14]:
# Savey save!

output_path = 'food_cleaned.csv'
df_food_col_subset.to_csv(output_path, index=False)

print(f"Saved cleaned data to {output_path}")

Saved cleaned data to food_cleaned.csv

In [ ]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [16]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.

df_salary = pd.read_csv('../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv', sep='\t')

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [17]:
# Count by hand. I’m dead serious.

print("Number of rows:", len(df_salary))
print("Number of columns:", len(df_salary.columns))
print("Shape:", df_salary.shape)

Number of rows: 28062
Number of columns: 18
Shape: (28062, 18)

What are the columns and their types?

In [18]:
# Show the column names and their types.

df_salary.dtypes

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [19]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed, gender, race

new_columns = [
    "timestamp", "age", "industry", "title", "title_context", "salary",
    "additional_compensation", "currency", "other_currency", "salary_context",
    "country", "state", "city", "total_yoe", "field_yoe",
    "highest_education_completed", "gender", "race"
]

df_salary.columns = new_columns

df_salary.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [20]:
# List the unique industries and a count of their instances.

industry_counts = df_salary["industry"].value_counts()
print(industry_counts.head(10))

industry
Computing or Tech                       4699
Education (Higher Education)            2464
Nonprofits                              2419
Health care                             1896
Government and Public Administration    1889
Accounting, Banking & Finance           1809
Engineering or Manufacturing            1695
Marketing, Advertising & PR             1133
Law                                     1097
Business or Consulting                   852
Name: count, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [21]:
# Filtery filter.

tech_industry = df_salary["industry"].value_counts().head(5).index[0]
df_salary_tech = df_salary[df_salary["industry"] == tech_industry].copy()

print(df_salary_tech.shape)

(4699, 18)

Do a sanity check by counting.

In [22]:
# Sanity check count.

print("Tech rows:", len(df_salary_tech))

Tech rows: 4699

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [23]:
# Filtery filter (in place) for just the jobs that pay in USD!

df_salary_tech = df_salary_tech[df_salary_tech['currency'] == 'USD'].copy()

print(df_salary_tech.shape)

(3777, 18)

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [24]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.

country_counts = df_salary_tech["country"].value_counts()
print(country_counts.head(10))

country
United States               1576
USA                         1222
US                           412
U.S.                         108
United States of America      90
United States                 68
Usa                           59
USA                           56
usa                           28
United states                 23
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [25]:
# Replace them all in-place with 'US'.

for value in ['United States', 'United States of America', 'USA', 'U.S.', 'US']:
    df_salary_tech.loc[df_salary_tech['country'] == value, 'country'] = 'US'

Have a look at the count of each unique country again now.

In [26]:
# Count again.

print(df_salary_tech["country"].value_counts().head(10))

country
US                3408
United States       68
Usa                 59
USA                 56
usa                 28
United states       23
united states       14
Us                  12
us                   9
U.S.A.               7
Name: count, dtype: int64

Did you notice anything interesting?

In [ ]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [ ]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [27]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.

# This is the step that will reveal the salary column is still stored as text.
state_summary = (
    df_salary_tech[df_salary_tech['country'] == 'US']
    .groupby('state')['salary']
    .agg(['min', 'mean', 'max'])
    .sort_values('mean', ascending=False)
)

print(state_summary.head(10))

TypeError: dtype 'str' does not support operation 'mean'

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [28]:
# Fix it in-place.

df_salary_tech["salary"] = pd.to_numeric(
    df_salary_tech['salary']
    .astype(str)
    .str.replace(',', '', regex=False),
    errors="coerce"
)

df_salary_tech = df_salary_tech.dropna(subset=["salary"]).copy()

print(df_salary_tech["salary"].dtype)

int64

Let’s try that again.

In [29]:
# Try it again. Yeah!

state_summary = (
    df_salary_tech[df_salary_tech['country'] == 'US']
    .groupby('state')['salary']
    .agg(['min', 'mean', 'max'])
    .sort_values('mean', ascending=False)
)

print(state_summary.head(10))

                                  min           mean      max
state
California, Oregon             200000  200000.000000   200000
California, Colorado           176000  176000.000000   176000
Florida                         28800  160155.204082  2600000
California                          0  156001.126230   875000
Alabama, District of Columbia  156000  156000.000000   156000
Washington                         72  150592.449367   950000
New York                        14000  148213.307692   590000
New Mexico                      82000  140466.666667   300000
New Jersey, New York           135000  137500.000000   140000
Massachusetts                   37000  135924.303704  1650000

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [30]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.

df_salary_tech["timestamp"] = pd.to_datetime(df_salary_tech["timestamp"], errors="coerce")
df_salary_tech_2021_2023 = df_salary_tech[df_salary_tech["timestamp"].dt.year.isin([2021, 2022, 2023])].copy()

state_summary_2021_2023 = (
    df_salary_tech_2021_2023[df_salary_tech_2021_2023['country'] == 'US']
    .groupby('state')['salary']
    .agg(['min', 'mean', 'max'])
    .sort_values('mean', ascending=False)
)

print(state_summary_2021_2023.head(10))

                                  min           mean      max
state
California, Oregon             200000  200000.000000   200000
California, Colorado           176000  176000.000000   176000
California                          0  156142.343186   875000
Alabama, District of Columbia  156000  156000.000000   156000
Washington                         72  150749.409524   950000
New York                        14000  148213.307692   590000
New Mexico                      82000  140466.666667   300000
New Jersey, New York           135000  137500.000000   140000
Massachusetts                   37000  135924.303704  1650000
District of Columbia            10000  134191.673469   267500

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)