# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy in /usr/local/python/3.14.2/lib/python3.14/site-packages (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [3]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)
df_food_def = df_food

### Explore the Data

How much data did you just load?

In [4]:
# Count by hand. (lol kidding)
df_food.shape

(125, 61)

In [66]:
# Try to print or display it nicely.

df_food.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190

What are the columns and their types in this data set?

In [5]:
# Show the column names and their types.

df_food.head().dtypes

GPA                     str
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports             str
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight                  str
Length: 61, dtype: object

In [44]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
display(df_food)

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,...,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,...,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,...,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,...,1.0,2.0,2,725.0,345,NaN,4,2,575,135

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [ ]:
# Remove ‘em.
df_food_col_subset = df_food[['calories_day', 'weight', 'Gender']].copy()

In [7]:
# Is there a second way to remove columns?
df_drop = df_food.drop(columns=['breakfast'])

In [ ]:
# 🚀 Extra credit: What about a third way to remove columns?

What about `NaN`s? How many are there?

In [8]:
# Count ‘em.
df_food.isna().sum().sum()

np.int64(149)

In [9]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.

df_na = pd.DataFrame(df_food.isna().sum())
df_na.columns = ["Nan Count"]
df_na.head()

                  Nan Count
GPA                       2
Gender                    0
breakfast                 0
calories_chicken          0
calories_day             19

In [38]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

We gotta remove those `NaN`s―the entire row.

In [10]:
# Drop ‘em in-place.
# df_food.replace("nan", " ", inplace=True)
df_food = df_food.dropna()

df_food

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
6,3.8,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.0,1.0,5,940.0,690,soccer,4,1,1315,180
7,3.3,1,1,720,3.0,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,...,1.0,2.0,1,725.0,500,none,4,2,1315,137
9,3.3,1,1,430,3.0,315.0,2,"Mac and cheese, chocolate, and pasta","Stress, anger and sadness",1.0,...,1.0,1.0,4,580.0,345,field hockey,5,1,900,125
10,3.5,1,1,610,3.0,980.0,2,"Pasta, grandma homemade chocolate cake anythin...",Boredom,2.0,...,1.0,1.0,2,940.0,345,soccer,5,2,900,116
11,3.904,1,1,720,4.0,420.0,2,"chocolate, pasta, soup, chips, popcorn","sadness, stress, cold weather",3.0,...,1.0,1.0,5,940.0,500,Running,5,1,900,110
12,3.4,2,1,430,3.0,420.0,2,"Cookies, popcorn, and chips","Sadness, boredom, late night snack",3.0,...,2.0,1.0,3,940.0,500,Soccer and basketball,3,2,575,264
13,3.6,1,1,610,3.0,420.0,2,"ice cream, cake, chocolate","stress, boredom, special occasions",1.0,...,1.0,1.0,5,1165.0,850,intramural volleyball,5,2,1315,123
14,3.1,2,1,610,3.0,420.0,2,"Pizza, fruit, spaghetti, chicken and Potatoes","Friends, environment and boredom",2.0,...,1.0,1.0,4,940.0,500,Hockey,5,1,900,185
17,3.6,2,1,430,3.0,980.0,2,"chips, cookies, ice cream",I usually only eat comfort food when I'm bored...,2.0,...,1.0,1.0,3,940.0,500,hockey,4,2,900,170
18,3.4,1,1,720,3.0,980.0,1,"Chocolate, ice crea","Sadness, stress",3.0,...,2.0,2.0,1,1165.0,690,dancing,5,1,1315,135
20,3.3,2,1,610,3.0,980.0,2,"Fast food, pizza, subs","happiness, satisfaction",7.0,...,1.0,1.0,1,1165.0,850,Soccer,3,2,1315,175
22,3.7,2,1,610,3.0,420.0,1,"burgers, chips, cookies","sadness, depression",3.0,...,1.0,1.0,4,940.0,850,tennis soccer gym,3,1,1315,185
23,3.7,2,2,610,3.0,420.0,2,"Chilli, soup, pot pie",Stress and boredom,1.0,...,1.0,1.0,4,940.0,690,Gaelic Football,4,1,1315,185
25,2.8,1,2,720,3.0,420.0,2,"chocolate, ice cream/milkshake, cookies",boredom,2.0,...,1.0,1.0,3,1165.0,690,Ice hockey,3,2,760,125
26,3.7,2,1,610,2.0,420.0,1,"Chips, ice cream, microwaveable foods","Boredom, lazyniss",2.0,...,2.0,1.0,2,1165.0,850,Hockey,3,2,1315,160
27,3,2,1,610,4.0,980.0,2,"Chicken fingers, pizza",Boredom,2.0,...,1.0,1.0,3,1165.0,500,Lacrosse,5,1,1315,175
31,4,2,1,610,3.0,420.0,2,"chips and dip, pepsi,","stres, boredom, and nighttime",1.0,...,2.0,2.0,4,940.0,690,none organized,5,1,1315,205
34,3.65,1,1,610,3.0,420.0,2,"french fries, chips, ice cream","boredom, stressed, sad",2.0,...,1.0,1.0,3,940.0,345,softball,4,1,1315,150
35,3,1,1,610,2.0,420.0,2,"mac n cheese, peanut butter and banana sandwic...",Boredom usually,2.0,...,1.0,1.0,2,940.0,690,Lacrosse,5,2,760,150
37,3.4,1,1,720,4.0,420.0,2,"chocolate, chips, candy",Stress,1.0,...,1.0,1.0,5,940.0,500,Dancing,4,2,1315,170
38,3.89,1,1,610,3.0,980.0,2,"chocolate, popcorn, ice cream","boredom, stress",2.0,...,1.0,1.0,2,1165.0,690,Lacrosse,3,2,1315,150
40,3.4,2,1,430,3.0,315.0,1,"Pizza, Ice cream, fries, cereal, cookies",Usually if I'm sad or depressed.,3.0,...,1.0,1.0,3,940.0,500,wrestling,4,2,760,140
44,3.2,1,1,610,4.0,420.0,2,"Potato chips, ice cream, chocolate, cookies","Stress, boredom, craving",1.0,...,1.0,1.0,5,725.0,500,Volleyball,5,1,760,170
46,3.8,2,1,430,2.0,420.0,1,"popcorn, chips, candy, & fries","sadness, boredom, & anger",3.0,...,1.0,1.0,3,725.0,345,soccer,4,2,900,168
51,3.3,2,1,610,4.0,980.0,1,Burger,Lazy,5.0,...,1.0,1.0,5,1165.0,500,Hockey,4,1,1315,185
54,3.5,2,1,610,3.0,420.0,2,"peanut butter sandwich, pretzals, garlic bread","stress, anger and boredom",1.0,...,1.0,1.0,4,940.0,690,hockey,5,1,900,165
56,3.8,2,1,720,4.0,315.0,2,"Pizza, Ice Cream, Chicken Wings",I usually only eat comfort foods when I am bor...,2.0,...,1.0,1.0,5,1165.0,500,Hockey,5,1,1315,175
57,2.8,1,1,610,4.0,980.0,2,Pizza chocolate chips bagels ice Capps,Just cause,9.0,...,2.0,1.0,2,725.0,345,softball,4,1,1315,140
58,3.5,1,1,610,3.0,420.0,2,"Chocolate, ice cream, pasta","Stress, boredom, sadness",1.0,...,1.0,1.0,5,1165.0,690,Skiing,5,1,1315,155
60,3.6,1,1,610,4.0,420.0,2,"peanut butter, dessets, pretzels.","Sadness, boredom, lonely.",3.0,...,1.0,1.0,1,1165.0,690,Water polo and running,5,1,1315,135
62,3.9,2,1,610,4.0,980.0,2,"ice cream, cookies, ice cream","boredom, sadness",2.0,...,1.0,1.0,2,1165.0,850,Ice Hockey,4,1,1315,210
64,3.5,1,1,610,3.0,420.0,1,"cookies, nutella, ice cream, coffee, fruit","Bordem, happiness, sadness",2.0,...,2.0,1.0,3,940.0,500,Volleyball,5,1,760,140
67,3.6,1,1,610,2.0,420.0,1,"Ice cream, cake, mozzarella sticks, pierogies",Boredom,2.0,...,1.0,1.0,2,940.0,690,"Recreational Basketball, Equestrian Team",5,2,1315,144 lbs
68,3.2,1,1,430,3.0,315.0,1,"Chips, Mac and cheese, pizza, French fries","Stress, sadness, bored",1.0,...,1.0,1.0,4,725.0,500,soccer,5,2,760,145
70,3.73,1,1,610,3.0,980.0,2,"Broccoli, spaghetti squash, quinoa, and grille...","Bad day, bored, sadness",2.0,...,1.0,1.0,5,1165.0,500,Rec Volleyball,5,1,1315,140
73,3.79 bitch,2,1,720,4.0,420.0,2,"Chips, ice cream","Boredom, stress",2.0,...,1.0,1.0,2,1165.0,850,baseball,4,1,1315,200
75,3,1,1,610,3.0,420.0,2,"mac and cheese, potato soup, ice cream, chips ...","sadness, stressed, boredom",3.0,...,1.0,2.0,4,940.0,500,I danced in high school,4,1,900,120
76,3.7,1,2,610,3.0,420.0,1,"chocolate, pizza, and mashed potatoes",boredom and stress,2.0,...,2.0,1.0,1,1165.0,690,horse back riding,2,2,1315,150
77,3.1,2,2,265,2.0,420.0,1,Pizza cookies steak,Boredom comfort hunger,2.0,...,2.0,1.0,2,725.0,345,Basketball,2,2,900,200
78,3,1,1,720,3.0,420.0,2,"chocolate, fruit, and ice cream","stress, boredom",1.0,...,1.0,1.0,3,580.0,345,competitive skiing,4,1,1315,135
79,3.9,2,1,720,3.0,420.0,2,Chips sweets popcorn,Boredom,2.0,...,1.0,1.0,5,1165.0,850,"Rowing, Running, and Cycling",4,2,1315,145
81,3.5,1,2,610,3.0,420.0,1,"cake, French fries, chicken nuggets","boredom, sadness",2.0,...,2.0,1.0,4,725.0,500,softball and basketball,2,2,900,190
84,3.83,1,1,720,3.0,420.0,2,"Pasta dishes, Cheesecake, Pancakes","Sadness, Loneliness, Boredom",3.0,...,1.0,1.0,5,725.0,690,Collegiate Water Polo,5,1,760,167
85,2.6,1,1,265,3.0,315.0,2,"Ice cream, pizza, cookies",Mostly Stress,1.0,...,1.0,2.0,3,580.0,500,None right now,4,1,760,140
86,3,1,1,610,3.0,420.0,2,"Chinese food, moes, sponge candy, homemade las...","boredom, sadness",2.0,...,1.0,1.0,4,580.0,500,"volleyball, lacrosse",4,1,900,190
87,3.2,2,1,720,3.0,420.0,1,"pizza, pasta, mac and cheese",when i am sad or craving,3.0,...,1.0,1.0,1,1165.0,690,field hockey,4,1,1315,155
91,3.8,1,2,610,2.0,420.0,2,"Macaroni and cheese, chicken noodle soup, pizza",Boredom and stress,2.0,...,1.0,2.0,1,725.0,500,crew,1,2,900,135
96,3.92,2,1,430,3.0,420.0,2,"Ice cream, cake, pop, pizza, and milkshakes.","Happiness, sadness, celebration.",7.0,...,1.0,2.0,3,725.0,500,Soccer,2,1,900,210
103,3.7,1,1,610,3.0,420.0,2,"dark chocolate, terra chips, reese's cups(dark...","Anxiousness, watching TV I desire ""comfort food""",8.0,...,1.0,2.0,3,725.0,345,"When I can, rarely though play pool, darts, an...",5,1,760,130

In [ ]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [11]:
# Fix that in-place.
df_food['GPA'] = pd.to_numeric(df_food['GPA'], errors='coerce')
df_food = df_food.dropna()
df_food

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.300,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
4,3.500,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
6,3.800,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.0,1.0,5,940.0,690,soccer,4,1,1315,180
7,3.300,1,1,720,3.0,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,...,1.0,2.0,1,725.0,500,none,4,2,1315,137
9,3.300,1,1,430,3.0,315.0,2,"Mac and cheese, chocolate, and pasta","Stress, anger and sadness",1.0,...,1.0,1.0,4,580.0,345,field hockey,5,1,900,125
10,3.500,1,1,610,3.0,980.0,2,"Pasta, grandma homemade chocolate cake anythin...",Boredom,2.0,...,1.0,1.0,2,940.0,345,soccer,5,2,900,116
11,3.904,1,1,720,4.0,420.0,2,"chocolate, pasta, soup, chips, popcorn","sadness, stress, cold weather",3.0,...,1.0,1.0,5,940.0,500,Running,5,1,900,110
12,3.400,2,1,430,3.0,420.0,2,"Cookies, popcorn, and chips","Sadness, boredom, late night snack",3.0,...,2.0,1.0,3,940.0,500,Soccer and basketball,3,2,575,264
13,3.600,1,1,610,3.0,420.0,2,"ice cream, cake, chocolate","stress, boredom, special occasions",1.0,...,1.0,1.0,5,1165.0,850,intramural volleyball,5,2,1315,123
14,3.100,2,1,610,3.0,420.0,2,"Pizza, fruit, spaghetti, chicken and Potatoes","Friends, environment and boredom",2.0,...,1.0,1.0,4,940.0,500,Hockey,5,1,900,185
17,3.600,2,1,430,3.0,980.0,2,"chips, cookies, ice cream",I usually only eat comfort food when I'm bored...,2.0,...,1.0,1.0,3,940.0,500,hockey,4,2,900,170
18,3.400,1,1,720,3.0,980.0,1,"Chocolate, ice crea","Sadness, stress",3.0,...,2.0,2.0,1,1165.0,690,dancing,5,1,1315,135
20,3.300,2,1,610,3.0,980.0,2,"Fast food, pizza, subs","happiness, satisfaction",7.0,...,1.0,1.0,1,1165.0,850,Soccer,3,2,1315,175
22,3.700,2,1,610,3.0,420.0,1,"burgers, chips, cookies","sadness, depression",3.0,...,1.0,1.0,4,940.0,850,tennis soccer gym,3,1,1315,185
23,3.700,2,2,610,3.0,420.0,2,"Chilli, soup, pot pie",Stress and boredom,1.0,...,1.0,1.0,4,940.0,690,Gaelic Football,4,1,1315,185
25,2.800,1,2,720,3.0,420.0,2,"chocolate, ice cream/milkshake, cookies",boredom,2.0,...,1.0,1.0,3,1165.0,690,Ice hockey,3,2,760,125
26,3.700,2,1,610,2.0,420.0,1,"Chips, ice cream, microwaveable foods","Boredom, lazyniss",2.0,...,2.0,1.0,2,1165.0,850,Hockey,3,2,1315,160
27,3.000,2,1,610,4.0,980.0,2,"Chicken fingers, pizza",Boredom,2.0,...,1.0,1.0,3,1165.0,500,Lacrosse,5,1,1315,175
31,4.000,2,1,610,3.0,420.0,2,"chips and dip, pepsi,","stres, boredom, and nighttime",1.0,...,2.0,2.0,4,940.0,690,none organized,5,1,1315,205
34,3.650,1,1,610,3.0,420.0,2,"french fries, chips, ice cream","boredom, stressed, sad",2.0,...,1.0,1.0,3,940.0,345,softball,4,1,1315,150
35,3.000,1,1,610,2.0,420.0,2,"mac n cheese, peanut butter and banana sandwic...",Boredom usually,2.0,...,1.0,1.0,2,940.0,690,Lacrosse,5,2,760,150
37,3.400,1,1,720,4.0,420.0,2,"chocolate, chips, candy",Stress,1.0,...,1.0,1.0,5,940.0,500,Dancing,4,2,1315,170
38,3.890,1,1,610,3.0,980.0,2,"chocolate, popcorn, ice cream","boredom, stress",2.0,...,1.0,1.0,2,1165.0,690,Lacrosse,3,2,1315,150
40,3.400,2,1,430,3.0,315.0,1,"Pizza, Ice cream, fries, cereal, cookies",Usually if I'm sad or depressed.,3.0,...,1.0,1.0,3,940.0,500,wrestling,4,2,760,140
44,3.200,1,1,610,4.0,420.0,2,"Potato chips, ice cream, chocolate, cookies","Stress, boredom, craving",1.0,...,1.0,1.0,5,725.0,500,Volleyball,5,1,760,170
46,3.800,2,1,430,2.0,420.0,1,"popcorn, chips, candy, & fries","sadness, boredom, & anger",3.0,...,1.0,1.0,3,725.0,345,soccer,4,2,900,168
51,3.300,2,1,610,4.0,980.0,1,Burger,Lazy,5.0,...,1.0,1.0,5,1165.0,500,Hockey,4,1,1315,185
54,3.500,2,1,610,3.0,420.0,2,"peanut butter sandwich, pretzals, garlic bread","stress, anger and boredom",1.0,...,1.0,1.0,4,940.0,690,hockey,5,1,900,165
56,3.800,2,1,720,4.0,315.0,2,"Pizza, Ice Cream, Chicken Wings",I usually only eat comfort foods when I am bor...,2.0,...,1.0,1.0,5,1165.0,500,Hockey,5,1,1315,175
57,2.800,1,1,610,4.0,980.0,2,Pizza chocolate chips bagels ice Capps,Just cause,9.0,...,2.0,1.0,2,725.0,345,softball,4,1,1315,140
58,3.500,1,1,610,3.0,420.0,2,"Chocolate, ice cream, pasta","Stress, boredom, sadness",1.0,...,1.0,1.0,5,1165.0,690,Skiing,5,1,1315,155
60,3.600,1,1,610,4.0,420.0,2,"peanut butter, dessets, pretzels.","Sadness, boredom, lonely.",3.0,...,1.0,1.0,1,1165.0,690,Water polo and running,5,1,1315,135
62,3.900,2,1,610,4.0,980.0,2,"ice cream, cookies, ice cream","boredom, sadness",2.0,...,1.0,1.0,2,1165.0,850,Ice Hockey,4,1,1315,210
64,3.500,1,1,610,3.0,420.0,1,"cookies, nutella, ice cream, coffee, fruit","Bordem, happiness, sadness",2.0,...,2.0,1.0,3,940.0,500,Volleyball,5,1,760,140
67,3.600,1,1,610,2.0,420.0,1,"Ice cream, cake, mozzarella sticks, pierogies",Boredom,2.0,...,1.0,1.0,2,940.0,690,"Recreational Basketball, Equestrian Team",5,2,1315,144 lbs
68,3.200,1,1,430,3.0,315.0,1,"Chips, Mac and cheese, pizza, French fries","Stress, sadness, bored",1.0,...,1.0,1.0,4,725.0,500,soccer,5,2,760,145
70,3.730,1,1,610,3.0,980.0,2,"Broccoli, spaghetti squash, quinoa, and grille...","Bad day, bored, sadness",2.0,...,1.0,1.0,5,1165.0,500,Rec Volleyball,5,1,1315,140
75,3.000,1,1,610,3.0,420.0,2,"mac and cheese, potato soup, ice cream, chips ...","sadness, stressed, boredom",3.0,...,1.0,2.0,4,940.0,500,I danced in high school,4,1,900,120
76,3.700,1,2,610,3.0,420.0,1,"chocolate, pizza, and mashed potatoes",boredom and stress,2.0,...,2.0,1.0,1,1165.0,690,horse back riding,2,2,1315,150
77,3.100,2,2,265,2.0,420.0,1,Pizza cookies steak,Boredom comfort hunger,2.0,...,2.0,1.0,2,725.0,345,Basketball,2,2,900,200
78,3.000,1,1,720,3.0,420.0,2,"chocolate, fruit, and ice cream","stress, boredom",1.0,...,1.0,1.0,3,580.0,345,competitive skiing,4,1,1315,135
79,3.900,2,1,720,3.0,420.0,2,Chips sweets popcorn,Boredom,2.0,...,1.0,1.0,5,1165.0,850,"Rowing, Running, and Cycling",4,2,1315,145
81,3.500,1,2,610,3.0,420.0,1,"cake, French fries, chicken nuggets","boredom, sadness",2.0,...,2.0,1.0,4,725.0,500,softball and basketball,2,2,900,190
84,3.830,1,1,720,3.0,420.0,2,"Pasta dishes, Cheesecake, Pancakes","Sadness, Loneliness, Boredom",3.0,...,1.0,1.0,5,725.0,690,Collegiate Water Polo,5,1,760,167
85,2.600,1,1,265,3.0,315.0,2,"Ice cream, pizza, cookies",Mostly Stress,1.0,...,1.0,2.0,3,580.0,500,None right now,4,1,760,140
86,3.000,1,1,610,3.0,420.0,2,"Chinese food, moes, sponge candy, homemade las...","boredom, sadness",2.0,...,1.0,1.0,4,580.0,500,"volleyball, lacrosse",4,1,900,190
87,3.200,2,1,720,3.0,420.0,1,"pizza, pasta, mac and cheese",when i am sad or craving,3.0,...,1.0,1.0,1,1165.0,690,field hockey,4,1,1315,155
91,3.800,1,2,610,2.0,420.0,2,"Macaroni and cheese, chicken noodle soup, pizza",Boredom and stress,2.0,...,1.0,2.0,1,725.0,500,crew,1,2,900,135
96,3.920,2,1,430,3.0,420.0,2,"Ice cream, cake, pop, pizza, and milkshakes.","Happiness, sadness, celebration.",7.0,...,1.0,2.0,3,725.0,500,Soccer,2,1,900,210
103,3.700,1,1,610,3.0,420.0,2,"dark chocolate, terra chips, reese's cups(dark...","Anxiousness, watching TV I desire ""comfort food""",8.0,...,1.0,2.0,3,725.0,345,"When I can, rarely though play pool, darts, an...",5,1,760,130

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [12]:
# Savey save!
df_food.to_csv(
    "../data/cleaned_data.csv", index=False
)

In [82]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.
df_cleaned = pd.read_csv('../data/cleaned_data.csv')
df_cleaned

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
1,3.300,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
2,3.500,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
3,3.800,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.0,1.0,5,940.0,690,soccer,4,1,1315,180
4,3.300,1,1,720,3.0,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,...,1.0,2.0,1,725.0,500,none,4,2,1315,137
5,3.300,1,1,430,3.0,315.0,2,"Mac and cheese, chocolate, and pasta","Stress, anger and sadness",1.0,...,1.0,1.0,4,580.0,345,field hockey,5,1,900,125
6,3.500,1,1,610,3.0,980.0,2,"Pasta, grandma homemade chocolate cake anythin...",Boredom,2.0,...,1.0,1.0,2,940.0,345,soccer,5,2,900,116
7,3.904,1,1,720,4.0,420.0,2,"chocolate, pasta, soup, chips, popcorn","sadness, stress, cold weather",3.0,...,1.0,1.0,5,940.0,500,Running,5,1,900,110
8,3.400,2,1,430,3.0,420.0,2,"Cookies, popcorn, and chips","Sadness, boredom, late night snack",3.0,...,2.0,1.0,3,940.0,500,Soccer and basketball,3,2,575,264
9,3.600,1,1,610,3.0,420.0,2,"ice cream, cake, chocolate","stress, boredom, special occasions",1.0,...,1.0,1.0,5,1165.0,850,intramural volleyball,5,2,1315,123
10,3.100,2,1,610,3.0,420.0,2,"Pizza, fruit, spaghetti, chicken and Potatoes","Friends, environment and boredom",2.0,...,1.0,1.0,4,940.0,500,Hockey,5,1,900,185
11,3.600,2,1,430,3.0,980.0,2,"chips, cookies, ice cream",I usually only eat comfort food when I'm bored...,2.0,...,1.0,1.0,3,940.0,500,hockey,4,2,900,170
12,3.400,1,1,720,3.0,980.0,1,"Chocolate, ice crea","Sadness, stress",3.0,...,2.0,2.0,1,1165.0,690,dancing,5,1,1315,135
13,3.300,2,1,610,3.0,980.0,2,"Fast food, pizza, subs","happiness, satisfaction",7.0,...,1.0,1.0,1,1165.0,850,Soccer,3,2,1315,175
14,3.700,2,1,610,3.0,420.0,1,"burgers, chips, cookies","sadness, depression",3.0,...,1.0,1.0,4,940.0,850,tennis soccer gym,3,1,1315,185
15,3.700,2,2,610,3.0,420.0,2,"Chilli, soup, pot pie",Stress and boredom,1.0,...,1.0,1.0,4,940.0,690,Gaelic Football,4,1,1315,185
16,2.800,1,2,720,3.0,420.0,2,"chocolate, ice cream/milkshake, cookies",boredom,2.0,...,1.0,1.0,3,1165.0,690,Ice hockey,3,2,760,125
17,3.700,2,1,610,2.0,420.0,1,"Chips, ice cream, microwaveable foods","Boredom, lazyniss",2.0,...,2.0,1.0,2,1165.0,850,Hockey,3,2,1315,160
18,3.000,2,1,610,4.0,980.0,2,"Chicken fingers, pizza",Boredom,2.0,...,1.0,1.0,3,1165.0,500,Lacrosse,5,1,1315,175
19,4.000,2,1,610,3.0,420.0,2,"chips and dip, pepsi,","stres, boredom, and nighttime",1.0,...,2.0,2.0,4,940.0,690,none organized,5,1,1315,205
20,3.650,1,1,610,3.0,420.0,2,"french fries, chips, ice cream","boredom, stressed, sad",2.0,...,1.0,1.0,3,940.0,345,softball,4,1,1315,150
21,3.000,1,1,610,2.0,420.0,2,"mac n cheese, peanut butter and banana sandwic...",Boredom usually,2.0,...,1.0,1.0,2,940.0,690,Lacrosse,5,2,760,150
22,3.400,1,1,720,4.0,420.0,2,"chocolate, chips, candy",Stress,1.0,...,1.0,1.0,5,940.0,500,Dancing,4,2,1315,170
23,3.890,1,1,610,3.0,980.0,2,"chocolate, popcorn, ice cream","boredom, stress",2.0,...,1.0,1.0,2,1165.0,690,Lacrosse,3,2,1315,150
24,3.400,2,1,430,3.0,315.0,1,"Pizza, Ice cream, fries, cereal, cookies",Usually if I'm sad or depressed.,3.0,...,1.0,1.0,3,940.0,500,wrestling,4,2,760,140
25,3.200,1,1,610,4.0,420.0,2,"Potato chips, ice cream, chocolate, cookies","Stress, boredom, craving",1.0,...,1.0,1.0,5,725.0,500,Volleyball,5,1,760,170
26,3.800,2,1,430,2.0,420.0,1,"popcorn, chips, candy, & fries","sadness, boredom, & anger",3.0,...,1.0,1.0,3,725.0,345,soccer,4,2,900,168
27,3.300,2,1,610,4.0,980.0,1,Burger,Lazy,5.0,...,1.0,1.0,5,1165.0,500,Hockey,4,1,1315,185
28,3.500,2,1,610,3.0,420.0,2,"peanut butter sandwich, pretzals, garlic bread","stress, anger and boredom",1.0,...,1.0,1.0,4,940.0,690,hockey,5,1,900,165
29,3.800,2,1,720,4.0,315.0,2,"Pizza, Ice Cream, Chicken Wings",I usually only eat comfort foods when I am bor...,2.0,...,1.0,1.0,5,1165.0,500,Hockey,5,1,1315,175
30,2.800,1,1,610,4.0,980.0,2,Pizza chocolate chips bagels ice Capps,Just cause,9.0,...,2.0,1.0,2,725.0,345,softball,4,1,1315,140
31,3.500,1,1,610,3.0,420.0,2,"Chocolate, ice cream, pasta","Stress, boredom, sadness",1.0,...,1.0,1.0,5,1165.0,690,Skiing,5,1,1315,155
32,3.600,1,1,610,4.0,420.0,2,"peanut butter, dessets, pretzels.","Sadness, boredom, lonely.",3.0,...,1.0,1.0,1,1165.0,690,Water polo and running,5,1,1315,135
33,3.900,2,1,610,4.0,980.0,2,"ice cream, cookies, ice cream","boredom, sadness",2.0,...,1.0,1.0,2,1165.0,850,Ice Hockey,4,1,1315,210
34,3.500,1,1,610,3.0,420.0,1,"cookies, nutella, ice cream, coffee, fruit","Bordem, happiness, sadness",2.0,...,2.0,1.0,3,940.0,500,Volleyball,5,1,760,140
35,3.600,1,1,610,2.0,420.0,1,"Ice cream, cake, mozzarella sticks, pierogies",Boredom,2.0,...,1.0,1.0,2,940.0,690,"Recreational Basketball, Equestrian Team",5,2,1315,144 lbs
36,3.200,1,1,430,3.0,315.0,1,"Chips, Mac and cheese, pizza, French fries","Stress, sadness, bored",1.0,...,1.0,1.0,4,725.0,500,soccer,5,2,760,145
37,3.730,1,1,610,3.0,980.0,2,"Broccoli, spaghetti squash, quinoa, and grille...","Bad day, bored, sadness",2.0,...,1.0,1.0,5,1165.0,500,Rec Volleyball,5,1,1315,140
38,3.000,1,1,610,3.0,420.0,2,"mac and cheese, potato soup, ice cream, chips ...","sadness, stressed, boredom",3.0,...,1.0,2.0,4,940.0,500,I danced in high school,4,1,900,120
39,3.700,1,2,610,3.0,420.0,1,"chocolate, pizza, and mashed potatoes",boredom and stress,2.0,...,2.0,1.0,1,1165.0,690,horse back riding,2,2,1315,150
40,3.100,2,2,265,2.0,420.0,1,Pizza cookies steak,Boredom comfort hunger,2.0,...,2.0,1.0,2,725.0,345,Basketball,2,2,900,200
41,3.000,1,1,720,3.0,420.0,2,"chocolate, fruit, and ice cream","stress, boredom",1.0,...,1.0,1.0,3,580.0,345,competitive skiing,4,1,1315,135
42,3.900,2,1,720,3.0,420.0,2,Chips sweets popcorn,Boredom,2.0,...,1.0,1.0,5,1165.0,850,"Rowing, Running, and Cycling",4,2,1315,145
43,3.500,1,2,610,3.0,420.0,1,"cake, French fries, chicken nuggets","boredom, sadness",2.0,...,2.0,1.0,4,725.0,500,softball and basketball,2,2,900,190
44,3.830,1,1,720,3.0,420.0,2,"Pasta dishes, Cheesecake, Pancakes","Sadness, Loneliness, Boredom",3.0,...,1.0,1.0,5,725.0,690,Collegiate Water Polo,5,1,760,167
45,2.600,1,1,265,3.0,315.0,2,"Ice cream, pizza, cookies",Mostly Stress,1.0,...,1.0,2.0,3,580.0,500,None right now,4,1,760,140
46,3.000,1,1,610,3.0,420.0,2,"Chinese food, moes, sponge candy, homemade las...","boredom, sadness",2.0,...,1.0,1.0,4,580.0,500,"volleyball, lacrosse",4,1,900,190
47,3.200,2,1,720,3.0,420.0,1,"pizza, pasta, mac and cheese",when i am sad or craving,3.0,...,1.0,1.0,1,1165.0,690,field hockey,4,1,1315,155
48,3.800,1,2,610,2.0,420.0,2,"Macaroni and cheese, chicken noodle soup, pizza",Boredom and stress,2.0,...,1.0,2.0,1,725.0,500,crew,1,2,900,135
49,3.920,2,1,430,3.0,420.0,2,"Ice cream, cake, pop, pizza, and milkshakes.","Happiness, sadness, celebration.",7.0,...,1.0,2.0,3,725.0,500,Soccer,2,1,900,210
50,3.700,1,1,610,3.0,420.0,2,"dark chocolate, terra chips, reese's cups(dark...","Anxiousness, watching TV I desire ""comfort food""",8.0,...,1.0,2.0,3,725.0,345,"When I can, rarely though play pool, darts, an...",5,1,760,130

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [13]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.
df_salary = pd.read_csv(
    '../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv',
    sep='\t'
    )

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [14]:
# Count by hand. I’m dead serious.
print(f"Number of rows = {df_salary.shape[0]}")

Number of rows = 28062

What are the columns and their types?

In [15]:
# Show the column names and their types.
# df_salary.shape
df_salary.dtypes.to_frame(name="Data Type")

                                                   Data Type
Timestamp                                                str
How old are you?                                         str
What industry do you work in?                            str
Job title                                                str
If your job title needs additional context, ple...       str
What is your annual salary? (You'll indicate th...       str
How much additional monetary compensation do yo...   float64
Please indicate the currency                             str
If "Other," please indicate the currency here:           str
If your income needs additional context, please...       str
What country do you work in?                             str
If you're in the U.S., what state do you work in?        str
What city do you work in?                                str
How many years of professional work experience ...       str
How many years of professional work experience ...       str
What is your highest level of education completed?       str
What is your gender?                                     str
What is your race? (Choose all that apply.)              str

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [35]:

df_salary.columns = df_salary.columns.str.strip()

df_salary.rename(
    columns={
        "How old are you?": "age",
        "What industry do you work in?": "industry",
        "Job title": "title",
        "If your job title needs additional context, please clarify here:": "title_context",
        "What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)": "salary",
        "How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.": "additional_compensation",
        "Please indicate the currency": "currency",
        'If "Other," please indicate the currency here:': "other_currency",
        "If your income needs additional context, please provide it here:": "salary_context",
        "What country do you work in?": "country",
        "If you're in the U.S., what state do you work in?": "state",
        "What city do you work in?": "city",
        "How many years of professional work experience do you have overall?": "total_yoe",
        "How many years of professional work experience do you have in your field?": "field_yoe",
        "What is your highest level of education completed?": "highest_education_completed",
        "What is your gender?": "gender",
        "What is your race? (Choose all that apply.)": "race",
    },
    inplace=True,
)
df_salary.head(10)

,Timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
5,4/27/2021 11:02:46,25-34,Education (Higher Education),Scholarly Publishing Librarian,NaN,"62,000",NaN,USD,NaN,NaN,USA,New Hampshire,Hanover,8 - 10 years,2 - 4 years,Master's degree,Man,White
6,4/27/2021 11:02:51,25-34,Publishing,Publishing Assistant,NaN,"33,000",2000.0,USD,NaN,NaN,USA,South Carolina,Columbia,2 - 4 years,2 - 4 years,College degree,Woman,White
7,4/27/2021 11:03:00,25-34,Education (Primary/Secondary),Librarian,"High school, FT","50,000",NaN,USD,NaN,NaN,United States,Arizona,Yuma,5-7 years,5-7 years,Master's degree,Man,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
9,4/27/2021 11:03:02,35-44,"Accounting, Banking & Finance",Senior Accountant,NaN,"45,000",0.0,USD,NaN,I work for a Charter School,United States,Florida,Palm Coast,21 - 30 years,21 - 30 years,College degree,Woman,"Hispanic, Latino, or Spanish origin, White"

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [36]:
# List the unique industries and a count of their instances.
df_salary['industry'].value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [37]:
# Filtery filter.
top_inds = df_salary['industry'].value_counts().head(5).index
# df_salary_tech = df_salary['industry'].value_counts().head(5)
df_salary_tech = df_salary[df_salary["industry"].isin(top_inds)]

df_salary_tech

,Timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
5,4/27/2021 11:02:46,25-34,Education (Higher Education),Scholarly Publishing Librarian,NaN,"62,000",NaN,USD,NaN,NaN,USA,New Hampshire,Hanover,8 - 10 years,2 - 4 years,Master's degree,Man,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28053,7/12/2024 18:23:10,18-24,Nonprofits,Adminstration Specialist,NaN,1641,NaN,CAD,NaN,NaN,Taiwan,NaN,Taipei,1 year or less,1 year or less,NaN,Man,Asian or Asian American
28057,7/12/2024 22:52:01,35-44,Health care,Veterinarian,NaN,135000,NaN,USD,NaN,NaN,United States,Missouri,Wentzville,11 - 20 years,11 - 20 years,"Professional degree (MD, JD, etc.)",Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American
28061,8/20/2024 1:06:13,25-34,Health care,Clinical physiologist,NaN,1200000,NaN,Other,NGN,NaN,Nigeria,NaN,Lagos,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American

Do a sanity check by counting.

In [38]:
# Sanity check count.

df_salary_tech.value_counts()

Timestamp           age    industry                      title                     title_context  salary  additional_compensation  currency  other_currency                                                                              salary_context                                                                  country  state       city     total_yoe     field_yoe      highest_education_completed  gender  race
4/27/2021 11:14:45  45-54  Education (Higher Education)  Sr Technical Support Rep  I              53,000  0.0                      USD       I work for an online state university, managing admissions data. Not direct tech support.   I have excellent health benefits, time off, sick leave, and union protections.  USA      New Jersey  Trenton  8 - 10 years  2 - 4 years    Master's degree              Woman   White                        1
2/6/2024 21:15:28   18-24  Computing or Tech             sdsd                      ds             4       22.0                     USD       1                                                                                           dd                                                                              ss       Arkansas    s        5-7 years     11 - 20 years  Some college                 Man     Black or African American    1
Name: count, dtype: int64

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [39]:
# Filtery filter (in place) for just the jobs that pay in USD!
df_salary_tech = df_salary_tech[df_salary_tech['currency'] == 'USD']
# jobs that pay in usd
df_salary_tech

,Timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
5,4/27/2021 11:02:46,25-34,Education (Higher Education),Scholarly Publishing Librarian,NaN,"62,000",NaN,USD,NaN,NaN,USA,New Hampshire,Hanover,8 - 10 years,2 - 4 years,Master's degree,Man,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
10,4/27/2021 11:03:03,25-34,Nonprofits,Office Manager,NaN,"47,500",0.0,USD,NaN,NaN,United States,NaN,"Boston, MA",5-7 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28051,7/1/2024 20:05:58,25-34,Computing or Tech,Junior data analyst,NaN,35000,15000.0,USD,NaN,NaN,Usa,Alabama,Alabama,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American
28052,7/3/2024 14:02:01,25-34,Computing or Tech,Senior Global Public Relations Manager,NaN,144000,15000.0,USD,NaN,NaN,Usa,Massachusetts,Boise-but remote. Company located in Boston,8 - 10 years,8 - 10 years,Master's degree,Woman,White
28057,7/12/2024 22:52:01,35-44,Health care,Veterinarian,NaN,135000,NaN,USD,NaN,NaN,United States,Missouri,Wentzville,11 - 20 years,11 - 20 years,"Professional degree (MD, JD, etc.)",Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [41]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary_tech['country'].value_counts()

country
United States               1576
USA                         1222
US                           412
U.S.                         108
United States of America      90
                            ...
Ghana                          1
Nigeria                        1
ss                             1
Nigeria                        1
Burma                          1
Name: count, Length: 76, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [49]:
# Replace them all in-place with 'US'.
top_5_countries = df_salary_tech["country"].value_counts().head(5).index

df_salary_tech["country"] = df_salary_tech["country"].replace(
    top_5_countries, "US"
)
df_salary_tech

,Timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,US,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",US,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,US,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,US,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28044,6/3/2024 16:15:43,18-24,Computing or Tech,Research Data Analyst Associate,NaN,60000,0.0,USD,NaN,NaN,US,Illinois,Evanston,2 - 4 years,1 year or less,College degree,Woman,White
28051,7/1/2024 20:05:58,25-34,Computing or Tech,Junior data analyst,NaN,35000,15000.0,USD,NaN,NaN,US,Alabama,Alabama,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American
28052,7/3/2024 14:02:01,25-34,Computing or Tech,Senior Global Public Relations Manager,NaN,144000,15000.0,USD,NaN,NaN,US,Massachusetts,Boise-but remote. Company located in Boston,8 - 10 years,8 - 10 years,Master's degree,Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,US,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American

Have a look at the count of each unique country again now.

In [63]:
# Count again.

df_salary_tech['country'].value_counts()

country
US               3619
United states      23
united states      14
Us                 12
us                  9
                 ...
Ghana               1
Nigeria             1
ss                  1
Nigeria             1
Burma               1
Name: count, Length: 68, dtype: int64

Did you notice anything interesting?

In [69]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

type(df_salary_tech['salary'][0] )

KeyError: 0

In [ ]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [ ]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.

salary_stats = df_salary_tech['salary'].agg(['min', 'mean', 'max'])
salary_stats.to_frame()
salary_stats.apply(lambda x: f"${x:,.2f}")

min             $0.00
mean      $130,569.70
max     $2,600,000.00
Name: salary, dtype: str

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [62]:
# Fix it in-place.

Let’s try that again.

In [ ]:
# Try it again. Yeah!

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [ ]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)