# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [ ]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

In [1]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [2]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [3]:
# Count by hand. (lol kidding)

df_food.shape

(125, 61)

In [4]:
# Try to print or display it nicely.
print(f"Rows: {df_food.shape[0]}, Columns: {df_food.shape[1]}")

Rows: 125, Columns: 61

What are the columns and their types in this data set?

In [5]:
# Show the column names and their types.
print(df_food.dtypes)

GPA                     str
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports             str
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight                  str
Length: 61, dtype: object

In [6]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
pd.DataFrame(df_food.dtypes, columns=["type"])

                                 type
GPA                               str
Gender                          int64
breakfast                       int64
calories_chicken                int64
calories_day                  float64
calories_scone                float64
coffee                          int64
comfort_food                      str
comfort_food_reasons              str
comfort_food_reasons_coded    float64
cook                          float64
comfort_food_reasons_coded.1    int64
cuisine                       float64
diet_current                      str
diet_current_coded              int64
drink                         float64
eating_changes                    str
eating_changes_coded            int64
eating_changes_coded1           int64
eating_out                      int64
employment                    float64
ethnic_food                     int64
exercise                      float64
father_education              float64
father_profession                 str
fav_cuisine                       str
fav_cuisine_coded               int64
fav_food                      float64
food_childhood                    str
fries                           int64
fruit_day                       int64
grade_level                     int64
greek_food                      int64
healthy_feeling                 int64
healthy_meal                      str
ideal_diet                        str
ideal_diet_coded                int64
income                        float64
indian_food                     int64
italian_food                    int64
life_rewarding                float64
marital_status                float64
meals_dinner_friend               str
mother_education              float64
mother_profession                 str
nutritional_check               int64
on_off_campus                 float64
parents_cook                    int64
pay_meal_out                    int64
persian_food                  float64
self_perception_weight        float64
soup                          float64
sports                        float64
thai_food                       int64
tortilla_calories             float64
turkey_calories                 int64
type_sports                       str
veggies_day                     int64
vitamins                        int64
waffle_calories                 int64
weight                            str

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [7]:
# Remove ‘em.
df_food_col_subset = df_food[["calories_day","weight","Gender"]].copy()
df_food_col_subset

     calories_day                    weight  Gender
0             NaN                       187       2
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
..            ...                       ...     ...
120           4.0                       156       1
121           2.0                       180       1
122           NaN                       120       1
123           4.0                       135       2
124           NaN                       135       1

[125 rows x 3 columns]

In [8]:
# Is there a second way to remove columns?

df_food_subset = df_food.filter(["calories_day","weight","Gender"]).copy()
df_food_subset

     calories_day                    weight  Gender
0             NaN                       187       2
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
..            ...                       ...     ...
120           4.0                       156       1
121           2.0                       180       1
122           NaN                       120       1
123           4.0                       135       2
124           NaN                       135       1

[125 rows x 3 columns]

In [9]:
# 🚀 Extra credit: What about a third way to remove columns?
df_food_col_subset2 = df_food.loc[:, ["calories_day","weight","Gender"]].copy()
df_food_col_subset2

     calories_day                    weight  Gender
0             NaN                       187       2
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
..            ...                       ...     ...
120           4.0                       156       1
121           2.0                       180       1
122           NaN                       120       1
123           4.0                       135       2
124           NaN                       135       1

[125 rows x 3 columns]

What about `NaN`s? How many are there?

In [10]:
# Count ‘em.
df_food_col_subset.isna().sum()

calories_day    19
weight           2
Gender           0
dtype: int64

In [19]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.

In [ ]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

We gotta remove those `NaN`s―the entire row.

In [11]:
# Drop ‘em in-place.
df_food_col_subset.dropna(inplace=True)
df_food_col_subset

     calories_day                    weight  Gender
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
5             3.0                       190       1
..            ...                       ...     ...
118           3.0                       140       1
119           3.0                       185       2
120           4.0                       156       1
121           2.0                       180       1
123           4.0                       135       2

[104 rows x 3 columns]

In [12]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂

df_food[["calories_day","weight","Gender"]]

     calories_day                    weight  Gender
0             NaN                       187       2
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
..            ...                       ...     ...
120           4.0                       156       1
121           2.0                       180       1
122           NaN                       120       1
123           4.0                       135       2
124           NaN                       135       1

[125 rows x 3 columns]

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [13]:
# Fix that in-place.
df_food_col_subset = df_food_col_subset.apply(pd.to_numeric, errors="coerce")
df_food_col_subset.dropna(inplace=True)
df_food_col_subset

     calories_day  weight  Gender
1             3.0   155.0       1
4             2.0   190.0       1
5             3.0   190.0       1
6             3.0   180.0       2
7             3.0   137.0       1
..            ...     ...     ...
118           3.0   140.0       1
119           3.0   185.0       2
120           4.0   156.0       1
121           2.0   180.0       1
123           4.0   135.0       2

[101 rows x 3 columns]

In [14]:
# checking dtypes
df_food_col_subset.dtypes

calories_day    float64
weight          float64
Gender            int64
dtype: object

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [15]:
# Savey save!
df_food_col_subset.to_csv("../data/food_coded_cleaned.csv",index=False)

In [16]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.

with open("../data/food_coded_cleaned.csv") as f:
    for _ in range(5):
        print(f.readline(), end="")

calories_day,weight,Gender
3.0,155.0,1
2.0,190.0,1
3.0,190.0,1
3.0,180.0,2

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [17]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.
df_salary = pd.read_csv("../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv", sep="\t")
df_salary

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28057,7/12/2024 22:52:01,35-44,Health care,Veterinarian,NaN,135000,NaN,USD,NaN,NaN,United States,Missouri,Wentzville,11 - 20 years,11 - 20 years,"Professional degree (MD, JD, etc.)",Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28059,7/24/2024 12:22:58,18-24,"Accounting, Banking & Finance",Risk Management Associate,NaN,1200,0.0,USD,NaN,NaN,Myanmar,Colorado,Yangon,2 - 4 years,2 - 4 years,Some college,Man,Asian or Asian American
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American
28061,8/20/2024 1:06:13,25-34,Health care,Clinical physiologist,NaN,1200000,NaN,Other,NGN,NaN,Nigeria,NaN,Lagos,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [18]:
# Count by hand. I’m dead serious.
print(f"Rows: {df_salary.shape[0]}, Columns: {df_salary.shape[1]}")

Rows: 28062, Columns: 18

What are the columns and their types?

In [19]:
# Show the column names and their types.
df_salary.dtypes.to_frame().reset_index().rename(columns={'index':"Column",0:"type"})

                                               Column     type
0                                           Timestamp      str
1                                    How old are you?      str
2                       What industry do you work in?      str
3                                           Job title      str
4   If your job title needs additional context, pl...      str
5   What is your annual salary? (You'll indicate t...      str
6   How much additional monetary compensation do y...  float64
7                        Please indicate the currency      str
8     If "Other," please indicate the currency here:       str
9   If your income needs additional context, pleas...      str
10                       What country do you work in?      str
11  If you're in the U.S., what state do you work in?      str
12                          What city do you work in?      str
13  How many years of professional work experience...      str
14  How many years of professional work experience...      str
15  What is your highest level of education comple...      str
16                               What is your gender?      str
17        What is your race? (Choose all that apply.)      str

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [20]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race
column_names = ["timestamp", "age", "industry", "title", "title_context", "salary", 
                "additional_compensation", "currency", "other_currency", "salary_context", "country", 
                "state", "city", "total_yoe", "field_yoe", 
                "highest_education_completed", "gender", "race"]

df_salary.columns = column_names
df_salary.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [21]:
# List the unique industries and a count of their instances.
df_salary["industry"].value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [22]:
# Filtery filter.
df_salary_tech = df_salary[df_salary["industry"] == "Computing or Tech"].reset_index(drop=True).copy()
df_salary_tech.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
1,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
2,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
3,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
4,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White

Do a sanity check by counting.

In [23]:
# Sanity check count.
df_salary_tech.shape

(4699, 18)

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [24]:
# Filtery filter (in place) for just the jobs that pay in USD!
df_salary_tech = df_salary_tech[df_salary_tech.currency == "USD"].reset_index(drop = True)
df_salary_tech

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
1,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
2,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
3,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
4,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,USA,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3772,6/3/2024 16:15:43,18-24,Computing or Tech,Research Data Analyst Associate,NaN,60000,0.0,USD,NaN,NaN,United States,Illinois,Evanston,2 - 4 years,1 year or less,College degree,Woman,White
3773,7/1/2024 20:05:58,25-34,Computing or Tech,Junior data analyst,NaN,35000,15000.0,USD,NaN,NaN,Usa,Alabama,Alabama,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American
3774,7/3/2024 14:02:01,25-34,Computing or Tech,Senior Global Public Relations Manager,NaN,144000,15000.0,USD,NaN,NaN,Usa,Massachusetts,Boise-but remote. Company located in Boston,8 - 10 years,8 - 10 years,Master's degree,Woman,White
3775,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
3776,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [25]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary_tech.country.value_counts()

country
United States                1576
USA                          1222
US                            412
U.S.                          108
United States of America       90
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [26]:
# Replace them all in-place with 'US'.
df_salary_tech.loc[df_salary_tech.country
                   .isin(df_salary_tech.country.value_counts().head(5).index.to_list()), 
                   "country"] = "US"

Have a look at the count of each unique country again now.

In [27]:
# Count again.
df_salary_tech.country.value_counts()

country
US                           3408
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

Did you notice anything interesting?

In [28]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.
df_salary_tech.loc[df_salary_tech.country.isin(df_salary_tech.country.value_counts().head(11).index), "country"] = "US"
df_salary_tech["country"].value_counts()

country
US                          3691
Israel                         5
Canada                         4
U.S.                           2
United State of America        2
Unite States                   2
Australia                      2
UnitedStates                   2
India                          2
U.S                            2
Usa                            2
United States Of America       2
Spain                          2
Brazil                         2
United Kingdom                 2
united States                  2
New Zealand                    2
Poland                         2
France                         2
U.S.A                          2
United States of america       2
US                             1
Uniyed states                  1
America                        1
Puerto Rico                    1
U.s.                           1
 US                            1
United State                   1
Cuba                           1
Danmark                        1
Italy                          1
International                  1
United Stated                  1
Remote (philippines)           1
Singapore                      1
Uruguay                        1
Mexico                         1
Canada                         1
United Stateds                 1
ISA                            1
singapore                      1
Pakistan                       1
Netherlands                    1
China                          1
San Francisco                  1
Romania                        1
United STates                  1
Japan                          1
United Stares                  1
Australian                     1
Denmark                        1
Jamaica                        1
Unites States                  1
Thailand                       1
U.S.A                          1
Colombia                       1
denmark                        1
Ghana                          1
Nigeria                        1
ss                             1
Nigeria                        1
Burma                          1
Name: count, dtype: int64

In [ ]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [29]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
df_salary_tech[df_salary_tech['country'] == "US"].groupby('state')['salary']\
    .agg(["min", "mean", "max"]).sort_values(by = "mean", ascending = False)

TypeError: dtype 'str' does not support operation 'mean'

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [30]:
# Fix it in-place.
df_salary_tech.salary = pd.to_numeric(
    df_salary_tech.salary.astype(str).str.replace('$','',regex=False)
    .str.replace(',','').str.strip()
    , errors="coerce")

Let’s try that again.

In [31]:
# Try it again. Yeah!
df_salary_tech[df_salary_tech['country'] == "US"].groupby('state')['salary']\
    .agg(["min", "mean", "max"]).sort_values(by = "mean", ascending = False)

                                   min           mean      max
state
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Florida                          28800  158501.909091  2600000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  155224.893130   875000
Washington                          72  151525.934328   950000
New York                         14000  148224.909884   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  134969.109635  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127370.512821   450000
Colorado                         45000  127293.993007   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  123790.238994   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119268.242604   315000
Maryland                         51260  118916.377358   205000
Georgia                          29120  117893.098765   250000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Texas                            10700  113451.882353   280000
Tennessee                        36550  112847.058824   240000
Wisconsin                            1  112717.192771   920000
Alaska                           67000  112500.000000   158000
Pennsylvania                     32000  111851.901786   237000
Vermont                          65000  111781.250000   200000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
District of Columbia, Virginia  109200  109200.000000   109200
Ohio                             32240  106868.212121   954000
Minnesota                        34000  106752.793103   230000
Utah                             33280  105836.479167   245000
New York, Texas                 105000  105000.000000   105000
Massachusetts, New Hampshire    105000  105000.000000   105000
North Carolina                   29000  104972.127273   260000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
South Carolina                   40000  102111.111111   205000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   97723.055556   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
New Hampshire                       55   93003.437500   193000
Alabama                          29120   92510.000000   350000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Massachusetts, Pennsylvania      83000   83000.000000    83000
Arkansas                         55000   81682.300000   144000
California, Maryland             81500   81500.000000    81500
Louisiana                        35360   79884.444444   110000
Alabama, Montana                 72000   72000.000000    72000

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [32]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_salary_tech.timestamp = pd.to_datetime(df_salary_tech.timestamp)

df_salary_tech_select = df_salary_tech[df_salary_tech.timestamp.dt.year.isin([2021,2022,2023])].copy()

df_salary_tech_select[df_salary_tech_select.country == "US"].groupby("state")["salary"]\
    .agg(["min","mean","max"]).sort_values(by="mean", ascending=False)

                                   min           mean      max
state
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  155355.206422   875000
Washington                          72  151676.760479   950000
New York                         14000  148224.909884   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  134939.006667  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127370.512821   450000
Colorado                         45000  127293.993007   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  123790.238994   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119621.029762   315000
Maryland                         51260  118916.377358   205000
Georgia                          29120  118004.262500   250000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Texas                            10700  113451.882353   280000
Florida                          28800  113288.981481   400000
Tennessee                        36550  112847.058824   240000
Wisconsin                            1  112717.192771   920000
Alaska                           67000  112500.000000   158000
Pennsylvania                     32000  111851.901786   237000
Vermont                          65000  111781.250000   200000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
South Carolina                   40000  109875.000000   205000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  107063.872093   230000
Ohio                             32240  106868.212121   954000
Utah                             33280  105836.479167   245000
New York, Texas                 105000  105000.000000   105000
Massachusetts, New Hampshire    105000  105000.000000   105000
North Carolina                   29000  104880.128440   260000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Alabama                          29120   97738.181818   350000
Michigan                         36800   97723.055556   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
New Hampshire                       55   93003.437500   193000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Massachusetts, Pennsylvania      83000   83000.000000    83000
Arkansas                         55000   81682.300000   144000
California, Maryland             81500   81500.000000    81500
Louisiana                        35360   79884.444444   110000
Alabama, Montana                 72000   72000.000000    72000

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)