# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy in /usr/local/python/3.14.2/lib/python3.14/site-packages (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [9]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [10]:
# Count by hand. (lol kidding)
df_food.shape

(125, 61)

In [11]:
# Try to print or display it nicely.

df_food.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190

What are the columns and their types in this data set?

In [12]:
# Show the column names and their types.
df_food.info()

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    str
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    str
 8   comfort_food_reasons          123 non-null    str
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    str
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    str
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    str
 25  fav_cuisine                   123 non-null    str
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    str
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    str
 35  ideal_diet                    124 non-null    str
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    str
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    str
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     str
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    str
dtypes: float64(20), int64(27), str(14)
memory usage: 59.7 KB

In [13]:
pd.set_option("display.max_rows", 100)

df_info = pd.DataFrame({
    'Column Name': df_food.columns,
    'Data Type': df_food.dtypes.values
})

df_info

                     Column Name Data Type
0                            GPA       str
1                         Gender     int64
2                      breakfast     int64
3               calories_chicken     int64
4                   calories_day   float64
5                 calories_scone   float64
6                         coffee     int64
7                   comfort_food       str
8           comfort_food_reasons       str
9     comfort_food_reasons_coded   float64
10                          cook   float64
11  comfort_food_reasons_coded.1     int64
12                       cuisine   float64
13                  diet_current       str
14            diet_current_coded     int64
15                         drink   float64
16                eating_changes       str
17          eating_changes_coded     int64
18         eating_changes_coded1     int64
19                    eating_out     int64
20                    employment   float64
21                   ethnic_food     int64
22                      exercise   float64
23              father_education   float64
24             father_profession       str
25                   fav_cuisine       str
26             fav_cuisine_coded     int64
27                      fav_food   float64
28                food_childhood       str
29                         fries     int64
30                     fruit_day     int64
31                   grade_level     int64
32                    greek_food     int64
33               healthy_feeling     int64
34                  healthy_meal       str
35                    ideal_diet       str
36              ideal_diet_coded     int64
37                        income   float64
38                   indian_food     int64
39                  italian_food     int64
40                life_rewarding   float64
41                marital_status   float64
42           meals_dinner_friend       str
43              mother_education   float64
44             mother_profession       str
45             nutritional_check     int64
46                 on_off_campus   float64
47                  parents_cook     int64
48                  pay_meal_out     int64
49                  persian_food   float64
50        self_perception_weight   float64
51                          soup   float64
52                        sports   float64
53                     thai_food     int64
54             tortilla_calories   float64
55               turkey_calories     int64
56                   type_sports       str
57                   veggies_day     int64
58                      vitamins     int64
59               waffle_calories     int64
60                        weight       str

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [14]:
# Remove ‘em.
df_food_col_subset = df_food[['calories_day', 'weight', 'Gender']]
df_food_col_subset.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

In [15]:
# Is there a second way to remove columns?
cols_to_drop = [col for col in df_food.columns if col not in ['calories_day', 'weight', 'Gender']]

df_food_col_subset = df_food.drop(columns=cols_to_drop)

df_food_col_subset.head()

   Gender  calories_day                    weight
0       2           NaN                       187
1       1           3.0                       155
2       1           4.0  I'm not answering this.
3       1           3.0             Not sure, 240
4       1           2.0                       190

In [16]:
# 🚀 Extra credit: What about a third way to remove columns?

df_food_col_subset = df_food.loc[:, ['calories_day', 'weight', 'Gender']]

df_food_col_subset.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

What about `NaN`s? How many are there?

In [17]:
# Count ‘em.
df_food_col_subset.isna().sum()

calories_day    19
weight           2
Gender           0
dtype: int64

In [18]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.

df_nans = df_food_col_subset.isna().sum().reset_index()
df_nans.columns = ['Column Name', 'NaN Count']

df_nans

    Column Name  NaN Count
0  calories_day         19
1        weight          2
2        Gender          0

In [ ]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

We gotta remove those `NaN`s―the entire row.

In [19]:
# Drop ‘em in-place.
df_food_col_subset.dropna(inplace=True)

In [ ]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [20]:
# Fix that in-place.
df_food_col_subset['weight'] = pd.to_numeric(df_food_col_subset['weight'], errors='coerce')
df_food_col_subset.dropna(inplace=True)

df_food_col_subset.dtypes

calories_day    float64
weight          float64
Gender            int64
dtype: object

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [22]:
# Savey save!
df_food_col_subset.to_csv('../data/cleaned_food_data.csv', index=False)

In [ ]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [24]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.
salary_data_path = '../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv'

df_salary = pd.read_csv(salary_data_path, sep='\t')

df_salary.head()

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [26]:
# Count by hand. I’m dead serious.

df_salary.shape  #nah that's too much work lol

(28062, 18)

What are the columns and their types?

In [27]:
# Show the column names and their types.

pd.DataFrame({
    'Column Name': df_salary.columns,
    'Data Type': df_salary.dtypes.values
})

                                          Column Name Data Type
0                                           Timestamp       str
1                                    How old are you?       str
2                       What industry do you work in?       str
3                                           Job title       str
4   If your job title needs additional context, pl...       str
5   What is your annual salary? (You'll indicate t...       str
6   How much additional monetary compensation do y...   float64
7                        Please indicate the currency       str
8     If "Other," please indicate the currency here:        str
9   If your income needs additional context, pleas...       str
10                       What country do you work in?       str
11  If you're in the U.S., what state do you work in?       str
12                          What city do you work in?       str
13  How many years of professional work experience...       str
14  How many years of professional work experience...       str
15  What is your highest level of education comple...       str
16                               What is your gender?       str
17        What is your race? (Choose all that apply.)       str

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [28]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race

new_column_names = {
    df_salary.columns[0]: 'timestamp',
    df_salary.columns[1]: 'age',
    df_salary.columns[2]: 'industry',
    df_salary.columns[3]: 'title',
    df_salary.columns[4]: 'title_context',
    df_salary.columns[5]: 'salary',
    df_salary.columns[6]: 'additional_compensation',
    df_salary.columns[7]: 'currency',
    df_salary.columns[8]: 'other_currency',
    df_salary.columns[9]: 'income_context',
    df_salary.columns[10]: 'country',
    df_salary.columns[11]: 'state',
    df_salary.columns[12]: 'city',
    df_salary.columns[13]: 'years_experience_overall',
    df_salary.columns[14]: 'years_experience_field',
    df_salary.columns[15]: 'education',
    df_salary.columns[16]: 'gender',
    df_salary.columns[17]: 'race'
}

df_salary.rename(columns=new_column_names, inplace=True)
df_salary.columns

Index(['timestamp', 'age', 'industry', 'title', 'title_context', 'salary',
       'additional_compensation', 'currency', 'other_currency',
       'income_context', 'country', 'state', 'city',
       'years_experience_overall', 'years_experience_field', 'education',
       'gender', 'race'],
      dtype='str')

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [29]:
# List the unique industries and a count of their instances.
df_salary['industry'].value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [30]:
# Filtery filter.
df_salary_tech = df_salary[df_salary['industry'] == 'Computing or Tech']

print(df_salary_tech.shape)
df_salary_tech.head()

(4699, 18)

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,income_context,country,state,city,years_experience_overall,years_experience_field,education,gender,race
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White

Do a sanity check by counting.

In [31]:
# Sanity check count.
len(df_salary_tech)

4699

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [32]:
# Filtery filter (in place) for just the jobs that pay in USD!
df_salary_tech = df_salary_tech[df_salary_tech['currency'] == 'USD'].copy()
df_salary_tech['salary'] = pd.to_numeric(
    df_salary_tech['salary'].str.replace(',', '', regex=False)
)

print(df_salary_tech.shape)
df_salary_tech.head()

(3777, 18)

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,income_context,country,state,city,years_experience_overall,years_experience_field,education,gender,race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,USA,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [33]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.

df_salary_tech['country'].value_counts()

country
United States                1576
USA                          1222
US                            412
U.S.                          108
United States of America       90
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [34]:
# Replace them all in-place with 'US'.
top_5_countries = df_salary_tech['country'].value_counts().head(5).index.tolist()

df_salary_tech['country'].replace(top_5_countries, 'US', inplace=True)

df_salary_tech['country'].value_counts()

/tmp/ipykernel_6550/2671871932.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_salary_tech['country'].replace(top_5_countries, 'US', inplace=True)

country
United States                1576
USA                          1222
US                            412
U.S.                          108
United States of America       90
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

Have a look at the count of each unique country again now.

In [35]:
# Count again.

df_salary_tech['country'].value_counts()

country
United States                1576
USA                          1222
US                            412
U.S.                          108
United States of America       90
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

Did you notice anything interesting?

In [ ]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [ ]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [42]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
df_salary_tech['salary'] = pd.to_numeric(
    df_salary_tech['salary'].astype(str).str.replace(',', ''), 
    errors='coerce'
)

df_salary_tech.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values(by='mean', ascending=False)

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Florida                          28800  157457.232143  2600000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  154857.215478   875000
Washington                          72  151423.670588   950000
New York                         14000  148054.638968   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135213.537954  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127706.355932   450000
Colorado                         45000  127240.006849   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119268.242604   315000
Georgia                          29120  117893.098765   250000
Maryland                         51260  117862.370370   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114268.000000   920000
Texas                            10700  113909.713004   280000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  106752.793103   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
North Carolina                   29000  105035.441441   260000
New York, Texas                 105000  105000.000000   105000
Massachusetts, New Hampshire    105000  105000.000000   105000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
South Carolina                   40000  102111.111111   205000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   96855.363636   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
New Hampshire                       55   95179.705882   193000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
Alabama                          29120   92510.000000   350000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Louisiana                        35360   83269.090909   150000
Massachusetts, Pennsylvania      83000   83000.000000    83000
California, Maryland             81500   81500.000000    81500
Arkansas                             4   74257.000000   144000
Alabama, Montana                 72000   72000.000000    72000

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [43]:
# Fix it in-place.

df_salary_tech['salary'] = pd.to_numeric(
    df_salary_tech['salary'].astype(str).str.replace(',', ''), 
    errors='coerce'
)

df_salary_tech['salary'].dtype

dtype('int64')

Let’s try that again.

In [44]:
# Try it again. Yeah!
df_salary_tech.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values(by='mean', ascending=False)

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Florida                          28800  157457.232143  2600000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  154857.215478   875000
Washington                          72  151423.670588   950000
New York                         14000  148054.638968   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135213.537954  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127706.355932   450000
Colorado                         45000  127240.006849   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119268.242604   315000
Georgia                          29120  117893.098765   250000
Maryland                         51260  117862.370370   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114268.000000   920000
Texas                            10700  113909.713004   280000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  106752.793103   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
North Carolina                   29000  105035.441441   260000
New York, Texas                 105000  105000.000000   105000
Massachusetts, New Hampshire    105000  105000.000000   105000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
South Carolina                   40000  102111.111111   205000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   96855.363636   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
New Hampshire                       55   95179.705882   193000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
Alabama                          29120   92510.000000   350000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Louisiana                        35360   83269.090909   150000
Massachusetts, Pennsylvania      83000   83000.000000    83000
California, Maryland             81500   81500.000000    81500
Arkansas                             4   74257.000000   144000
Alabama, Montana                 72000   72000.000000    72000

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [45]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.

df_salary_tech['timestamp'] = pd.to_datetime(df_salary_tech['timestamp'])

df_salary_tech_recent = df_salary_tech[df_salary_tech['timestamp'].dt.year.isin([2021, 2022, 2023])]

df_salary_tech_recent.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values(by='mean', ascending=False)

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  154986.177812   875000
Washington                          72  151571.970501   950000
New York                         14000  148054.638968   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135184.443709  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127706.355932   450000
Colorado                         45000  127240.006849   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119621.029762   315000
Georgia                          29120  118004.262500   250000
Maryland                         51260  117862.370370   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114268.000000   920000
Texas                            10700  113909.713004   280000
Florida                          28800  113047.363636   400000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
South Carolina                   40000  109875.000000   205000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  107063.872093   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
New York, Texas                 105000  105000.000000   105000
Massachusetts, New Hampshire    105000  105000.000000   105000
North Carolina                   29000  104944.854545   260000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Alabama                          29120   97738.181818   350000
Michigan                         36800   96855.363636   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
New Hampshire                       55   95179.705882   193000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Louisiana                        35360   83269.090909   150000
Massachusetts, Pennsylvania      83000   83000.000000    83000
Arkansas                         55000   81682.300000   144000
California, Maryland             81500   81500.000000    81500
Alabama, Montana                 72000   72000.000000    72000

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)