# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
!pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy in /usr/local/python/3.14.2/lib/python3.14/site-packages (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [4]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'
df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [6]:
# Count by hand. (lol kidding)
print(f"Columns, Rows: {df_food.shape}")
print(f"This many cells: {df_food.size}")

Columns, Rows: (125, 61)
This many cells: 7625

In [7]:
# Try to print or display it nicely.
df_food.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190

What are the columns and their types in this data set?

In [9]:
# Show the column names and their types.
df_food.dtypes

GPA                     str
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports             str
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight                  str
Length: 61, dtype: object

In [10]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
df_info = pd.DataFrame(df_food.dtypes, columns=['Data Type'])
df_info

                             Data Type
GPA                                str
Gender                           int64
breakfast                        int64
calories_chicken                 int64
calories_day                   float64
calories_scone                 float64
coffee                           int64
comfort_food                       str
comfort_food_reasons               str
comfort_food_reasons_coded     float64
cook                           float64
comfort_food_reasons_coded.1     int64
cuisine                        float64
diet_current                       str
diet_current_coded               int64
drink                          float64
eating_changes                     str
eating_changes_coded             int64
eating_changes_coded1            int64
eating_out                       int64
employment                     float64
ethnic_food                      int64
exercise                       float64
father_education               float64
father_profession                  str
fav_cuisine                        str
fav_cuisine_coded                int64
fav_food                       float64
food_childhood                     str
fries                            int64
fruit_day                        int64
grade_level                      int64
greek_food                       int64
healthy_feeling                  int64
healthy_meal                       str
ideal_diet                         str
ideal_diet_coded                 int64
income                         float64
indian_food                      int64
italian_food                     int64
life_rewarding                 float64
marital_status                 float64
meals_dinner_friend                str
mother_education               float64
mother_profession                  str
nutritional_check                int64
on_off_campus                  float64
parents_cook                     int64
pay_meal_out                     int64
persian_food                   float64
self_perception_weight         float64
soup                           float64
sports                         float64
thai_food                        int64
tortilla_calories              float64
turkey_calories                  int64
type_sports                        str
veggies_day                      int64
vitamins                         int64
waffle_calories                  int64
weight                             str

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [11]:
# Remove ‘em.
df_food_col_subset = df_food[['calories_day', 'weight', 'Gender']]
df_food_col_subset

     calories_day                    weight  Gender
0             NaN                       187       2
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
..            ...                       ...     ...
120           4.0                       156       1
121           2.0                       180       1
122           NaN                       120       1
123           4.0                       135       2
124           NaN                       135       1

[125 rows x 3 columns]

In [12]:
# Is there a second way to remove columns?
targeted = ['calories_day', 'weight', 'Gender']
df_food_col_targeted = df_food[targeted]
df_food_col_targeted

     calories_day                    weight  Gender
0             NaN                       187       2
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
..            ...                       ...     ...
120           4.0                       156       1
121           2.0                       180       1
122           NaN                       120       1
123           4.0                       135       2
124           NaN                       135       1

[125 rows x 3 columns]

In [ ]:
# 🚀 Extra credit: What about a third way to remove columns?

What about `NaN`s? How many are there?

In [14]:
# Count ‘em.
df_food.isna().sum()

GPA                              2
Gender                           0
breakfast                        0
calories_chicken                 0
calories_day                    19
calories_scone                   1
coffee                           0
comfort_food                     1
comfort_food_reasons             2
comfort_food_reasons_coded      19
cook                             3
comfort_food_reasons_coded.1     0
cuisine                         17
diet_current                     1
diet_current_coded               0
drink                            2
eating_changes                   3
eating_changes_coded             0
eating_changes_coded1            0
eating_out                       0
employment                       9
ethnic_food                      0
exercise                        13
father_education                 1
father_profession                3
fav_cuisine                      2
fav_cuisine_coded                0
fav_food                         2
food_childhood                   1
fries                            0
fruit_day                        0
grade_level                      0
greek_food                       0
healthy_feeling                  0
healthy_meal                     1
ideal_diet                       1
ideal_diet_coded                 0
income                           1
indian_food                      0
italian_food                     0
life_rewarding                   1
marital_status                   1
meals_dinner_friend              3
mother_education                 3
mother_profession                2
nutritional_check                0
on_off_campus                    1
parents_cook                     0
pay_meal_out                     0
persian_food                     1
self_perception_weight           1
soup                             1
sports                           2
thai_food                        0
tortilla_calories                1
turkey_calories                  0
type_sports                     26
veggies_day                      0
vitamins                         0
waffle_calories                  0
weight                           2
dtype: int64

In [ ]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.

In [ ]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

We gotta remove those `NaN`s―the entire row.

In [15]:
# Drop ‘em in-place.
#df_food.isna().sum()
df_food.dropna(inplace = True)

In [16]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂
print(df_food.isna().sum())
df_food.head()

GPA                             0
Gender                          0
breakfast                       0
calories_chicken                0
calories_day                    0
calories_scone                  0
coffee                          0
comfort_food                    0
comfort_food_reasons            0
comfort_food_reasons_coded      0
cook                            0
comfort_food_reasons_coded.1    0
cuisine                         0
diet_current                    0
diet_current_coded              0
drink                           0
eating_changes                  0
eating_changes_coded            0
eating_changes_coded1           0
eating_out                      0
employment                      0
ethnic_food                     0
exercise                        0
father_education                0
father_profession               0
fav_cuisine                     0
fav_cuisine_coded               0
fav_food                        0
food_childhood                  0
fries                           0
fruit_day                       0
grade_level                     0
greek_food                      0
healthy_feeling                 0
healthy_meal                    0
ideal_diet                      0
ideal_diet_coded                0
income                          0
indian_food                     0
italian_food                    0
life_rewarding                  0
marital_status                  0
meals_dinner_friend             0
mother_education                0
mother_profession               0
nutritional_check               0
on_off_campus                   0
parents_cook                    0
pay_meal_out                    0
persian_food                    0
self_perception_weight          0
soup                            0
sports                          0
thai_food                       0
tortilla_calories               0
turkey_calories                 0
type_sports                     0
veggies_day                     0
vitamins                        0
waffle_calories                 0
weight                          0
dtype: int64

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
6,3.8,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.0,1.0,5,940.0,690,soccer,4,1,1315,180
7,3.3,1,1,720,3.0,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,...,1.0,2.0,1,725.0,500,none,4,2,1315,137

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [17]:
# Fix that in-place.
nowNumeric = ['GPA', 'weight']
df_food[nowNumeric] = df_food[nowNumeric].apply(pd.to_numeric, errors='coerce')
df_food.dropna(subset=nowNumeric, inplace=True)

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [22]:
# Savey save!
df_food.to_csv('../data/food_cleanedUp.csv', index=False)

In [20]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.
with open('../data/food_cleanedUp.csv', "r") as file:
    lines = file.readlines()

print(lines[:2])

['GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,cook,comfort_food_reasons_coded.1,cuisine,diet_current,diet_current_coded,drink,eating_changes,eating_changes_coded,eating_changes_coded1,eating_out,employment,ethnic_food,exercise,father_education,father_profession,fav_cuisine,fav_cuisine_coded,fav_food,food_childhood,fries,fruit_day,grade_level,greek_food,healthy_feeling,healthy_meal,ideal_diet,ideal_diet_coded,income,indian_food,italian_food,life_rewarding,marital_status,meals_dinner_friend,mother_education,mother_profession,nutritional_check,on_off_campus,parents_cook,pay_meal_out,persian_food,self_perception_weight,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight\n', '2.4,2,1,430,,315.0,1,none,we dont have comfort ,9.0,2.0,9,,eat good and exercise,1,1.0,eat faster ,1,1,3,3.0,1,1.0,5.0,profesor ,Arabic cuisine,3,1.0,rice  and chicken ,2,5,2,5,2,looks not oily ,being healthy ,8,5.0,5,5,1.0,1.0,"rice, chicken,  soup",1.0,unemployed,5,1.0,1,2,5.0,3.0,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187.0\n']

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [21]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.
salary_data_set_path = '../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv'
df_salary = pd.read_csv(salary_data_set_path, sep='\t')

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [22]:
# Count by hand. I’m dead serious.
print(f"Columns, Rows: {df_salary.shape}")
print(f"This many cells: {df_salary.size}")

Columns, Rows: (28062, 18)
This many cells: 505116

What are the columns and their types?

In [23]:
# Show the column names and their types.
df_salary.dtypes

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [77]:
# Rename ‘em in-place.
df_salary = df_salary.rename(columns={
    'Timestamp': 'timestamp',
    'How old are you?': 'age',
    'What industry do you work in?': 'industry',
    'Job title': 'title',
    'If your job title needs additional context, please clarify here:': 'title_context',
    "What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)": 'salary',
    'How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.': 'additional_compensation',
    'Please indicate the currency': 'currency',
    'If "Other," please indicate the currency here: ': 'other_currency',
    'If your income needs additional context, please provide it here:': 'salary_context',
    'What country do you work in?': 'country',
    "If you're in the U.S., what state do you work in?": 'state',
    'What city do you work in?': 'city',
    'How many years of professional work experience do you have overall?': 'total_yoe',
    'How many years of professional work experience do you have in your field?': 'field_yoe',
    'What is your highest level of education completed?': 'highest_education_completed',
    'What is your gender?': 'gender',
    'What is your race? (Choose all that apply.)': 'race',
})

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [78]:
# List the unique industries and a count of their instances.
industry_counts = df_salary['industry'].value_counts()
industry_counts

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [79]:
# Filtery filter.
df_salary_tech = df_salary[df_salary["industry"] == "Computing or Tech"]
df_salary_tech.head

<bound method NDFrame.head of                 timestamp    age           industry  \
1      4/27/2021 11:02:22  25-34  Computing or Tech
8      4/27/2021 11:03:01  45-54  Computing or Tech
43     4/27/2021 11:04:04  25-34  Computing or Tech
44     4/27/2021 11:04:04  25-34  Computing or Tech
46     4/27/2021 11:04:07  35-44  Computing or Tech
...                   ...    ...                ...
28050   7/1/2024 13:38:46  25-34  Computing or Tech
28051   7/1/2024 20:05:58  25-34  Computing or Tech
28052   7/3/2024 14:02:01  25-34  Computing or Tech
28058  7/23/2024 17:51:03  25-34  Computing or Tech
28060  7/26/2024 11:20:45  18-24  Computing or Tech

                                              title  \
1          Change & Internal Communications Manager
8                                   Systems Analyst
43                      Principal Software Engineer
44                             Intelligence Analyst
46                                 Mobile developer
...                                             ...
28050  Research & Systems Technician Data Analytics
28051                          Junior data analyst
28052        Senior Global Public Relations Manager
28058                             Systems Architect
28060                                            IT

                      title_context   salary  additional_compensation  \
1                               NaN   54,600                   4000.0
8      Data developer/ETL Developer  112,000                  10000.0
43                              NaN  187,500                   5000.0
44                              NaN  110,000                  20000.0
46                              NaN  144,600                   2500.0
...                             ...      ...                      ...
28050                           NaN    22000                      NaN
28051                           NaN    35000                  15000.0
28052                           NaN   144000                  15000.0
28058                           NaN   109000                      NaN
28060                           NaN     1700                     10.0

      currency other_currency                 salary_context         country  \
1          GBP            NaN                            NaN  United Kingdom
8          USD            NaN                            NaN              US
43         USD            NaN                            NaN   United States
44         USD            NaN  Around 20,000 a year in stock             USA
46         USD            NaN                            NaN             USA
...        ...            ...                            ...             ...
28050      EUR            NaN                            NaN           Spain
28051      USD            NaN                            NaN             Usa
28052      USD            NaN                            NaN             Usa
28058      USD            NaN                            NaN             USA
28060      USD            NaN                            NaN           Burma

               state                                          city  \
1                NaN                                     Cambridge
8           Missouri                                     St. Louis
43      Pennsylvania                                    Pittsburgh
44          Virginia                                 Arlington, VA
46     Massachusetts                                        Boston
...              ...                                           ...
28050            NaN                                     Barcelona
28051        Alabama                                      Alabama
28052  Massachusetts  Boise-but remote. Company located in Boston
28058        Georgia                                       Atlanta
28060            NaN                                        Yangon

           total_yoe       field_yoe highest_education_completed      gender  \
1       8 - 10 years       5-7 years              College degree  Non-binary
8      21 - 30 years   21 - 30 years              College degree       Woman
43      8 - 10 years       5-7 years              College degree       Woman
44      8 - 10 years    8 - 10 years             Master's degree         Man
46         5-7 years       5-7 years                         PhD       Woman
...              ...             ...                         ...         ...
28050    2 - 4 years     2 - 4 years              College degree         Man
28051    2 - 4 years     2 - 4 years              College degree       Woman
28052   8 - 10 years    8 - 10 years             Master's degree       Woman
28058      5-7 years       5-7 years              College degree         Man
28060    2 - 4 years  1 year or less                Some college         Man

                                      race
1                                    White
8                                    White
43                                   White
44                                   White
46                                   White
...                                    ...
28050  Hispanic, Latino, or Spanish origin
28051            Black or African American
28052                                White
28058                                White
28060              Asian or Asian American

[4699 rows x 18 columns]>

Do a sanity check by counting.

In [80]:
# Sanity check count.
print(df_salary_tech.shape)

(4699, 18)

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [81]:
# Filtery filter (in place) for just the jobs that pay in USD!
df_salary_tech.drop(
    df_salary_tech[df_salary_tech["currency"] != "USD"].index,
    inplace=True
)

df_salary_tech["currency"].value_counts()

currency
USD    3777
Name: count, dtype: int64

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [82]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary_tech["country"].value_counts()

country
United States                1576
USA                          1222
US                            412
U.S.                          108
United States of America       90
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [83]:
# Replace them all in-place with 'US'.
df_salary_tech["country"] = df_salary_tech["country"].replace(
    [
        "United States",
        "USA",
        "US",
        "U.S.",
        "United States of America",
        "united states",
        "United states",
        "Usa",
        "usa",
        "us",
        "Us",
        "U.S.A.",
        "Unite States",
        "UnitedStates",
        "U.S"
    ],
    "US"
)

Have a look at the count of each unique country again now.

In [84]:
# Count again.
df_salary_tech["country"].value_counts()

country
US                           3566
United States                  68
USA                            56
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Australia                       2
India                           2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

Did you notice anything interesting?

In [ ]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [ ]:
# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [85]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
#df_usd_salary_tech[df_usd_salary_tech['Country'].isin(['US'])].groupby('State')['Salary'].agg(['min', 'mean', 'max']).sort_values(by='mean', ascending=False)

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [86]:
# Fix it in-place.

df_salary_tech["salary"] = df_salary.loc[df_salary_tech.index, "salary"]
df_salary_tech["salary"].head(20)

df_salary_tech["salary"] = df_salary_tech["salary"].str.replace(",", "", regex=False)
df_salary_tech["salary"].head(20)

df_salary_tech["salary"] = pd.to_numeric(
    df_salary_tech["salary"],
    errors="coerce"
)
df_salary_tech["salary"].isna().sum()

np.int64(0)

In [87]:
# Fix it in-place.
df_salary_tech["salary"] = (
    df_salary_tech["salary"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

df_salary_tech["salary"] = pd.to_numeric(
    df_salary_tech["salary"],
    errors="coerce"
)

df_salary_tech.groupby("state")["salary"].agg(
    ["min", "mean", "max"]
).sort_values("mean", ascending=False)

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Florida                          28800  157457.232143  2600000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  154857.215478   875000
Washington                          72  151423.670588   950000
New York                         14000  148054.638968   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135213.537954  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127706.355932   450000
Colorado                         45000  127240.006849   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119268.242604   315000
Georgia                          29120  117893.098765   250000
Maryland                         51260  117862.370370   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114268.000000   920000
Texas                            10700  113909.713004   280000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  106752.793103   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
North Carolina                   29000  105035.441441   260000
New York, Texas                 105000  105000.000000   105000
Massachusetts, New Hampshire    105000  105000.000000   105000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
South Carolina                   40000  102111.111111   205000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   96855.363636   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
New Hampshire                       55   95179.705882   193000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
Alabama                          29120   92510.000000   350000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Louisiana                        35360   83269.090909   150000
Massachusetts, Pennsylvania      83000   83000.000000    83000
California, Maryland             81500   81500.000000    81500
Arkansas                             4   74257.000000   144000
Alabama, Montana                 72000   72000.000000    72000

Let’s try that again.

In [88]:
# Try it again. Yeah!
df_salary_tech.groupby("state")["salary"] \
   .agg(["min", "mean", "max"]) \
   .sort_values("mean", ascending=False)

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Florida                          28800  157457.232143  2600000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  154857.215478   875000
Washington                          72  151423.670588   950000
New York                         14000  148054.638968   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135213.537954  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127706.355932   450000
Colorado                         45000  127240.006849   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119268.242604   315000
Georgia                          29120  117893.098765   250000
Maryland                         51260  117862.370370   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114268.000000   920000
Texas                            10700  113909.713004   280000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  106752.793103   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
North Carolina                   29000  105035.441441   260000
New York, Texas                 105000  105000.000000   105000
Massachusetts, New Hampshire    105000  105000.000000   105000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
South Carolina                   40000  102111.111111   205000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   96855.363636   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
New Hampshire                       55   95179.705882   193000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
Alabama                          29120   92510.000000   350000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Louisiana                        35360   83269.090909   150000
Massachusetts, Pennsylvania      83000   83000.000000    83000
California, Maryland             81500   81500.000000    81500
Arkansas                             4   74257.000000   144000
Alabama, Montana                 72000   72000.000000    72000

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [89]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_salary_tech['timestamp'] = pd.to_datetime(df_salary_tech['timestamp'])
df_salary_tech['year'] = df_salary_tech['timestamp'].dt.year
filtered_data = df_salary_tech[df_salary_tech['year'].isin([2021, 2022, 2023])].copy()
salary_by_state_filtered = (
    filtered_data.groupby('state')['salary']
    .agg(['min', 'mean', 'max'])
    .reset_index()
    .sort_values('mean', ascending=False)
)
salary_by_state_filtered

                             state     min           mean      max
35     Michigan, Texas, Washington  340000  340000.000000   340000
10              California, Oregon  200000  200000.000000   200000
8             California, Colorado  176000  176000.000000   176000
18          Georgia, Massachusetts  175000  175000.000000   175000
1    Alabama, District of Columbia  156000  156000.000000   156000
7                       California       0  154986.177812   875000
63                      Washington      72  151571.970501   950000
46                        New York   14000  148054.638968   590000
41                          Nevada   38000  141310.000000   425000
44            New Jersey, New York  135000  137500.000000   140000
30                   Massachusetts   37000  135184.443709  1650000
14            District of Columbia   10000  132318.036364   267500
45                      New Mexico   70000  132200.000000   300000
60                   Utah, Vermont  130000  130000.000000   130000
43                      New Jersey   40000  128802.475000   603000
12                     Connecticut   62400  128375.000000   270000
62                        Virginia   43642  127706.355932   450000
11                        Colorado   45000  127240.006849   630000
33     Massachusetts, Rhode Island  125000  125000.000000   125000
52                          Oregon   16200  124297.800000   320000
19             Georgia, Washington  123000  123000.000000   123000
64                   West Virginia  116500  120500.000000   125000
21                        Illinois   13500  119621.029762   315000
17                         Georgia   29120  118004.262500   250000
29                        Maryland   51260  117862.370370   205000
27           Louisiana, Washington  117000  117000.000000   117000
13                        Delaware   63000  116600.000000   169000
56                    South Dakota   86000  115333.333333   150000
65                       Wisconsin       1  114268.000000   920000
58                           Texas   10700  113909.713004   280000
16                         Florida   28800  113047.363636   400000
57                       Tennessee   36550  112847.058824   240000
3                           Alaska   67000  112500.000000   158000
61                         Vermont   65000  111781.250000   200000
53                    Pennsylvania   32000  111623.123894   237000
20                           Idaho   50000  111527.692308   312000
54                    Rhode Island   76000  111491.666667   180000
55                  South Carolina   40000  109875.000000   205000
15  District of Columbia, Virginia  109200  109200.000000   109200
36                       Minnesota   34000  107063.872093   230000
50                            Ohio   32240  106338.835821   954000
59                            Utah   33280  105836.479167   245000
47                 New York, Texas  105000  105000.000000   105000
31    Massachusetts, New Hampshire  105000  105000.000000   105000
48                  North Carolina   29000  104944.854545   260000
4                          Arizona   35000  104491.891892   210000
28                           Maine   50000  103571.428571   173000
23                            Iowa   47840   99729.736842   160000
24                          Kansas   41500   99565.052632   167000
49                    North Dakota   45760   97880.000000   150000
0                          Alabama   29120   97738.181818   350000
34                        Michigan   36800   96855.363636   235000
39                         Montana   65000   95500.000000   145000
38                        Missouri      80   95317.652174   200000
42                   New Hampshire      55   95179.705882   193000
5                    Arizona, Utah   95000   95000.000000    95000
37                     Mississippi   94000   94000.000000    94000
25                        Kentucky   39000   92375.000000   170000
40                        Nebraska   43000   90975.294118   166400
22                         Indiana   15000   88566.647059   200000
51                        Oklahoma   28536   87929.500000   180000
26                       Louisiana   35360   83269.090909   150000
32     Massachusetts, Pennsylvania   83000   83000.000000    83000
6                         Arkansas   55000   81682.300000   144000
9             California, Maryland   81500   81500.000000    81500
2                 Alabama, Montana   72000   72000.000000    72000

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

In [90]:
# Bonus #0
df_salary_clean = df_salary.copy()
df_salary_clean = df_salary_clean.rename(columns={
    'Timestamp': 'timestamp',
    'How old are you?': 'age',
    'What industry do you work in?': 'industry',
    'Job title': 'title',
    'If your job title needs additional context, please clarify here:': 'title_context',
    'What is your annual salary? (You’ll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)': 'salary',
    'How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.': 'additional_compensation',
    'Please indicate the currency': 'currency',
    'If "Other," please indicate the currency here: ': 'other_currency',
    'If your income needs additional context, please provide it here:': 'salary_context',
    'What country do you work in?': 'country',
    "If you're in the U.S., what state do you work in?": 'state',
    'What city do you work in?': 'city',
    'How many years of professional work experience do you have overall?': 'total_yoe',
    'How many years of professional work experience do you have in your field?': 'field_yoe',
    'What is your highest level of education completed?': 'highest_education_completed',
    'What is your gender?': 'gender',
    'What is your race? (Choose all that apply.)': 'race',
})
df_salary_clean = df_salary_clean[df_salary_clean['currency'].eq('USD')].copy()
df_salary_clean['salary'] = pd.to_numeric(df_salary_clean['salary'], errors='coerce')
df_salary_clean['country'] = df_salary_clean['country'].str.replace(
    r'(?i).*united states.*|.*u\.s\.a.*|.*usa.*|.*america.*',
    'US',
    regex=True,
)
# more brute-force normalization for the top five irrelevant country values
country_top_five = df_salary_clean['country'].value_counts().head(5).index
df_salary_clean['country'] = df_salary_clean['country'].replace(country_top_five, 'US')
salary_by_state_all = (
    df_salary_clean.groupby('state')['salary']
    .agg(['min', 'mean', 'max'])
    .reset_index()
    .sort_values('mean', ascending=False)
)
salary_by_state_all

                           state        min       mean         max
8        Alabama, South Carolina  5000000.0  5000000.0   5000000.0
9                         Alaska    47840.0   737319.2  10000000.0
88   Michigan, Texas, Washington   340000.0   340000.0    340000.0
32            California, Oregon   200000.0   200000.0    200000.0
24          California, Colorado   176000.0   176000.0    176000.0
..                           ...        ...        ...         ...
109         North Carolina, Utah        NaN        NaN         NaN
112             Ohio, Washington        NaN        NaN         NaN
113                Ohio, Wyoming        NaN        NaN         NaN
124              Texas, Virginia        NaN        NaN         NaN
126                Utah, Vermont        NaN        NaN         NaN

[133 rows x 4 columns]

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

In [ ]:
# Bonus #1

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

In [ ]:
# Bonus #2

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)

In [ ]:
# Bonus #3