# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [3]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

In [4]:
# Load the Food choices data set into a variable (e.g., df_food).

food_data_set_path = 'C:\\Users\\jonni\\Desktop\\ctp\\ds-fall-2026\\Week-02-Pandas-and-How-to-Make-a-Sick-Project\\data\\food_coded.csv'

df_food = pd.read_csv(food_data_set_path)
df_food

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,...,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,...,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,...,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,...,1.0,2.0,2,725.0,345,NaN,4,2,575,135

### Explore the Data

How much data did you just load?

In [5]:
# Count by hand. (lol kidding)
len(df_food)

125

What are the columns and their types in this data set?

In [6]:
# Show the column names and their types.

print(str(df_food.dtypes) + "\n\n" + str(df_food.columns))

GPA                     str
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports             str
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight                  str
Length: 61, dtype: object

Index(['GPA', 'Gender', 'breakfast', 'calories_chicken', 'calories_day',
       'calories_scone', 'coffee', 'comfort_food', 'comfort_food_reasons',
       'comfort_food_reasons_coded', 'cook', 'comfort_food_reasons_coded.1',
       'cuisine', 'diet_current', 'diet_current_coded', 'drink',
       'eating_changes', 'eating_changes_coded', 'eating_changes_coded1',
       'eating_out', 'employment', 'ethnic_food', 'exercise',
       'father_education', 'father_profession', 'fav_cuisine',
       'fav_cuisine_coded', 'fav_food', 'food_childhood', 'fries', 'fruit_day',
       'grade_level', 'greek_food', 'healthy_feeling', 'healthy_meal',
       'ideal_diet', 'ideal_diet_coded', 'income', 'indian_food',
       'italian_food', 'life_rewarding', 'marital_status',
       'meals_dinner_friend', 'mother_education', 'mother_profession',
       'nutritional_check', 'on_off_campus', 'parents_cook', 'pay_meal_out',
       'persian_food', 'self_perception_weight', 'soup', 'sports', 'thai_food',
       'tortilla_calories', 'turkey_calories', 'type_sports', 'veggies_day',
       'vitamins', 'waffle_calories', 'weight'],
      dtype='str')

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns?

In [7]:
# Remove ‘em.
CandW = df_food[["calories_day","weight"]]
CandW

     calories_day                    weight
0             NaN                       187
1             3.0                       155
2             4.0  I'm not answering this.
3             3.0             Not sure, 240
4             2.0                       190
..            ...                       ...
120           4.0                       156
121           2.0                       180
122           NaN                       120
123           4.0                       135
124           NaN                       135

[125 rows x 2 columns]

What about `NaN`s? How many are there?

In [8]:
# Count ‘em.
CandW.isna().sum()

calories_day    19
weight           2
dtype: int64

We gotta remove those `NaN`s―the entire row.

In [9]:
# Drop ‘em.


#line 73 is diabolical
CandW.dropna()

     calories_day                    weight
1             3.0                       155
2             4.0  I'm not answering this.
3             3.0             Not sure, 240
4             2.0                       190
5             3.0                       190
..            ...                       ...
118           3.0                       140
119           3.0                       185
120           4.0                       156
121           2.0                       180
123           4.0                       135

[104 rows x 2 columns]

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [10]:
# Fix that.
CandW = CandW.apply(pd.to_numeric,errors='coerce')
CandW.dropna()

     calories_day  weight
1             3.0   155.0
4             2.0   190.0
5             3.0   190.0
6             3.0   180.0
7             3.0   137.0
..            ...     ...
118           3.0   140.0
119           3.0   185.0
120           4.0   156.0
121           2.0   180.0
123           4.0   135.0

[101 rows x 2 columns]

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [11]:
# Savey save!
CandW.to_csv("shipped_to_another_teamamte_Jonathan_Davydov_wee2.csv")

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

In [12]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set into a variable (e.g., df_salary).
df_salary = pd.read_csv("C:\\Users\\jonni\\Desktop\\ctp\\ds-fall-2026\\Week-02-Pandas-and-How-to-Make-a-Sick-Project\\data\\Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv",sep = '\t')
df_salary

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28057,7/12/2024 22:52:01,35-44,Health care,Veterinarian,NaN,135000,NaN,USD,NaN,NaN,United States,Missouri,Wentzville,11 - 20 years,11 - 20 years,"Professional degree (MD, JD, etc.)",Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28059,7/24/2024 12:22:58,18-24,"Accounting, Banking & Finance",Risk Management Associate,NaN,1200,0.0,USD,NaN,NaN,Myanmar,Colorado,Yangon,2 - 4 years,2 - 4 years,Some college,Man,Asian or Asian American
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American
28061,8/20/2024 1:06:13,25-34,Health care,Clinical physiologist,NaN,1200000,NaN,Other,NGN,NaN,Nigeria,NaN,Lagos,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American

Was that hard? 🙃

#### rename the file to something that is better for all systems.  
* No spaces in filename (can use '_')
* all lower case

In [13]:
df_salary.to_csv("manager_salary_survey_2021")

### Explore

You know the drill.

How much data did you just load?

In [14]:
# Count by hand. I’m dead serious.
df_salary.size

505116

What are the columns and their types?

In [15]:
# Show the column names and their types.
sal_c_types = df_salary.dtypes
print(sal_c_types)

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [16]:
# Rename ‘em.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race
c_names = ["timestamp", "age", "industry", "title", "title_context", "salary", "additional_compensation", "currency", "other_currency", "salary_context", "country", "state", "city", "total_yoe", "field_yoe", "highest_education_completed", "gender", "race"]
# thank you 🙌
df_salary.columns = c_names
df_salary

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28057,7/12/2024 22:52:01,35-44,Health care,Veterinarian,NaN,135000,NaN,USD,NaN,NaN,United States,Missouri,Wentzville,11 - 20 years,11 - 20 years,"Professional degree (MD, JD, etc.)",Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28059,7/24/2024 12:22:58,18-24,"Accounting, Banking & Finance",Risk Management Associate,NaN,1200,0.0,USD,NaN,NaN,Myanmar,Colorado,Yangon,2 - 4 years,2 - 4 years,Some college,Man,Asian or Asian American
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American
28061,8/20/2024 1:06:13,25-34,Health care,Clinical physiologist,NaN,1200000,NaN,Other,NGN,NaN,Nigeria,NaN,Lagos,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [17]:
# List the unique industries and a count of their instances.
unique_names = df_salary["industry"].value_counts()  
#unique_names.loc["Computing or Tech"]
unique_names

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new dataframe.

In [204]:
# Filtery filter. (Save it to a new variable, df_salary_tech.)

df_tech = df_salary[df_salary["industry"] == "Computing or Tech"]
df_tech

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28050,7/1/2024 13:38:46,25-34,Computing or Tech,Research & Systems Technician Data Analytics,NaN,22000,NaN,EUR,NaN,NaN,Spain,NaN,Barcelona,2 - 4 years,2 - 4 years,College degree,Man,"Hispanic, Latino, or Spanish origin"
28051,7/1/2024 20:05:58,25-34,Computing or Tech,Junior data analyst,NaN,35000,15000.0,USD,NaN,NaN,Usa,Alabama,Alabama,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American
28052,7/3/2024 14:02:01,25-34,Computing or Tech,Senior Global Public Relations Manager,NaN,144000,15000.0,USD,NaN,NaN,Usa,Massachusetts,Boise-but remote. Company located in Boston,8 - 10 years,8 - 10 years,Master's degree,Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American

Do a sanity check to make sure that the only values you kept are the one you are filtered for.

In [205]:
# Sanity Check 
df_tech #?

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28050,7/1/2024 13:38:46,25-34,Computing or Tech,Research & Systems Technician Data Analytics,NaN,22000,NaN,EUR,NaN,NaN,Spain,NaN,Barcelona,2 - 4 years,2 - 4 years,College degree,Man,"Hispanic, Latino, or Spanish origin"
28051,7/1/2024 20:05:58,25-34,Computing or Tech,Junior data analyst,NaN,35000,15000.0,USD,NaN,NaN,Usa,Alabama,Alabama,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American
28052,7/3/2024 14:02:01,25-34,Computing or Tech,Senior Global Public Relations Manager,NaN,144000,15000.0,USD,NaN,NaN,Usa,Massachusetts,Boise-but remote. Company located in Boston,8 - 10 years,8 - 10 years,Master's degree,Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [206]:
# Filtery filter for just the jobs that pay in USD!
us_salary = df_tech[df_tech['currency']=='USD']
us_salary

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,USA,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28044,6/3/2024 16:15:43,18-24,Computing or Tech,Research Data Analyst Associate,NaN,60000,0.0,USD,NaN,NaN,United States,Illinois,Evanston,2 - 4 years,1 year or less,College degree,Woman,White
28051,7/1/2024 20:05:58,25-34,Computing or Tech,Junior data analyst,NaN,35000,15000.0,USD,NaN,NaN,Usa,Alabama,Alabama,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American
28052,7/3/2024 14:02:01,25-34,Computing or Tech,Senior Global Public Relations Manager,NaN,144000,15000.0,USD,NaN,NaN,Usa,Massachusetts,Boise-but remote. Company located in Boston,8 - 10 years,8 - 10 years,Master's degree,Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American

What we really want know is how each U.S. city pays in tech. What value in `country` represents the United States of America?

In [207]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.

r_us_salary = us_salary['country'].value_counts()
r_us_salary

country
United States               1576
USA                         1222
US                           412
U.S.                         108
United States of America      90
                            ...
Ghana                          1
Nigeria                        1
ss                             1
Nigeria                        1
Burma                          1
Name: count, Length: 76, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [208]:
# Replace them all with 'US'.

top_5 = r_us_salary.head(5).index #head is like top 5 of a series i guess? and index puts them in a list

us_salary.loc[us_salary['country'].isin(top_5), 'country'] = 'US' #locate in the country colomn if one of the countries has a name thats in the list replace it w "us"
us_salary['country'].value_counts()

country
US                3408
United States       68
Usa                 59
USA                 56
usa                 28
                  ...
Ghana                1
Nigeria              1
ss                   1
Nigeria              1
Burma                1
Name: count, Length: 72, dtype: int64

Have a look at the count of each unique country again now.

In [ ]:
# Count again. 
#thats the best i got
top_5 = r_us_salary.head(5).index.str.upper().str.replace(" ","").str.replace(".","")

us_salary.loc[us_salary['country'].str.upper().str.replace(" ","").str.replace(".","").isin(top_5), 'country'] = 'US'
print(us_salary['country'].value_counts())
top_5

country
US                         3712
Israel                        5
Canada                        4
United State of America       2
Unite States                  2
Australia                     2
India                         2
Spain                         2
Brazil                        2
United Kingdom                2
New Zealand                   2
Poland                        2
France                        2
Uniyed states                 1
America                       1
Puerto Rico                   1
United State                  1
Cuba                          1
Danmark                       1
Italy                         1
International                 1
United Stated                 1
Remote (philippines)          1
Singapore                     1
Uruguay                       1
Mexico                        1
Canada                        1
United Stateds                1
ISA                           1
singapore                     1
Pakistan                      1
Netherlands                   1
China                         1
San Francisco                 1
Romania                       1
Japan                         1
United Stares                 1
Australian                    1
Denmark                       1
Jamaica                       1
Unites States                 1
Thailand                      1
Colombia                      1
denmark                       1
Ghana                         1
Nigeria                       1
ss                            1
Nigeria                       1
Burma                         1
Name: count, dtype: int64

Index(['UNITEDSTATES', 'USA', 'US', 'US', 'UNITEDSTATESOFAMERICA'], dtype='str', name='country')

Did you notice anything interesting?

In [210]:
# BONUS CREDIT: resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [211]:

# BONUS CREDIT: if you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [235]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
mi = us_salary['salary'].min()
ma = us_salary['salary'].max()
me = us_salary['salary'].mean()

TypeError: Cannot perform reduction 'mean' with string dtype

Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed.

In [ ]:
# Fix it.
us_salary['salary'] = pd.to_numeric(us_salary['salary'], errors='coerce')
us_salary['salary'].dropna()

8999          1.0
11900        55.0
15238         0.0
15885       240.0
18140        72.0
           ...
28044     60000.0
28051     35000.0
28052    144000.0
28058    109000.0
28060      1700.0
Name: salary, Length: 1038, dtype: float64

Let’s try that again.

In [ ]:
# Try it again. Yeah!
mi = us_salary['salary'].min()
ma = us_salary['salary'].max()
me = us_salary['salary'].mean()

print(f"min: {mi} avg: {me} max: {ma}")

min: 0.0 avg: 127733.75722543352 max: 2600000.0

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [250]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.

us_salary_filtered = us_salary.loc[us_salary['timestamp'].str.contains("2021|2022|2023")]
us_salary_filtered

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,NaN,10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,NaN,5000.0,USD,NaN,NaN,US,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,NaN,20000.0,USD,NaN,"Around 20,000 a year in stock",US,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,NaN,2500.0,USD,NaN,NaN,US,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,NaN,40000.0,USD,NaN,NaN,US,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27960,5/9/2023 17:57:30,45-54,Computing or Tech,Junior Data Analyst,NaN,65000.0,0.0,USD,NaN,NaN,US,Virginia,Richmond,21 - 30 years,1 year or less,College degree,Man,White
27961,5/28/2023 16:10:53,45-54,Computing or Tech,Data Analyst,NaN,65000.0,0.0,USD,NaN,NaN,US,New York,Bronx,21 - 30 years,8 - 10 years,College degree,Man,Black or African American
27971,8/8/2023 7:12:10,25-34,Computing or Tech,Data scientist,NaN,500.0,NaN,USD,NaN,NaN,Ghana,NaN,Accra,2 - 4 years,2 - 4 years,College degree,Man,Black or African American
27975,9/8/2023 12:35:45,18-24,Computing or Tech,intern,NaN,35000.0,0.0,USD,NaN,NaN,US,Texas,Dallas,1 year or less,1 year or less,Master's degree,Man,Asian or Asian American
27989,10/26/2023 8:17:05,18-24,Computing or Tech,Ibterb,NaN,456.0,NaN,USD,NaN,NaN,Nigeria,NaN,Lagos,2 - 4 years,2 - 4 years,College degree,Man,Another option not listed here or prefer not t...

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)