# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

In [3]:
# Load the Food choices data set into a variable (e.g., df_food).

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [4]:
# Count by hand. (lol kidding)
df_food.shape

(125, 61)

What are the columns and their types in this data set?

In [5]:
# Show the column names and their types.
df_food.dtypes

GPA                     str
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports             str
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight                  str
Length: 61, dtype: object

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns?

In [6]:
# Remove ‘em.
rm_df_food=df_food[['calories_day','weight','Gender']]
rm_df_food.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

What about `NaN`s? How many are there?

In [7]:
# Count ‘em.
count_nan=rm_df_food.isna().sum()
print(count_nan)

calories_day    19
weight           2
Gender           0
dtype: int64

We gotta remove those `NaN`s―the entire row.

In [8]:
# Drop ‘em.
no_nan_df=rm_df_food.dropna()
no_nan_df.head()

   calories_day                    weight  Gender
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1
5           3.0                       190       1

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [9]:
# Fix that.
no_nan_df['weight']=pd.to_numeric(no_nan_df['weight'],errors='coerce')
no_nan_df=no_nan_df.dropna()
no_nan_df.head()

   calories_day  weight  Gender
1           3.0   155.0       1
4           2.0   190.0       1
5           3.0   190.0       1
6           3.0   180.0       2
7           3.0   137.0       1

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [10]:
# Savey save!
no_nan_df.to_csv('food_coded_cleaned.csv', index=False)

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

In [12]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set into a variable (e.g., df_salary).
df_salary_path=('../data/manager_salary_survey.tsv')

df_salary=pd.read_csv(df_salary_path,sep='\t')

Was that hard? 🙃

#### rename the file to something that is better for all systems.  
* No spaces in filename (can use '_')
* all lower case

### Explore

You know the drill.

How much data did you just load?

In [13]:
# Count by hand. I’m dead serious.
df_salary.shape

(28062, 18)

What are the columns and their types?

In [14]:
# Show the column names and their types.
df_salary.dtypes

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [15]:
# Rename ‘em.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race
df_salary.columns=[
    'timestamp', 'age','industry','title','title_context','salary','additional_compensation','currency','other_currency','salary_context','country','state','city','total_yoe',
    'field_yoe','highest_education','gender','race',
]

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [16]:
# List the unique industries and a count of their instances.
df_salary['industry'].value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new dataframe.

In [17]:
# Filtery filter. (Save it to a new variable, df_salary_tech.)
df_salary_tech=df_salary[df_salary['industry']=='Computing or Tech']

Do a sanity check to make sure that the only values you kept are the one you are filtered for.

In [18]:
# Sanity Check 
df_salary_tech.head

<bound method NDFrame.head of                 timestamp    age           industry  \
1      4/27/2021 11:02:22  25-34  Computing or Tech
8      4/27/2021 11:03:01  45-54  Computing or Tech
43     4/27/2021 11:04:04  25-34  Computing or Tech
44     4/27/2021 11:04:04  25-34  Computing or Tech
46     4/27/2021 11:04:07  35-44  Computing or Tech
...                   ...    ...                ...
28050   7/1/2024 13:38:46  25-34  Computing or Tech
28051   7/1/2024 20:05:58  25-34  Computing or Tech
28052   7/3/2024 14:02:01  25-34  Computing or Tech
28058  7/23/2024 17:51:03  25-34  Computing or Tech
28060  7/26/2024 11:20:45  18-24  Computing or Tech

                                              title  \
1          Change & Internal Communications Manager
8                                   Systems Analyst
43                      Principal Software Engineer
44                             Intelligence Analyst
46                                 Mobile developer
...                                             ...
28050  Research & Systems Technician Data Analytics
28051                          Junior data analyst
28052        Senior Global Public Relations Manager
28058                             Systems Architect
28060                                            IT

                      title_context   salary  additional_compensation  \
1                               NaN   54,600                   4000.0
8      Data developer/ETL Developer  112,000                  10000.0
43                              NaN  187,500                   5000.0
44                              NaN  110,000                  20000.0
46                              NaN  144,600                   2500.0
...                             ...      ...                      ...
28050                           NaN    22000                      NaN
28051                           NaN    35000                  15000.0
28052                           NaN   144000                  15000.0
28058                           NaN   109000                      NaN
28060                           NaN     1700                     10.0

      currency other_currency                 salary_context         country  \
1          GBP            NaN                            NaN  United Kingdom
8          USD            NaN                            NaN              US
43         USD            NaN                            NaN   United States
44         USD            NaN  Around 20,000 a year in stock             USA
46         USD            NaN                            NaN             USA
...        ...            ...                            ...             ...
28050      EUR            NaN                            NaN           Spain
28051      USD            NaN                            NaN             Usa
28052      USD            NaN                            NaN             Usa
28058      USD            NaN                            NaN             USA
28060      USD            NaN                            NaN           Burma

               state                                          city  \
1                NaN                                     Cambridge
8           Missouri                                     St. Louis
43      Pennsylvania                                    Pittsburgh
44          Virginia                                 Arlington, VA
46     Massachusetts                                        Boston
...              ...                                           ...
28050            NaN                                     Barcelona
28051        Alabama                                      Alabama
28052  Massachusetts  Boise-but remote. Company located in Boston
28058        Georgia                                       Atlanta
28060            NaN                                        Yangon

           total_yoe       field_yoe highest_education      gender  \
1       8 - 10 years       5-7 years    College degree  Non-binary
8      21 - 30 years   21 - 30 years    College degree       Woman
43      8 - 10 years       5-7 years    College degree       Woman
44      8 - 10 years    8 - 10 years   Master's degree         Man
46         5-7 years       5-7 years               PhD       Woman
...              ...             ...               ...         ...
28050    2 - 4 years     2 - 4 years    College degree         Man
28051    2 - 4 years     2 - 4 years    College degree       Woman
28052   8 - 10 years    8 - 10 years   Master's degree       Woman
28058      5-7 years       5-7 years    College degree         Man
28060    2 - 4 years  1 year or less      Some college         Man

                                      race
1                                    White
8                                    White
43                                   White
44                                   White
46                                   White
...                                    ...
28050  Hispanic, Latino, or Spanish origin
28051            Black or African American
28052                                White
28058                                White
28060              Asian or Asian American

[4699 rows x 18 columns]>

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [19]:
# Filtery filter for just the jobs that pay in USD!
df_salary_usd=df_salary[df_salary['currency']=='USD']
df_salary_usd.head

<bound method NDFrame.head of                 timestamp    age                       industry  \
0      4/27/2021 11:02:10  25-34   Education (Higher Education)
2      4/27/2021 11:02:38  25-34  Accounting, Banking & Finance
3      4/27/2021 11:02:41  25-34                     Nonprofits
4      4/27/2021 11:02:42  25-34  Accounting, Banking & Finance
5      4/27/2021 11:02:46  25-34   Education (Higher Education)
...                   ...    ...                            ...
28052   7/3/2024 14:02:01  25-34              Computing or Tech
28057  7/12/2024 22:52:01  35-44                    Health care
28058  7/23/2024 17:51:03  25-34              Computing or Tech
28059  7/24/2024 12:22:58  18-24  Accounting, Banking & Finance
28060  7/26/2024 11:20:45  18-24              Computing or Tech

                                        title title_context  salary  \
0          Research and Instruction Librarian           NaN  55,000
2                        Marketing Specialist           NaN  34,000
3                             Program Manager           NaN  62,000
4                          Accounting Manager           NaN  60,000
5              Scholarly Publishing Librarian           NaN  62,000
...                                       ...           ...     ...
28052  Senior Global Public Relations Manager           NaN  144000
28057                            Veterinarian           NaN  135000
28058                       Systems Architect           NaN  109000
28059               Risk Management Associate           NaN    1200
28060                                      IT           NaN    1700

       additional_compensation currency other_currency salary_context  \
0                          0.0      USD            NaN            NaN
2                          NaN      USD            NaN            NaN
3                       3000.0      USD            NaN            NaN
4                       7000.0      USD            NaN            NaN
5                          NaN      USD            NaN            NaN
...                        ...      ...            ...            ...
28052                  15000.0      USD            NaN            NaN
28057                      NaN      USD            NaN            NaN
28058                      NaN      USD            NaN            NaN
28059                      0.0      USD            NaN            NaN
28060                     10.0      USD            NaN            NaN

              country           state  \
0       United States   Massachusetts
2                  US       Tennessee
3                 USA       Wisconsin
4                  US  South Carolina
5                 USA   New Hampshire
...               ...             ...
28052             Usa   Massachusetts
28057  United States         Missouri
28058             USA         Georgia
28059         Myanmar        Colorado
28060           Burma             NaN

                                               city      total_yoe  \
0                                            Boston      5-7 years
2                                       Chattanooga    2 - 4 years
3                                         Milwaukee   8 - 10 years
4                                        Greenville   8 - 10 years
5                                           Hanover   8 - 10 years
...                                             ...            ...
28052  Boise-but remote. Company located in Boston    8 - 10 years
28057                                   Wentzville   11 - 20 years
28058                                       Atlanta      5-7 years
28059                                        Yangon    2 - 4 years
28060                                        Yangon    2 - 4 years

            field_yoe                   highest_education gender  \
0           5-7 years                     Master's degree  Woman
2         2 - 4 years                      College degree  Woman
3           5-7 years                      College degree  Woman
4           5-7 years                      College degree  Woman
5         2 - 4 years                     Master's degree    Man
...               ...                                 ...    ...
28052    8 - 10 years                     Master's degree  Woman
28057   11 - 20 years  Professional degree (MD, JD, etc.)  Woman
28058       5-7 years                      College degree    Man
28059     2 - 4 years                        Some college    Man
28060  1 year or less                        Some college    Man

                          race
0                        White
2                        White
3                        White
4                        White
5                        White
...                        ...
28052                    White
28057                    White
28058                    White
28059  Asian or Asian American
28060  Asian or Asian American

[23374 rows x 18 columns]>

What we really want know is how each U.S. city pays in tech. What value in `country` represents the United States of America?

In [20]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary_usd['country'].value_counts()

country
United States     8989
USA               7922
US                2606
United States      667
U.S.               580
                  ...
Saudi Arabia         1
LOUTRELAND           1
philippines          1
Myanmar              1
Burma                1
Name: count, Length: 229, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [21]:
# Replace them all with 'US'.
df_salary_usd['country']=df_salary_usd['country'].replace(['USA', 'U.S.','Usa','United States of America','United states','usa','united states','Us','U.S.A.',
                                                           'United States','us', 'U.S', 'America','United States of America ','US ','U.S>','U.S. ','ISA','United States ',
                                                           'United states ', 'united states of america','United State','U.S.A','USA ','The United States','Unites States','United Stated','Usa ',
                                                           'UNITED STATES','u.s.','united States'], 'US')

Have a look at the count of each unique country again now.

In [22]:
# Count again.
df_salary_usd['country'].value_counts()

country
US                23028
Canada               16
Australia             8
United Kingdom        7
Israel                7
                  ...
Saudi Arabia          1
LOUTRELAND            1
philippines           1
Myanmar               1
Burma                 1
Name: count, Length: 198, dtype: int64

Did you notice anything interesting?

In [23]:
# BONUS CREDIT: resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [24]:

# BONUS CREDIT: if you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [25]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.

#df_salary_usd.groupby('state')['salary'].agg(['min','mean','max'])

Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed.

In [26]:
# Fix it.
df_salary_usd['salary']=pd.to_numeric(df_salary_usd['salary'], errors='coerce')

Let’s try that again.

In [27]:
# Try it again. Yeah!
df_salary_usd.groupby('state')['salary'].agg(['min','mean','max'])

                                   min          mean        max
state
Alabama                            0.0  65524.911111   350000.0
Alabama, Alaska, Arizona          15.0     15.000000       15.0
Alabama, California            29120.0  29120.000000    29120.0
Alabama, District of Columbia      NaN           NaN        NaN
Alabama, Kansas                    NaN           NaN        NaN
...                                ...           ...        ...
Virginia                          57.0  96247.442922  1300000.0
Washington                        72.0  98032.896552   300000.0
West Virginia                      0.0  52754.375000   120000.0
Wisconsin                          1.0  83000.628788   920000.0
Wyoming                        42500.0  59906.333333    98000.0

[133 rows x 3 columns]

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [28]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_salary_usd['timestamp']=pd.to_datetime(df_salary_usd['timestamp'])
df_salary_usd_some=df_salary_usd[df_salary_usd['timestamp'].dt.year.isin([2021,2022])]

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)