# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [99]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in /home/nothing/ds-fall-2026/.venv/lib/python3.12/site-packages (3.0.5)
Requirement already satisfied: numpy in /home/nothing/ds-fall-2026/.venv/lib/python3.12/site-packages (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/nothing/ds-fall-2026/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/nothing/ds-fall-2026/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [100]:
# Import here.

import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [101]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [102]:
# Count by hand. (lol kidding)

len(df_food)

125

In [103]:
# Try to print or display it nicely.

df_food

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,...,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,...,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,...,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,...,1.0,2.0,2,725.0,345,NaN,4,2,575,135

What are the columns and their types in this data set?

In [104]:
# Show the column names and their types.

df_food.dtypes

GPA                                 str
Gender                            int64
breakfast                         int64
calories_chicken                  int64
calories_day                    float64
calories_scone                  float64
coffee                            int64
comfort_food                        str
comfort_food_reasons                str
comfort_food_reasons_coded      float64
cook                            float64
comfort_food_reasons_coded.1      int64
cuisine                         float64
diet_current                        str
diet_current_coded                int64
drink                           float64
eating_changes                      str
eating_changes_coded              int64
eating_changes_coded1             int64
eating_out                        int64
employment                      float64
ethnic_food                       int64
exercise                        float64
father_education                float64
father_profession                   str
fav_cuisine                         str
fav_cuisine_coded                 int64
fav_food                        float64
food_childhood                      str
fries                             int64
fruit_day                         int64
grade_level                       int64
greek_food                        int64
healthy_feeling                   int64
healthy_meal                        str
ideal_diet                          str
ideal_diet_coded                  int64
income                          float64
indian_food                       int64
italian_food                      int64
life_rewarding                  float64
marital_status                  float64
meals_dinner_friend                 str
mother_education                float64
mother_profession                   str
nutritional_check                 int64
on_off_campus                   float64
parents_cook                      int64
pay_meal_out                      int64
persian_food                    float64
self_perception_weight          float64
soup                            float64
sports                          float64
thai_food                         int64
tortilla_calories               float64
turkey_calories                   int64
type_sports                         str
veggies_day                       int64
vitamins                          int64
waffle_calories                   int64
weight                              str
dtype: object

In [105]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.

df_food.dtypes.to_frame(name='dtype')

                                dtype
GPA                               str
Gender                          int64
breakfast                       int64
calories_chicken                int64
calories_day                  float64
calories_scone                float64
coffee                          int64
comfort_food                      str
comfort_food_reasons              str
comfort_food_reasons_coded    float64
cook                          float64
comfort_food_reasons_coded.1    int64
cuisine                       float64
diet_current                      str
diet_current_coded              int64
drink                         float64
eating_changes                    str
eating_changes_coded            int64
eating_changes_coded1           int64
eating_out                      int64
employment                    float64
ethnic_food                     int64
exercise                      float64
father_education              float64
father_profession                 str
fav_cuisine                       str
fav_cuisine_coded               int64
fav_food                      float64
food_childhood                    str
fries                           int64
fruit_day                       int64
grade_level                     int64
greek_food                      int64
healthy_feeling                 int64
healthy_meal                      str
ideal_diet                        str
ideal_diet_coded                int64
income                        float64
indian_food                     int64
italian_food                    int64
life_rewarding                float64
marital_status                float64
meals_dinner_friend               str
mother_education              float64
mother_profession                 str
nutritional_check               int64
on_off_campus                 float64
parents_cook                    int64
pay_meal_out                    int64
persian_food                  float64
self_perception_weight        float64
soup                          float64
sports                        float64
thai_food                       int64
tortilla_calories             float64
turkey_calories                 int64
type_sports                       str
veggies_day                     int64
vitamins                        int64
waffle_calories                 int64
weight                            str

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [106]:
# Remove ‘em.
df_food_col_subset = df_food[['calories_day', 'weight', 'Gender']]

In [107]:
# Is there a second way to remove columns?

cols_to_drop = [c for c in df_food.columns if c not in ('calories_day', 'weight', 'Gender')]
df_food_col_subset = df_food.drop(columns=cols_to_drop)

In [108]:
# 🚀 Extra credit: What about a third way to remove columns?

df_food_col_subset = df_food.loc[:, ['calories_day', 'weight', 'Gender']]

What about `NaN`s? How many are there?

In [109]:
# Count ‘em.

df_food_col_subset.isna().sum()

calories_day    19
weight           2
Gender           0
dtype: int64

In [110]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.

df_food_col_subset.isna().sum().to_frame(name='nan_count')

              nan_count
calories_day         19
weight                2
Gender                0

In [111]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

df_food_col_subset \
    .isna() \
    .sum() \
    .to_frame(name='nan_count')

              nan_count
calories_day         19
weight                2
Gender                0

We gotta remove those `NaN`s―the entire row.

In [112]:
# Drop ‘em in-place.

df_food_col_subset.dropna(inplace=True)

In [113]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂

df_food.isna().sum()

# df_food still has its original NaNs -- df_food_col_subset was created with a column
# selection (a copy), so dropping rows on it in-place did not touch df_food.

GPA                              2
Gender                           0
breakfast                        0
calories_chicken                 0
calories_day                    19
calories_scone                   1
coffee                           0
comfort_food                     1
comfort_food_reasons             2
comfort_food_reasons_coded      19
cook                             3
comfort_food_reasons_coded.1     0
cuisine                         17
diet_current                     1
diet_current_coded               0
drink                            2
eating_changes                   3
eating_changes_coded             0
eating_changes_coded1            0
eating_out                       0
employment                       9
ethnic_food                      0
exercise                        13
father_education                 1
father_profession                3
fav_cuisine                      2
fav_cuisine_coded                0
fav_food                         2
food_childhood                   1
fries                            0
fruit_day                        0
grade_level                      0
greek_food                       0
healthy_feeling                  0
healthy_meal                     1
ideal_diet                       1
ideal_diet_coded                 0
income                           1
indian_food                      0
italian_food                     0
life_rewarding                   1
marital_status                   1
meals_dinner_friend              3
mother_education                 3
mother_profession                2
nutritional_check                0
on_off_campus                    1
parents_cook                     0
pay_meal_out                     0
persian_food                     1
self_perception_weight           1
soup                             1
sports                           2
thai_food                        0
tortilla_calories                1
turkey_calories                  0
type_sports                     26
veggies_day                      0
vitamins                         0
waffle_calories                  0
weight                           2
dtype: int64

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [114]:
# Fix that in-place.

df_food_col_subset['weight'] = pd.to_numeric(df_food_col_subset['weight'], errors='coerce')
df_food_col_subset.dropna(subset=['weight'], inplace=True)

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [115]:
# Savey save!

df_food_col_subset.to_csv('../data/food_coded_cleaned.csv', index=False)

In [116]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.

with open('../data/food_coded_cleaned.csv') as f:
    for _ in range(5):
        print(f.readline().rstrip())

calories_day,weight,Gender
3.0,155.0,1
2.0,190.0,1
3.0,190.0,1
3.0,180.0,2

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [117]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.

salary_data_set_path = "../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv"

df_salary = pd.read_csv(salary_data_set_path, sep='\t')

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [118]:
# Count by hand. I’m dead serious.

len(df_salary)

28062

What are the columns and their types?

In [119]:
# Show the column names and their types.

df_salary.dtypes

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [120]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race

df_salary.columns = [
    'timestamp', 'age', 'industry', 'title', 'title_context', 'salary',
    'additional_compensation', 'currency', 'other_currency', 'salary_context',
    'country', 'state', 'city', 'total_yoe', 'field_yoe',
    'highest_education_completed', 'gender', 'race',
]

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [121]:
# List the unique industries and a count of their instances.

df_salary['industry'].value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [122]:
# Filtery filter.

df_salary_tech = df_salary[df_salary['industry'] == 'Computing or Tech']

Do a sanity check by counting.

In [123]:
# Sanity check count.

len(df_salary_tech)

4699

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [124]:
# Filtery filter (in place) for just the jobs that pay in USD!

df_salary_tech = df_salary_tech[df_salary_tech['currency'] == 'USD'].copy()

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [125]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.

df_salary_tech['country'].value_counts()

country
United States                1576
USA                          1222
US                            412
U.S.                          108
United States of America       90
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [126]:
# Replace them all in-place with 'US'.

top5_us_values = ['United States', 'USA', 'US', 'U.S.', 'United States of America']
df_salary_tech['country'] = df_salary_tech['country'].replace(top5_us_values, 'US')

Have a look at the count of each unique country again now.

In [127]:
# Count again.

df_salary_tech['country'].value_counts()

country
US                           3408
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

Did you notice anything interesting?

In [128]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

# Catch stray whitespace/case/typo variants of "US"/"USA"/"United States (of America)"
# with one regex instead of blacklisting every misspelling individually.
us_pattern = r'^u\.?s\.?a?\.?$|^unite[d]?\s*states?(\s*of\s*america)?$'
looks_like_us = (
    df_salary_tech['country']
    .astype('string')
    .str.strip()
    .str.lower()
    .str.match(us_pattern, na=False)
)
df_salary_tech.loc[looks_like_us, 'country'] = 'US'

In [129]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

df_salary_tech['country'].value_counts()

country
US                      3717
Israel                     5
Canada                     4
Australia                  2
India                      2
Spain                      2
Brazil                     2
United Kingdom             2
New Zealand                2
Poland                     2
France                     2
Uniyed states              1
America                    1
Puerto Rico                1
Cuba                       1
Danmark                    1
Italy                      1
International              1
United Stated              1
Remote (philippines)       1
Singapore                  1
Uruguay                    1
Mexico                     1
Canada                     1
United Stateds             1
ISA                        1
singapore                  1
Pakistan                   1
Netherlands                1
China                      1
San Francisco              1
Romania                    1
Japan                      1
United Stares              1
Australian                 1
Denmark                    1
Jamaica                    1
Unites States              1
Thailand                   1
Colombia                   1
denmark                    1
Ghana                      1
Nigeria                    1
ss                         1
Nigeria                    1
Burma                      1
Name: count, dtype: int64

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [130]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.

df_salary_tech.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

TypeError: dtype 'str' does not support operation 'mean'

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [131]:
# Fix it in-place.

df_salary_tech['salary'] = pd.to_numeric(
    df_salary_tech['salary'].astype(str).str.replace(',', '', regex=False),
    errors='coerce',
)

Let’s try that again.

In [132]:
# Try it again. Yeah!

df_salary_tech.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Florida                          28800  157457.232143  2600000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  154857.215478   875000
Washington                          72  151423.670588   950000
New York                         14000  148054.638968   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135213.537954  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127706.355932   450000
Colorado                         45000  127240.006849   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119268.242604   315000
Georgia                          29120  117893.098765   250000
Maryland                         51260  117862.370370   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114268.000000   920000
Texas                            10700  113909.713004   280000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  106752.793103   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
North Carolina                   29000  105035.441441   260000
New York, Texas                 105000  105000.000000   105000
Massachusetts, New Hampshire    105000  105000.000000   105000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
South Carolina                   40000  102111.111111   205000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   96855.363636   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
New Hampshire                       55   95179.705882   193000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
Alabama                          29120   92510.000000   350000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Louisiana                        35360   83269.090909   150000
Massachusetts, Pennsylvania      83000   83000.000000    83000
California, Maryland             81500   81500.000000    81500
Arkansas                             4   74257.000000   144000
Alabama, Montana                 72000   72000.000000    72000

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [133]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.

df_salary_tech['timestamp'] = pd.to_datetime(df_salary_tech['timestamp'], errors='coerce')

df_salary_tech_recent = df_salary_tech[df_salary_tech['timestamp'].dt.year.isin([2021, 2022, 2023])]

df_salary_tech_recent.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  154986.177812   875000
Washington                          72  151571.970501   950000
New York                         14000  148054.638968   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135184.443709  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127706.355932   450000
Colorado                         45000  127240.006849   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119621.029762   315000
Georgia                          29120  118004.262500   250000
Maryland                         51260  117862.370370   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114268.000000   920000
Texas                            10700  113909.713004   280000
Florida                          28800  113047.363636   400000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
South Carolina                   40000  109875.000000   205000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  107063.872093   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
New York, Texas                 105000  105000.000000   105000
Massachusetts, New Hampshire    105000  105000.000000   105000
North Carolina                   29000  104944.854545   260000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Alabama                          29120   97738.181818   350000
Michigan                         36800   96855.363636   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
New Hampshire                       55   95179.705882   193000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Louisiana                        35360   83269.090909   150000
Massachusetts, Pennsylvania      83000   83000.000000    83000
Arkansas                         55000   81682.300000   144000
California, Maryland             81500   81500.000000    81500
Alabama, Montana                 72000   72000.000000    72000

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

In [134]:
# Bonus #0: Apply the same cleaning steps to df_salary, but without filtering by industry.

df_salary_all = df_salary[df_salary['currency'] == 'USD'].copy()

top5_us_values = ['United States', 'USA', 'US', 'U.S.', 'United States of America']
df_salary_all['country'] = df_salary_all['country'].replace(top5_us_values, 'US')

us_pattern = r'^u\.?s\.?a?\.?$|^unite[d]?\s*states?(\s*of\s*america)?$'
looks_like_us = (
    df_salary_all['country']
    .astype('string')
    .str.strip()
    .str.lower()
    .str.match(us_pattern, na=False)
)
df_salary_all.loc[looks_like_us, 'country'] = 'US'
df_salary_all = df_salary_all[df_salary_all['country'] == 'US']

df_salary_all['salary'] = pd.to_numeric(
    df_salary_all['salary'].astype(str).str.replace(',', '', regex=False),
    errors='coerce',
)

salary_by_state_all = (
    df_salary_all.groupby('state')['salary']
    .agg(['min', 'mean', 'max'])
    .sort_values('mean', ascending=False)
)
salary_by_state_all

,min,mean,max
state,,,
"Michigan, Texas, Washington",340000,340000.000000,340000
"Indiana, Ohio",245000,245000.000000,245000
Alaska,27040,232275.078125,10000000
"Colorado, Nevada",190000,190000.000000,190000
"California, Montana",185000,185000.000000,185000
...,...,...,...
"Delaware, Pennsylvania",35000,35000.000000,35000
"District of Columbia, Washington",35000,35000.000000,35000
"Alabama, California",29120,29120.000000,29120
"District of Columbia, Maryland, Pennsylvania, Virginia",27040,27040.000000,27040
"Maryland, New York",14000,14000.000000,14000

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

In [135]:
# Bonus #1: Format the table nicely without modifying the underlying DataFrame values.

salary_by_state_all.style.format({
    'min': '${:,.2f}',
    'mean': '${:,.2f}',
    'max': '${:,.2f}',
})

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

In [136]:
# Bonus #2: Filter out multi-state entries (e.g., 'California, Colorado') elegantly.

df_salary_all_single_state = df_salary_all[~df_salary_all['state'].str.contains(',', na=False)]
df_salary_all_single_state['state'].unique()

<StringArray>
[       'Massachusetts',            'Tennessee',            'Wisconsin',
       'South Carolina',        'New Hampshire',              'Arizona',
             'Missouri',              'Florida',                    nan,
         'Pennsylvania',             'Michigan',            'Minnesota',
             'Illinois',           'California',              'Georgia',
                 'Ohio', 'District of Columbia',             'Maryland',
                'Texas',             'Virginia',       'North Carolina',
             'New York',           'New Jersey',         'Rhode Island',
             'Colorado',               'Oregon',           'Washington',
              'Indiana',                 'Iowa',             'Nebraska',
             'Oklahoma',                'Maine',          'Connecticut',
         'South Dakota',        'West Virginia',                'Idaho',
            'Louisiana',              'Montana',             'Kentucky',
         'North Dakota',               'Kansas',              'Vermont',
             'Arkansas',              'Alabama',               'Nevada',
             'Delaware',           'New Mexico',               'Hawaii',
                 'Utah',          'Mississippi',               'Alaska',
              'Wyoming']
Length: 52, dtype: str

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)

In [137]:
# Bonus #3: Show quantiles (plus a count) by state instead of just min/mean/max.

quantiles = [0, 0.05, 0.25, 0.5, 0.75, 0.95, 1.0]

salary_quantiles_by_state = (
    df_salary_all_single_state
    .groupby('state')['salary']
    .quantile(quantiles)
    .unstack()
)
salary_quantiles_by_state.columns = [f'{int(q * 100)}%' for q in quantiles]

salary_quantiles_by_state['count'] = df_salary_all_single_state.groupby('state')['salary'].count()

salary_quantiles_by_state.sort_values('50%', ascending=False)

,0%,5%,25%,50%,75%,95%,100%,count
state,,,,,,,,
California,0.0,42000.00,72000.00,100440.0,147000.00,220000.00,875000.0,2587
Washington,72.0,40000.00,65000.00,91000.0,135000.00,200600.00,1260000.0,1177
District of Columbia,40.0,48000.00,66500.00,90000.0,125000.00,189600.00,1334782.0,969
New York,80.0,40916.00,64527.50,90000.0,127000.00,210000.00,3000000.0,2167
Massachusetts,155.0,42000.00,64000.00,86000.0,120000.00,180700.00,1650000.0,1514
Maryland,0.0,40000.00,60000.00,82000.0,110000.00,165000.00,353200.0,561
Connecticut,0.0,33787.50,61750.00,81900.0,100000.00,162500.00,1900000.0,236
Delaware,35000.0,41704.00,58869.75,81322.5,105750.00,164247.50,220000.0,46
Virginia,57.0,37380.00,58750.00,80616.5,115000.00,180000.00,1300000.0,780
Oregon,0.0,36340.00,59125.00,78000.0,110000.00,185000.00,320000.0,618
Colorado,65.0,38888.00,58000.00,76000.0,111000.00,165300.00,630000.0,629
Illinois,0.0,37452.00,56000.00,76000.0,110000.00,171600.00,1100000.0,1205
Texas,0.0,35139.60,55000.00,76000.0,110000.00,175000.00,1200000.0,1255
Minnesota,40.0,39520.00,55000.00,75000.0,100000.00,150000.00,321250.0,714
Georgia,0.0,32000.00,53000.00,75000.0,105000.00,173800.00,860000.0,533
New Jersey,14850.0,35776.00,58000.00,75000.0,104750.00,177920.00,5000044.0,394
North Carolina,4000.0,34491.00,51000.00,73500.0,98000.00,150000.00,560000.0,600
Utah,18720.0,33796.00,54175.00,72807.0,100500.00,175700.00,576000.0,207
Alaska,27040.0,40000.00,56500.00,72400.0,90500.00,144550.00,10000000.0,64
Rhode Island,18000.0,35950.00,51250.00,71500.0,93875.00,134250.00,200000.0,76
Pennsylvania,0.0,33135.00,52000.00,70584.0,100400.00,165200.00,1100000.0,939
Nevada,55.0,33753.10,51500.00,70500.0,95100.00,167250.00,425000.0,92
New Mexico,78.0,33892.00,52000.00,69000.0,107000.00,166800.00,300000.0,98
Michigan,55.0,31985.00,52455.00,68000.0,91000.00,148075.00,500000.0,540
Ohio,36.0,33000.00,50000.00,67000.0,88761.25,148650.00,954000.0,650
Florida,150.0,31200.00,47840.00,67000.0,97500.00,162200.00,2600000.0,517
Arizona,12000.0,34000.00,50000.00,66850.0,100000.00,155100.00,380000.0,300
Wisconsin,1.0,34000.00,50000.00,66560.0,90000.00,146400.00,920000.0,467
Missouri,70.0,30500.00,47670.00,65520.0,94250.00,145000.00,335000.0,339
Indiana,105.0,35000.00,49250.00,65000.0,84835.00,134400.00,925000.0,327
New Hampshire,55.0,30983.20,46200.00,65000.0,88875.00,142734.75,208000.0,118
Nebraska,18000.0,32947.85,45073.50,64000.0,88250.00,138250.00,224000.0,108
Tennessee,20800.0,32982.80,47450.00,63250.0,85500.00,157478.00,657900.0,280
Hawaii,12000.0,31107.00,53250.00,62850.0,75000.00,123100.00,500000.0,30
Iowa,13000.0,30000.00,47840.00,62500.0,87500.00,123087.50,200000.0,178
Louisiana,17000.0,30128.00,46650.00,62250.0,85000.00,150000.00,253300.0,128
Vermont,24960.0,33472.00,50000.00,62000.0,83000.00,124600.00,200000.0,65
Kansas,52.0,33600.00,45000.00,61000.0,81000.00,125000.00,734400.0,153
Idaho,38.0,30900.00,45940.00,60500.0,78500.00,130000.00,312000.0,96
South Dakota,29000.0,31470.00,44937.50,60175.0,69728.75,127850.00,150000.0,24
Alabama,54.0,27600.00,45600.00,60000.0,85000.00,141200.00,350000.0,117
Arkansas,26000.0,30680.00,46000.00,60000.0,85000.00,144600.00,488000.0,69
Kentucky,0.0,29000.00,43545.00,59317.5,78000.00,130000.00,208000.0,190
North Dakota,0.0,27584.00,45000.00,59000.0,75000.00,110500.00,150000.0,35
Maine,22000.0,34511.20,43000.00,58500.0,83000.00,114800.00,173000.0,125
South Carolina,0.0,29146.00,43000.00,56000.0,79000.00,128519.00,250000.0,145
Oklahoma,18000.0,27521.60,43000.00,54000.0,80000.00,142200.00,180000.0,113
Mississippi,25000.0,31080.00,36663.00,53000.0,82000.00,113600.00,130000.0,49
Wyoming,29000.0,31803.20,43250.00,50004.0,71500.00,97200.00,140000.0,23
West Virginia,0.0,27000.00,41000.00,49088.0,71400.00,117516.00,125000.0,41
Montana,19200.0,33557.20,37250.00,48000.0,83500.00,125800.00,172000.0,63