# Fall 2026 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in /workspaces/ds-fall-2026/.venv/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy in /workspaces/ds-fall-2026/.venv/lib/python3.14/site-packages (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /workspaces/ds-fall-2026/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /workspaces/ds-fall-2026/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [3]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [4]:
# Count by hand. (lol kidding)
df_food.head(5)
df_food.shape

print(df_food.describe())

           Gender   breakfast  calories_chicken  calories_day  calories_scone  \
count  125.000000  125.000000        125.000000    106.000000      124.000000
mean     1.392000    1.112000        577.320000      3.028302      505.241935
std      0.490161    0.316636        131.214156      0.639308      230.840506
min      1.000000    1.000000        265.000000      2.000000      315.000000
25%      1.000000    1.000000        430.000000      3.000000      420.000000
50%      1.000000    1.000000        610.000000      3.000000      420.000000
75%      2.000000    1.000000        720.000000      3.000000      420.000000
max      2.000000    2.000000        720.000000      4.000000      980.000000

          coffee  comfort_food_reasons_coded        cook  \
count  125.00000                  106.000000  122.000000
mean     1.75200                    2.698113    2.786885
std      0.43359                    1.972042    1.038351
min      1.00000                    1.000000    1.000000
25%      2.00000                    2.000000    2.000000
50%      2.00000                    2.000000    3.000000
75%      2.00000                    3.000000    3.000000
max      2.00000                    9.000000    5.000000

       comfort_food_reasons_coded.1     cuisine  ...  persian_food  \
count                    125.000000  108.000000  ...    124.000000
mean                       2.688000    1.388889  ...      2.806452
std                        1.910987    0.974759  ...      1.423824
min                        1.000000    1.000000  ...      1.000000
25%                        2.000000    1.000000  ...      2.000000
50%                        2.000000    1.000000  ...      3.000000
75%                        3.000000    1.000000  ...      4.000000
max                        9.000000    6.000000  ...      5.000000

       self_perception_weight        soup      sports   thai_food  \
count              124.000000  124.000000  123.000000  125.000000
mean                 3.120968    1.217742    1.390244    3.336000
std                  1.115980    0.414385    0.489800    1.436528
min                  1.000000    1.000000    1.000000    1.000000
25%                  2.000000    1.000000    1.000000    2.000000
50%                  3.000000    1.000000    1.000000    3.000000
75%                  4.000000    1.000000    2.000000    5.000000
max                  6.000000    2.000000    2.000000    5.000000

       tortilla_calories  turkey_calories  veggies_day    vitamins  \
count         124.000000       125.000000   125.000000  125.000000
mean          947.580645       555.040000     4.008000    1.512000
std           202.090179       152.370379     1.081337    0.501867
min           580.000000       345.000000     1.000000    1.000000
25%           725.000000       500.000000     3.000000    1.000000
50%           940.000000       500.000000     4.000000    2.000000
75%          1165.000000       690.000000     5.000000    2.000000
max          1165.000000       850.000000     5.000000    2.000000

       waffle_calories
count       125.000000
mean       1073.400000
std         248.667092
min         575.000000
25%         900.000000
50%         900.000000
75%        1315.000000
max        1315.000000

[8 rows x 47 columns]

In [5]:
# Try to print or display it nicely.
df_food.head(10)

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
5,2.25,1,1,610,3.0,980.0,2,"Candy, brownies and soda.","None, i don't eat comfort food. I just eat whe...",4.0,...,1.0,2.0,4,940.0,345,None.,1,2,1315,190
6,3.8,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.0,1.0,5,940.0,690,soccer,4,1,1315,180
7,3.3,1,1,720,3.0,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,...,1.0,2.0,1,725.0,500,none,4,2,1315,137
8,3.3,1,1,430,NaN,420.0,1,"Donuts, ice cream, chips",Boredom,2.0,...,2.0,2.0,5,725.0,345,none,3,2,760,180
9,3.3,1,1,430,3.0,315.0,2,"Mac and cheese, chocolate, and pasta","Stress, anger and sadness",1.0,...,1.0,1.0,4,580.0,345,field hockey,5,1,900,125

What are the columns and their types in this data set?

In [6]:
# Show the column names and their types.
print(df_food.columns.to_list())
print('\n')
print(df_food.info())

['GPA', 'Gender', 'breakfast', 'calories_chicken', 'calories_day', 'calories_scone', 'coffee', 'comfort_food', 'comfort_food_reasons', 'comfort_food_reasons_coded', 'cook', 'comfort_food_reasons_coded.1', 'cuisine', 'diet_current', 'diet_current_coded', 'drink', 'eating_changes', 'eating_changes_coded', 'eating_changes_coded1', 'eating_out', 'employment', 'ethnic_food', 'exercise', 'father_education', 'father_profession', 'fav_cuisine', 'fav_cuisine_coded', 'fav_food', 'food_childhood', 'fries', 'fruit_day', 'grade_level', 'greek_food', 'healthy_feeling', 'healthy_meal', 'ideal_diet', 'ideal_diet_coded', 'income', 'indian_food', 'italian_food', 'life_rewarding', 'marital_status', 'meals_dinner_friend', 'mother_education', 'mother_profession', 'nutritional_check', 'on_off_campus', 'parents_cook', 'pay_meal_out', 'persian_food', 'self_perception_weight', 'soup', 'sports', 'thai_food', 'tortilla_calories', 'turkey_calories', 'type_sports', 'veggies_day', 'vitamins', 'waffle_calories', 'weight']


<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    str
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    str
 8   comfort_food_reasons          123 non-null    str
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    str
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    str
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    str
 25  fav_cuisine                   123 non-null    str
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    str
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    str
 35  ideal_diet                    124 non-null    str
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    str
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    str
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     str
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    str
dtypes: float64(20), int64(27), str(14)
memory usage: 59.7 KB
None

In [7]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
df_food_column_info = df_food.info()
df_food_column_info

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    str
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    str
 8   comfort_food_reasons          123 non-null    str
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    str
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    str
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    str
 25  fav_cuisine                   123 non-null    str
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    str
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    str
 35  ideal_diet                    124 non-null    str
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    str
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    str
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     str
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    str
dtypes: float64(20), int64(27), str(14)
memory usage: 59.7 KB

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [8]:
# Remove ‘em.
df_food_col_subset = df_food[['calories_day', 'Gender', 'weight']]
df_food_col_subset

     calories_day  Gender                    weight
0             NaN       2                       187
1             3.0       1                       155
2             4.0       1  I'm not answering this.
3             3.0       1             Not sure, 240
4             2.0       1                       190
..            ...     ...                       ...
120           4.0       1                       156
121           2.0       1                       180
122           NaN       1                       120
123           4.0       2                       135
124           NaN       1                       135

[125 rows x 3 columns]

In [9]:
# Is there a second way to remove columns?
cols_to_keep = ['calories_day', 'weight', 'Gender']
cols_to_drop = [col for col in df_food.columns if col not in cols_to_keep]
df_food_col_subset = df_food.drop(columns=cols_to_drop)
df_food_col_subset

     Gender  calories_day                    weight
0         2           NaN                       187
1         1           3.0                       155
2         1           4.0  I'm not answering this.
3         1           3.0             Not sure, 240
4         1           2.0                       190
..      ...           ...                       ...
120       1           4.0                       156
121       1           2.0                       180
122       1           NaN                       120
123       2           4.0                       135
124       1           NaN                       135

[125 rows x 3 columns]

In [10]:
# 🚀 Extra credit: What about a third way to remove columns?

What about `NaN`s? How many are there?

In [11]:
# Count ‘em
df_calories_day = df_food_col_subset[['calories_day']].isnull().sum()
print(df_calories_day)
df_weight = df_food_col_subset[['weight']].isnull().sum()
print(df_weight)
df_gender = df_food_col_subset[['Gender']].isnull().sum()
print(df_gender)

calories_day    19
dtype: int64
weight    2
dtype: int64
Gender    0
dtype: int64

In [12]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.
nan_sums_df = df_food_col_subset.isna().sum()
print(nan_sums_df)

Gender           0
calories_day    19
weight           2
dtype: int64

In [13]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

We gotta remove those `NaN`s―the entire row.

In [14]:
# Drop ‘em in-place.

df_food_col_subset.dropna(inplace=True)

In [15]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂
df_food_col_subset.isna().sum()

Gender          0
calories_day    0
weight          0
dtype: int64

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [16]:
# Fix that in-place.
df_food_col_subset['weight'] = pd.to_numeric(df_food_col_subset['weight'], errors='coerce')
df_food_col_subset.dropna(inplace=True)
df_food_col_subset['weight']

1      155.0
4      190.0
5      190.0
6      180.0
7      137.0
       ...
118    140.0
119    185.0
120    156.0
121    180.0
123    135.0
Name: weight, Length: 101, dtype: float64

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [17]:
# Savey save!
saved_csv_file = df_food_col_subset.to_csv('../data/food_col_subset.csv')
saved_csv_file

In [18]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.

saved_file = pd.read_csv('../data/food_col_subset.csv')
print(saved_file)

     Unnamed: 0  Gender  calories_day  weight
0             1       1           3.0   155.0
1             4       1           2.0   190.0
2             5       1           3.0   190.0
3             6       2           3.0   180.0
4             7       1           3.0   137.0
..          ...     ...           ...     ...
96          118       1           3.0   140.0
97          119       2           3.0   185.0
98          120       1           4.0   156.0
99          121       1           2.0   180.0
100         123       2           4.0   135.0

[101 rows x 4 columns]

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [19]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.
df_salary = pd.read_csv('../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv', sep='\t')
df_salary.head(5)

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

Was that hard? 🙃

Not too hard, you had to use a delimeter to separate the spacing

### Explore

You know the drill.

How much data did you just load?

In [20]:
# Count by hand. I’m dead serious.
df_salary
print(f"Salary dimensions: {df_salary.shape}")

Salary dimensions: (28062, 18)

What are the columns and their types?

In [21]:
# Show the column names and their types.
df_salary.info()

<class 'pandas.DataFrame'>
RangeIndex: 28062 entries, 0 to 28061
Data columns (total 18 columns):
 #   Column                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                --------------  -----
 0   Timestamp                                                                                                                                                                                                                             28062 non-null  str
 1   How old are you?                                                                                                                                                                                                                      28062 non-null  str
 2   What industry do you work in?                                                                                                                                                                                                         27988 non-null  str
 3   Job title                                                                                                                                                                                                                             28061 non-null  str
 4   If your job title needs additional context, please clarify here:                                                                                                                                                                      7262 non-null   str
 5   What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)  28062 non-null  str
 6   How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                        20766 non-null  float64
 7   Please indicate the currency                                                                                                                                                                                                          28062 non-null  str
 8   If "Other," please indicate the currency here:                                                                                                                                                                                        206 non-null    str
 9   If your income needs additional context, please provide it here:                                                                                                                                                                      3042 non-null   str
 10  What country do you work in?                                                                                                                                                                                                          28062 non-null  str
 11  If you're in the U.S., what state do you work in?                                                                                                                                                                                     23039 non-null  str
 12  What city do you work in?                                                                                                                                                                                                             27980 non-null  str
 13  How many years of professional work experience do you have overall?                                                                                                                                                                   28062 non-null  str
 14  How many years of professional work experience do you have in your field?                                                                                                                                                             28062 non-null  str
 15  What is your highest level of education completed?                                                                                                                                                                                    27840 non-null  str
 16  What is your gender?                                                                                                                                                                                                                  27891 non-null  str
 17  What is your race? (Choose all that apply.)                                                                                                                                                                                           27885 non-null  str
dtypes: float64(1), str(17)
memory usage: 3.9 MB

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [22]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race
df_salary.rename(
    columns ={
        "Timestamp": 'timestamp',
        'How old are you?': 'age',
        'What industry do you work in?': 'industry',
        'Job Title': 'title',
        'If your job title needs additional context, please clarify here:': 'title_context',
        "What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)": 'salary',
        "How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.": 'additional_compensation',
        "Please indicate the currency": 'currency',
        "If \"Other,\" please indicate the currency here: ": 'other_currency',
        "If your income needs additional context, please provide it here:": "salary_context",
        "What country do you work in?": 'country',
        "If you're in the U.S., what state do you work in?": 'state',
        "What city do you work in?": 'city',
        "How many years of professional work experience do you have overall?": 'total_yoe',
        "How many years of professional work experience do you have in your field?": 'field_yoe',
        "What is your highest level of education completed?": 'highest_education_completed',
        "What is your gender?": 'gender',
        "What is your race? (Choose all that apply.)": 'race'


    },
    inplace=True
)
df_salary

,timestamp,age,industry,Job title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28057,7/12/2024 22:52:01,35-44,Health care,Veterinarian,NaN,135000,NaN,USD,NaN,NaN,United States,Missouri,Wentzville,11 - 20 years,11 - 20 years,"Professional degree (MD, JD, etc.)",Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28059,7/24/2024 12:22:58,18-24,"Accounting, Banking & Finance",Risk Management Associate,NaN,1200,0.0,USD,NaN,NaN,Myanmar,Colorado,Yangon,2 - 4 years,2 - 4 years,Some college,Man,Asian or Asian American
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American
28061,8/20/2024 1:06:13,25-34,Health care,Clinical physiologist,NaN,1200000,NaN,Other,NGN,NaN,Nigeria,NaN,Lagos,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [23]:
df_salary['industry'].value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [37]:
# Filtery filter.
df_salary_tech = df_salary[df_salary['industry'] == 'Computing or Tech'].copy()


df_salary_tech['industry'].value_counts()

industry
Computing or Tech    4699
Name: count, dtype: int64

Do a sanity check by counting.

In [25]:
# Sanity check count.

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [41]:
# Filtery filter (in place) for just the jobs that pay in USD!
df_job = df_salary['Job title']
df_job[df_salary['currency'] == 'USD']

0            Research and Instruction Librarian
2                          Marketing Specialist
3                               Program Manager
4                            Accounting Manager
5                Scholarly Publishing Librarian
                          ...
28052    Senior Global Public Relations Manager
28057                              Veterinarian
28058                         Systems Architect
28059                 Risk Management Associate
28060                                        IT
Name: Job title, Length: 23374, dtype: str

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [49]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.

df = df_salary_tech['country'].value_counts()
df

country
United States     1576
USA               1222
US                 413
Canada             227
United Kingdom     145
                  ...
Nigeria              1
ss                   1
ibdia                1
Nigeria              1
Burma                1
Name: count, Length: 145, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [50]:
# Replace them all in-place with 'US'.
top_5 = ['United States', 'USA', 'US', 'United States of America', 'U.S.']
df_salary_tech['country'] = df_salary_tech['country'].replace(top_5, 'US')
df_salary_tech

,timestamp,age,industry,Job title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,US,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",US,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,US,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28050,7/1/2024 13:38:46,25-34,Computing or Tech,Research & Systems Technician Data Analytics,NaN,22000,NaN,EUR,NaN,NaN,Spain,NaN,Barcelona,2 - 4 years,2 - 4 years,College degree,Man,"Hispanic, Latino, or Spanish origin"
28051,7/1/2024 20:05:58,25-34,Computing or Tech,Junior data analyst,NaN,35000,15000.0,USD,NaN,NaN,Usa,Alabama,Alabama,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American
28052,7/3/2024 14:02:01,25-34,Computing or Tech,Senior Global Public Relations Manager,NaN,144000,15000.0,USD,NaN,NaN,Usa,Massachusetts,Boise-but remote. Company located in Boston,8 - 10 years,8 - 10 years,Master's degree,Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,US,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American

Have a look at the count of each unique country again now.

In [51]:
# Count again.
df_salary_tech['country'].value_counts()

country
US                3409
Canada             227
United Kingdom     145
UK                 112
Germany             69
                  ...
Nigeria              1
ss                   1
ibdia                1
Nigeria              1
Burma                1
Name: count, Length: 141, dtype: int64

Did you notice anything interesting?

In [30]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [31]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [ ]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
filtered_us_country = df_salary_tech[df_salary_tech['country'] == 'US'].copy()
salary_stats = filtered_us_country.groupby('state')['salary'].agg(['min', 'mean', 'max'])
salary_stats.sort_values()

TypeError: dtype 'str' does not support operation 'mean'

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [61]:
# Fix it in-place.
df_salary_tech['salary'] = pd.to_numeric(filtered_us_country['salary'], errors='coerce')
filtered_us_country = filtered_us_country.dropna(subset=['salary', 'state'])

Let’s try that again.

In [62]:
# Try it again. Yeah!

salary_stats = filtered_us_country.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values(by='mean', ascending=False)

TypeError: dtype 'str' does not support operation 'mean'

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [35]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)