# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Collecting pandas
  Downloading pandas-3.0.5-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy
  Downloading numpy-2.5.3-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 19.9 MB/s  0:00:006m0:00:01
Downloading numpy-2.5.3-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 27.9 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.5.3 pandas-3.0.5
Note: you may need to restart the kernel to use updated packages.

In [1]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [2]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [3]:
# Count by hand. (lol kidding)
len(df_food)

125

In [4]:
# Try to print or display it nicely.
print(f"There are {len(df_food)} rows in this dataset.")

There are 125 rows in this dataset.

What are the columns and their types in this data set?

In [5]:
# Show the column names and their types.
df_food.dtypes

GPA                     str
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports             str
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight                  str
Length: 61, dtype: object

In [30]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
pd.DataFrame(df_food.dtypes, columns=["Data Type"])

                             Data Type
GPA                                str
Gender                           int64
breakfast                        int64
calories_chicken                 int64
calories_day                   float64
calories_scone                 float64
coffee                           int64
comfort_food                       str
comfort_food_reasons               str
comfort_food_reasons_coded     float64
cook                           float64
comfort_food_reasons_coded.1     int64
cuisine                        float64
diet_current                       str
diet_current_coded               int64
drink                          float64
eating_changes                     str
eating_changes_coded             int64
eating_changes_coded1            int64
eating_out                       int64
employment                     float64
ethnic_food                      int64
exercise                       float64
father_education               float64
father_profession                  str
fav_cuisine                        str
fav_cuisine_coded                int64
fav_food                       float64
food_childhood                     str
fries                            int64
fruit_day                        int64
grade_level                      int64
greek_food                       int64
healthy_feeling                  int64
healthy_meal                       str
ideal_diet                         str
ideal_diet_coded                 int64
income                         float64
indian_food                      int64
italian_food                     int64
life_rewarding                 float64
marital_status                 float64
meals_dinner_friend                str
mother_education               float64
mother_profession                  str
nutritional_check                int64
on_off_campus                  float64
parents_cook                     int64
pay_meal_out                     int64
persian_food                   float64
self_perception_weight         float64
soup                           float64
sports                         float64
thai_food                        int64
tortilla_calories              float64
turkey_calories                  int64
type_sports                        str
veggies_day                      int64
vitamins                         int64
waffle_calories                  int64
weight                             str

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [31]:
# Remove ‘em.
df_food_col_subset = df_food[['calories_day', 'weight', 'Gender']]

df_food_col_subset.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

In [26]:
# Is there a second way to remove columns?

df_food_col_subset = df_food.loc[:, ['calories_day', 'weight', 'Gender']]

df_food_col_subset.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

In [ ]:
# 🚀 Extra credit: What about a third way to remove columns?

What about `NaN`s? How many are there?

In [10]:
# Count ‘em.
df_food_col_subset.isna().sum()

calories_day    19
weight           2
Gender           0
dtype: int64

In [11]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.
df_nan = df_food_col_subset.isna().sum()
pd.DataFrame(df_nan, columns=["NaN Sum"])

              NaN Sum
calories_day       19
weight              2
Gender              0

In [12]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

# Although I solved previous problem in 2 parts which made it possible not to keep too long line of codes. But it could be done in one line too instead of storing in the var df_nan. In that case, we I use backslash to break into shorter lines, it would look as following

pd.DataFrame(df_food_col_subset.isna() \
             .sum(), \
             columns=['NaN Sum'])

              NaN Sum
calories_day       19
weight              2
Gender              0

We gotta remove those `NaN`s―the entire row.

In [13]:
# Drop ‘em in-place.

df_food_col_subset.dropna(inplace=True)
df_food_col_subset.isna().sum()

calories_day    0
weight          0
Gender          0
dtype: int64

In [19]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂

df_food[['calories_day', 'weight', 'Gender']].isna().sum()

calories_day    19
weight           2
Gender           0
dtype: int64

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [33]:
# Fix that in-place.
df_food_col_subset['weight'] = pd.to_numeric(df_food_col_subset['weight'], errors='coerce')
df_food_col_subset.dropna(inplace=True)
df_food_col_subset.head(30)

    calories_day  weight  Gender
1            3.0   155.0       1
4            2.0   190.0       1
5            3.0   190.0       1
6            3.0   180.0       2
7            3.0   137.0       1
9            3.0   125.0       1
10           3.0   116.0       1
11           4.0   110.0       1
12           3.0   264.0       2
13           3.0   123.0       1
14           3.0   185.0       2
16           3.0   145.0       1
17           3.0   170.0       2
18           3.0   135.0       1
19           2.0   165.0       2
20           3.0   175.0       2
21           3.0   195.0       2
22           3.0   185.0       2
23           3.0   185.0       2
24           2.0   105.0       1
25           3.0   125.0       1
26           2.0   160.0       2
27           4.0   175.0       2
28           2.0   180.0       2
29           2.0   167.0       2
30           3.0   115.0       1
31           3.0   205.0       2
33           3.0   128.0       1
34           3.0   150.0       1
35           2.0   150.0       1

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [37]:
# Savey save!
df_food_col_subset.to_csv('../data/cleaned_food.csv', index=False)

In [44]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.

df_food_col2 = pd.read_csv('../data/cleaned_food.csv')
df_food_col2.head()

   calories_day  weight  Gender
0           3.0   155.0       1
1           2.0   190.0       1
2           3.0   190.0       1
3           3.0   180.0       2
4           3.0   137.0       1

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [51]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.

salary_data_set_path = '../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv'

df_salary = pd.read_csv(salary_data_set_path, sep='\t')

df_salary.head()

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [67]:
# Count by hand. I’m dead serious.
len(df_salary)

#alternatively, we can also do:  df_salary.shape[0]

28062

What are the columns and their types?

In [69]:
# Show the column names and their types.

df_salary.dtypes

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [70]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race

df_salary.columns = [
    'timestamp',
    'age',
    'industry',
    'title',
    'title_context',
    'salary',
    'additional_compensation',
    'currency',
    'other_currency',
    'salary_context',
    'country',
    'state',
    'city',
    'total_yoe',
    'field_yoe',
    'highest_education_completed',
    'gender',
    'race'
]

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [71]:
# List the unique industries and a count of their instances.

df_salary['industry'].value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [72]:
# Filtery filter.

df_salary_tech = df_salary[df_salary['industry'] == 'Computing or Tech']

Do a sanity check by counting.

In [74]:
# Sanity check count.
len(df_salary_tech)

4699

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [76]:
# Filtery filter (in place) for just the jobs that pay in USD!
salary_in_usd = df_salary_tech[df_salary_tech['currency'] == 'USD']

len(salary_in_usd)

3777

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [77]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary_tech['country'].value_counts()

country
United States     1576
USA               1222
US                 413
Canada             227
United Kingdom     145
                  ...
Nigeria              1
ss                   1
ibdia                1
Nigeria              1
Burma                1
Name: count, Length: 145, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [78]:
# Replace them all in-place with 'US'.
df_salary_tech['country'] = df_salary_tech['country'].replace(
    df_salary_tech['country'].value_counts().head(5).index, 'US'
)

Have a look at the count of each unique country again now.

In [79]:
# Count again.
df_salary_tech['country'].value_counts()

country
US                          3583
UK                           112
U.S.                         108
United States of America      90
Germany                       69
                            ...
Nigeria                        1
ss                             1
ibdia                          1
Nigeria                        1
Burma                          1
Name: count, Length: 141, dtype: int64

Did you notice anything interesting?

In [80]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.
df_salary_tech['country'] = df_salary_tech['country'].replace(
    r'(?i)^\s*(?:u\.?\s*s\.?\s*a?\.?|united\s+states(?:\s+of\s+america)?)\s*$',
    'US',
    regex=True
)

# N.B: For the regex syntax part, I totally copied from chatGPT because I completely forgot and still do not remember anything about those regex symbols, which I learnt years ago from my Java OOP course

In [81]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.
df_salary_tech['country'].value_counts()

country
US           4083
UK            112
Germany        69
Australia      47
Ireland        29
             ...
Nigeria         1
ss              1
ibdia           1
Nigeria         1
Burma           1
Name: count, Length: 117, dtype: int64

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [88]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.


df_salary_tech.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Florida                          28800  157457.232143  2600000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  154857.215478   875000
Washington                          72  151423.670588   950000
New York                         14000  148054.638968   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135213.537954  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127706.355932   450000
Colorado                         45000  127240.006849   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119360.782353   315000
Georgia                          29120  117893.098765   250000
Maryland                         51260  117862.370370   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114268.000000   920000
Texas                            10700  113909.713004   280000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  106752.793103   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
North Carolina                   29000  105035.441441   260000
New York, Texas                 105000  105000.000000   105000
Massachusetts, New Hampshire    105000  105000.000000   105000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
South Carolina                   40000  102111.111111   205000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   96855.363636   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
New Hampshire                       55   95179.705882   193000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
Alabama                          29120   92510.000000   350000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Louisiana                        35360   83269.090909   150000
Massachusetts, Pennsylvania      83000   83000.000000    83000
California, Maryland             81500   81500.000000    81500
Arkansas                             4   74257.000000   144000
Alabama, Montana                 72000   72000.000000    72000

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [90]:
df_salary_tech['salary'] = pd.to_numeric(
    df_salary_tech['salary'].astype(str).str.replace(',', ''),
    errors='coerce'
)

Let’s try that again.

In [91]:
# Try it again. Yeah!
df_salary_tech.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Florida                          28800  157457.232143  2600000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  154857.215478   875000
Washington                          72  151423.670588   950000
New York                         14000  148054.638968   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135213.537954  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127706.355932   450000
Colorado                         45000  127240.006849   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119360.782353   315000
Georgia                          29120  117893.098765   250000
Maryland                         51260  117862.370370   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114268.000000   920000
Texas                            10700  113909.713004   280000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  106752.793103   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
North Carolina                   29000  105035.441441   260000
New York, Texas                 105000  105000.000000   105000
Massachusetts, New Hampshire    105000  105000.000000   105000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
South Carolina                   40000  102111.111111   205000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   96855.363636   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
New Hampshire                       55   95179.705882   193000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
Alabama                          29120   92510.000000   350000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Louisiana                        35360   83269.090909   150000
Massachusetts, Pennsylvania      83000   83000.000000    83000
California, Maryland             81500   81500.000000    81500
Arkansas                             4   74257.000000   144000
Alabama, Montana                 72000   72000.000000    72000

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [92]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.

df_salary_tech['timestamp'] = pd.to_datetime(df_salary_tech['timestamp'])

df_salary_recent = df_salary_tech[
    df_salary_tech['timestamp'].dt.year.isin([2021, 2022, 2023])
]

df_salary_recent.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  154986.177812   875000
Washington                          72  151571.970501   950000
New York                         14000  148054.638968   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135184.443709  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127706.355932   450000
Colorado                         45000  127240.006849   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119712.029586   315000
Georgia                          29120  118004.262500   250000
Maryland                         51260  117862.370370   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114268.000000   920000
Texas                            10700  113909.713004   280000
Florida                          28800  113047.363636   400000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
South Carolina                   40000  109875.000000   205000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  107063.872093   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
New York, Texas                 105000  105000.000000   105000
Massachusetts, New Hampshire    105000  105000.000000   105000
North Carolina                   29000  104944.854545   260000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Alabama                          29120   97738.181818   350000
Michigan                         36800   96855.363636   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
New Hampshire                       55   95179.705882   193000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Louisiana                        35360   83269.090909   150000
Massachusetts, Pennsylvania      83000   83000.000000    83000
Arkansas                         55000   81682.300000   144000
California, Maryland             81500   81500.000000    81500
Alabama, Montana                 72000   72000.000000    72000

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

In [93]:
df_salary_bonus = df_salary.copy()

df_salary_bonus = df_salary_bonus[df_salary_bonus['currency'] == 'USD']

df_salary_bonus['salary'] = pd.to_numeric(
    df_salary_bonus['salary'].astype(str).str.replace(',', ''),
    errors='coerce'
)

df_salary_bonus.groupby('state')['salary'] \
    .agg(['min', 'mean', 'max']) \
    .sort_values('mean', ascending=False)

,min,mean,max
state,,,
"Alabama, South Carolina",5000000,5.000000e+06,5000000
"Michigan, Texas, Washington",340000,3.400000e+05,340000
"Indiana, Ohio",245000,2.450000e+05,245000
Alaska,27040,2.322751e+05,10000000
"Colorado, Nevada",190000,1.900000e+05,190000
...,...,...,...
"District of Columbia, Washington",35000,3.500000e+04,35000
"Alabama, California",29120,2.912000e+04,29120
"District of Columbia, Maryland, Pennsylvania, Virginia",27040,2.704000e+04,27040
"Maryland, New York",14000,1.400000e+04,14000
"Alabama, Alaska, Arizona",15,1.500000e+01,15

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

In [94]:
salary_by_state = df_salary_bonus.groupby('state')['salary'] \
    .agg(['min', 'mean', 'max']) \
    .sort_values('mean', ascending=False)

salary_by_state.style.format('${:,.2f}')

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

In [98]:
df_salary_bonus = df_salary_bonus[
    ~df_salary_bonus['state'].str.contains(',')
]

df_salary_bonus.groupby('state')['salary'] \
    .agg(['min', 'mean', 'max']) \
    .sort_values('mean', ascending=False)

                        min           mean       max
state
Alaska                27040  232275.078125  10000000
California                0  114379.924818    875000
Washington               72  107830.313609   1260000
District of Columbia     40  106514.203666   1334782
New York                 80  105306.318140   3000000
New Jersey            14850  101252.434673   5000044
Massachusetts           155   98766.436555   1650000
Virginia                 57   94685.349045   1300000
Connecticut               0   93676.373950   1900000
Illinois                  0   90342.433884   1100000
Colorado                 65   89490.906646    630000
Maryland                  0   89470.515957    353200
Oregon                    0   88887.161600    320000
Texas                     0   88775.518957   1200000
Georgia                   0   86542.774674    860000
Utah                  18720   86462.053140    576000
Delaware              35000   86398.148936    220000
Florida                 150   83426.955769   2600000
Pennsylvania              0   83192.869427   1100000
New Mexico               78   81900.234694    300000
Minnesota                40   81635.923928    321250
North Carolina         4000   80937.878536    560000
Nevada                   55   80812.597826    425000
Arizona               12000   79756.821192    380000
Hawaii                12000   77699.466667    500000
Rhode Island          18000   77301.973684    200000
Michigan                 55   76501.732110    500000
Wisconsin                 1   76351.454158    920000
Ohio                     36   76012.946483    954000
Tennessee             20800   75821.322695    657900
Missouri                 70   75179.283626    335000
Arkansas                  4   74227.605634    488000
New Hampshire            55   73277.576271    208000
Louisiana             17000   72963.201550    253300
Indiana                 105   72820.478659    925000
Kansas                   52   72063.202614    734400
Nebraska              18000   71602.745455    224000
Idaho                    38   70439.804124    312000
Vermont               24960   70308.235294    200000
Alabama                   0   69237.801653    350000
Iowa                  13000   68741.391061    200000
Oklahoma              18000   66131.168142    180000
Kentucky                  0   65936.078534    208000
South Carolina            0   65837.258503    250000
Maine                 22000   64920.456000    173000
South Dakota          29000   64214.360000    150000
North Dakota              0   62174.342857    150000
Mississippi           25000   61624.313725    130000
Montana               19200   60949.015625    172000
West Virginia             0   58664.170732    125000
Wyoming               29000   58089.291667    140000

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)