# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [2]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy in /usr/local/python/3.14.2/lib/python3.14/site-packages (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [4]:
# Load the Food choices data set.

food_data_set_path = '/workspaces/ds-fall-2026/Week-02-Pandas-and-How-to-Make-a-Sick-Project/data/food_coded.csv'

#df_food will be the variable containing the data
df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [5]:
# Count by hand. (lol kidding)
print(len(df_food))
df_food.shape

125

(125, 61)

In [6]:
# Try to print or display it nicely.

df_food

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,...,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,...,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,...,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,...,1.0,2.0,2,725.0,345,NaN,4,2,575,135

What are the columns and their types in this data set?

In [7]:
# Show the column names and their types.
df_food.dtypes

GPA                     str
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports             str
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight                  str
Length: 61, dtype: object

In [8]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
df_food_cols = pd.DataFrame({'Column' : df_food.columns, 'DataType': df_food.dtypes.values,})

df_food_cols

                          Column DataType
0                            GPA      str
1                         Gender    int64
2                      breakfast    int64
3               calories_chicken    int64
4                   calories_day  float64
5                 calories_scone  float64
6                         coffee    int64
7                   comfort_food      str
8           comfort_food_reasons      str
9     comfort_food_reasons_coded  float64
10                          cook  float64
11  comfort_food_reasons_coded.1    int64
12                       cuisine  float64
13                  diet_current      str
14            diet_current_coded    int64
15                         drink  float64
16                eating_changes      str
17          eating_changes_coded    int64
18         eating_changes_coded1    int64
19                    eating_out    int64
20                    employment  float64
21                   ethnic_food    int64
22                      exercise  float64
23              father_education  float64
24             father_profession      str
25                   fav_cuisine      str
26             fav_cuisine_coded    int64
27                      fav_food  float64
28                food_childhood      str
29                         fries    int64
30                     fruit_day    int64
31                   grade_level    int64
32                    greek_food    int64
33               healthy_feeling    int64
34                  healthy_meal      str
35                    ideal_diet      str
36              ideal_diet_coded    int64
37                        income  float64
38                   indian_food    int64
39                  italian_food    int64
40                life_rewarding  float64
41                marital_status  float64
42           meals_dinner_friend      str
43              mother_education  float64
44             mother_profession      str
45             nutritional_check    int64
46                 on_off_campus  float64
47                  parents_cook    int64
48                  pay_meal_out    int64
49                  persian_food  float64
50        self_perception_weight  float64
51                          soup  float64
52                        sports  float64
53                     thai_food    int64
54             tortilla_calories  float64
55               turkey_calories    int64
56                   type_sports      str
57                   veggies_day    int64
58                      vitamins    int64
59               waffle_calories    int64
60                        weight      str

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [9]:
# Remove ‘em.
selected_cols = ['calories_day', 'weight', 'Gender']

df_food_col_subset= df_food[selected_cols].copy()
df_food_col_subset.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

In [10]:
# Is there a second way to remove columns?
selected_cols = ['calories_day', 'weight', 'Gender']

df_food_col_subset= df_food.filter(items=selected_cols).copy()
df_food_col_subset.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

In [11]:
# 🚀 Extra credit: What about a third way to remove columns?
selected_cols = ['calories_day', 'weight', 'Gender']

df_food_col_subset=  df_food.drop(columns = df_food.columns.difference(selected_cols))
df_food_col_subset.head()

   Gender  calories_day                    weight
0       2           NaN                       187
1       1           3.0                       155
2       1           4.0  I'm not answering this.
3       1           3.0             Not sure, 240
4       1           2.0                       190

What about `NaN`s? How many are there?

In [12]:
# Count ‘em.

df_food_nan= df_food_col_subset.isna()
df_food_nan.sum()

Gender           0
calories_day    19
weight           2
dtype: int64

In [13]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.

df_food_sub_nan = pd.DataFrame({
    'Column' : df_food_nan.columns,
    'NAN sums': df_food_nan.isnull().sum().values
})

df_food_sub_nan

         Column  NAN sums
0        Gender         0
1  calories_day         0
2        weight         0

In [ ]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

We gotta remove those `NaN`s―the entire row.

In [ ]:
# Drop ‘em in-place.
df_food_col_subset = df_food_col_subset.dropna()
df_food_col_subset

     Gender  calories_day                    weight
1         1           3.0                       155
2         1           4.0  I'm not answering this.
3         1           3.0             Not sure, 240
4         1           2.0                       190
5         1           3.0                       190
..      ...           ...                       ...
118       1           3.0                       140
119       2           3.0                       185
120       1           4.0                       156
121       1           2.0                       180
123       2           4.0                       135

[104 rows x 3 columns]

In [15]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂

df_food.isna().sum()

GPA                              2
Gender                           0
breakfast                        0
calories_chicken                 0
calories_day                    19
calories_scone                   1
coffee                           0
comfort_food                     1
comfort_food_reasons             2
comfort_food_reasons_coded      19
cook                             3
comfort_food_reasons_coded.1     0
cuisine                         17
diet_current                     1
diet_current_coded               0
drink                            2
eating_changes                   3
eating_changes_coded             0
eating_changes_coded1            0
eating_out                       0
employment                       9
ethnic_food                      0
exercise                        13
father_education                 1
father_profession                3
fav_cuisine                      2
fav_cuisine_coded                0
fav_food                         2
food_childhood                   1
fries                            0
fruit_day                        0
grade_level                      0
greek_food                       0
healthy_feeling                  0
healthy_meal                     1
ideal_diet                       1
ideal_diet_coded                 0
income                           1
indian_food                      0
italian_food                     0
life_rewarding                   1
marital_status                   1
meals_dinner_friend              3
mother_education                 3
mother_profession                2
nutritional_check                0
on_off_campus                    1
parents_cook                     0
pay_meal_out                     0
persian_food                     1
self_perception_weight           1
soup                             1
sports                           2
thai_food                        0
tortilla_calories                1
turkey_calories                  0
type_sports                     26
veggies_day                      0
vitamins                         0
waffle_calories                  0
weight                           2
dtype: int64

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [22]:
# Fix that in-place.
df_food_col_subset['weight']=pd.to_numeric(df_food_col_subset['weight'],errors='coerce')

df_food_col_subset_no_nan=df_food_col_subset.dropna()
df_food_col_subset_no_nan.head()

   Gender  calories_day  weight
1       1           3.0   155.0
4       1           2.0   190.0
5       1           3.0   190.0
6       2           3.0   180.0
7       1           3.0   137.0

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [25]:
# Savey save!

df_food_col_subset_no_nan.to_csv('food_cleaned.csv', index=False)

In [28]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.

file= '/workspaces/ds-fall-2026/Week-02-Pandas-and-How-to-Make-a-Sick-Project/data/food_cleaned.csv'

food_file_cleaned= pd.read_csv(file)
print(food_file_cleaned)

     Gender  calories_day  weight
0         1           3.0   155.0
1         1           2.0   190.0
2         1           3.0   190.0
3         2           3.0   180.0
4         1           3.0   137.0
..      ...           ...     ...
96        1           3.0   140.0
97        2           3.0   185.0
98        1           4.0   156.0
99        1           2.0   180.0
100       2           4.0   135.0

[101 rows x 3 columns]

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [38]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.

salary_file= '/workspaces/ds-fall-2026/Week-02-Pandas-and-How-to-Make-a-Sick-Project/data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv'

df_salary=pd.read_csv(salary_file, delimiter='\t')

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [39]:
# Count by hand. I’m dead serious.

df_salary.shape

(28062, 18)

What are the columns and their types?

In [41]:
# Show the column names and their types.

df_salary.dtypes

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [42]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race

df_salary.columns = [
    'timestamp',
    'age',
    'industry',
    'title',
    'title_context',
    'salary',
    'additional_compensation',
    'currency',
    'other_currency',
    'salary_context',
    'country',
    'state',
    'city',
    'total_yoe',
    'field_yoe',
    'highest_education_completed',
    'gender',
    'race'
]

df_salary.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [46]:
# List the unique industries and a count of their instances.

df_salary['industry'].value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [51]:
# Filtery filter.

filtering= df_salary['industry'] == 'Computing or Tech'

df_salary_tech = df_salary[filtering].copy()

Do a sanity check by counting.

In [50]:
# Sanity check count.

df_salary_tech.shape

(4699, 18)

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [58]:
# Filtery filter (in place) for just the jobs that pay in USD!

usd_filter= df_salary_tech['currency']=='USD'

df_usd= df_salary_tech[usd_filter]
df_usd.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,USA,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [59]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.

df_salary_tech['country'].value_counts()

country
United States     1576
USA               1222
US                 413
Canada             227
United Kingdom     145
                  ...
Nigeria              1
ss                   1
ibdia                1
Nigeria              1
Burma                1
Name: count, Length: 145, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [60]:
# Replace them all in-place with 'US'.
top_cinco = df_salary_tech['country'].value_counts().head(5).index

df_salary_tech.loc[df_salary_tech['country'].isin(top_cinco), 'country'] = 'US'

Have a look at the count of each unique country again now.

In [61]:
# Count again.
df_salary_tech['country'].value_counts()

country
US                          3583
UK                           112
U.S.                         108
United States of America      90
Germany                       69
                            ...
Nigeria                        1
ss                             1
ibdia                          1
Nigeria                        1
Burma                          1
Name: count, Length: 141, dtype: int64

Did you notice anything interesting?

In [ ]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [ ]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [70]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.

df_salary_tech.groupby('state')['salary'].agg(['min','mean','max']).round(2)

                                     min       mean        max
state
Alabama                          29120.0   92510.00   350000.0
Alabama, District of Columbia   156000.0  156000.00   156000.0
Alabama, Montana                 72000.0   72000.00    72000.0
Alaska                           67000.0  112500.00   158000.0
Arizona                          35000.0  104491.89   210000.0
Arizona, Utah                    95000.0   95000.00    95000.0
Arkansas                             4.0   74257.00   144000.0
California                           0.0  154857.22   875000.0
California, Colorado            176000.0  176000.00   176000.0
California, Maryland             81500.0   81500.00    81500.0
California, Oregon              200000.0  200000.00   200000.0
Colorado                         45000.0  127240.01   630000.0
Connecticut                      62400.0  128375.00   270000.0
Delaware                         63000.0  116600.00   169000.0
District of Columbia             10000.0  132318.04   267500.0
District of Columbia, Virginia  109200.0  109200.00   109200.0
Florida                          28800.0  157457.23  2600000.0
Georgia                          29120.0  117893.10   250000.0
Georgia, Massachusetts          175000.0  175000.00   175000.0
Georgia, Washington             123000.0  123000.00   123000.0
Idaho                            50000.0  111527.69   312000.0
Illinois                         13500.0  119360.78   315000.0
Indiana                          15000.0   88566.65   200000.0
Iowa                             47840.0   99729.74   160000.0
Kansas                           41500.0   99565.05   167000.0
Kentucky                         39000.0   92375.00   170000.0
Louisiana                        35360.0   83269.09   150000.0
Louisiana, Washington           117000.0  117000.00   117000.0
Maine                            50000.0  103571.43   173000.0
Maryland                         51260.0  117862.37   205000.0
Massachusetts                    37000.0  135213.54  1650000.0
Massachusetts, New Hampshire    105000.0  105000.00   105000.0
Massachusetts, Pennsylvania      83000.0   83000.00    83000.0
Massachusetts, Rhode Island     125000.0  125000.00   125000.0
Michigan                         36800.0   96855.36   235000.0
Michigan, Texas, Washington     340000.0  340000.00   340000.0
Minnesota                        34000.0  106752.79   230000.0
Mississippi                      94000.0   94000.00    94000.0
Missouri                            80.0   95317.65   200000.0
Montana                          65000.0   95500.00   145000.0
Nebraska                         43000.0   90975.29   166400.0
Nevada                           38000.0  141310.00   425000.0
New Hampshire                       55.0   95179.71   193000.0
New Jersey                       40000.0  128802.48   603000.0
New Jersey, New York            135000.0  137500.00   140000.0
New Mexico                       70000.0  132200.00   300000.0
New York                         14000.0  148054.64   590000.0
New York, Texas                 105000.0  105000.00   105000.0
North Carolina                   29000.0  105035.44   260000.0
North Dakota                     45760.0   97880.00   150000.0
Ohio                             32240.0  106338.84   954000.0
Oklahoma                         28536.0   87929.50   180000.0
Oregon                           16200.0  124297.80   320000.0
Pennsylvania                     32000.0  111623.12   237000.0
Rhode Island                     76000.0  111491.67   180000.0
South Carolina                   40000.0  102111.11   205000.0
South Dakota                     86000.0  115333.33   150000.0
Tennessee                        36550.0  112847.06   240000.0
Texas                            10700.0  113909.71   280000.0
Utah                             33280.0  105836.48   245000.0
Utah, Vermont                   130000.0  130000.00   130000.0
Vermont                          65000.0  111781.25   200000.0
Virginia                         43642.0  127706.36   450000.0
Washington                          72.0  151423.67   950000.0
West Virginia                   116500.0  120500.00   125000.0
Wisconsin                            1.0  114268.00   920000.0

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [71]:
# Fix it in-place.

# Fix it.
df_salary_tech['salary']=pd.to_numeric(df_salary_tech['salary'], errors='coerce')

Let’s try that again.

In [72]:
# Try it again. Yeah!

df_salary_tech.groupby('state')['salary'].agg(['min','mean','max']).round(2)

                                     min       mean        max
state
Alabama                          29120.0   92510.00   350000.0
Alabama, District of Columbia   156000.0  156000.00   156000.0
Alabama, Montana                 72000.0   72000.00    72000.0
Alaska                           67000.0  112500.00   158000.0
Arizona                          35000.0  104491.89   210000.0
Arizona, Utah                    95000.0   95000.00    95000.0
Arkansas                             4.0   74257.00   144000.0
California                           0.0  154857.22   875000.0
California, Colorado            176000.0  176000.00   176000.0
California, Maryland             81500.0   81500.00    81500.0
California, Oregon              200000.0  200000.00   200000.0
Colorado                         45000.0  127240.01   630000.0
Connecticut                      62400.0  128375.00   270000.0
Delaware                         63000.0  116600.00   169000.0
District of Columbia             10000.0  132318.04   267500.0
District of Columbia, Virginia  109200.0  109200.00   109200.0
Florida                          28800.0  157457.23  2600000.0
Georgia                          29120.0  117893.10   250000.0
Georgia, Massachusetts          175000.0  175000.00   175000.0
Georgia, Washington             123000.0  123000.00   123000.0
Idaho                            50000.0  111527.69   312000.0
Illinois                         13500.0  119360.78   315000.0
Indiana                          15000.0   88566.65   200000.0
Iowa                             47840.0   99729.74   160000.0
Kansas                           41500.0   99565.05   167000.0
Kentucky                         39000.0   92375.00   170000.0
Louisiana                        35360.0   83269.09   150000.0
Louisiana, Washington           117000.0  117000.00   117000.0
Maine                            50000.0  103571.43   173000.0
Maryland                         51260.0  117862.37   205000.0
Massachusetts                    37000.0  135213.54  1650000.0
Massachusetts, New Hampshire    105000.0  105000.00   105000.0
Massachusetts, Pennsylvania      83000.0   83000.00    83000.0
Massachusetts, Rhode Island     125000.0  125000.00   125000.0
Michigan                         36800.0   96855.36   235000.0
Michigan, Texas, Washington     340000.0  340000.00   340000.0
Minnesota                        34000.0  106752.79   230000.0
Mississippi                      94000.0   94000.00    94000.0
Missouri                            80.0   95317.65   200000.0
Montana                          65000.0   95500.00   145000.0
Nebraska                         43000.0   90975.29   166400.0
Nevada                           38000.0  141310.00   425000.0
New Hampshire                       55.0   95179.71   193000.0
New Jersey                       40000.0  128802.48   603000.0
New Jersey, New York            135000.0  137500.00   140000.0
New Mexico                       70000.0  132200.00   300000.0
New York                         14000.0  148054.64   590000.0
New York, Texas                 105000.0  105000.00   105000.0
North Carolina                   29000.0  105035.44   260000.0
North Dakota                     45760.0   97880.00   150000.0
Ohio                             32240.0  106338.84   954000.0
Oklahoma                         28536.0   87929.50   180000.0
Oregon                           16200.0  124297.80   320000.0
Pennsylvania                     32000.0  111623.12   237000.0
Rhode Island                     76000.0  111491.67   180000.0
South Carolina                   40000.0  102111.11   205000.0
South Dakota                     86000.0  115333.33   150000.0
Tennessee                        36550.0  112847.06   240000.0
Texas                            10700.0  113909.71   280000.0
Utah                             33280.0  105836.48   245000.0
Utah, Vermont                   130000.0  130000.00   130000.0
Vermont                          65000.0  111781.25   200000.0
Virginia                         43642.0  127706.36   450000.0
Washington                          72.0  151423.67   950000.0
West Virginia                   116500.0  120500.00   125000.0
Wisconsin                            1.0  114268.00   920000.0

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [74]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.

df_salary_tech['timestamp']=pd.to_datetime(df_salary_tech['timestamp'])
df_summary=df_salary_tech[df_salary_tech['timestamp'].dt.year.isin([2021])]
df_summary

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
1,2021-04-27 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,54600.0,4000.0,GBP,NaN,NaN,US,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
8,2021-04-27 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,112000.0,10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,2021-04-27 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,187500.0,5000.0,USD,NaN,NaN,US,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,2021-04-27 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,110000.0,20000.0,USD,NaN,"Around 20,000 a year in stock",US,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,2021-04-27 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,144600.0,2500.0,USD,NaN,NaN,US,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27565,2021-12-13 14:59:33,45-54,Computing or Tech,Senior Data Security Analyst,NaN,113000.0,NaN,USD,NaN,NaN,US,Kentucky,Louisville,21 - 30 years,21 - 30 years,Some college,Man,White
27567,2021-12-15 10:30:37,25-34,Computing or Tech,Software Engineer,NaN,110000.0,NaN,USD,NaN,NaN,US,Kentucky,Paducah,11 - 20 years,2 - 4 years,Master's degree,Woman,White
27571,2021-12-17 13:15:34,25-34,Computing or Tech,eDiscovery Specialist,NaN,103000.0,5000.0,USD,NaN,NaN,US,Colorado,Denver,8 - 10 years,5-7 years,College degree,Man,White
27577,2021-12-20 19:32:20,25-34,Computing or Tech,Interactive Writer,(Instructional Script writing and ux writing),75000.0,NaN,USD,NaN,NaN,U.S.A,New York,Remote,2 - 4 years,2 - 4 years,College degree,Woman,White
27580,2021-12-23 16:14:21,25-34,Computing or Tech,Front end developer,NaN,48000.0,NaN,EUR,NaN,NaN,France,NaN,Paris,5-7 years,2 - 4 years,High School,Man,"Hispanic, Latino, or Spanish origin, Middle Ea..."

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)