# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [34]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in /Users/ragibn/Library/CloudStorage/OneDrive-Personal/Documents/Programs/CUNY Tech Prep/Data Science - Fall/my-ds-fall-2026/.venv/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy in /Users/ragibn/Library/CloudStorage/OneDrive-Personal/Documents/Programs/CUNY Tech Prep/Data Science - Fall/my-ds-fall-2026/.venv/lib/python3.14/site-packages (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/ragibn/Library/CloudStorage/OneDrive-Personal/Documents/Programs/CUNY Tech Prep/Data Science - Fall/my-ds-fall-2026/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/ragibn/Library/CloudStorage/OneDrive-Personal/Documents/Programs/CUNY Tech Prep/Data Science - Fall/my-ds-fall-2026/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [35]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [36]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [37]:
# Count by hand. (lol kidding)

food_rows = df_food.shape[0]
food_cols = df_food.shape[1]

print(f"Loaded: {food_rows} rows and {food_cols} columns")

Loaded: 125 rows and 61 columns

In [38]:
# Try to print or display it nicely.
# We'll use the .head() method

df_food.head(10)
# It seems that many columns are in the 1-5 rating scale

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
5,2.25,1,1,610,3.0,980.0,2,"Candy, brownies and soda.","None, i don't eat comfort food. I just eat whe...",4.0,...,1.0,2.0,4,940.0,345,None.,1,2,1315,190
6,3.8,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.0,1.0,5,940.0,690,soccer,4,1,1315,180
7,3.3,1,1,720,3.0,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,...,1.0,2.0,1,725.0,500,none,4,2,1315,137
8,3.3,1,1,430,NaN,420.0,1,"Donuts, ice cream, chips",Boredom,2.0,...,2.0,2.0,5,725.0,345,none,3,2,760,180
9,3.3,1,1,430,3.0,315.0,2,"Mac and cheese, chocolate, and pasta","Stress, anger and sadness",1.0,...,1.0,1.0,4,580.0,345,field hockey,5,1,900,125

What are the columns and their types in this data set?

In [39]:
# Show the column names and their types.

df_food.dtypes

GPA                                 str
Gender                            int64
breakfast                         int64
calories_chicken                  int64
calories_day                    float64
calories_scone                  float64
coffee                            int64
comfort_food                        str
comfort_food_reasons                str
comfort_food_reasons_coded      float64
cook                            float64
comfort_food_reasons_coded.1      int64
cuisine                         float64
diet_current                        str
diet_current_coded                int64
drink                           float64
eating_changes                      str
eating_changes_coded              int64
eating_changes_coded1             int64
eating_out                        int64
employment                      float64
ethnic_food                       int64
exercise                        float64
father_education                float64
father_profession                   str
fav_cuisine                         str
fav_cuisine_coded                 int64
fav_food                        float64
food_childhood                      str
fries                             int64
fruit_day                         int64
grade_level                       int64
greek_food                        int64
healthy_feeling                   int64
healthy_meal                        str
ideal_diet                          str
ideal_diet_coded                  int64
income                          float64
indian_food                       int64
italian_food                      int64
life_rewarding                  float64
marital_status                  float64
meals_dinner_friend                 str
mother_education                float64
mother_profession                   str
nutritional_check                 int64
on_off_campus                   float64
parents_cook                      int64
pay_meal_out                      int64
persian_food                    float64
self_perception_weight          float64
soup                            float64
sports                          float64
thai_food                         int64
tortilla_calories               float64
turkey_calories                   int64
type_sports                         str
veggies_day                       int64
vitamins                          int64
waffle_calories                   int64
weight                              str
dtype: object

In [40]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
column_dtypes = pd.DataFrame({
  "column": df_food.columns,
  "data_types": df_food.dtypes.values
})

column_dtypes

                          column data_types
0                            GPA        str
1                         Gender      int64
2                      breakfast      int64
3               calories_chicken      int64
4                   calories_day    float64
5                 calories_scone    float64
6                         coffee      int64
7                   comfort_food        str
8           comfort_food_reasons        str
9     comfort_food_reasons_coded    float64
10                          cook    float64
11  comfort_food_reasons_coded.1      int64
12                       cuisine    float64
13                  diet_current        str
14            diet_current_coded      int64
15                         drink    float64
16                eating_changes        str
17          eating_changes_coded      int64
18         eating_changes_coded1      int64
19                    eating_out      int64
20                    employment    float64
21                   ethnic_food      int64
22                      exercise    float64
23              father_education    float64
24             father_profession        str
25                   fav_cuisine        str
26             fav_cuisine_coded      int64
27                      fav_food    float64
28                food_childhood        str
29                         fries      int64
30                     fruit_day      int64
31                   grade_level      int64
32                    greek_food      int64
33               healthy_feeling      int64
34                  healthy_meal        str
35                    ideal_diet        str
36              ideal_diet_coded      int64
37                        income    float64
38                   indian_food      int64
39                  italian_food      int64
40                life_rewarding    float64
41                marital_status    float64
42           meals_dinner_friend        str
43              mother_education    float64
44             mother_profession        str
45             nutritional_check      int64
46                 on_off_campus    float64
47                  parents_cook      int64
48                  pay_meal_out      int64
49                  persian_food    float64
50        self_perception_weight    float64
51                          soup    float64
52                        sports    float64
53                     thai_food      int64
54             tortilla_calories    float64
55               turkey_calories      int64
56                   type_sports        str
57                   veggies_day      int64
58                      vitamins      int64
59               waffle_calories      int64
60                        weight        str

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [41]:
# Remove ‘em.
cols_list = ["calories_day", "weight", "Gender"]
df_food_col_subset = df_food[cols_list]
df_food_col_subset.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

In [42]:
# Is there a second way to remove columns?
# Yea, we can use the drop method

cols_list_2 = ["calories_day", "weight", "Gender"]
df_food_col_subset_2 = df_food.drop(
  columns=df_food.columns.difference(cols_list_2)
)
df_food_col_subset_2

     Gender  calories_day                    weight
0         2           NaN                       187
1         1           3.0                       155
2         1           4.0  I'm not answering this.
3         1           3.0             Not sure, 240
4         1           2.0                       190
..      ...           ...                       ...
120       1           4.0                       156
121       1           2.0                       180
122       1           NaN                       120
123       2           4.0                       135
124       1           NaN                       135

[125 rows x 3 columns]

In [43]:
# 🚀 Extra credit: What about a third way to remove columns?

What about `NaN`s? How many are there?

In [44]:
# Count ‘em.
df_food_col_subset.isna().sum() # we can use sum() to get the counts of each column

calories_day    19
weight           2
Gender           0
dtype: int64

In [45]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.

df_nan_count = df_food_col_subset.isna().sum().reset_index()
df_nan_count.columns = ["columns", "nan_count"]
df_nan_count

        columns  nan_count
0  calories_day         19
1        weight          2
2        Gender          0

In [46]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.
# OR just use () :)

df_nan_count = (df_food_col_subset.isna()
                .sum()
                .reset_index())

df_nan_count.columns = ["columns", "nan_count"]
df_nan_count

        columns  nan_count
0  calories_day         19
1        weight          2
2        Gender          0

We gotta remove those `NaN`s―the entire row.

In [47]:
# Drop ‘em in-place.

df_food_col_subset.dropna(inplace=True)
df_food_col_subset

     calories_day                    weight  Gender
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
5             3.0                       190       1
..            ...                       ...     ...
118           3.0                       140       1
119           3.0                       185       2
120           4.0                       156       1
121           2.0                       180       1
123           4.0                       135       2

[104 rows x 3 columns]

In [48]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂
# No b/c its a seperate dataframe 

df_food[cols_list].isna().sum() # null values still present

calories_day    19
weight           2
Gender           0
dtype: int64

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [49]:
# Fix that in-place.
# Note: that weight is the only non-number, its a str type

# First convert those non-numeric values to NaN
# Then drop all rows with null values 

df_food_col_subset["Weight"] = pd.to_numeric(
  df_food_col_subset["weight"],
  errors="coerce"
)

# Now we can drop the null vals
df_food_col_subset.dropna(subset=["weight"], inplace=True)
df_food_col_subset

     calories_day                    weight  Gender  Weight
1             3.0                       155       1   155.0
2             4.0  I'm not answering this.        1     NaN
3             3.0             Not sure, 240       1     NaN
4             2.0                       190       1   190.0
5             3.0                       190       1   190.0
..            ...                       ...     ...     ...
118           3.0                       140       1   140.0
119           3.0                       185       2   185.0
120           4.0                       156       1   156.0
121           2.0                       180       1   180.0
123           4.0                       135       2   135.0

[104 rows x 4 columns]

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [50]:
# Savey save!
food_cleaned_path = "../data/food_cleaned.csv"
df_food_col_subset.to_csv(food_cleaned_path, index=False)

In [51]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [52]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.

df_salary = pd.read_csv("../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv", sep="\t")

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [53]:
# Count by hand. I’m dead serious.

sal_rows = df_salary.shape[0]
sal_cols = df_salary.shape[1]
print(f"Loaded: {sal_rows} rows and {sal_cols} columns")

Loaded: 28062 rows and 18 columns

What are the columns and their types?

In [54]:
# Show the column names and their types.

df_sal_dtypes = pd.DataFrame({
  "column": df_salary.columns, 
  "type": df_salary.dtypes.values
})

In [55]:
df_salary.head(10)

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
5,4/27/2021 11:02:46,25-34,Education (Higher Education),Scholarly Publishing Librarian,NaN,"62,000",NaN,USD,NaN,NaN,USA,New Hampshire,Hanover,8 - 10 years,2 - 4 years,Master's degree,Man,White
6,4/27/2021 11:02:51,25-34,Publishing,Publishing Assistant,NaN,"33,000",2000.0,USD,NaN,NaN,USA,South Carolina,Columbia,2 - 4 years,2 - 4 years,College degree,Woman,White
7,4/27/2021 11:03:00,25-34,Education (Primary/Secondary),Librarian,"High school, FT","50,000",NaN,USD,NaN,NaN,United States,Arizona,Yuma,5-7 years,5-7 years,Master's degree,Man,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
9,4/27/2021 11:03:02,35-44,"Accounting, Banking & Finance",Senior Accountant,NaN,"45,000",0.0,USD,NaN,I work for a Charter School,United States,Florida,Palm Coast,21 - 30 years,21 - 30 years,College degree,Woman,"Hispanic, Latino, or Spanish origin, White"

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [56]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race

df_salary.columns = [
    "timestamp",
    "age",
    "industry",
    "title",
    "title_context",
    "salary",
    "additional_compensation",
    "currency",
    "other_currency",
    "salary_context",
    "country",
    "state",
    "city",
    "total_yoe",
    "field_yoe",
    "highest_education_completed",
    "gender",
    "race"
]

df_salary.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [57]:
# List the unique industries and a count of their instances.

df_salary["industry"].value_counts().sort_values(ascending=False)

industry
Computing or Tech                       4699
Education (Higher Education)            2464
Nonprofits                              2419
Health care                             1896
Government and Public Administration    1889
                                        ...
awards and engraving                       1
Political Consulting                       1
Library/Information managment              1
Learning and Development                   1
Wine & Spirits                             1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [58]:
# Filtery filter.

df_salary_tech = df_salary[df_salary["industry"] == "Computing or Tech"]
df_salary_tech

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28050,7/1/2024 13:38:46,25-34,Computing or Tech,Research & Systems Technician Data Analytics,NaN,22000,NaN,EUR,NaN,NaN,Spain,NaN,Barcelona,2 - 4 years,2 - 4 years,College degree,Man,"Hispanic, Latino, or Spanish origin"
28051,7/1/2024 20:05:58,25-34,Computing or Tech,Junior data analyst,NaN,35000,15000.0,USD,NaN,NaN,Usa,Alabama,Alabama,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American
28052,7/3/2024 14:02:01,25-34,Computing or Tech,Senior Global Public Relations Manager,NaN,144000,15000.0,USD,NaN,NaN,Usa,Massachusetts,Boise-but remote. Company located in Boston,8 - 10 years,8 - 10 years,Master's degree,Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American

Do a sanity check by counting.

In [59]:
# Sanity check count.

assert df_salary_tech.shape[0] == 4699 # row count
print("Passed. ✅")

Passed. ✅

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [60]:
# Filtery filter (in place) for just the jobs that pay in USD!

df_salary_tech[df_salary_tech["currency"] == "USD"]

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,USA,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28044,6/3/2024 16:15:43,18-24,Computing or Tech,Research Data Analyst Associate,NaN,60000,0.0,USD,NaN,NaN,United States,Illinois,Evanston,2 - 4 years,1 year or less,College degree,Woman,White
28051,7/1/2024 20:05:58,25-34,Computing or Tech,Junior data analyst,NaN,35000,15000.0,USD,NaN,NaN,Usa,Alabama,Alabama,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American
28052,7/3/2024 14:02:01,25-34,Computing or Tech,Senior Global Public Relations Manager,NaN,144000,15000.0,USD,NaN,NaN,Usa,Massachusetts,Boise-but remote. Company located in Boston,8 - 10 years,8 - 10 years,Master's degree,Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [61]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.

df_salary_tech["country"].value_counts()

country
United States     1576
USA               1222
US                 413
Canada             227
United Kingdom     145
                  ...
Nigeria              1
ss                   1
ibdia                1
Nigeria              1
Burma                1
Name: count, Length: 145, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [62]:
# Replace them all in-place with 'US'.
top_5_countries = (
  df_salary_tech["country"]
  .value_counts()
  .head(5)
  .index
)

df_salary_tech.loc[
  df_salary_tech["country"].isin(top_5_countries),
  "country"
 ] = "US"

df_salary_tech.head(5)

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,US,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,US,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",US,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,US,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White

Have a look at the count of each unique country again now.

In [63]:
# Count again.

df_salary_tech["country"].value_counts()

country
US                          3583
UK                           112
U.S.                         108
United States of America      90
Germany                       69
                            ...
Nigeria                        1
ss                             1
ibdia                          1
Nigeria                        1
Burma                          1
Name: count, Length: 141, dtype: int64

Did you notice anything interesting?

In [64]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [65]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [66]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.

df_salary_tech("state")["salary"].agg(
  ["min", "mean", "max"]
).sort_values("mean", ascending=False)

TypeError: 'DataFrame' object is not callable

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [67]:
# Fix it in-place.
# lets convert salary (str) to numeric
df_salary_tech["salary"] = pd.to_numeric(
  df_salary_tech["salary"], 
  errors="coerce"
)

Let’s try that again.

In [68]:
# Try it again. Yeah!

df_salary_tech.groupby("state")["salary"].agg(
  ["min", "mean", "max"]
).sort_values("mean", ascending=False)

                                     min           mean        max
state
Michigan, Texas, Washington     340000.0  340000.000000   340000.0
Florida                          28800.0  210711.000000  2600000.0
California, Oregon              200000.0  200000.000000   200000.0
California, Colorado            176000.0  176000.000000   176000.0
Delaware                        169000.0  169000.000000   169000.0
Connecticut                      68000.0  161610.000000   270000.0
California                           0.0  153286.988827   520000.0
New York                         14000.0  146594.112150   590000.0
Wisconsin                            1.0  145806.888889   920000.0
District of Columbia             59000.0  142923.076923   200000.0
New Jersey, New York            135000.0  137500.000000   140000.0
Ohio                             42000.0  137066.666667   954000.0
Washington                          72.0  136923.916667   300000.0
Massachusetts                    41000.0  125899.155844   400000.0
Nevada                          107100.0  124550.000000   142000.0
New Jersey                       67500.0  124090.909091   192000.0
Oregon                           16200.0  122640.000000   230000.0
West Virginia                   120000.0  120000.000000   120000.0
Maryland                         62000.0  119955.461538   176000.0
Illinois                         36000.0  117555.571429   228800.0
Alabama                          35000.0  117400.000000   350000.0
Louisiana, Washington           117000.0  117000.000000   117000.0
Pennsylvania                     52000.0  116826.388889   237000.0
Georgia                          29120.0  115297.647059   242000.0
Virginia                         58750.0  115086.696970   378000.0
Montana                          65000.0  112666.666667   145000.0
Kansas                           41500.0  109666.666667   167000.0
Colorado                         49400.0  109291.891892   165000.0
District of Columbia, Virginia  109200.0  109200.000000   109200.0
Vermont                          91250.0  105625.000000   120000.0
Idaho                            74860.0  105465.000000   170000.0
Utah                             33280.0  105023.333333   176000.0
Maine                            50000.0  103833.333333   173000.0
Texas                            10700.0  103685.245902   190000.0
Kentucky                         62000.0  102500.000000   125000.0
Iowa                             63000.0  101200.000000   142000.0
Minnesota                        52124.0  101064.941176   210000.0
Rhode Island                     76000.0   99475.000000   122950.0
North Carolina                   29000.0   97841.666667   165000.0
Arizona                          35000.0   97833.333333   145000.0
Michigan                         41600.0   95758.823529   235000.0
New Mexico                       82000.0   95733.333333   115200.0
Tennessee                        61500.0   91750.000000   144000.0
New Hampshire                       55.0   87175.833333   130000.0
Oklahoma                         36958.0   84802.571429   180000.0
Indiana                          15000.0   82875.000000   140000.0
California, Maryland             81500.0   81500.000000    81500.0
Louisiana                        75000.0   80500.000000    84000.0
Missouri                            80.0   80339.923077   200000.0
Nebraska                         43000.0   76736.000000   140000.0
Arkansas                             4.0   58001.000000    95000.0
South Carolina                   40000.0   40000.000000    40000.0
Alabama, District of Columbia        NaN            NaN        NaN
Alabama, Montana                     NaN            NaN        NaN
Alaska                               NaN            NaN        NaN
Arizona, Utah                        NaN            NaN        NaN
Georgia, Massachusetts               NaN            NaN        NaN
Georgia, Washington                  NaN            NaN        NaN
Massachusetts, New Hampshire         NaN            NaN        NaN
Massachusetts, Pennsylvania          NaN            NaN        NaN
Massachusetts, Rhode Island          NaN            NaN        NaN
Mississippi                          NaN            NaN        NaN
New York, Texas                      NaN            NaN        NaN
North Dakota                         NaN            NaN        NaN
South Dakota                         NaN            NaN        NaN
Utah, Vermont                        NaN            NaN        NaN

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [ ]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.

df_salary_tech["timestamp"] = pd.to_datetime(
  df_salary_tech["timestamp"],
  errors="coerce"
)

df_salary_tech_2021_2022 = df_salary_tech[
  df_salary_tech["timestamp"].dt.year.isin([2021, 2022]) # list of years
]

# lets rerun the summary script
df_salary_tech_2021_2022.groupby("state")["salary"].agg(
    ["min", "mean", "max"]
).sort_values("mean", ascending=False)

                                     min           mean       max
state
Michigan, Texas, Washington     340000.0  340000.000000  340000.0
California, Oregon              200000.0  200000.000000  200000.0
California, Colorado            176000.0  176000.000000  176000.0
Delaware                        169000.0  169000.000000  169000.0
Connecticut                      68000.0  161610.000000  270000.0
California                           0.0  153754.893258  520000.0
New York                         14000.0  147363.867925  590000.0
Wisconsin                            1.0  145806.888889  920000.0
District of Columbia             59000.0  142923.076923  200000.0
Ohio                             42000.0  141894.117647  954000.0
Alabama                          52000.0  138000.000000  350000.0
New Jersey, New York            135000.0  137500.000000  140000.0
Washington                          72.0  137427.774648  300000.0
New Jersey                       67500.0  127500.000000  192000.0
Massachusetts                    41000.0  126576.466667  400000.0
Nevada                          107100.0  124550.000000  142000.0
Oregon                           16200.0  122640.000000  230000.0
Illinois                         36795.0  121771.060606  228800.0
Maryland                         62000.0  120250.000000  176000.0
West Virginia                   120000.0  120000.000000  120000.0
Georgia                          29120.0  117222.500000  242000.0
Louisiana, Washington           117000.0  117000.000000  117000.0
Pennsylvania                     52000.0  116826.388889  237000.0
Virginia                         58750.0  116651.906250  378000.0
Montana                          65000.0  112666.666667  145000.0
Kansas                           41500.0  109666.666667  167000.0
Colorado                         49400.0  109291.891892  165000.0
District of Columbia, Virginia  109200.0  109200.000000  109200.0
Vermont                          91250.0  105625.000000  120000.0
Idaho                            74860.0  105465.000000  170000.0
Utah                             33280.0  105023.333333  176000.0
Maine                            50000.0  103833.333333  173000.0
Texas                            10700.0  103386.440678  185000.0
Kentucky                         62000.0  102500.000000  125000.0
Minnesota                        52124.0  102381.500000  210000.0
Florida                          28800.0  102106.954545  170000.0
Iowa                             63000.0  101200.000000  142000.0
Rhode Island                     76000.0   99475.000000  122950.0
Arizona                          35000.0   97833.333333  145000.0
North Carolina                   29000.0   97250.000000  165000.0
Michigan                         41600.0   95758.823529  235000.0
New Mexico                       82000.0   95733.333333  115200.0
Tennessee                        61500.0   91750.000000  144000.0
New Hampshire                       55.0   87175.833333  130000.0
Oklahoma                         36958.0   84802.571429  180000.0
Missouri                            80.0   83275.833333  200000.0
Indiana                          15000.0   82875.000000  140000.0
California, Maryland             81500.0   81500.000000   81500.0
Louisiana                        75000.0   80500.000000   84000.0
Arkansas                         60000.0   77333.333333   95000.0
Nebraska                         43000.0   76736.000000  140000.0
Alabama, District of Columbia        NaN            NaN       NaN
Alabama, Montana                     NaN            NaN       NaN
Alaska                               NaN            NaN       NaN
Arizona, Utah                        NaN            NaN       NaN
Georgia, Massachusetts               NaN            NaN       NaN
Georgia, Washington                  NaN            NaN       NaN
Massachusetts, New Hampshire         NaN            NaN       NaN
Massachusetts, Pennsylvania          NaN            NaN       NaN
Massachusetts, Rhode Island          NaN            NaN       NaN
Mississippi                          NaN            NaN       NaN
New York, Texas                      NaN            NaN       NaN
North Dakota                         NaN            NaN       NaN
South Carolina                       NaN            NaN       NaN
South Dakota                         NaN            NaN       NaN
Utah, Vermont                        NaN            NaN       NaN

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)