# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in c:\users\rafid\anaconda3\lib\site-packages (2.2.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy in c:\users\rafid\anaconda3\lib\site-packages (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rafid\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rafid\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rafid\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\rafid\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [3]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [4]:
# Count by hand. (lol kidding)
print(df_food.shape)
#125 rows and 61 columns

(125, 61)

In [5]:
# Try to print or display it nicely.

print(f"{df_food.shape[0]} rows and {df_food.shape[1]} columns")

125 rows and 61 columns

What are the columns and their types in this data set?

In [6]:
# Show the column names and their types.
print(df_food.dtypes)

GPA                  object
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports          object
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight               object
Length: 61, dtype: object

In [7]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.

df_food.dtypes.to_frame(name="Column Data Type")

                             Column Data Type
GPA                                    object
Gender                                  int64
breakfast                               int64
calories_chicken                        int64
calories_day                          float64
calories_scone                        float64
coffee                                  int64
comfort_food                           object
comfort_food_reasons                   object
comfort_food_reasons_coded            float64
cook                                  float64
comfort_food_reasons_coded.1            int64
cuisine                               float64
diet_current                           object
diet_current_coded                      int64
drink                                 float64
eating_changes                         object
eating_changes_coded                    int64
eating_changes_coded1                   int64
eating_out                              int64
employment                            float64
ethnic_food                             int64
exercise                              float64
father_education                      float64
father_profession                      object
fav_cuisine                            object
fav_cuisine_coded                       int64
fav_food                              float64
food_childhood                         object
fries                                   int64
fruit_day                               int64
grade_level                             int64
greek_food                              int64
healthy_feeling                         int64
healthy_meal                           object
ideal_diet                             object
ideal_diet_coded                        int64
income                                float64
indian_food                             int64
italian_food                            int64
life_rewarding                        float64
marital_status                        float64
meals_dinner_friend                    object
mother_education                      float64
mother_profession                      object
nutritional_check                       int64
on_off_campus                         float64
parents_cook                            int64
pay_meal_out                            int64
persian_food                          float64
self_perception_weight                float64
soup                                  float64
sports                                float64
thai_food                               int64
tortilla_calories                     float64
turkey_calories                         int64
type_sports                            object
veggies_day                             int64
vitamins                                int64
waffle_calories                         int64
weight                                 object

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [8]:
# Remove ‘em.
df_food_col_subset = df_food[['calories_day', 'weight', 'Gender']]
df_food_col_subset.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

In [9]:
# Is there a second way to remove columns?
to_drop = df_food.columns.tolist()
to_drop.remove('calories_day')
to_drop.remove('weight')
to_drop.remove('Gender')
df_food_col_subset_2_= df_food.drop(columns=to_drop)
df_food_col_subset_2_.head(10)

   Gender  calories_day                    weight
0       2           NaN                       187
1       1           3.0                       155
2       1           4.0  I'm not answering this.
3       1           3.0             Not sure, 240
4       1           2.0                       190
5       1           3.0                       190
6       2           3.0                       180
7       1           3.0                       137
8       1           NaN                       180
9       1           3.0                       125

In [10]:
# 🚀 Extra credit: What about a third way to remove columns?

What about `NaN`s? How many are there?

In [11]:
# Count ‘em.

df_food.isna().sum().sum()

149

In [12]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.

df_food.isna().sum().to_frame(name="Count")

                              Count
GPA                               2
Gender                            0
breakfast                         0
calories_chicken                  0
calories_day                     19
calories_scone                    1
coffee                            0
comfort_food                      1
comfort_food_reasons              2
comfort_food_reasons_coded       19
cook                              3
comfort_food_reasons_coded.1      0
cuisine                          17
diet_current                      1
diet_current_coded                0
drink                             2
eating_changes                    3
eating_changes_coded              0
eating_changes_coded1             0
eating_out                        0
employment                        9
ethnic_food                       0
exercise                         13
father_education                  1
father_profession                 3
fav_cuisine                       2
fav_cuisine_coded                 0
fav_food                          2
food_childhood                    1
fries                             0
fruit_day                         0
grade_level                       0
greek_food                        0
healthy_feeling                   0
healthy_meal                      1
ideal_diet                        1
ideal_diet_coded                  0
income                            1
indian_food                       0
italian_food                      0
life_rewarding                    1
marital_status                    1
meals_dinner_friend               3
mother_education                  3
mother_profession                 2
nutritional_check                 0
on_off_campus                     1
parents_cook                      0
pay_meal_out                      0
persian_food                      1
self_perception_weight            1
soup                              1
sports                            2
thai_food                         0
tortilla_calories                 1
turkey_calories                   0
type_sports                      26
veggies_day                       0
vitamins                          0
waffle_calories                   0
weight                            2

In [13]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

We gotta remove those `NaN`s―the entire row.

In [14]:
# Drop ‘em in-place.

df_food.dropna(inplace=True)
df_food.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
6,3.8,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.0,1.0,5,940.0,690,soccer,4,1,1315,180
7,3.3,1,1,720,3.0,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,...,1.0,2.0,1,725.0,500,none,4,2,1315,137

In [15]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [42]:
# Fix that in-place.

df_food_col_subset = df_food[['calories_day', 'weight', 'Gender']].copy()

df_food_col_subset["weight"] = pd.to_numeric(df_food_col_subset["weight"], errors="coerce")
df_food_col_subset.dropna(inplace=True)

df_food_col_subset.dtypes
df_food_col_subset.head()

   calories_day  weight  Gender
1           3.0   155.0       1
4           2.0   190.0       1
6           3.0   180.0       2
7           3.0   137.0       1
9           3.0   125.0       1

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [ ]:
# Savey save!

df_food_col_subset.to_csv('../data/food_coded_cleaned.csv', index=False)

In [18]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [44]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.

df_manager_salary = pd.read_csv('../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv', sep='\t')

df_manager_salary.head()

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [45]:
# Count by hand. I’m dead serious. X_X

df_manager_salary.shape

(28062, 18)

What are the columns and their types?

In [46]:
# Show the column names and their types.
df_manager_salary.dtypes

Timestamp                                                                                                                                                                                                                                object
How old are you?                                                                                                                                                                                                                         object
What industry do you work in?                                                                                                                                                                                                            object
Job title                                                                                                                                                                                                                                object
If your job title needs additional context, please clarify here:                                                                                                                                                                         object
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)     object
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                             object
If "Other," please indicate the currency here:                                                                                                                                                                                           object
If your income needs additional context, please provide it here:                                                                                                                                                                         object
What country do you work in?                                                                                                                                                                                                             object
If you're in the U.S., what state do you work in?                                                                                                                                                                                        object
What city do you work in?                                                                                                                                                                                                                object
How many years of professional work experience do you have overall?                                                                                                                                                                      object
How many years of professional work experience do you have in your field?                                                                                                                                                                object
What is your highest level of education completed?                                                                                                                                                                                       object
What is your gender?                                                                                                                                                                                                                     object
What is your race? (Choose all that apply.)                                                                                                                                                                                              object
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [47]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race

df_manager_salary.columns = ['timestamp', 'age', 'industry', 'title', 'title_context', 'salary', 'additional_compensation', 'currency', 'other_currency', 'salary_context', 'country', 'state', 'city', 'total_yoe', 'field_yoe', 'highest_education_completed','gender','race']

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [48]:
# List the unique industries and a count of their instances.

df_manager_salary['industry'].value_counts()

industry
Computing or Tech                          4699
Education (Higher Education)               2464
Nonprofits                                 2419
Health care                                1896
Government and Public Administration       1889
                                           ...
Gaming (Gambling)                             1
Regulatory Affairs- nutraceuticals            1
Manufacturing : corporate admin support       1
Real Estate Investment Support                1
Wine & Spirits                                1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [49]:
# Filtery filter.
df_salary_filtered = df_manager_salary[df_manager_salary['industry'] == 'Computing or Tech'].copy()

df_salary_filtered.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White

Do a sanity check by counting.

In [55]:
# Sanity check count.

condition = df_manager_salary['industry'] == 'Computing or Tech'
print(df_manager_salary[condition]["industry"].value_counts())
print(df_salary_filtered.shape)

industry
Computing or Tech    4699
Name: count, dtype: int64
(4699, 18)

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [56]:
# Filtery filter (in place) for just the jobs that pay in USD!
df_salary_filtered = df_salary_filtered[df_salary_filtered['currency'] == 'USD']

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [57]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.

df_salary_filtered['country'].value_counts()

country
United States                1576
USA                          1222
US                            412
U.S.                          108
United States of America       90
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
UnitedStates                    2
New Zealand                     2
united States                   2
United Kingdom                  2
Brazil                          2
France                          2
U.S.A                           2
Spain                           2
United States of america        2
Usa                             2
U.S                             2
India                           2
Poland                          2
United States Of America        2
United State of America         2
Australia                       2
U.S.                            2
Unite States                    2
Jamaica                         1
Romania                         1
United STates                   1
Japan                           1
US                              1
United Stares                   1
Australian                      1
Denmark                         1
Thailand                        1
Unites States                   1
China                           1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
San Francisco                   1
International                   1
Netherlands                     1
Mexico                          1
United Stated                   1
Danmark                         1
Cuba                            1
Remote (philippines)            1
Singapore                       1
United State                    1
Uruguay                         1
 US                             1
U.s.                            1
Italy                           1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Puerto Rico                     1
America                         1
Uniyed states                   1
Burma                           1
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [60]:
# Replace them all in-place with 'US'.

us_condition = df_salary_filtered['country'] == 'US'

df_salary_filtered['country'] = np.where(us_condition, df_salary_filtered['country'], 'US')

df_salary_filtered['country'].value_counts()

country
US    3777
Name: count, dtype: int64

Have a look at the count of each unique country again now.

In [61]:
# Count again.

df_salary_filtered['country'].value_counts()

country
US    3777
Name: count, dtype: int64

Did you notice anything interesting?

In [30]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [ ]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [ ]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.

# gb = df_salary_filtered.groupby('state')['salary'].agg(['min', 'mean', 'max'])
# gb

TypeError: agg function failed [how->mean,dtype->object]

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [64]:
# Fix it in-place.
df_salary_filtered['salary'] = pd.to_numeric(df_salary_filtered['salary'], errors='coerce')

df_salary_filtered

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,NaN,10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,NaN,5000.0,USD,NaN,NaN,US,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,NaN,20000.0,USD,NaN,"Around 20,000 a year in stock",US,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,NaN,2500.0,USD,NaN,NaN,US,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,NaN,40000.0,USD,NaN,NaN,US,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28044,6/3/2024 16:15:43,18-24,Computing or Tech,Research Data Analyst Associate,NaN,60000.0,0.0,USD,NaN,NaN,US,Illinois,Evanston,2 - 4 years,1 year or less,College degree,Woman,White
28051,7/1/2024 20:05:58,25-34,Computing or Tech,Junior data analyst,NaN,35000.0,15000.0,USD,NaN,NaN,US,Alabama,Alabama,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American
28052,7/3/2024 14:02:01,25-34,Computing or Tech,Senior Global Public Relations Manager,NaN,144000.0,15000.0,USD,NaN,NaN,US,Massachusetts,Boise-but remote. Company located in Boston,8 - 10 years,8 - 10 years,Master's degree,Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000.0,NaN,USD,NaN,NaN,US,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700.0,10.0,USD,NaN,NaN,US,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American

Let’s try that again.

In [65]:
# Try it again. Yeah!

gb = df_salary_filtered.groupby('state')['salary'].agg(['min', 'mean', 'max'])
gb

                                     min           mean        max
state
Alabama                          35000.0  117400.000000   350000.0
Alabama, District of Columbia        NaN            NaN        NaN
Alabama, Montana                     NaN            NaN        NaN
Alaska                               NaN            NaN        NaN
Arizona                          35000.0   97833.333333   145000.0
Arizona, Utah                        NaN            NaN        NaN
Arkansas                             4.0   58001.000000    95000.0
California                           0.0  153286.988827   520000.0
California, Colorado            176000.0  176000.000000   176000.0
California, Maryland             81500.0   81500.000000    81500.0
California, Oregon              200000.0  200000.000000   200000.0
Colorado                         49400.0  109291.891892   165000.0
Connecticut                      68000.0  161610.000000   270000.0
Delaware                        169000.0  169000.000000   169000.0
District of Columbia             59000.0  142923.076923   200000.0
District of Columbia, Virginia  109200.0  109200.000000   109200.0
Florida                          28800.0  210711.000000  2600000.0
Georgia                          29120.0  115297.647059   242000.0
Georgia, Massachusetts               NaN            NaN        NaN
Georgia, Washington                  NaN            NaN        NaN
Idaho                            74860.0  105465.000000   170000.0
Illinois                         36000.0  117555.571429   228800.0
Indiana                          15000.0   82875.000000   140000.0
Iowa                             63000.0  101200.000000   142000.0
Kansas                           41500.0  109666.666667   167000.0
Kentucky                         62000.0  102500.000000   125000.0
Louisiana                        75000.0   80500.000000    84000.0
Louisiana, Washington           117000.0  117000.000000   117000.0
Maine                            50000.0  103833.333333   173000.0
Maryland                         62000.0  119955.461538   176000.0
Massachusetts                    41000.0  125899.155844   400000.0
Massachusetts, New Hampshire         NaN            NaN        NaN
Massachusetts, Pennsylvania          NaN            NaN        NaN
Massachusetts, Rhode Island          NaN            NaN        NaN
Michigan                         41600.0   95758.823529   235000.0
Michigan, Texas, Washington     340000.0  340000.000000   340000.0
Minnesota                        52124.0  101064.941176   210000.0
Mississippi                          NaN            NaN        NaN
Missouri                            80.0   80339.923077   200000.0
Montana                          65000.0  112666.666667   145000.0
Nebraska                         43000.0   76736.000000   140000.0
Nevada                          107100.0  124550.000000   142000.0
New Hampshire                       55.0   87175.833333   130000.0
New Jersey                       67500.0  124090.909091   192000.0
New Jersey, New York            135000.0  137500.000000   140000.0
New Mexico                       82000.0   95733.333333   115200.0
New York                         14000.0  146594.112150   590000.0
New York, Texas                      NaN            NaN        NaN
North Carolina                   29000.0   97841.666667   165000.0
North Dakota                         NaN            NaN        NaN
Ohio                             42000.0  137066.666667   954000.0
Oklahoma                         36958.0   84802.571429   180000.0
Oregon                           16200.0  122640.000000   230000.0
Pennsylvania                     52000.0  116826.388889   237000.0
Rhode Island                     76000.0   99475.000000   122950.0
South Carolina                   40000.0   40000.000000    40000.0
South Dakota                         NaN            NaN        NaN
Tennessee                        61500.0   91750.000000   144000.0
Texas                            10700.0  103685.245902   190000.0
Utah                             33280.0  105023.333333   176000.0
Utah, Vermont                        NaN            NaN        NaN
Vermont                          91250.0  105625.000000   120000.0
Virginia                         58750.0  115086.696970   378000.0
Washington                          72.0  136923.916667   300000.0
West Virginia                   120000.0  120000.000000   120000.0
Wisconsin                            1.0  145806.888889   920000.0

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [67]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.

#Discrepency in comment above and markdown above that btw
df_salary_filtered['timestamp'] = pd.to_datetime(df_salary_filtered['timestamp'], errors='coerce')
df_years_filtered = df_salary_filtered[df_salary_filtered['timestamp'].dt.year.isin([2021, 2022])]
df_years_filtered

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8,2021-04-27 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,NaN,10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,2021-04-27 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,NaN,5000.0,USD,NaN,NaN,US,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,2021-04-27 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,NaN,20000.0,USD,NaN,"Around 20,000 a year in stock",US,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,2021-04-27 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,NaN,2500.0,USD,NaN,NaN,US,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,2021-04-27 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,NaN,40000.0,USD,NaN,NaN,US,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27887,2022-10-19 18:19:22,35-44,Computing or Tech,Senior UX Designer,NaN,175000.0,15000.0,USD,NaN,NaN,US,California,Sunnyvale,11 - 20 years,11 - 20 years,Master's degree,Woman,"Hispanic, Latino, or Spanish origin"
27888,2022-10-21 19:59:05,25-34,Computing or Tech,Systems Engineer,NaN,114000.0,20000.0,USD,NaN,NaN,US,Wisconsin,Verona,2 - 4 years,2 - 4 years,Master's degree,Woman,White
27892,2022-11-03 17:18:54,35-44,Computing or Tech,Program Manager,NaN,138000.0,5000.0,USD,NaN,NaN,US,Texas,Houston,21 - 30 years,21 - 30 years,College degree,Woman,White
27907,2022-11-30 16:49:40,25-34,Computing or Tech,Senior bioinformatics scientist,NaN,170420.0,20000.0,USD,NaN,NaN,US,California,SF Bay Area,2 - 4 years,2 - 4 years,PhD,Woman,White
27915,2022-12-13 18:21:14,25-34,Computing or Tech,Business Development Director,NaN,111000.0,30000.0,USD,NaN,NaN,US,California,Costa Mesa,5-7 years,2 - 4 years,College degree,Man,"Hispanic, Latino, or Spanish origin, White"

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)