# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [4]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [5]:
# Count by hand. (lol kidding)
df_food.shape

(125, 61)

In [6]:
# Try to print or display it nicely.
print(f"Rows: {df_food.shape[0]}, Columns: {df_food.shape[1]}")

Rows: 125, Columns: 61

What are the columns and their types in this data set?

In [7]:
# Show the column names and their types.
df_food.dtypes

GPA                  object
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports          object
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight               object
Length: 61, dtype: object

In [8]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
pd.DataFrame(df_food.dtypes, columns = ["Data Type"])

                             Data Type
GPA                             object
Gender                           int64
breakfast                        int64
calories_chicken                 int64
calories_day                   float64
calories_scone                 float64
coffee                           int64
comfort_food                    object
comfort_food_reasons            object
comfort_food_reasons_coded     float64
cook                           float64
comfort_food_reasons_coded.1     int64
cuisine                        float64
diet_current                    object
diet_current_coded               int64
drink                          float64
eating_changes                  object
eating_changes_coded             int64
eating_changes_coded1            int64
eating_out                       int64
employment                     float64
ethnic_food                      int64
exercise                       float64
father_education               float64
father_profession               object
fav_cuisine                     object
fav_cuisine_coded                int64
fav_food                       float64
food_childhood                  object
fries                            int64
fruit_day                        int64
grade_level                      int64
greek_food                       int64
healthy_feeling                  int64
healthy_meal                    object
ideal_diet                      object
ideal_diet_coded                 int64
income                         float64
indian_food                      int64
italian_food                     int64
life_rewarding                 float64
marital_status                 float64
meals_dinner_friend             object
mother_education               float64
mother_profession               object
nutritional_check                int64
on_off_campus                  float64
parents_cook                     int64
pay_meal_out                     int64
persian_food                   float64
self_perception_weight         float64
soup                           float64
sports                         float64
thai_food                        int64
tortilla_calories              float64
turkey_calories                  int64
type_sports                     object
veggies_day                      int64
vitamins                         int64
waffle_calories                  int64
weight                          object

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [9]:
# Remove ‘em.
df_food_col_subset = df_food[['calories_day', 'Gender', 'weight']].copy()
df_food_col_subset.shape

(125, 3)

In [10]:
# Is there a second way to remove columns?
df_food_col_subset = df_food.loc[:,['calories_day', 'Gender', 'weight']]
df_food_col_subset.shape

(125, 3)

In [11]:
# 🚀 Extra credit: What about a third way to remove columns?
keep_cols = ['calories_day', 'Gender', 'weight']
df_food_col_subset = df_food.drop(columns = [col for col in df_food.columns if col not in keep_cols])
df_food_col_subset.shape

(125, 3)

What about `NaN`s? How many are there?

In [12]:
# Count ‘em.
df_food_col_subset.isna().sum()

Gender           0
calories_day    19
weight           2
dtype: int64

In [13]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.
df_food_col_subset.isna().sum().to_frame(name = 'Missing Cols')

              Missing Cols
Gender                   0
calories_day            19
weight                   2

In [14]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.
df_food_col_subset.isna().sum() \
    .reset_index() \
    .rename(columns={"index": "Column", 0:"Missing Cols"})

         Column  Missing Cols
0        Gender             0
1  calories_day            19
2        weight             2

We gotta remove those `NaN`s―the entire row.

In [15]:
# Drop ‘em in-place.
df_food_col_subset.dropna(inplace = True)

In [16]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂
df_food.isna().sum()

GPA                              2
Gender                           0
breakfast                        0
calories_chicken                 0
calories_day                    19
calories_scone                   1
coffee                           0
comfort_food                     1
comfort_food_reasons             2
comfort_food_reasons_coded      19
cook                             3
comfort_food_reasons_coded.1     0
cuisine                         17
diet_current                     1
diet_current_coded               0
drink                            2
eating_changes                   3
eating_changes_coded             0
eating_changes_coded1            0
eating_out                       0
employment                       9
ethnic_food                      0
exercise                        13
father_education                 1
father_profession                3
fav_cuisine                      2
fav_cuisine_coded                0
fav_food                         2
food_childhood                   1
fries                            0
fruit_day                        0
grade_level                      0
greek_food                       0
healthy_feeling                  0
healthy_meal                     1
ideal_diet                       1
ideal_diet_coded                 0
income                           1
indian_food                      0
italian_food                     0
life_rewarding                   1
marital_status                   1
meals_dinner_friend              3
mother_education                 3
mother_profession                2
nutritional_check                0
on_off_campus                    1
parents_cook                     0
pay_meal_out                     0
persian_food                     1
self_perception_weight           1
soup                             1
sports                           2
thai_food                        0
tortilla_calories                1
turkey_calories                  0
type_sports                     26
veggies_day                      0
vitamins                         0
waffle_calories                  0
weight                           2
dtype: int64

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [17]:
# Fix that in-place.
df_food_col_subset['weight'] = pd.to_numeric(df_food_col_subset['weight'], errors = 'coerce')
df_food_col_subset.dropna(subset = "weight", inplace=True)

df_food_col_subset['weight'] = df_food_col_subset['weight'].astype(int)

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [18]:
# Savey save!
df_food_col_subset.to_csv("../data/gender_cals_weight.csv", index=False)

In [19]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.
with open("../data/gender_cals_weight.csv") as f:
    for _ in range(5):
        print(f.readline(), end = "")

Gender,calories_day,weight
1,3.0,155
1,2.0,190
1,3.0,190
2,3.0,180

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [143]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.
data = ("../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv")
df_salary = pd.read_csv(data, sep="\t")

df_salary.head()

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

Was that hard? 🙃

nope

### Explore

You know the drill.

How much data did you just load?

In [144]:
# Count by hand. I’m dead serious.
print(f"Rows: {df_salary.shape[0]}, Columns: {df_salary.shape[1]}")

Rows: 28062, Columns: 18

What are the columns and their types?

In [145]:
# Show the column names and their types.
df_salary.dtypes.to_frame().reset_index().rename(columns = {'index':"Column Names", 0:'Dtype'})

                                         Column Names    Dtype
0                                           Timestamp   object
1                                    How old are you?   object
2                       What industry do you work in?   object
3                                           Job title   object
4   If your job title needs additional context, pl...   object
5   What is your annual salary? (You'll indicate t...   object
6   How much additional monetary compensation do y...  float64
7                        Please indicate the currency   object
8     If "Other," please indicate the currency here:    object
9   If your income needs additional context, pleas...   object
10                       What country do you work in?   object
11  If you're in the U.S., what state do you work in?   object
12                          What city do you work in?   object
13  How many years of professional work experience...   object
14  How many years of professional work experience...   object
15  What is your highest level of education comple...   object
16                               What is your gender?   object
17        What is your race? (Choose all that apply.)   object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [146]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race
column_names = ['timestamp', 'age', 'industry', 'title', 'title_context', 'salary',
                'additional_compensation', 'currency', 'other_currency', 'salary_context',
                'country', 'state', 'city', 'total_yoe', 'field_yoe', 'education', 'gender', 'race']

df_salary.columns = column_names

df_salary.columns

Index(['timestamp', 'age', 'industry', 'title', 'title_context', 'salary',
       'additional_compensation', 'currency', 'other_currency',
       'salary_context', 'country', 'state', 'city', 'total_yoe', 'field_yoe',
       'education', 'gender', 'race'],
      dtype='object')

It’s a lot, and that should not have been easy. 😏

Like a breeze

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [147]:
# List the unique industries and a count of their instances
df_salary['industry'].value_counts()

industry
Computing or Tech                        4699
Education (Higher Education)             2464
Nonprofits                               2419
Health care                              1896
Government and Public Administration     1889
                                         ...
Warehousing                                 1
Education (Early Childhood Education)       1
SAAS                                        1
Health and Safety                           1
Aerospace Manufacturing                     1
Name: count, Length: 1219, dtype: int64

4699

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [148]:
# Filtery filter.
df_salary_tech = df_salary[df_salary['industry'] == "Computing or Tech"].reset_index(drop = True)
df_salary_tech.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,education,gender,race
0,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
1,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
2,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
3,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
4,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White

Do a sanity check by counting.

In [149]:
# Sanity check count.
print(f"Rows: {df_salary_tech.shape[0]}, Columns: {df_salary_tech.shape[1]}")

Rows: 4699, Columns: 18

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [150]:
# Filtery filter (in place) for just the jobs that pay in USD!
df_salary_tech = df_salary_tech[df_salary_tech["currency"] == "USD"].reset_index(drop = True)

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [151]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary_tech['country'].value_counts()

country
United States                1576
USA                          1222
US                            412
U.S.                          108
United States of America       90
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
United States Of America        2
U.S.                            2
United State of America         2
India                           2
Spain                           2
Brazil                          2
Usa                             2
UnitedStates                    2
U.S                             2
Unite States                    2
Australia                       2
Poland                          2
United States of america        2
U.S.A                           2
France                          2
New Zealand                     2
united States                   2
United Kingdom                  2
US                              1
Danmark                         1
Cuba                            1
 US                             1
United State                    1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
Mexico                          1
Uruguay                         1
Singapore                       1
Remote (philippines)            1
Italy                           1
International                   1
United Stated                   1
United Stateds                  1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
ISA                             1
Canada                          1
Japan                           1
United STates                   1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [152]:
# Replace them all in-place with 'US'.
top_5_countries = df_salary_tech['country'].value_counts().head(5).index.tolist()
df_salary_tech['country'].replace(top_5_countries, 'US', inplace=True)

C:\Users\Rostyslav Kharevych\AppData\Local\Temp\ipykernel_13164\1463674304.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_salary_tech['country'].replace(top_5_countries, 'US', inplace=True)

Have a look at the count of each unique country again now.

In [153]:
# Count again.
df_salary_tech['country'].value_counts()

country
US                           3408
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
United States Of America        2
U.S.                            2
United State of America         2
India                           2
Spain                           2
Brazil                          2
Usa                             2
UnitedStates                    2
U.S                             2
Unite States                    2
Australia                       2
Poland                          2
United States of america        2
U.S.A                           2
France                          2
New Zealand                     2
united States                   2
United Kingdom                  2
US                              1
Danmark                         1
Cuba                            1
 US                             1
United State                    1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
Mexico                          1
Uruguay                         1
Singapore                       1
Remote (philippines)            1
Italy                           1
International                   1
United Stated                   1
United Stateds                  1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
ISA                             1
Canada                          1
Japan                           1
United STates                   1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

Did you notice anything interesting?

In [154]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [155]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [156]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
df_salary_tech['salary'] = pd.to_numeric(
    df_salary_tech['salary'].astype(str).str.replace('$', '', regex = False)\
    .str.replace(',', '', regex = False).str.strip(), errors = 'coerce')

df_salary_tech[df_salary_tech['country'] == "US"] \
    .groupby('state')['salary'] \
    .agg(["min", "mean", "max"]) \
    .sort_values(by = "mean", ascending = False)

                                   min           mean      max
state
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Florida                          28800  160155.204082  2600000
California                           0  156001.126230   875000
Alabama, District of Columbia   156000  156000.000000   156000
Washington                          72  150592.449367   950000
New York                         14000  148213.307692   590000
New Mexico                       82000  140466.666667   300000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135924.303704  1650000
District of Columbia             10000  134191.673469   267500
Connecticut                      62400  130390.625000   270000
Utah, Vermont                   130000  130000.000000   130000
Virginia                         43642  129387.704762   450000
Colorado                         49400  128038.887218   630000
Oregon                           16200  125205.888889   320000
Massachusetts, Rhode Island     125000  125000.000000   125000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  118039.063694   315000
Louisiana, Washington           117000  117000.000000   117000
New Jersey                       40000  116953.125000   245000
Georgia                          29120  116928.546667   242000
Maryland                         51260  116449.333333   205000
South Dakota                     86000  115333.333333   150000
Idaho                            50000  114583.333333   312000
Wisconsin                            1  113891.371795   920000
Texas                            10700  113128.049505   280000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Rhode Island                     76000  111491.666667   180000
Pennsylvania                     32000  109941.802083   237000
Nevada                           38000  109788.888889   175000
District of Columbia, Virginia  109200  109200.000000   109200
Tennessee                        36550  109022.666667   240000
Utah                             33280  106958.911111   245000
Minnesota                        34000  106752.793103   230000
New York, Texas                 105000  105000.000000   105000
Delaware                         63000  104666.666667   145000
North Carolina                   29000  104386.169811   260000
Arizona                          35000  103893.939394   210000
South Carolina                   40000  102111.111111   205000
Kansas                           41500   98983.500000   167000
Iowa                             47840   98325.833333   160000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   96847.019231   235000
Missouri                            80   96631.181818   200000
Montana                          65000   95500.000000   145000
Nebraska                         43000   95184.285714   166400
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
Ohio                             32240   92577.451613   179000
Kentucky                         39000   92375.000000   170000
Maine                            50000   92000.000000   114000
New Hampshire                       55   91403.666667   193000
Indiana                          15000   90830.928571   200000
Oklahoma                         28536   87929.500000   180000
Massachusetts, Pennsylvania      83000   83000.000000    83000
Arkansas                         55000   81682.300000   144000
California, Maryland             81500   81500.000000    81500
Louisiana                        35360   79884.444444   110000
Alabama                          29120   74457.777778   120000
Alabama, Montana                 72000   72000.000000    72000

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [157]:
# Fix it in-place.

Let’s try that again.

In [158]:
# Try it again. Yeah!

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [159]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_salary_tech['timestamp'] = pd.to_datetime(df_salary_tech['timestamp'])

df_salary_select = df_salary_tech[df_salary_tech['timestamp'].dt.year.isin([2021,2022,2023])].copy()

df_salary_select[df_salary_select['country'] == "US"] \
    .groupby('state')['salary'] \
    .agg(['min', 'mean', 'max']) \
    .sort_values(by = 'mean', ascending = False)

                                   min           mean      max
state
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
California                           0  156142.343186   875000
Alabama, District of Columbia   156000  156000.000000   156000
Washington                          72  150749.409524   950000
New York                         14000  148213.307692   590000
New Mexico                       82000  140466.666667   300000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135924.303704  1650000
District of Columbia             10000  134191.673469   267500
Connecticut                      62400  130390.625000   270000
Utah, Vermont                   130000  130000.000000   130000
Virginia                         43642  129387.704762   450000
Colorado                         49400  128038.887218   630000
Oregon                           16200  125205.888889   320000
Massachusetts, Rhode Island     125000  125000.000000   125000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  118411.108974   315000
Georgia                          29120  117035.689189   242000
Louisiana, Washington           117000  117000.000000   117000
New Jersey                       40000  116953.125000   245000
Maryland                         51260  116449.333333   205000
South Dakota                     86000  115333.333333   150000
Idaho                            50000  114583.333333   312000
Wisconsin                            1  113891.371795   920000
Texas                            10700  113128.049505   280000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Rhode Island                     76000  111491.666667   180000
Pennsylvania                     32000  109941.802083   237000
South Carolina                   40000  109875.000000   205000
Nevada                           38000  109788.888889   175000
Florida                          28800  109325.104167   190000
District of Columbia, Virginia  109200  109200.000000   109200
Tennessee                        36550  109022.666667   240000
Minnesota                        34000  107063.872093   230000
Utah                             33280  106958.911111   245000
New York, Texas                 105000  105000.000000   105000
Delaware                         63000  104666.666667   145000
North Carolina                   29000  104285.085714   260000
Arizona                          35000  103893.939394   210000
Kansas                           41500   98983.500000   167000
Iowa                             47840   98325.833333   160000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   96847.019231   235000
Missouri                            80   96631.181818   200000
Montana                          65000   95500.000000   145000
Nebraska                         43000   95184.285714   166400
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
Ohio                             32240   92577.451613   179000
Kentucky                         39000   92375.000000   170000
Maine                            50000   92000.000000   114000
New Hampshire                       55   91403.666667   193000
Indiana                          15000   90830.928571   200000
Oklahoma                         28536   87929.500000   180000
Massachusetts, Pennsylvania      83000   83000.000000    83000
Arkansas                         55000   81682.300000   144000
California, Maryland             81500   81500.000000    81500
Louisiana                        35360   79884.444444   110000
Alabama                          29120   74457.777778   120000
Alabama, Montana                 72000   72000.000000    72000

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

In [160]:
#Create a copy without filtering
df_usd = df_salary[df_salary['currency'] == "USD"].copy()

#Standardize US country variations
top_5_countries = df_usd['country'].value_counts().head(5).index.tolist()
df_usd['country'].replace(top_5_countries, 'US', inplace=True)

#Clean and convert salary to numeric
df_usd['salary'] = pd.to_numeric(
    df_usd['salary'].astype(str).str.replace('$', '', regex = False)\
    .str.replace(',', '', regex = False).str.strip(), errors = 'coerce')

#Filter out US and calculate the aggregation by state
df_usd[df_usd['country'] == "US"] \
    .groupby('state')['salary'] \
    .agg(["min", "mean", "max"]) \
    .sort_values(by = "mean", ascending = False)

C:\Users\Rostyslav Kharevych\AppData\Local\Temp\ipykernel_13164\1300480615.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_usd['country'].replace(top_5_countries, 'US', inplace=True)

                                                       min      mean     max
state
Indiana, Ohio                                       245000  245000.0  245000
Colorado, Nevada                                    190000  190000.0  190000
California, Montana                                 185000  185000.0  185000
California, Texas                                   185000  185000.0  185000
Alabama, District of Columbia                       156000  156000.0  156000
...                                                    ...       ...     ...
District of Columbia, Washington                     35000   35000.0   35000
Delaware, Pennsylvania                               35000   35000.0   35000
Alabama, California                                  29120   29120.0   29120
District of Columbia, Maryland, Pennsylvania, V...   27040   27040.0   27040
Maryland, New York                                   14000   14000.0   14000

[115 rows x 3 columns]

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

In [141]:
!pip install jinja2

Requirement already satisfied: jinja2 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (3.1.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\rostyslav kharevych\anaconda3\lib\site-packages (from jinja2) (3.0.2)

In [161]:
#Create a summary from a copy so that the original doesn't get touched
summary_table = (
    df_salary[df_salary['currency'] == 'USD'].copy()
    .assign(
        country=lambda d: d['country'].replace(d['country'].value_counts().head(5).index, 'US'),
        salary=lambda d: pd.to_numeric(d['salary'].astype(str).str.replace(r'[\$,]', '', regex=True), errors='coerce')
    )
    .query("country == 'US'")
    .groupby('state')['salary']
    .agg(['min', 'mean', 'max'])
    .sort_values(by='mean', ascending=False)
)

#Format using Styler
summary_table.style.format("${:,.2f}")

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

In [162]:
df_single_states = df_usd[~df_usd['state'].astype(str).str.contains(',')].copy()

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)