# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in /home/sams22/Projects/ds-fall-2026/.venv/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy in /home/sams22/Projects/ds-fall-2026/.venv/lib/python3.14/site-packages (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/sams22/Projects/ds-fall-2026/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/sams22/Projects/ds-fall-2026/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

Note: you may need to restart the kernel to use updated packages.

In [2]:
# Import here.

import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [3]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [4]:
# Count by hand. (lol kidding)
df_food.shape

(125, 61)

In [5]:
# Try to print or display it nicely.

df_food.head(125)

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,...,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,...,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,...,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,...,1.0,2.0,2,725.0,345,NaN,4,2,575,135

What are the columns and their types in this data set?

In [6]:
# Show the column names and their types.
df_food.dtypes
df_food.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190

In [7]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
df_info = pd.DataFrame({"dtypes" : df_food.dtypes, "counts" : df_food.count()})
df_info

                               dtypes  counts
GPA                               str     123
Gender                          int64     125
breakfast                       int64     125
calories_chicken                int64     125
calories_day                  float64     106
calories_scone                float64     124
coffee                          int64     125
comfort_food                      str     124
comfort_food_reasons              str     123
comfort_food_reasons_coded    float64     106
cook                          float64     122
comfort_food_reasons_coded.1    int64     125
cuisine                       float64     108
diet_current                      str     124
diet_current_coded              int64     125
drink                         float64     123
eating_changes                    str     122
eating_changes_coded            int64     125
eating_changes_coded1           int64     125
eating_out                      int64     125
employment                    float64     116
ethnic_food                     int64     125
exercise                      float64     112
father_education              float64     124
father_profession                 str     122
fav_cuisine                       str     123
fav_cuisine_coded               int64     125
fav_food                      float64     123
food_childhood                    str     124
fries                           int64     125
fruit_day                       int64     125
grade_level                     int64     125
greek_food                      int64     125
healthy_feeling                 int64     125
healthy_meal                      str     124
ideal_diet                        str     124
ideal_diet_coded                int64     125
income                        float64     124
indian_food                     int64     125
italian_food                    int64     125
life_rewarding                float64     124
marital_status                float64     124
meals_dinner_friend               str     122
mother_education              float64     122
mother_profession                 str     123
nutritional_check               int64     125
on_off_campus                 float64     124
parents_cook                    int64     125
pay_meal_out                    int64     125
persian_food                  float64     124
self_perception_weight        float64     124
soup                          float64     124
sports                        float64     123
thai_food                       int64     125
tortilla_calories             float64     124
turkey_calories                 int64     125
type_sports                       str      99
veggies_day                     int64     125
vitamins                        int64     125
waffle_calories                 int64     125
weight                            str     123

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [8]:
# Remove ‘em.
keep = ["Gender", "weight", "calories_day"]
df_food_col_subset = df_food[keep]
df_food_col_subset

     Gender                    weight  calories_day
0         2                       187           NaN
1         1                       155           3.0
2         1  I'm not answering this.            4.0
3         1             Not sure, 240           3.0
4         1                       190           2.0
..      ...                       ...           ...
120       1                       156           4.0
121       1                       180           2.0
122       1                       120           NaN
123       2                       135           4.0
124       1                       135           NaN

[125 rows x 3 columns]

In [9]:
# Is there a second way to remove columns?
remove = set(df_food.columns.to_list())
remove.remove("Gender")
remove.remove("weight")
remove.remove("calories_day")

df_food_col_subset = df_food.drop(columns = list(remove))

df_food_col_subset

     Gender  calories_day                    weight
0         2           NaN                       187
1         1           3.0                       155
2         1           4.0  I'm not answering this.
3         1           3.0             Not sure, 240
4         1           2.0                       190
..      ...           ...                       ...
120       1           4.0                       156
121       1           2.0                       180
122       1           NaN                       120
123       2           4.0                       135
124       1           NaN                       135

[125 rows x 3 columns]

In [10]:
# 🚀 Extra credit: What about a third way to remove columns?

df_food_col_subset = df_food.loc[:, keep]
df_food_col_subset

     Gender                    weight  calories_day
0         2                       187           NaN
1         1                       155           3.0
2         1  I'm not answering this.            4.0
3         1             Not sure, 240           3.0
4         1                       190           2.0
..      ...                       ...           ...
120       1                       156           4.0
121       1                       180           2.0
122       1                       120           NaN
123       2                       135           4.0
124       1                       135           NaN

[125 rows x 3 columns]

What about `NaN`s? How many are there?

In [11]:
# Count ‘em.
df_food.isnull().sum()

GPA                              2
Gender                           0
breakfast                        0
calories_chicken                 0
calories_day                    19
calories_scone                   1
coffee                           0
comfort_food                     1
comfort_food_reasons             2
comfort_food_reasons_coded      19
cook                             3
comfort_food_reasons_coded.1     0
cuisine                         17
diet_current                     1
diet_current_coded               0
drink                            2
eating_changes                   3
eating_changes_coded             0
eating_changes_coded1            0
eating_out                       0
employment                       9
ethnic_food                      0
exercise                        13
father_education                 1
father_profession                3
fav_cuisine                      2
fav_cuisine_coded                0
fav_food                         2
food_childhood                   1
fries                            0
fruit_day                        0
grade_level                      0
greek_food                       0
healthy_feeling                  0
healthy_meal                     1
ideal_diet                       1
ideal_diet_coded                 0
income                           1
indian_food                      0
italian_food                     0
life_rewarding                   1
marital_status                   1
meals_dinner_friend              3
mother_education                 3
mother_profession                2
nutritional_check                0
on_off_campus                    1
parents_cook                     0
pay_meal_out                     0
persian_food                     1
self_perception_weight           1
soup                             1
sports                           2
thai_food                        0
tortilla_calories                1
turkey_calories                  0
type_sports                     26
veggies_day                      0
vitamins                         0
waffle_calories                  0
weight                           2
dtype: int64

In [12]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.

df_food_nan = df_food.isna().sum().to_frame()
df_food_nan

                               0
GPA                            2
Gender                         0
breakfast                      0
calories_chicken               0
calories_day                  19
calories_scone                 1
coffee                         0
comfort_food                   1
comfort_food_reasons           2
comfort_food_reasons_coded    19
cook                           3
comfort_food_reasons_coded.1   0
cuisine                       17
diet_current                   1
diet_current_coded             0
drink                          2
eating_changes                 3
eating_changes_coded           0
eating_changes_coded1          0
eating_out                     0
employment                     9
ethnic_food                    0
exercise                      13
father_education               1
father_profession              3
fav_cuisine                    2
fav_cuisine_coded              0
fav_food                       2
food_childhood                 1
fries                          0
fruit_day                      0
grade_level                    0
greek_food                     0
healthy_feeling                0
healthy_meal                   1
ideal_diet                     1
ideal_diet_coded               0
income                         1
indian_food                    0
italian_food                   0
life_rewarding                 1
marital_status                 1
meals_dinner_friend            3
mother_education               3
mother_profession              2
nutritional_check              0
on_off_campus                  1
parents_cook                   0
pay_meal_out                   0
persian_food                   1
self_perception_weight         1
soup                           1
sports                         2
thai_food                      0
tortilla_calories              1
turkey_calories                0
type_sports                   26
veggies_day                    0
vitamins                       0
waffle_calories                0
weight                         2

In [13]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

df_food_nan = df_food.isna() \
    .sum() \
    .to_frame()

df_food_nan

                               0
GPA                            2
Gender                         0
breakfast                      0
calories_chicken               0
calories_day                  19
calories_scone                 1
coffee                         0
comfort_food                   1
comfort_food_reasons           2
comfort_food_reasons_coded    19
cook                           3
comfort_food_reasons_coded.1   0
cuisine                       17
diet_current                   1
diet_current_coded             0
drink                          2
eating_changes                 3
eating_changes_coded           0
eating_changes_coded1          0
eating_out                     0
employment                     9
ethnic_food                    0
exercise                      13
father_education               1
father_profession              3
fav_cuisine                    2
fav_cuisine_coded              0
fav_food                       2
food_childhood                 1
fries                          0
fruit_day                      0
grade_level                    0
greek_food                     0
healthy_feeling                0
healthy_meal                   1
ideal_diet                     1
ideal_diet_coded               0
income                         1
indian_food                    0
italian_food                   0
life_rewarding                 1
marital_status                 1
meals_dinner_friend            3
mother_education               3
mother_profession              2
nutritional_check              0
on_off_campus                  1
parents_cook                   0
pay_meal_out                   0
persian_food                   1
self_perception_weight         1
soup                           1
sports                         2
thai_food                      0
tortilla_calories              1
turkey_calories                0
type_sports                   26
veggies_day                    0
vitamins                       0
waffle_calories                0
weight                         2

We gotta remove those `NaN`s―the entire row.

In [14]:
# Drop ‘em in-place.
df_food.dropna()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
6,3.8,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.0,1.0,5,940.0,690,soccer,4,1,1315,180
7,3.3,1,1,720,3.0,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,...,1.0,2.0,1,725.0,500,none,4,2,1315,137
9,3.3,1,1,430,3.0,315.0,2,"Mac and cheese, chocolate, and pasta","Stress, anger and sadness",1.0,...,1.0,1.0,4,580.0,345,field hockey,5,1,900,125
10,3.5,1,1,610,3.0,980.0,2,"Pasta, grandma homemade chocolate cake anythin...",Boredom,2.0,...,1.0,1.0,2,940.0,345,soccer,5,2,900,116
11,3.904,1,1,720,4.0,420.0,2,"chocolate, pasta, soup, chips, popcorn","sadness, stress, cold weather",3.0,...,1.0,1.0,5,940.0,500,Running,5,1,900,110
12,3.4,2,1,430,3.0,420.0,2,"Cookies, popcorn, and chips","Sadness, boredom, late night snack",3.0,...,2.0,1.0,3,940.0,500,Soccer and basketball,3,2,575,264
13,3.6,1,1,610,3.0,420.0,2,"ice cream, cake, chocolate","stress, boredom, special occasions",1.0,...,1.0,1.0,5,1165.0,850,intramural volleyball,5,2,1315,123
14,3.1,2,1,610,3.0,420.0,2,"Pizza, fruit, spaghetti, chicken and Potatoes","Friends, environment and boredom",2.0,...,1.0,1.0,4,940.0,500,Hockey,5,1,900,185
17,3.6,2,1,430,3.0,980.0,2,"chips, cookies, ice cream",I usually only eat comfort food when I'm bored...,2.0,...,1.0,1.0,3,940.0,500,hockey,4,2,900,170
18,3.4,1,1,720,3.0,980.0,1,"Chocolate, ice crea","Sadness, stress",3.0,...,2.0,2.0,1,1165.0,690,dancing,5,1,1315,135
20,3.3,2,1,610,3.0,980.0,2,"Fast food, pizza, subs","happiness, satisfaction",7.0,...,1.0,1.0,1,1165.0,850,Soccer,3,2,1315,175
22,3.7,2,1,610,3.0,420.0,1,"burgers, chips, cookies","sadness, depression",3.0,...,1.0,1.0,4,940.0,850,tennis soccer gym,3,1,1315,185
23,3.7,2,2,610,3.0,420.0,2,"Chilli, soup, pot pie",Stress and boredom,1.0,...,1.0,1.0,4,940.0,690,Gaelic Football,4,1,1315,185
25,2.8,1,2,720,3.0,420.0,2,"chocolate, ice cream/milkshake, cookies",boredom,2.0,...,1.0,1.0,3,1165.0,690,Ice hockey,3,2,760,125
26,3.7,2,1,610,2.0,420.0,1,"Chips, ice cream, microwaveable foods","Boredom, lazyniss",2.0,...,2.0,1.0,2,1165.0,850,Hockey,3,2,1315,160
27,3,2,1,610,4.0,980.0,2,"Chicken fingers, pizza",Boredom,2.0,...,1.0,1.0,3,1165.0,500,Lacrosse,5,1,1315,175
31,4,2,1,610,3.0,420.0,2,"chips and dip, pepsi,","stres, boredom, and nighttime",1.0,...,2.0,2.0,4,940.0,690,none organized,5,1,1315,205
34,3.65,1,1,610,3.0,420.0,2,"french fries, chips, ice cream","boredom, stressed, sad",2.0,...,1.0,1.0,3,940.0,345,softball,4,1,1315,150
35,3,1,1,610,2.0,420.0,2,"mac n cheese, peanut butter and banana sandwic...",Boredom usually,2.0,...,1.0,1.0,2,940.0,690,Lacrosse,5,2,760,150
37,3.4,1,1,720,4.0,420.0,2,"chocolate, chips, candy",Stress,1.0,...,1.0,1.0,5,940.0,500,Dancing,4,2,1315,170
38,3.89,1,1,610,3.0,980.0,2,"chocolate, popcorn, ice cream","boredom, stress",2.0,...,1.0,1.0,2,1165.0,690,Lacrosse,3,2,1315,150
40,3.4,2,1,430,3.0,315.0,1,"Pizza, Ice cream, fries, cereal, cookies",Usually if I'm sad or depressed.,3.0,...,1.0,1.0,3,940.0,500,wrestling,4,2,760,140
44,3.2,1,1,610,4.0,420.0,2,"Potato chips, ice cream, chocolate, cookies","Stress, boredom, craving",1.0,...,1.0,1.0,5,725.0,500,Volleyball,5,1,760,170
46,3.8,2,1,430,2.0,420.0,1,"popcorn, chips, candy, & fries","sadness, boredom, & anger",3.0,...,1.0,1.0,3,725.0,345,soccer,4,2,900,168
51,3.3,2,1,610,4.0,980.0,1,Burger,Lazy,5.0,...,1.0,1.0,5,1165.0,500,Hockey,4,1,1315,185
54,3.5,2,1,610,3.0,420.0,2,"peanut butter sandwich, pretzals, garlic bread","stress, anger and boredom",1.0,...,1.0,1.0,4,940.0,690,hockey,5,1,900,165
56,3.8,2,1,720,4.0,315.0,2,"Pizza, Ice Cream, Chicken Wings",I usually only eat comfort foods when I am bor...,2.0,...,1.0,1.0,5,1165.0,500,Hockey,5,1,1315,175
57,2.8,1,1,610,4.0,980.0,2,Pizza chocolate chips bagels ice Capps,Just cause,9.0,...,2.0,1.0,2,725.0,345,softball,4,1,1315,140
58,3.5,1,1,610,3.0,420.0,2,"Chocolate, ice cream, pasta","Stress, boredom, sadness",1.0,...,1.0,1.0,5,1165.0,690,Skiing,5,1,1315,155
60,3.6,1,1,610,4.0,420.0,2,"peanut butter, dessets, pretzels.","Sadness, boredom, lonely.",3.0,...,1.0,1.0,1,1165.0,690,Water polo and running,5,1,1315,135
62,3.9,2,1,610,4.0,980.0,2,"ice cream, cookies, ice cream","boredom, sadness",2.0,...,1.0,1.0,2,1165.0,850,Ice Hockey,4,1,1315,210
64,3.5,1,1,610,3.0,420.0,1,"cookies, nutella, ice cream, coffee, fruit","Bordem, happiness, sadness",2.0,...,2.0,1.0,3,940.0,500,Volleyball,5,1,760,140
67,3.6,1,1,610,2.0,420.0,1,"Ice cream, cake, mozzarella sticks, pierogies",Boredom,2.0,...,1.0,1.0,2,940.0,690,"Recreational Basketball, Equestrian Team",5,2,1315,144 lbs
68,3.2,1,1,430,3.0,315.0,1,"Chips, Mac and cheese, pizza, French fries","Stress, sadness, bored",1.0,...,1.0,1.0,4,725.0,500,soccer,5,2,760,145
70,3.73,1,1,610,3.0,980.0,2,"Broccoli, spaghetti squash, quinoa, and grille...","Bad day, bored, sadness",2.0,...,1.0,1.0,5,1165.0,500,Rec Volleyball,5,1,1315,140
73,3.79 bitch,2,1,720,4.0,420.0,2,"Chips, ice cream","Boredom, stress",2.0,...,1.0,1.0,2,1165.0,850,baseball,4,1,1315,200
75,3,1,1,610,3.0,420.0,2,"mac and cheese, potato soup, ice cream, chips ...","sadness, stressed, boredom",3.0,...,1.0,2.0,4,940.0,500,I danced in high school,4,1,900,120
76,3.7,1,2,610,3.0,420.0,1,"chocolate, pizza, and mashed potatoes",boredom and stress,2.0,...,2.0,1.0,1,1165.0,690,horse back riding,2,2,1315,150
77,3.1,2,2,265,2.0,420.0,1,Pizza cookies steak,Boredom comfort hunger,2.0,...,2.0,1.0,2,725.0,345,Basketball,2,2,900,200
78,3,1,1,720,3.0,420.0,2,"chocolate, fruit, and ice cream","stress, boredom",1.0,...,1.0,1.0,3,580.0,345,competitive skiing,4,1,1315,135
79,3.9,2,1,720,3.0,420.0,2,Chips sweets popcorn,Boredom,2.0,...,1.0,1.0,5,1165.0,850,"Rowing, Running, and Cycling",4,2,1315,145
81,3.5,1,2,610,3.0,420.0,1,"cake, French fries, chicken nuggets","boredom, sadness",2.0,...,2.0,1.0,4,725.0,500,softball and basketball,2,2,900,190
84,3.83,1,1,720,3.0,420.0,2,"Pasta dishes, Cheesecake, Pancakes","Sadness, Loneliness, Boredom",3.0,...,1.0,1.0,5,725.0,690,Collegiate Water Polo,5,1,760,167
85,2.6,1,1,265,3.0,315.0,2,"Ice cream, pizza, cookies",Mostly Stress,1.0,...,1.0,2.0,3,580.0,500,None right now,4,1,760,140
86,3,1,1,610,3.0,420.0,2,"Chinese food, moes, sponge candy, homemade las...","boredom, sadness",2.0,...,1.0,1.0,4,580.0,500,"volleyball, lacrosse",4,1,900,190
87,3.2,2,1,720,3.0,420.0,1,"pizza, pasta, mac and cheese",when i am sad or craving,3.0,...,1.0,1.0,1,1165.0,690,field hockey,4,1,1315,155
91,3.8,1,2,610,2.0,420.0,2,"Macaroni and cheese, chicken noodle soup, pizza",Boredom and stress,2.0,...,1.0,2.0,1,725.0,500,crew,1,2,900,135
96,3.92,2,1,430,3.0,420.0,2,"Ice cream, cake, pop, pizza, and milkshakes.","Happiness, sadness, celebration.",7.0,...,1.0,2.0,3,725.0,500,Soccer,2,1,900,210
103,3.7,1,1,610,3.0,420.0,2,"dark chocolate, terra chips, reese's cups(dark...","Anxiousness, watching TV I desire ""comfort food""",8.0,...,1.0,2.0,3,725.0,345,"When I can, rarely though play pool, darts, an...",5,1,760,130

In [15]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂
df_food

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,...,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,...,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,...,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,...,1.0,2.0,2,725.0,345,NaN,4,2,575,135

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [16]:
# Fix that in-place.
df_food["weight"] = pd.to_numeric(df_food["weight"], errors= "coerce")
df_food = df_food.dropna()
df_food

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155.0
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190.0
6,3.8,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.0,1.0,5,940.0,690,soccer,4,1,1315,180.0
7,3.3,1,1,720,3.0,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,...,1.0,2.0,1,725.0,500,none,4,2,1315,137.0
9,3.3,1,1,430,3.0,315.0,2,"Mac and cheese, chocolate, and pasta","Stress, anger and sadness",1.0,...,1.0,1.0,4,580.0,345,field hockey,5,1,900,125.0
10,3.5,1,1,610,3.0,980.0,2,"Pasta, grandma homemade chocolate cake anythin...",Boredom,2.0,...,1.0,1.0,2,940.0,345,soccer,5,2,900,116.0
11,3.904,1,1,720,4.0,420.0,2,"chocolate, pasta, soup, chips, popcorn","sadness, stress, cold weather",3.0,...,1.0,1.0,5,940.0,500,Running,5,1,900,110.0
12,3.4,2,1,430,3.0,420.0,2,"Cookies, popcorn, and chips","Sadness, boredom, late night snack",3.0,...,2.0,1.0,3,940.0,500,Soccer and basketball,3,2,575,264.0
13,3.6,1,1,610,3.0,420.0,2,"ice cream, cake, chocolate","stress, boredom, special occasions",1.0,...,1.0,1.0,5,1165.0,850,intramural volleyball,5,2,1315,123.0
14,3.1,2,1,610,3.0,420.0,2,"Pizza, fruit, spaghetti, chicken and Potatoes","Friends, environment and boredom",2.0,...,1.0,1.0,4,940.0,500,Hockey,5,1,900,185.0
17,3.6,2,1,430,3.0,980.0,2,"chips, cookies, ice cream",I usually only eat comfort food when I'm bored...,2.0,...,1.0,1.0,3,940.0,500,hockey,4,2,900,170.0
18,3.4,1,1,720,3.0,980.0,1,"Chocolate, ice crea","Sadness, stress",3.0,...,2.0,2.0,1,1165.0,690,dancing,5,1,1315,135.0
20,3.3,2,1,610,3.0,980.0,2,"Fast food, pizza, subs","happiness, satisfaction",7.0,...,1.0,1.0,1,1165.0,850,Soccer,3,2,1315,175.0
22,3.7,2,1,610,3.0,420.0,1,"burgers, chips, cookies","sadness, depression",3.0,...,1.0,1.0,4,940.0,850,tennis soccer gym,3,1,1315,185.0
23,3.7,2,2,610,3.0,420.0,2,"Chilli, soup, pot pie",Stress and boredom,1.0,...,1.0,1.0,4,940.0,690,Gaelic Football,4,1,1315,185.0
25,2.8,1,2,720,3.0,420.0,2,"chocolate, ice cream/milkshake, cookies",boredom,2.0,...,1.0,1.0,3,1165.0,690,Ice hockey,3,2,760,125.0
26,3.7,2,1,610,2.0,420.0,1,"Chips, ice cream, microwaveable foods","Boredom, lazyniss",2.0,...,2.0,1.0,2,1165.0,850,Hockey,3,2,1315,160.0
27,3,2,1,610,4.0,980.0,2,"Chicken fingers, pizza",Boredom,2.0,...,1.0,1.0,3,1165.0,500,Lacrosse,5,1,1315,175.0
31,4,2,1,610,3.0,420.0,2,"chips and dip, pepsi,","stres, boredom, and nighttime",1.0,...,2.0,2.0,4,940.0,690,none organized,5,1,1315,205.0
34,3.65,1,1,610,3.0,420.0,2,"french fries, chips, ice cream","boredom, stressed, sad",2.0,...,1.0,1.0,3,940.0,345,softball,4,1,1315,150.0
35,3,1,1,610,2.0,420.0,2,"mac n cheese, peanut butter and banana sandwic...",Boredom usually,2.0,...,1.0,1.0,2,940.0,690,Lacrosse,5,2,760,150.0
37,3.4,1,1,720,4.0,420.0,2,"chocolate, chips, candy",Stress,1.0,...,1.0,1.0,5,940.0,500,Dancing,4,2,1315,170.0
38,3.89,1,1,610,3.0,980.0,2,"chocolate, popcorn, ice cream","boredom, stress",2.0,...,1.0,1.0,2,1165.0,690,Lacrosse,3,2,1315,150.0
40,3.4,2,1,430,3.0,315.0,1,"Pizza, Ice cream, fries, cereal, cookies",Usually if I'm sad or depressed.,3.0,...,1.0,1.0,3,940.0,500,wrestling,4,2,760,140.0
44,3.2,1,1,610,4.0,420.0,2,"Potato chips, ice cream, chocolate, cookies","Stress, boredom, craving",1.0,...,1.0,1.0,5,725.0,500,Volleyball,5,1,760,170.0
46,3.8,2,1,430,2.0,420.0,1,"popcorn, chips, candy, & fries","sadness, boredom, & anger",3.0,...,1.0,1.0,3,725.0,345,soccer,4,2,900,168.0
51,3.3,2,1,610,4.0,980.0,1,Burger,Lazy,5.0,...,1.0,1.0,5,1165.0,500,Hockey,4,1,1315,185.0
54,3.5,2,1,610,3.0,420.0,2,"peanut butter sandwich, pretzals, garlic bread","stress, anger and boredom",1.0,...,1.0,1.0,4,940.0,690,hockey,5,1,900,165.0
56,3.8,2,1,720,4.0,315.0,2,"Pizza, Ice Cream, Chicken Wings",I usually only eat comfort foods when I am bor...,2.0,...,1.0,1.0,5,1165.0,500,Hockey,5,1,1315,175.0
57,2.8,1,1,610,4.0,980.0,2,Pizza chocolate chips bagels ice Capps,Just cause,9.0,...,2.0,1.0,2,725.0,345,softball,4,1,1315,140.0
58,3.5,1,1,610,3.0,420.0,2,"Chocolate, ice cream, pasta","Stress, boredom, sadness",1.0,...,1.0,1.0,5,1165.0,690,Skiing,5,1,1315,155.0
60,3.6,1,1,610,4.0,420.0,2,"peanut butter, dessets, pretzels.","Sadness, boredom, lonely.",3.0,...,1.0,1.0,1,1165.0,690,Water polo and running,5,1,1315,135.0
62,3.9,2,1,610,4.0,980.0,2,"ice cream, cookies, ice cream","boredom, sadness",2.0,...,1.0,1.0,2,1165.0,850,Ice Hockey,4,1,1315,210.0
64,3.5,1,1,610,3.0,420.0,1,"cookies, nutella, ice cream, coffee, fruit","Bordem, happiness, sadness",2.0,...,2.0,1.0,3,940.0,500,Volleyball,5,1,760,140.0
68,3.2,1,1,430,3.0,315.0,1,"Chips, Mac and cheese, pizza, French fries","Stress, sadness, bored",1.0,...,1.0,1.0,4,725.0,500,soccer,5,2,760,145.0
70,3.73,1,1,610,3.0,980.0,2,"Broccoli, spaghetti squash, quinoa, and grille...","Bad day, bored, sadness",2.0,...,1.0,1.0,5,1165.0,500,Rec Volleyball,5,1,1315,140.0
73,3.79 bitch,2,1,720,4.0,420.0,2,"Chips, ice cream","Boredom, stress",2.0,...,1.0,1.0,2,1165.0,850,baseball,4,1,1315,200.0
75,3,1,1,610,3.0,420.0,2,"mac and cheese, potato soup, ice cream, chips ...","sadness, stressed, boredom",3.0,...,1.0,2.0,4,940.0,500,I danced in high school,4,1,900,120.0
76,3.7,1,2,610,3.0,420.0,1,"chocolate, pizza, and mashed potatoes",boredom and stress,2.0,...,2.0,1.0,1,1165.0,690,horse back riding,2,2,1315,150.0
77,3.1,2,2,265,2.0,420.0,1,Pizza cookies steak,Boredom comfort hunger,2.0,...,2.0,1.0,2,725.0,345,Basketball,2,2,900,200.0
78,3,1,1,720,3.0,420.0,2,"chocolate, fruit, and ice cream","stress, boredom",1.0,...,1.0,1.0,3,580.0,345,competitive skiing,4,1,1315,135.0
79,3.9,2,1,720,3.0,420.0,2,Chips sweets popcorn,Boredom,2.0,...,1.0,1.0,5,1165.0,850,"Rowing, Running, and Cycling",4,2,1315,145.0
81,3.5,1,2,610,3.0,420.0,1,"cake, French fries, chicken nuggets","boredom, sadness",2.0,...,2.0,1.0,4,725.0,500,softball and basketball,2,2,900,190.0
84,3.83,1,1,720,3.0,420.0,2,"Pasta dishes, Cheesecake, Pancakes","Sadness, Loneliness, Boredom",3.0,...,1.0,1.0,5,725.0,690,Collegiate Water Polo,5,1,760,167.0
85,2.6,1,1,265,3.0,315.0,2,"Ice cream, pizza, cookies",Mostly Stress,1.0,...,1.0,2.0,3,580.0,500,None right now,4,1,760,140.0
86,3,1,1,610,3.0,420.0,2,"Chinese food, moes, sponge candy, homemade las...","boredom, sadness",2.0,...,1.0,1.0,4,580.0,500,"volleyball, lacrosse",4,1,900,190.0
87,3.2,2,1,720,3.0,420.0,1,"pizza, pasta, mac and cheese",when i am sad or craving,3.0,...,1.0,1.0,1,1165.0,690,field hockey,4,1,1315,155.0
91,3.8,1,2,610,2.0,420.0,2,"Macaroni and cheese, chicken noodle soup, pizza",Boredom and stress,2.0,...,1.0,2.0,1,725.0,500,crew,1,2,900,135.0
96,3.92,2,1,430,3.0,420.0,2,"Ice cream, cake, pop, pizza, and milkshakes.","Happiness, sadness, celebration.",7.0,...,1.0,2.0,3,725.0,500,Soccer,2,1,900,210.0
103,3.7,1,1,610,3.0,420.0,2,"dark chocolate, terra chips, reese's cups(dark...","Anxiousness, watching TV I desire ""comfort food""",8.0,...,1.0,2.0,3,725.0,345,"When I can, rarely though play pool, darts, an...",5,1,760,130.0

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [17]:
# Savey save!
df_food.to_csv("food.csv")

In [18]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.
df = pd.read_csv("food.csv")

print(df.head(5))

   Unnamed: 0    GPA  Gender  breakfast  calories_chicken  calories_day  \
0           1  3.654       1          1               610           3.0
1           4    3.5       1          1               720           2.0
2           6    3.8       2          1               610           3.0
3           7    3.3       1          1               720           3.0
4           9    3.3       1          1               430           3.0

   calories_scone  coffee                                  comfort_food  \
0           420.0       2                   chocolate, chips, ice cream
1           420.0       2                  Ice cream, chocolate, chips
2           420.0       2  Chocolate, ice cream, french fries, pretzels
3           420.0       1              Ice cream, cheeseburgers, chips.
4           315.0       2         Mac and cheese, chocolate, and pasta

                                comfort_food_reasons  ...  soup  sports  \
0                               Stress, bored, anger  ...   1.0     1.0
1                         Stress, boredom, cravings   ...   1.0     1.0
2                                    stress, boredom  ...   1.0     1.0
3  I eat comfort food when im stressed out from s...  ...   1.0     2.0
4                         Stress, anger and sadness   ...   1.0     1.0

   thai_food  tortilla_calories turkey_calories   type_sports  veggies_day  \
0          2              725.0             690   Basketball             4
1          4              940.0             500      Softball            4
2          5              940.0             690        soccer            4
3          1              725.0             500          none            4
4          4              580.0             345  field hockey            5

  vitamins  waffle_calories  weight
0        2              900   155.0
1        2              760   190.0
2        1             1315   180.0
3        2             1315   137.0
4        1              900   125.0

[5 rows x 62 columns]

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [19]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.

df_manager = pd.read_csv('../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv', sep='\t')
df_manager

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28057,7/12/2024 22:52:01,35-44,Health care,Veterinarian,NaN,135000,NaN,USD,NaN,NaN,United States,Missouri,Wentzville,11 - 20 years,11 - 20 years,"Professional degree (MD, JD, etc.)",Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28059,7/24/2024 12:22:58,18-24,"Accounting, Banking & Finance",Risk Management Associate,NaN,1200,0.0,USD,NaN,NaN,Myanmar,Colorado,Yangon,2 - 4 years,2 - 4 years,Some college,Man,Asian or Asian American
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American
28061,8/20/2024 1:06:13,25-34,Health care,Clinical physiologist,NaN,1200000,NaN,Other,NGN,NaN,Nigeria,NaN,Lagos,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [20]:
# Count by hand. I’m dead serious.
df_manager.shape

# I will not be counting by hand

(28062, 18)

What are the columns and their types?

In [21]:
# Show the column names and their types.
df_manager.dtypes

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [22]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race

df_manager.columns = ['timestamp', 'age', 'industry', 'job_title', 'title_context', 'salary', 'additional_compensation', 'currency', 'other_currency', 'salary_context', 'country', 'state', 'city', 'total_yoe', 'field_yoe', 'highest_education_completed', 'gender', 'race']
df_manager.columns

Index(['timestamp', 'age', 'industry', 'job_title', 'title_context', 'salary',
       'additional_compensation', 'currency', 'other_currency',
       'salary_context', 'country', 'state', 'city', 'total_yoe', 'field_yoe',
       'highest_education_completed', 'gender', 'race'],
      dtype='str')

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [23]:
# List the unique industries and a count of their instances.

df_manager['industry'].value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [24]:
# Filtery filter.

df_salary_tech = df_manager[df_manager['industry'] == 'Computing or Tech']

df_salary_tech

,timestamp,age,industry,job_title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28050,7/1/2024 13:38:46,25-34,Computing or Tech,Research & Systems Technician Data Analytics,NaN,22000,NaN,EUR,NaN,NaN,Spain,NaN,Barcelona,2 - 4 years,2 - 4 years,College degree,Man,"Hispanic, Latino, or Spanish origin"
28051,7/1/2024 20:05:58,25-34,Computing or Tech,Junior data analyst,NaN,35000,15000.0,USD,NaN,NaN,Usa,Alabama,Alabama,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American
28052,7/3/2024 14:02:01,25-34,Computing or Tech,Senior Global Public Relations Manager,NaN,144000,15000.0,USD,NaN,NaN,Usa,Massachusetts,Boise-but remote. Company located in Boston,8 - 10 years,8 - 10 years,Master's degree,Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American

Do a sanity check by counting.

In [25]:
# Sanity check count.
len(df_salary_tech)

4699

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [26]:
# Filtery filter (in place) for just the jobs that pay in USD!

df_salary_tech = df_salary_tech[df_salary_tech['currency'] == 'USD']

df_salary_tech

,timestamp,age,industry,job_title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,USA,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28044,6/3/2024 16:15:43,18-24,Computing or Tech,Research Data Analyst Associate,NaN,60000,0.0,USD,NaN,NaN,United States,Illinois,Evanston,2 - 4 years,1 year or less,College degree,Woman,White
28051,7/1/2024 20:05:58,25-34,Computing or Tech,Junior data analyst,NaN,35000,15000.0,USD,NaN,NaN,Usa,Alabama,Alabama,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American
28052,7/3/2024 14:02:01,25-34,Computing or Tech,Senior Global Public Relations Manager,NaN,144000,15000.0,USD,NaN,NaN,Usa,Massachusetts,Boise-but remote. Company located in Boston,8 - 10 years,8 - 10 years,Master's degree,Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [27]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary_tech['country'].value_counts()

country
United States                1576
USA                          1222
US                            412
U.S.                          108
United States of America       90
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [28]:
# Replace them all in-place with 'US'.
lf = ['United States', 'USA', 'U.S.', 'United States of America', 'United States']
mask = df_salary_tech['country'].isin(lf)
df_salary_tech.loc[mask, 'country'] = 'US'

Have a look at the count of each unique country again now.

In [29]:
# Count again.

df_salary_tech['country'].value_counts()

country
US                           3408
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

Did you notice anything interesting?

In [30]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.
lf = ['united states', 'usa', 'united states of america', 'us']
df_salary_tech['country'] = df_salary_tech['country'].str.strip().str.lower().str.replace('.', '')

mask = df_salary_tech['country'].isin(lf)
df_salary_tech.loc[mask, 'country'] = 'US'

In [31]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

df_salary_tech['country'].value_counts()

country
US                         3710
canada                        5
israel                        5
united state of america       2
unite states                  2
australia                     2
unitedstates                  2
india                         2
singapore                     2
spain                         2
brazil                        2
united kingdom                2
new zealand                   2
poland                        2
france                        2
denmark                       2
nigeria                       2
uniyed states                 1
america                       1
puerto rico                   1
united state                  1
cuba                          1
danmark                       1
italy                         1
international                 1
united stated                 1
remote (philippines)          1
uruguay                       1
mexico                        1
united stateds                1
isa                           1
pakistan                      1
netherlands                   1
china                         1
san francisco                 1
romania                       1
japan                         1
united stares                 1
australian                    1
jamaica                       1
unites states                 1
thailand                      1
colombia                      1
ghana                         1
ss                            1
burma                         1
Name: count, dtype: int64

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [32]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
mask = df_salary_tech['country'] == 'US'

df_salary_tech[mask].groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

TypeError: dtype 'str' does not support operation 'mean'

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [33]:
# Fix it in-place.
df_salary_tech['salary'] = pd.to_numeric(df_salary_tech['salary'].str.replace(',', ''), errors = "coerce")

df_salary_tech['salary']

8        112000
43       187500
44       110000
46       144600
47       200850
          ...
28044     60000
28051     35000
28052    144000
28058    109000
28060      1700
Name: salary, Length: 3777, dtype: int64

Let’s try that again.

In [34]:
# Try it again. Yeah!
mask = df_salary_tech['country'] == 'US'

df_salary_tech[mask].groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Florida                          28800  157457.232143  2600000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  155224.893130   875000
Washington                          72  151372.923077   950000
New York                         14000  148157.669540   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135018.880795  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127370.512821   450000
Colorado                         45000  127048.895833   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119268.242604   315000
Georgia                          29120  117893.098765   250000
Maryland                         51260  117862.370370   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114268.000000   920000
Texas                            10700  113909.713004   280000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  106752.793103   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
Massachusetts, New Hampshire    105000  105000.000000   105000
New York, Texas                 105000  105000.000000   105000
North Carolina                   29000  104972.127273   260000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
South Carolina                   40000  102111.111111   205000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   97723.055556   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
New Hampshire                       55   93003.437500   193000
Alabama                          29120   92510.000000   350000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Massachusetts, Pennsylvania      83000   83000.000000    83000
Arkansas                         55000   81682.300000   144000
California, Maryland             81500   81500.000000    81500
Louisiana                        35360   76596.000000   110000
Alabama, Montana                 72000   72000.000000    72000

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [35]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_salary_tech['timestamp'] = pd.to_datetime(df_salary_tech['timestamp'])

mask = (df_salary_tech['country'] == 'US') & (df_salary_tech['timestamp'].dt.year.isin([2021, 2022, 2023]))
df_salary_recent = df_salary_tech[mask]

df_salary_recent.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  155355.206422   875000
Washington                          72  151521.952522   950000
New York                         14000  148157.669540   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  134989.043189  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127370.512821   450000
Colorado                         45000  127048.895833   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119621.029762   315000
Georgia                          29120  118004.262500   250000
Maryland                         51260  117862.370370   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114268.000000   920000
Texas                            10700  113909.713004   280000
Florida                          28800  113047.363636   400000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
South Carolina                   40000  109875.000000   205000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  107063.872093   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
New York, Texas                 105000  105000.000000   105000
Massachusetts, New Hampshire    105000  105000.000000   105000
North Carolina                   29000  104880.128440   260000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Alabama                          29120   97738.181818   350000
Michigan                         36800   97723.055556   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
New Hampshire                       55   93003.437500   193000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Massachusetts, Pennsylvania      83000   83000.000000    83000
Arkansas                         55000   81682.300000   144000
California, Maryland             81500   81500.000000    81500
Louisiana                        35360   76596.000000   110000
Alabama, Montana                 72000   72000.000000    72000

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

In [36]:
df_salary = df_manager[df_manager['currency'] == 'USD']

lf = ['United States', 'USA', 'U.S.', 'United States of America', 'US']
mask = df_salary['country'].isin(lf)
df_salary.loc[mask, 'country'] = 'US'

df_salary['salary'] = pd.to_numeric(df_salary['salary'].str.replace(',', ''), errors = "coerce")

mask = df_salary['country'] == 'US'
df_salary_summary = df_salary[mask].groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

df_salary_summary

                                                       min      mean     max
state
Indiana, Ohio                                       245000  245000.0  245000
Colorado, Nevada                                    190000  190000.0  190000
California, Montana                                 185000  185000.0  185000
California, Texas                                   185000  185000.0  185000
Alabama, District of Columbia                       156000  156000.0  156000
...                                                    ...       ...     ...
Illinois, Kentucky                                   41000   41000.0   41000
Delaware, Pennsylvania                               35000   35000.0   35000
District of Columbia, Washington                     35000   35000.0   35000
District of Columbia, Maryland, Pennsylvania, V...   27040   27040.0   27040
Maryland, New York                                   14000   14000.0   14000

[113 rows x 3 columns]

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

In [37]:
df_salary_summary.style.format('${:,.2f}')

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

In [38]:
mask = (df_salary['country'] == 'US') & (~df_salary['state'].str.contains(',', na=False))
df_salary_single = df_salary[mask]

df_salary_single.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

                        min           mean      max
state
California                0  115416.542344   875000
Washington               72  107865.241088  1260000
District of Columbia     40  107231.447339  1334782
New York                 80  105591.720144  3000000
Massachusetts          4100   98247.338996  1650000
Connecticut               0   95868.565000  1900000
Virginia                 57   94481.754986  1300000
Illinois                  0   90219.231350  1100000
Oregon                    0   89754.292115   320000
Colorado                 65   89316.395018   630000
Maryland                 58   89096.098790   323000
Texas                     0   89092.663384  1200000
New Jersey            14850   88784.956268   400000
Utah                  18720   87845.978261   576000
Delaware              35000   86526.285714   220000
Georgia                   0   85978.928721   415000
New Mexico              130   85342.759494   300000
Hawaii                30000   84041.000000   500000
Pennsylvania           1000   83746.695706  1100000
Florida                 150   83702.142232  2600000
Minnesota                40   82880.283951   321250
North Carolina         4000   81323.041199   560000
Arizona               12000   80279.945312   380000
Rhode Island          18000   78131.538462   200000
Alaska                27040   77247.363636   158000
Nevada                   55   77210.105882   200000
Wisconsin                 1   76830.484561   920000
Michigan                 55   76599.506198   500000
Tennessee             20800   76249.400000   657900
Missouri                 70   75185.158451   335000
Indiana               12600   74676.868794   925000
New Hampshire            55   73555.481481   208000
Nebraska              18000   73431.829787   224000
Kansas                   52   73365.220588   734400
Ohio                     36   73221.388401   283000
Vermont               24960   71971.379310   200000
Louisiana             17000   71433.241071   253300
Alabama                  54   70833.504762   235000
Iowa                  13000   68002.754601   200000
Idaho                    38   67924.602273   312000
Kentucky                  0   67901.308642   208000
Arkansas              26000   66940.965517   190000
South Dakota          29000   66869.476190   150000
Oklahoma              18000   66318.311321   180000
South Carolina            0   65519.000000   250000
Maine                 22000   65373.412281   132999
North Dakota          29120   64080.846154   150000
Montana               19200   63198.894737   172000
Wyoming               29000   62194.388889   140000
West Virginia             0   59575.861111   125000
Mississippi           25000   59341.428571   130000

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)

In [39]:
df_salary_single.groupby('state')['salary'].describe(percentiles=[0.05, 0.25, 0.5, 0.75, 0.95]).sort_values('50%', ascending=False)

,count,mean,std,min,5%,25%,50%,75%,95%,max
state,,,,,,,,,,
California,2338.0,115416.542344,63008.385938,0.0,42544.00,72000.00,102000.0,149000.00,220000.00,875000.0
Washington,1066.0,107865.241088,74500.888671,72.0,40000.00,66125.00,91100.0,135800.00,205000.00,1260000.0
District of Columbia,883.0,107231.447339,90731.371535,40.0,48000.00,67000.00,90000.0,125000.00,189900.00,1334782.0
New York,1951.0,105591.720144,87989.670813,80.0,41100.00,64587.50,90000.0,129850.00,210500.00,3000000.0
Massachusetts,1354.0,98247.338996,63889.194414,4100.0,42416.90,64000.00,85000.0,120000.00,180000.00,1650000.0
Connecticut,200.0,95868.565000,134440.012808,0.0,33957.50,62000.00,82737.5,100000.00,175250.00,1900000.0
Maryland,496.0,89096.098790,40453.585657,58.0,39750.00,60000.00,82000.0,110000.00,162750.00,323000.0
Delaware,42.0,86526.285714,39139.097327,35000.0,41620.80,58869.75,81322.5,105750.00,149740.50,220000.0
Virginia,702.0,94481.754986,68505.213399,57.0,38214.00,59011.00,80000.0,114850.00,180000.00,1300000.0
Oregon,558.0,89754.292115,45882.185041,0.0,36000.00,60000.00,79000.0,110000.00,188900.00,320000.0
Illinois,1059.0,90219.231350,62255.884813,0.0,37360.00,55650.00,76000.0,110000.00,175000.00,1100000.0
Texas,1117.0,89092.663384,59375.161196,0.0,35360.00,55000.00,76000.0,110000.00,175000.00,1200000.0
Minnesota,648.0,82880.283951,37903.471475,40.0,40000.00,56000.00,75000.0,101324.25,150650.00,321250.0
Colorado,562.0,89316.395018,52600.603150,65.0,38024.00,58000.00,75000.0,106935.50,167900.00,630000.0
Georgia,477.0,85978.928721,49824.166461,0.0,32000.00,53000.00,75000.0,108000.00,173400.00,415000.0
New Jersey,343.0,88784.956268,48603.912841,14850.0,37050.00,58000.00,75000.0,105750.00,175900.00,400000.0
Rhode Island,65.0,78131.538462,35668.065375,18000.0,34520.00,48925.00,74000.0,99000.00,128600.00,200000.0
North Carolina,534.0,81323.041199,44628.855728,4000.0,34364.20,51294.50,73500.0,99375.00,150000.00,560000.0
Alaska,55.0,77247.363636,27367.772352,27040.0,37000.00,63500.00,73000.0,90000.00,134160.00,158000.0
Utah,184.0,87845.978261,58000.023880,18720.0,35756.00,55000.00,72653.5,105000.00,175850.00,576000.0
New Mexico,79.0,85342.759494,48860.786345,130.0,34900.00,53500.00,72000.0,114350.00,177230.10,300000.0
Pennsylvania,815.0,83746.695706,59646.748994,1000.0,33644.00,52000.00,71000.0,100400.00,167570.00,1100000.0
Nevada,85.0,77210.105882,38712.111593,55.0,32128.40,50000.00,70000.0,95000.00,160400.00,200000.0
Wisconsin,421.0,76830.484561,54443.129215,1.0,34000.00,50000.00,68640.0,90000.00,145000.00,920000.0
Michigan,484.0,76599.506198,40583.843400,55.0,33280.00,53000.00,68000.0,91175.00,147550.00,500000.0
Florida,457.0,83702.142232,127775.148395,150.0,31160.00,47840.00,67500.0,97500.00,160400.00,2600000.0
Nebraska,94.0,73431.829787,36197.374964,18000.0,32317.85,46240.00,66150.0,90089.25,140000.00,224000.0
Ohio,569.0,73221.388401,35472.481874,36.0,32504.00,50000.00,66000.0,87552.00,140000.00,283000.0
Arizona,256.0,80279.945312,45298.691272,12000.0,34000.00,50000.00,65500.0,100250.00,160000.00,380000.0
New Hampshire,108.0,73555.481481,37308.165755,55.0,30997.20,46600.00,65474.5,89250.00,144067.25,208000.0
Hawaii,24.0,84041.000000,91796.032592,30000.0,32583.00,53750.00,65300.0,80000.00,135700.00,500000.0
Louisiana,112.0,71433.241071,36751.690364,17000.0,30704.00,47625.00,65260.0,84250.00,148350.00,253300.0
Missouri,284.0,75185.158451,40571.658815,70.0,30500.00,48000.00,65000.0,94625.00,146700.00,335000.0
Indiana,282.0,74676.868794,59363.938073,12600.0,35000.00,51250.00,65000.0,85925.00,135190.00,925000.0
Alabama,105.0,70833.504762,37707.092885,54.0,28215.60,49500.00,64000.0,85000.00,135000.00,235000.0
Tennessee,255.0,76249.400000,54706.248542,20800.0,32459.20,47275.00,64000.0,88754.50,148600.00,657900.0
Vermont,58.0,71971.379310,34029.660860,24960.0,32700.00,50000.00,63500.0,89187.50,125750.00,200000.0
Iowa,163.0,68002.754601,30841.344980,13000.0,30167.80,47840.00,62286.0,80500.00,120594.00,200000.0
South Dakota,21.0,66869.476190,33257.275727,29000.0,31200.00,45750.00,62000.0,78500.00,131000.00,150000.0
Kansas,136.0,73365.220588,64419.529768,52.0,32919.00,46625.00,61669.0,81250.00,126250.00,734400.0
Kentucky,162.0,67901.308642,34126.835182,0.0,29287.50,45059.25,61000.0,80000.00,130000.00,208000.0
Idaho,88.0,67924.602273,40531.494235,38.0,30420.00,45940.00,60000.0,76500.00,130000.00,312000.0
Maine,114.0,65373.412281,26247.001240,22000.0,35495.20,43625.00,59250.0,84750.00,114350.00,132999.0
Arkansas,58.0,66940.965517,32491.206564,26000.0,31445.00,45820.00,56500.0,77344.25,123600.00,190000.0
South Carolina,131.0,65519.000000,35899.748355,0.0,29120.00,43280.00,56500.0,79500.00,126297.50,250000.0
North Dakota,26.0,64080.846154,29004.986596,29120.0,33762.50,45190.00,56080.0,73930.00,126250.00,150000.0
Oklahoma,106.0,66318.311321,35484.040324,18000.0,28902.00,43236.00,53500.0,80000.00,146750.00,180000.0
Montana,57.0,63198.894737,32590.410673,19200.0,33206.40,39000.00,52000.0,85000.00,128400.00,172000.0
Mississippi,42.0,59341.428571,28250.312794,25000.0,31010.00,36465.75,51898.5,78750.00,119200.00,130000.0
Wyoming,18.0,62194.388889,28377.618321,29000.0,31046.80,43125.00,50772.5,80250.00,104300.00,140000.0
West Virginia,36.0,59575.861111,31040.417361,0.0,21008.75,41750.00,49544.0,72300.00,118137.00,125000.0