# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

In [2]:
# Load the Food choices data set into a variable (e.g., df_food).

food_data_set_path = '/workspaces/ds-fall-2026/Week-02-Pandas-and-How-to-Make-a-Sick-Project/data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [3]:
# Count by hand. (lol kidding)
len(df_food)

125

What are the columns and their types in this data set?

In [4]:
# Show the column names and their types.
df_food.info()

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    str
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    str
 8   comfort_food_reasons          123 non-null    str
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    str
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    str
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    str
 25  fav_cuisine                   123 non-null    str
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    str
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    str
 35  ideal_diet                    124 non-null    str
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    str
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    str
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     str
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    str
dtypes: float64(20), int64(27), str(14)
memory usage: 59.7 KB

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns?

In [5]:
# Remove ‘em.
cols = ['calories_day', 'Gender', 'weight']

df_filtered_food = df_food[cols]

In [6]:
df_filtered_food

     calories_day  Gender                    weight
0             NaN       2                       187
1             3.0       1                       155
2             4.0       1  I'm not answering this.
3             3.0       1             Not sure, 240
4             2.0       1                       190
..            ...     ...                       ...
120           4.0       1                       156
121           2.0       1                       180
122           NaN       1                       120
123           4.0       2                       135
124           NaN       1                       135

[125 rows x 3 columns]

What about `NaN`s? How many are there?

In [62]:
# Count ‘em.
total_nan = df_food.isna().sum().sum()
filtered_nan = df_filtered_food.isna().sum().sum()
print(f"Total: {total_nan}")
print(f"Filtered: {filtered_nan}")

Total: 149
Filtered: 21

We gotta remove those `NaN`s―the entire row.

In [7]:
# Drop ‘em.
df_food_NAN = df_filtered_food.dropna()

df_food_NAN

     calories_day  Gender                    weight
1             3.0       1                       155
2             4.0       1  I'm not answering this.
3             3.0       1             Not sure, 240
4             2.0       1                       190
5             3.0       1                       190
..            ...     ...                       ...
118           3.0       1                       140
119           3.0       2                       185
120           4.0       1                       156
121           2.0       1                       180
123           4.0       2                       135

[104 rows x 3 columns]

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [ ]:
# Fix that.
df_food_NAN['weight'] = pd.to_numeric(df_food_NAN['weight'], errors="coerce")
df_final = df_food_NAN.dropna()

     calories_day  Gender  weight
1             3.0       1   155.0
4             2.0       1   190.0
5             3.0       1   190.0
6             3.0       2   180.0
7             3.0       1   137.0
..            ...     ...     ...
118           3.0       1   140.0
119           3.0       2   185.0
120           4.0       1   156.0
121           2.0       1   180.0
123           4.0       2   135.0

[101 rows x 3 columns]

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [ ]:
# Savey save!
# file_path = "/workspaces/ds-fall-2026/Week-02-Pandas-and-How-to-Make-a-Sick-Project/data/clean.csv"
# df_final.to_csv(file_path, index=False)

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

In [13]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set into a variable (e.g., df_salary).
file_path = "/workspaces/ds-fall-2026/Week-02-Pandas-and-How-to-Make-a-Sick-Project/data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv"
df_salary = pd.read_csv(file_path, sep='\t')

Was that hard? 🙃

#### rename the file to something that is better for all systems.  
* No spaces in filename (can use '_')
* all lower case

### Explore

You know the drill.

How much data did you just load?

In [14]:
# Count by hand. I’m dead serious.
len(df_salary)

28062

What are the columns and their types?

In [15]:
# Show the column names and their types.
df_salary.info()

<class 'pandas.DataFrame'>
RangeIndex: 28062 entries, 0 to 28061
Data columns (total 18 columns):
 #   Column                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                --------------  -----
 0   Timestamp                                                                                                                                                                                                                             28062 non-null  str
 1   How old are you?                                                                                                                                                                                                                      28062 non-null  str
 2   What industry do you work in?                                                                                                                                                                                                         27988 non-null  str
 3   Job title                                                                                                                                                                                                                             28061 non-null  str
 4   If your job title needs additional context, please clarify here:                                                                                                                                                                      7262 non-null   str
 5   What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)  28062 non-null  str
 6   How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                        20766 non-null  float64
 7   Please indicate the currency                                                                                                                                                                                                          28062 non-null  str
 8   If "Other," please indicate the currency here:                                                                                                                                                                                        206 non-null    str
 9   If your income needs additional context, please provide it here:                                                                                                                                                                      3042 non-null   str
 10  What country do you work in?                                                                                                                                                                                                          28062 non-null  str
 11  If you're in the U.S., what state do you work in?                                                                                                                                                                                     23039 non-null  str
 12  What city do you work in?                                                                                                                                                                                                             27980 non-null  str
 13  How many years of professional work experience do you have overall?                                                                                                                                                                   28062 non-null  str
 14  How many years of professional work experience do you have in your field?                                                                                                                                                             28062 non-null  str
 15  What is your highest level of education completed?                                                                                                                                                                                    27840 non-null  str
 16  What is your gender?                                                                                                                                                                                                                  27891 non-null  str
 17  What is your race? (Choose all that apply.)                                                                                                                                                                                           27885 non-null  str
dtypes: float64(1), str(17)
memory usage: 3.9 MB

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [19]:
# Rename ‘em.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed, gender, race
df_salary.columns = ["timestamp", "age", "industry", "title", "title_context", "salary", "additional_compensation", "currency", "other_currency", "salary_context", "country", "state", "city", "total_yoe", "field_yoe", "highest_education_completed", "gender", "race"]
df_salary.info()

<class 'pandas.DataFrame'>
RangeIndex: 28062 entries, 0 to 28061
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   timestamp                    28062 non-null  str
 1   age                          28062 non-null  str
 2   industry                     27988 non-null  str
 3   title                        28061 non-null  str
 4   title_context                7262 non-null   str
 5   salary                       28062 non-null  str
 6   additional_compensation      20766 non-null  float64
 7   currency                     28062 non-null  str
 8   other_currency               206 non-null    str
 9   salary_context               3042 non-null   str
 10  country                      28062 non-null  str
 11  state                        23039 non-null  str
 12  city                         27980 non-null  str
 13  total_yoe                    28062 non-null  str
 14  field_yoe                    28062 non-null  str
 15  highest_education_completed  27840 non-null  str
 16  gender                       27891 non-null  str
 17  race                         27885 non-null  str
dtypes: float64(1), str(17)
memory usage: 3.9 MB

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [ ]:
# List the unique industries and a count of their instances.
df_salary["industry"].value_counts()
# "Computing or Tech" corresponds to that industry

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new dataframe.

In [ ]:
# Filtery filter. (Save it to a new variable, df_salary_tech.)
tech_mask = df_salary["industry"] == "Computing or Tech"
df_salary_tech = df_salary[tech_mask]

Do a sanity check to make sure that the only values you kept are the one you are filtered for.

In [ ]:
# Sanity Check 
df_salary_tech["industry"].value_counts()
# should be correct b/c no other industries are present in value_count

industry
Computing or Tech    4699
Name: count, dtype: int64

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [ ]:
# Filtery filter for just the jobs that pay in USD!
usd_mask = df_salary_tech["currency"] == "USD"
df_salary_tech_usd = df_salary_tech[usd_mask] 
#df_salary_tech_usd["currency"].value_counts()

currency
USD    3777
Name: count, dtype: int64

What we really want know is how each U.S. city pays in tech. What value in `country` represents the United States of America?

In [ ]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary_tech_usd["country"].value_counts(ascending=False)

country
United States               1576
USA                         1222
US                           412
U.S.                         108
United States of America      90
                            ...
Ghana                          1
Nigeria                        1
ss                             1
Nigeria                        1
Burma                          1
Name: count, Length: 76, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [36]:
# Replace them all with 'US'.
top_five_us = {
    "United States": "US",
    "USA": "US", 
    "US": "US", 
    "U.S.": "US",
    "United States of America": "US",
}

df_salary_tech_usd["country"] = df_salary_tech_usd["country"].replace(top_five_us)

Have a look at the count of each unique country again now.

In [35]:
# Count again.
df_salary_tech_usd["country"].value_counts(ascending=False)

country
US                3408
United States       68
Usa                 59
USA                 56
usa                 28
                  ...
Ghana                1
Nigeria              1
ss                   1
Nigeria              1
Burma                1
Name: count, Length: 72, dtype: int64

Did you notice anything interesting?

In [ ]:
# BONUS CREDIT: resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.
# AI regex pattern pretty cool 
regex_pattern = r'(?i)^\s*(u\.?s\.?a?|united\s*states.*)\s*$'

df_salary_tech_usd['country'] = df_salary_tech_usd['country'].replace(regex_pattern, 'US', regex=True)

In [42]:
# BONUS CREDIT: if you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.
df_salary_tech_usd['country'].value_counts(ascending=False)

country
US                         3712
Israel                        5
Canada                        4
United State of America       2
Unite States                  2
Australia                     2
India                         2
Spain                         2
Brazil                        2
United Kingdom                2
New Zealand                   2
Poland                        2
France                        2
Uniyed states                 1
America                       1
Puerto Rico                   1
United State                  1
Cuba                          1
Danmark                       1
Italy                         1
International                 1
United Stated                 1
Remote (philippines)          1
Singapore                     1
Uruguay                       1
Mexico                        1
Canada                        1
United Stateds                1
ISA                           1
singapore                     1
Pakistan                      1
Netherlands                   1
China                         1
San Francisco                 1
Romania                       1
Japan                         1
United Stares                 1
Australian                    1
Denmark                       1
Jamaica                       1
Unites States                 1
Thailand                      1
Colombia                      1
denmark                       1
Ghana                         1
Nigeria                       1
ss                            1
Nigeria                       1
Burma                         1
Name: count, dtype: int64

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [59]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
# I accidentally reran this and it gave the correct output now because "salary" is filtered but it should actually have given a error here
functions = ["min", "mean", "max"]

country_mask = df_salary_tech_usd["country"] == "US" 
df_salary_tech_usd = df_salary_tech_usd[country_mask]

df_salary_tech_usd.groupby("state")["salary"].agg(functions)

                                    min           mean       max
state
Alabama                         35000.0  117400.000000  350000.0
Alabama, District of Columbia       NaN            NaN       NaN
Alabama, Montana                    NaN            NaN       NaN
Alaska                              NaN            NaN       NaN
Arizona                         35000.0   97833.333333  145000.0
...                                 ...            ...       ...
Vermont                         91250.0  105625.000000  120000.0
Virginia                        58750.0  115086.696970  378000.0
Washington                         72.0  136923.916667  300000.0
West Virginia                  120000.0  120000.000000  120000.0
Wisconsin                           1.0  145806.888889  920000.0

[66 rows x 3 columns]

Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed.

In [ ]:
# Fix it.
df_salary_tech_usd["salary"] = pd.to_numeric(df_salary_tech_usd["salary"], errors="coerce")
df_salary_tech_usd["salary"] = df_salary_tech_usd["salary"].dropna()

Let’s try that again.

In [58]:
# Try it again. Yeah!
df_salary_tech_usd.groupby("state")["salary"].agg(functions)

                                    min           mean       max
state
Alabama                         35000.0  117400.000000  350000.0
Alabama, District of Columbia       NaN            NaN       NaN
Alabama, Montana                    NaN            NaN       NaN
Alaska                              NaN            NaN       NaN
Arizona                         35000.0   97833.333333  145000.0
...                                 ...            ...       ...
Vermont                         91250.0  105625.000000  120000.0
Virginia                        58750.0  115086.696970  378000.0
Washington                         72.0  136923.916667  300000.0
West Virginia                  120000.0  120000.000000  120000.0
Wisconsin                           1.0  145806.888889  920000.0

[66 rows x 3 columns]

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [83]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
years = ["2021", "2022", "2023"]
year_mask = df_salary_tech_usd["timestamp"].str.split(" ").str[0].str[-4:].isin(years)

df_salary_tech_usd[year_mask].groupby("state")["salary"].agg(functions)

                                    min           mean       max
state
Alabama                         52000.0  138000.000000  350000.0
Alabama, District of Columbia       NaN            NaN       NaN
Alabama, Montana                    NaN            NaN       NaN
Alaska                              NaN            NaN       NaN
Arizona                         35000.0   97833.333333  145000.0
...                                 ...            ...       ...
Vermont                         91250.0  105625.000000  120000.0
Virginia                        58750.0  115086.696970  378000.0
Washington                         72.0  137427.774648  300000.0
West Virginia                  120000.0  120000.000000  120000.0
Wisconsin                           1.0  145806.888889  920000.0

[66 rows x 3 columns]

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

In [ ]:
# Delware and west virgina have same mean max and min meaning only one entry for those states
state_summary = df_salary_tech_usd[year_mask].groupby("state")["salary"].agg(functions)
virgina_summary = state_summary.loc["West Virginia"]
delware_summary = state_summary.loc["Delaware"]
print(virgina_summary)
print(delware_summary)

min     120000.0
mean    120000.0
max     120000.0
Name: West Virginia, dtype: float64
min     169000.0
mean    169000.0
max     169000.0
Name: Delaware, dtype: float64

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)