# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [154]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy in /usr/local/python/3.14.2/lib/python3.14/site-packages (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [155]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [156]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'
df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [157]:
# Count by hand. (lol kidding)
print(f"Columns, Rows: {df_food.shape}")
print(f"Number of cells: {df_food.size}")

Columns, Rows: (125, 61)
Number of cells: 7625

In [158]:
# Try to print or display it nicely.
df_food.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190

What are the columns and their types in this data set?

In [159]:
# Show the column names and their types.
df_food.info()

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    str
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    str
 8   comfort_food_reasons          123 non-null    str
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    str
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    str
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    str
 25  fav_cuisine                   123 non-null    str
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    str
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    str
 35  ideal_diet                    124 non-null    str
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    str
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    str
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     str
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    str
dtypes: float64(20), int64(27), str(14)
memory usage: 59.7 KB

In [160]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
# Convert column metadata into a DataFrame
df_info = pd.DataFrame(df_food.dtypes, columns=['Data Type'])
df_info

                             Data Type
GPA                                str
Gender                           int64
breakfast                        int64
calories_chicken                 int64
calories_day                   float64
calories_scone                 float64
coffee                           int64
comfort_food                       str
comfort_food_reasons               str
comfort_food_reasons_coded     float64
cook                           float64
comfort_food_reasons_coded.1     int64
cuisine                        float64
diet_current                       str
diet_current_coded               int64
drink                          float64
eating_changes                     str
eating_changes_coded             int64
eating_changes_coded1            int64
eating_out                       int64
employment                     float64
ethnic_food                      int64
exercise                       float64
father_education               float64
father_profession                  str
fav_cuisine                        str
fav_cuisine_coded                int64
fav_food                       float64
food_childhood                     str
fries                            int64
fruit_day                        int64
grade_level                      int64
greek_food                       int64
healthy_feeling                  int64
healthy_meal                       str
ideal_diet                         str
ideal_diet_coded                 int64
income                         float64
indian_food                      int64
italian_food                     int64
life_rewarding                 float64
marital_status                 float64
meals_dinner_friend                str
mother_education               float64
mother_profession                  str
nutritional_check                int64
on_off_campus                  float64
parents_cook                     int64
pay_meal_out                     int64
persian_food                   float64
self_perception_weight         float64
soup                           float64
sports                         float64
thai_food                        int64
tortilla_calories              float64
turkey_calories                  int64
type_sports                        str
veggies_day                      int64
vitamins                         int64
waffle_calories                  int64
weight                             str

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [161]:
# Remove ‘em.
subset = ['calories_day', 'weight', 'Gender']
df_food_col_subset = df_food[subset]
df_food_col_subset

     calories_day                    weight  Gender
0             NaN                       187       2
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
..            ...                       ...     ...
120           4.0                       156       1
121           2.0                       180       1
122           NaN                       120       1
123           4.0                       135       2
124           NaN                       135       1

[125 rows x 3 columns]

In [162]:
# Is there a second way to remove columns?
df_food_col_subset = df_food[['calories_day', 'weight', 'Gender']]
df_food_col_subset

     calories_day                    weight  Gender
0             NaN                       187       2
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
..            ...                       ...     ...
120           4.0                       156       1
121           2.0                       180       1
122           NaN                       120       1
123           4.0                       135       2
124           NaN                       135       1

[125 rows x 3 columns]

In [163]:
# 🚀 Extra credit: What about a third way to remove columns?

What about `NaN`s? How many are there?

In [164]:
# Count ‘em.
df_food.isna().sum().sum()

np.int64(149)

In [165]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.
df_Nan = df_food.isna().sum().to_frame(name='NaN Count')
df_Nan

                              NaN Count
GPA                                   2
Gender                                0
breakfast                             0
calories_chicken                      0
calories_day                         19
calories_scone                        1
coffee                                0
comfort_food                          1
comfort_food_reasons                  2
comfort_food_reasons_coded           19
cook                                  3
comfort_food_reasons_coded.1          0
cuisine                              17
diet_current                          1
diet_current_coded                    0
drink                                 2
eating_changes                        3
eating_changes_coded                  0
eating_changes_coded1                 0
eating_out                            0
employment                            9
ethnic_food                           0
exercise                             13
father_education                      1
father_profession                     3
fav_cuisine                           2
fav_cuisine_coded                     0
fav_food                              2
food_childhood                        1
fries                                 0
fruit_day                             0
grade_level                           0
greek_food                            0
healthy_feeling                       0
healthy_meal                          1
ideal_diet                            1
ideal_diet_coded                      0
income                                1
indian_food                           0
italian_food                          0
life_rewarding                        1
marital_status                        1
meals_dinner_friend                   3
mother_education                      3
mother_profession                     2
nutritional_check                     0
on_off_campus                         1
parents_cook                          0
pay_meal_out                          0
persian_food                          1
self_perception_weight                1
soup                                  1
sports                                2
thai_food                             0
tortilla_calories                     1
turkey_calories                       0
type_sports                          26
veggies_day                           0
vitamins                              0
waffle_calories                       0
weight                                2

In [166]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

We gotta remove those `NaN`s―the entire row.

In [167]:
# Drop ‘em in-place.
df_food.dropna(inplace=True)

In [168]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂
print(f"Columns, Rows: {df_food.shape}")
print(f"Number of cells: {df_food.size}")

Columns, Rows: (52, 61)
Number of cells: 3172

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [169]:
# Fix that in-place.
should_be_numeric = ['GPA', 'weight']
df_food[should_be_numeric] = df_food[should_be_numeric].apply(pd.to_numeric, errors='coerce')
df_food.dropna(subset=should_be_numeric, inplace=True)

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [170]:
# Savey save!
df_food.to_csv('../data/food_cleaned.csv', index=False)

In [171]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.
df_food_cleaned = pd.read_csv('../data/food_cleaned.csv')
df_food_cleaned.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155.0
1,3.500,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190.0
2,3.800,2,1,610,3.0,420.0,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1.0,...,1.0,1.0,5,940.0,690,soccer,4,1,1315,180.0
3,3.300,1,1,720,3.0,420.0,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1.0,...,1.0,2.0,1,725.0,500,none,4,2,1315,137.0
4,3.300,1,1,430,3.0,315.0,2,"Mac and cheese, chocolate, and pasta","Stress, anger and sadness",1.0,...,1.0,1.0,4,580.0,345,field hockey,5,1,900,125.0

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [172]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.
df_salary = pd.read_csv('../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv', sep='\t')
df_salary.head()

,Timestamp,How old are you?,What industry do you work in?,Job title,"If your job title needs additional context, please clarify here:","What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)","How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.",Please indicate the currency,"If ""Other,"" please indicate the currency here:","If your income needs additional context, please provide it here:",What country do you work in?,"If you're in the U.S., what state do you work in?",What city do you work in?,How many years of professional work experience do you have overall?,How many years of professional work experience do you have in your field?,What is your highest level of education completed?,What is your gender?,What is your race? (Choose all that apply.)
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [173]:
# Count by hand. I’m dead serious.
print(f"Columns, Rows: {df_salary.shape}")
print(f"Number of cells: {df_salary.size}")

Columns, Rows: (28062, 18)
Number of cells: 505116

What are the columns and their types?

In [174]:
# Show the column names and their types.
df_salary.info()

<class 'pandas.DataFrame'>
RangeIndex: 28062 entries, 0 to 28061
Data columns (total 18 columns):
 #   Column                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                --------------  -----
 0   Timestamp                                                                                                                                                                                                                             28062 non-null  str
 1   How old are you?                                                                                                                                                                                                                      28062 non-null  str
 2   What industry do you work in?                                                                                                                                                                                                         27988 non-null  str
 3   Job title                                                                                                                                                                                                                             28061 non-null  str
 4   If your job title needs additional context, please clarify here:                                                                                                                                                                      7262 non-null   str
 5   What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)  28062 non-null  str
 6   How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                        20766 non-null  float64
 7   Please indicate the currency                                                                                                                                                                                                          28062 non-null  str
 8   If "Other," please indicate the currency here:                                                                                                                                                                                        206 non-null    str
 9   If your income needs additional context, please provide it here:                                                                                                                                                                      3042 non-null   str
 10  What country do you work in?                                                                                                                                                                                                          28062 non-null  str
 11  If you're in the U.S., what state do you work in?                                                                                                                                                                                     23039 non-null  str
 12  What city do you work in?                                                                                                                                                                                                             27980 non-null  str
 13  How many years of professional work experience do you have overall?                                                                                                                                                                   28062 non-null  str
 14  How many years of professional work experience do you have in your field?                                                                                                                                                             28062 non-null  str
 15  What is your highest level of education completed?                                                                                                                                                                                    27840 non-null  str
 16  What is your gender?                                                                                                                                                                                                                  27891 non-null  str
 17  What is your race? (Choose all that apply.)                                                                                                                                                                                           27885 non-null  str
dtypes: float64(1), str(17)
memory usage: 3.9 MB

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [175]:
# Rename ‘em in-place.
df_salary.rename(
    columns={
        "Timestamp": "Timestamp",
        "How old are you?": "Age",
        "What industry do you work in?": "Industry",
        "Job title": "Title",
        "If your job title needs additional context, please clarify here:": "Title_context",
        "What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)": "Salary",
        "How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.": "Additional_compensation",
        "Please indicate the currency": "Currency",
        "If \"Other,\" please indicate the currency here: ": "Other_currency",
        "If your income needs additional context, please provide it here:": "Salary_context",
        "What country do you work in?": "Country",
        "If you're in the U.S., what state do you work in?": "State",
        "What city do you work in?": "City",
        "How many years of professional work experience do you have overall?": "Total_yoe",
        "How many years of professional work experience do you have in your field?": "Field_yoe",
        "What is your highest level of education completed?": "Highest_education_completed",
        "What is your gender?": "Gender",
        "What is your race? (Choose all that apply.)": "Race",
    },
    inplace=True,
)

df_salary.head()

,Timestamp,Age,Industry,Title,Title_context,Salary,Additional_compensation,Currency,Other_currency,Salary_context,Country,State,City,Total_yoe,Field_yoe,Highest_education_completed,Gender,Race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [176]:
# List the unique industries and a count of their instances.
df_salary['Industry'].value_counts()

Industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [177]:
# Filtery filter.
df_salary_tech = df_salary[df_salary['Industry'].isin(['Computing or Tech'])]
df_salary_tech.head()

,Timestamp,Age,Industry,Title,Title_context,Salary,Additional_compensation,Currency,Other_currency,Salary_context,Country,State,City,Total_yoe,Field_yoe,Highest_education_completed,Gender,Race
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White

Do a sanity check by counting.

In [178]:
# Sanity check count.
len(df_salary_tech)

4699

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [179]:
# Filtery filter (in place) for just the jobs that pay in USD!
df_usd_salary_tech = df_salary_tech[df_salary_tech['Currency'].isin(['USD'])]

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [180]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_usd_salary_tech['Country'].value_counts().sort_values(ascending=False)

Country
United States                1576
USA                          1222
US                            412
U.S.                          108
United States of America       90
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [181]:
# Replace them all in-place with 'US'.
df_usd_salary_tech['Country'] = df_usd_salary_tech['Country'].replace(['United States', 'USA', 'US', 'U.S', 'United States of America'], 'US')

Have a look at the count of each unique country again now.

In [182]:
# Count again.
df_usd_salary_tech['Country'].value_counts().sort_values(ascending=False)

Country
US                           3302
U.S.                          108
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

Did you notice anything interesting?

In [183]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [184]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [185]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
# Convert invalid salary values to NaN, then remove those rows.
df_usd_salary_tech[df_usd_salary_tech['Country'].isin(['US'])].groupby('State')['Salary'].agg(['min', 'mean', 'max']).sort_values(by='mean', ascending=False)

TypeError: dtype 'str' does not support operation 'mean'

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [ ]:
# Convert invalid salary values to NaN, then remove those rows.

df_usd_salary_tech["Salary"] = pd.to_numeric(df_usd_salary_tech["Salary"].astype(str).str.replace(",", "", regex=False), errors="coerce")

df_usd_salary_tech.dropna(subset=["Salary"], inplace=True)

Let’s try that again.

In [ ]:
# Try it again. Yeah!
df_usd_salary_tech[df_usd_salary_tech['Country'].isin(['US'])].groupby('State')['Salary'].agg(['min', 'mean', 'max']).sort_values(by='mean', ascending=False)

                                   min           mean      max
State
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Florida                          28800  160155.204082  2600000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  155929.434635   875000
Washington                          72  150447.288462   950000
New York                         14000  148756.672026   590000
New Mexico                       82000  146775.000000   300000
Delaware                        145000  145000.000000   145000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135470.996047  1650000
District of Columbia             10000  132987.063830   267500
Connecticut                      62400  130390.625000   270000
Utah, Vermont                   130000  130000.000000   130000
Virginia                         43642  129910.663462   450000
Colorado                         49400  127947.877863   630000
Oregon                           16200  126092.591549   320000
Massachusetts, Rhode Island     125000  125000.000000   125000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  118611.253247   315000
Georgia                          29120  117258.902778   242000
Louisiana, Washington           117000  117000.000000   117000
New Jersey                       45000  116844.827586   245000
Maryland                         51260  116285.636364   205000
South Dakota                     86000  115333.333333   150000
Idaho                            50000  114583.333333   312000
Wisconsin                            1  114414.828947   920000
Texas                            24000  114200.851282   280000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Rhode Island                     76000  111491.666667   180000
Pennsylvania                     32000  109780.136842   237000
District of Columbia, Virginia  109200  109200.000000   109200
Tennessee                        36550  109022.666667   240000
Utah                             33280  108026.159091   245000
Minnesota                        34000  106089.202381   230000
New York, Texas                 105000  105000.000000   105000
North Carolina                   29000  104859.942308   260000
Arizona                          35000  103893.939394   210000
South Carolina                   40000  102111.111111   205000
Nevada                           38000  101637.500000   142000
Nebraska                         43680   99198.461538   166400
Kansas                           41500   98983.500000   167000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   96847.019231   235000
Missouri                            80   95912.069767   200000
Montana                          65000   95500.000000   145000
Iowa                             47840   95241.562500   142000
Arizona, Utah                    95000   95000.000000    95000
Maine                            50000   94200.000000   114000
Mississippi                      94000   94000.000000    94000
Ohio                             32240   92444.862069   179000
Kentucky                         39000   92375.000000   170000
New Hampshire                       55   91403.666667   193000
Indiana                          15000   90830.928571   200000
Oklahoma                         28536   87929.500000   180000
Massachusetts, Pennsylvania      83000   83000.000000    83000
Arkansas                         55000   81682.300000   144000
Louisiana                        35360   81557.500000   110000
California, Maryland             81500   81500.000000    81500
Alabama                          29120   74457.777778   120000
Alabama, Montana                 72000   72000.000000    72000

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [ ]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_usd_salary_tech_filtered = df_usd_salary_tech[df_usd_salary_tech['Timestamp'].str.contains('2021|2022')]
df_usd_salary_tech_filtered

,Timestamp,Age,Industry,Title,Title_context,Salary,Additional_compensation,Currency,Other_currency,Salary_context,Country,State,City,Total_yoe,Field_yoe,Highest_education_completed,Gender,Race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,112000,10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,187500,5000.0,USD,NaN,NaN,US,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,110000,20000.0,USD,NaN,"Around 20,000 a year in stock",US,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,144600,2500.0,USD,NaN,NaN,US,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,200850,40000.0,USD,NaN,NaN,US,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27887,10/19/2022 18:19:22,35-44,Computing or Tech,Senior UX Designer,NaN,175000,15000.0,USD,NaN,NaN,US,California,Sunnyvale,11 - 20 years,11 - 20 years,Master's degree,Woman,"Hispanic, Latino, or Spanish origin"
27888,10/21/2022 19:59:05,25-34,Computing or Tech,Systems Engineer,NaN,114000,20000.0,USD,NaN,NaN,US,Wisconsin,Verona,2 - 4 years,2 - 4 years,Master's degree,Woman,White
27892,11/3/2022 17:18:54,35-44,Computing or Tech,Program Manager,NaN,138000,5000.0,USD,NaN,NaN,US,Texas,Houston,21 - 30 years,21 - 30 years,College degree,Woman,White
27907,11/30/2022 16:49:40,25-34,Computing or Tech,Senior bioinformatics scientist,NaN,170420,20000.0,USD,NaN,NaN,US,California,SF Bay Area,2 - 4 years,2 - 4 years,PhD,Woman,White
27915,12/13/2022 18:21:14,25-34,Computing or Tech,Business Development Director,NaN,111000,30000.0,USD,NaN,NaN,US,California,Costa Mesa,5-7 years,2 - 4 years,College degree,Man,"Hispanic, Latino, or Spanish origin, White"

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)