# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [43]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy in /usr/local/python/3.14.2/lib/python3.14/site-packages (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [44]:
# Import here.

import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [45]:
# Load the Food choices data set.

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [46]:
# Count by hand. (lol kidding)

df_food.shape

(125, 61)

In [47]:
# Try to print or display it nicely.

print(f"the food data set has {df_food.shape[0]} rows and {df_food.shape[1]} columns")

the food data set has 125 rows and 61 columns

What are the columns and their types in this data set?

In [48]:
# Show the column names and their types.

df_food.dtypes

GPA                                 str
Gender                            int64
breakfast                         int64
calories_chicken                  int64
calories_day                    float64
calories_scone                  float64
coffee                            int64
comfort_food                        str
comfort_food_reasons                str
comfort_food_reasons_coded      float64
cook                            float64
comfort_food_reasons_coded.1      int64
cuisine                         float64
diet_current                        str
diet_current_coded                int64
drink                           float64
eating_changes                      str
eating_changes_coded              int64
eating_changes_coded1             int64
eating_out                        int64
employment                      float64
ethnic_food                       int64
exercise                        float64
father_education                float64
father_profession                   str
fav_cuisine                         str
fav_cuisine_coded                 int64
fav_food                        float64
food_childhood                      str
fries                             int64
fruit_day                         int64
grade_level                       int64
greek_food                        int64
healthy_feeling                   int64
healthy_meal                        str
ideal_diet                          str
ideal_diet_coded                  int64
income                          float64
indian_food                       int64
italian_food                      int64
life_rewarding                  float64
marital_status                  float64
meals_dinner_friend                 str
mother_education                float64
mother_profession                   str
nutritional_check                 int64
on_off_campus                   float64
parents_cook                      int64
pay_meal_out                      int64
persian_food                    float64
self_perception_weight          float64
soup                            float64
sports                          float64
thai_food                         int64
tortilla_calories               float64
turkey_calories                   int64
type_sports                         str
veggies_day                       int64
vitamins                          int64
waffle_calories                   int64
weight                              str
dtype: object

In [49]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.

pd.DataFrame(df_food.dtypes, columns=["dtype"])

                                dtype
GPA                               str
Gender                          int64
breakfast                       int64
calories_chicken                int64
calories_day                  float64
calories_scone                float64
coffee                          int64
comfort_food                      str
comfort_food_reasons              str
comfort_food_reasons_coded    float64
cook                          float64
comfort_food_reasons_coded.1    int64
cuisine                       float64
diet_current                      str
diet_current_coded              int64
drink                         float64
eating_changes                    str
eating_changes_coded            int64
eating_changes_coded1           int64
eating_out                      int64
employment                    float64
ethnic_food                     int64
exercise                      float64
father_education              float64
father_profession                 str
fav_cuisine                       str
fav_cuisine_coded               int64
fav_food                      float64
food_childhood                    str
fries                           int64
fruit_day                       int64
grade_level                     int64
greek_food                      int64
healthy_feeling                 int64
healthy_meal                      str
ideal_diet                        str
ideal_diet_coded                int64
income                        float64
indian_food                     int64
italian_food                    int64
life_rewarding                float64
marital_status                float64
meals_dinner_friend               str
mother_education              float64
mother_profession                 str
nutritional_check               int64
on_off_campus                 float64
parents_cook                    int64
pay_meal_out                    int64
persian_food                  float64
self_perception_weight        float64
soup                          float64
sports                        float64
thai_food                       int64
tortilla_calories             float64
turkey_calories                 int64
type_sports                       str
veggies_day                     int64
vitamins                        int64
waffle_calories                 int64
weight                            str

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [50]:
# Remove ‘em.

cols_to_keep = ["calories_day", "weight", "Gender"]
df_food_col_subset = df_food[cols_to_keep].copy()
df_food_col_subset

     calories_day                    weight  Gender
0             NaN                       187       2
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
..            ...                       ...     ...
120           4.0                       156       1
121           2.0                       180       1
122           NaN                       120       1
123           4.0                       135       2
124           NaN                       135       1

[125 rows x 3 columns]

In [51]:
# Is there a second way to remove columns?

df_food_col_subset = df_food.drop(
    columns=[c for c in df_food.columns if c not in cols_to_keep]).copy()
df_food_col_subset

     Gender  calories_day                    weight
0         2           NaN                       187
1         1           3.0                       155
2         1           4.0  I'm not answering this.
3         1           3.0             Not sure, 240
4         1           2.0                       190
..      ...           ...                       ...
120       1           4.0                       156
121       1           2.0                       180
122       1           NaN                       120
123       2           4.0                       135
124       1           NaN                       135

[125 rows x 3 columns]

In [52]:
# 🚀 Extra credit: What about a third way to remove columns?

df_food_col_subset = df_food.loc[:, cols_to_keep].copy()
df_food_col_subset

     calories_day                    weight  Gender
0             NaN                       187       2
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
..            ...                       ...     ...
120           4.0                       156       1
121           2.0                       180       1
122           NaN                       120       1
123           4.0                       135       2
124           NaN                       135       1

[125 rows x 3 columns]

What about `NaN`s? How many are there?

In [53]:
# Count ‘em.

df_food_col_subset.isna().sum()

calories_day    19
weight           2
Gender           0
dtype: int64

In [54]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.

pd.DataFrame(df_food_col_subset.isna().sum(), columns=["num_missing"])

              num_missing
calories_day           19
weight                  2
Gender                  0

In [55]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.

We gotta remove those `NaN`s―the entire row.

In [56]:
# Drop ‘em in-place.

df_food_col_subset.dropna(inplace=True)

In [57]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂

print("df_food:", df_food.shape)
print("df_food_col_subset:", df_food_col_subset.shape)

df_food: (125, 61)
df_food_col_subset: (104, 3)

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [58]:
# Fix that in-place.

df_food_col_subset["calories_day"] = pd.to_numeric(
    df_food_col_subset["calories_day"], errors="coerce"
)
df_food_col_subset.dropna(subset=["calories_day"], inplace=True)
df_food_col_subset.dtypes

calories_day    float64
weight              str
Gender            int64
dtype: object

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [59]:
# Savey save!

df_food_col_subset.to_csv("../data/food_coded_cleaned.csv", index=False)

In [60]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [61]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.
salary_data_set_path = "../data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv"
df_salary = pd.read_csv(salary_data_set_path, sep="\t")

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [62]:
# Count by hand. I’m dead serious.

df_salary.shape

(28062, 18)

What are the columns and their types?

In [63]:
# Show the column names and their types.

df_salary.dtypes

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [64]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race
df_salary.columns = [
    "timestamp", "age", "industry", "title", "title_context", "salary",
    "additional_compensation", "currency", "other_currency", "salary_context",
    "country", "state", "city", "total_yoe", "field_yoe",
    "highest_education_completed", "gender", "race",
]

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [65]:
# List the unique industries and a count of their instances.

df_salary["industry"].value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [66]:
# Filtery filter.

top_5_industries = df_salary["industry"].value_counts().head(5)
print(top_5_industries)

tech_industry_label = "Computing or Tech" 
df_salary_tech = df_salary[df_salary["industry"] == tech_industry_label].copy()

industry
Computing or Tech                       4699
Education (Higher Education)            2464
Nonprofits                              2419
Health care                             1896
Government and Public Administration    1889
Name: count, dtype: int64

Do a sanity check by counting.

In [67]:
# Sanity check count.

len(df_salary_tech)

4699

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [68]:
# Filtery filter (in place) for just the jobs that pay in USD!

df_salary_tech = df_salary_tech[df_salary_tech["currency"] == "USD"]

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [69]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary_tech["country"].value_counts()

country
United States                1576
USA                          1222
US                            412
U.S.                          108
United States of America       90
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [70]:
# Replace them all in-place with 'US'.

top_5_country_values = df_salary_tech["country"].value_counts().head(5).index.tolist()
print(top_5_country_values)

df_salary_tech["country"] = df_salary_tech["country"].replace(top_5_country_values, "US")

['United States', 'USA', 'US', 'U.S.', 'United States of America']

Have a look at the count of each unique country again now.

In [71]:
# Count again.

df_salary_tech["country"].value_counts()

country
US                           3408
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                              9
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
U.S.                            2
United State of America         2
Unite States                    2
Australia                       2
UnitedStates                    2
India                           2
U.S                             2
Usa                             2
United States Of America        2
Spain                           2
Brazil                          2
United Kingdom                  2
united States                   2
New Zealand                     2
Poland                          2
France                          2
U.S.A                           2
United States of america        2
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Uruguay                         1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Netherlands                     1
China                           1
San Francisco                   1
Romania                         1
United STates                   1
Japan                           1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
Unites States                   1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Name: count, dtype: int64

Did you notice anything interesting?

In [72]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [73]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [74]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.

us_tech = df_salary_tech[df_salary_tech["country"] == "US"]
(
    us_tech.groupby("state")["salarys"]
    .agg(["min", "mean", "max"])
    .sort_values("mean", ascending=False)
)

KeyError: 'Column not found: salarys'

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [ ]:
# Fix it in-place.

df_salary_tech["salary"] = (
    df_salary_tech["salary"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("$", "", regex=False)
    .str.strip()
)
df_salary_tech["salary"] = pd.to_numeric(df_salary_tech["salary"], errors="coerce")

dtype('int64')

Let’s try that again.

In [ ]:
# Try it again. Yeah!

us_tech = df_salary_tech[df_salary_tech["country"] == "US"]
(
    us_tech.groupby("state")["salary"]
    .agg(["min", "mean", "max"])
    .sort_values("mean", ascending=False)
)

                                   min           mean      max
state
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Florida                          28800  160155.204082  2600000
California                           0  156001.126230   875000
Alabama, District of Columbia   156000  156000.000000   156000
Washington                          72  150592.449367   950000
New York                         14000  148213.307692   590000
New Mexico                       82000  140466.666667   300000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135924.303704  1650000
District of Columbia             10000  134191.673469   267500
Connecticut                      62400  130390.625000   270000
Utah, Vermont                   130000  130000.000000   130000
Virginia                         43642  129387.704762   450000
Colorado                         49400  128038.887218   630000
Oregon                           16200  125205.888889   320000
Massachusetts, Rhode Island     125000  125000.000000   125000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  118039.063694   315000
Louisiana, Washington           117000  117000.000000   117000
New Jersey                       40000  116953.125000   245000
Georgia                          29120  116928.546667   242000
Maryland                         51260  116449.333333   205000
South Dakota                     86000  115333.333333   150000
Idaho                            50000  114583.333333   312000
Wisconsin                            1  113891.371795   920000
Texas                            10700  113128.049505   280000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Rhode Island                     76000  111491.666667   180000
Pennsylvania                     32000  109941.802083   237000
Nevada                           38000  109788.888889   175000
District of Columbia, Virginia  109200  109200.000000   109200
Tennessee                        36550  109022.666667   240000
Utah                             33280  106958.911111   245000
Minnesota                        34000  106752.793103   230000
New York, Texas                 105000  105000.000000   105000
Delaware                         63000  104666.666667   145000
North Carolina                   29000  104386.169811   260000
Arizona                          35000  103893.939394   210000
South Carolina                   40000  102111.111111   205000
Kansas                           41500   98983.500000   167000
Iowa                             47840   98325.833333   160000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   96847.019231   235000
Missouri                            80   96631.181818   200000
Montana                          65000   95500.000000   145000
Nebraska                         43000   95184.285714   166400
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
Ohio                             32240   92577.451613   179000
Kentucky                         39000   92375.000000   170000
Maine                            50000   92000.000000   114000
New Hampshire                       55   91403.666667   193000
Indiana                          15000   90830.928571   200000
Oklahoma                         28536   87929.500000   180000
Massachusetts, Pennsylvania      83000   83000.000000    83000
Arkansas                         55000   81682.300000   144000
California, Maryland             81500   81500.000000    81500
Louisiana                        35360   79884.444444   110000
Alabama                          29120   74457.777778   120000
Alabama, Montana                 72000   72000.000000    72000

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [ ]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.

df_salary_tech["timestamp"] = pd.to_datetime(df_salary_tech["timestamp"], errors="coerce")
df_salary_tech_recent = df_salary_tech[
    df_salary_tech["timestamp"].dt.year.isin([2021, 2022, 2023])
]

us_tech_recent = df_salary_tech_recent[df_salary_tech_recent["country"] == "US"]
(
    us_tech_recent.groupby("state")["salary"]
    .agg(["min", "mean", "max"])
    .sort_values("mean", ascending=False)
)

                                   min           mean      max
state
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
California                           0  156142.343186   875000
Alabama, District of Columbia   156000  156000.000000   156000
Washington                          72  150749.409524   950000
New York                         14000  148213.307692   590000
New Mexico                       82000  140466.666667   300000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  135924.303704  1650000
District of Columbia             10000  134191.673469   267500
Connecticut                      62400  130390.625000   270000
Utah, Vermont                   130000  130000.000000   130000
Virginia                         43642  129387.704762   450000
Colorado                         49400  128038.887218   630000
Oregon                           16200  125205.888889   320000
Massachusetts, Rhode Island     125000  125000.000000   125000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  118411.108974   315000
Georgia                          29120  117035.689189   242000
Louisiana, Washington           117000  117000.000000   117000
New Jersey                       40000  116953.125000   245000
Maryland                         51260  116449.333333   205000
South Dakota                     86000  115333.333333   150000
Idaho                            50000  114583.333333   312000
Wisconsin                            1  113891.371795   920000
Texas                            10700  113128.049505   280000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Rhode Island                     76000  111491.666667   180000
Pennsylvania                     32000  109941.802083   237000
South Carolina                   40000  109875.000000   205000
Nevada                           38000  109788.888889   175000
Florida                          28800  109325.104167   190000
District of Columbia, Virginia  109200  109200.000000   109200
Tennessee                        36550  109022.666667   240000
Minnesota                        34000  107063.872093   230000
Utah                             33280  106958.911111   245000
New York, Texas                 105000  105000.000000   105000
Delaware                         63000  104666.666667   145000
North Carolina                   29000  104285.085714   260000
Arizona                          35000  103893.939394   210000
Kansas                           41500   98983.500000   167000
Iowa                             47840   98325.833333   160000
North Dakota                     45760   97880.000000   150000
Michigan                         36800   96847.019231   235000
Missouri                            80   96631.181818   200000
Montana                          65000   95500.000000   145000
Nebraska                         43000   95184.285714   166400
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
Ohio                             32240   92577.451613   179000
Kentucky                         39000   92375.000000   170000
Maine                            50000   92000.000000   114000
New Hampshire                       55   91403.666667   193000
Indiana                          15000   90830.928571   200000
Oklahoma                         28536   87929.500000   180000
Massachusetts, Pennsylvania      83000   83000.000000    83000
Arkansas                         55000   81682.300000   144000
California, Maryland             81500   81500.000000    81500
Louisiana                        35360   79884.444444   110000
Alabama                          29120   74457.777778   120000
Alabama, Montana                 72000   72000.000000    72000

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)